### ISSUE TITLE
error : received record with version 0 when expecting version 303

### ISSUE THREAD

**Issue by 11hhlin1** [rustls/rustls#1004]
rust client connet  tls 1.2 server

**Comment by djc** [comment]
If you'd like help with this issue, please provide some code that makes your problem reproducible.

**Comment by ctz** [comment]
A packet capture of this happening would also work!

**Comment by briansmith** [comment]
@11hhlin1 any updates? Did you find a solution to this issue? Should we close this? Thanks!

**Comment by bdaehlie** [comment]
Closing as there has been no response in a while.
