### ISSUE TITLE
QUIC expecting `EndOfEarlyData` !?

### ISSUE THREAD

**Issue by Lichtso** [rustls/rustls#1005]
I am using `rustls = { version = "0.20.3", default-features = false, features = ["quic"] }` for quinn and getting the following error message:
> received unexpected handshake message: got `Finished` when expecting `EndOfEarlyData`

When running the reproducer program here: https://github.com/quinn-rs/quinn/issues/1302

According to [rfc9001](https://www.rfc-editor.org/rfc/rfc9001.html#name-removing-the-endofearlydata) there is no `EndOfEarlyData` in QUIC.

**Comment by Ralith** [comment]
This is a simple oversight in rustls, and in quinn's test suite. Workaround by pinning rustls 0.20.2 for now; expect a PR from me tonight to fix the issue in rustls.

**Comment by Ralith** [comment]
This has been fixed in 0.20.4.
