### ISSUE TITLE
Include BetterTLS in the test suite somehow

### ISSUE THREAD

**Issue by djc** [rustls/rustls#1015]
https://github.com/Netflix/bettertls. Noticed it via Sleevi's Twitter account:

https://twitter.com/sleevi_/status/1496869274777915393

**Comment by cpu** [comment]
The upstream project already has a test runner that can exercise Rustls + Webpki against their suite of tests. There's been some bitrot (https://github.com/Netflix/bettertls/pull/20) but once fixed everything passes with flying colours. Pretty cool!

I think the main open question is how best to integrate that project into our test suite. I think this is largely a choice between [using their embedded test runner](https://github.com/Netflix/bettertls#execting-tests-with-the-embedded-test-runner) or [extracting the tests to use our own runner](https://github.com/Netflix/bettertls#exporting-tests-to-run-outside-of-the-bettertls-executor).

What do folks think? If we could figure out how to get the embedded runner to test against the branch in development via CI would that be an acceptable integration path or is it worth the effort to try and write our own runner that uses the extracted test metadata?

In terms of execution time a run with `--suite pathbuilding` completes quickly (~22s). Running all of the tests takes quite a bit longer (~11m) and would probably start to bog down development velocity unless restricted to a separate cron based CI config.

**Comment by cpu** [comment]
Looking deeper I think the best place to start is in webpki and using the exported pathbuilding test suite. It was painless to get that going: https://github.com/rustls/webpki/pull/116

**Comment by cpu** [comment]
We've added both the path building and the name constraint verification test suites from BetterTLS to the rustls/webpki repository.

I think since these tests are more specific to certificate verifiers than TLS libraries there's probably not too much utility in adding the same tests to this repo.
