### ISSUE TITLE
Determining which certificates are compatible with a `ClientHello`

### ISSUE THREAD

**Issue by jeromegn** [rustls/rustls#1019]
At Fly.io, we generate both a RSA and ECDSA certificate for every hostname we serve.

The way we did this was by using the `tls-parser` crate and peeking at the `TcpStream` to determine the list of supported client ciphers as well as the ALPN, servername and TLS protocol version.

With the ciphers, we knew which kinds of certificates we should fetch from our encrypted store.

```rust
static SUPPORTED_ANY_CIPHERSUITES: &[&str] = &[
     "TLS_CHACHA20_POLY1305_SHA256",
     "TLS_AES_128_GCM_SHA256",
     "TLS_AES_256_GCM_SHA38"
];

static SUPPORTED_ECDSA_CIPHERSUITES: &[&str] = &[
     "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
     "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
     "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
];

static SUPPORTED_RSA_CIPHERSUITES: &[&str] = &[
     "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
     "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
     "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
];
```

(Note: this was possibly flawed in its own way)

If we matched any of the ClientHello ciphers to the `SUPPORTED_ANY_CIPHERSUITES` list, we knew we could provide either RSA or ECDSA (we prioritize the latter). If not, we looked for ciphers in the other slices.

Now, with the new design, we're able to get more reliable information by starting the handshake and fetching the `ClientHello` (we're using tokio-rustls's `LazyAcceptor`).

Unfortunately, we don't have enough information to make a decision on which certificate we should fetch from our encrypted store.

The `ClientHello` doesn't provide a list of client ciphers we can match on. Instead, we need to rely on signature schemes.

As far as I can tell, this is not enough information for determining if we should fetch an RSA or ECDSA key / certificate. I suppose it might be possible by intersecting lists of known RSA, ECDSA, ANY signature schemes, but I don't know how much we can rely on this.

Would it be desirable to also expose the list of client ciphers in the `ClientHello`? I wouldn't mind knowing the protocol version as well.

Any other way to help determine with certainty which type of certificate key we should resolve in our `ResolvesServerCert` implementation would be helpful.

**Comment by djc** [comment]
The cipher suites sort of imply the protocol version, right? If you know the former, you also know the latter.
