### ISSUE TITLE
Doing POST HTTP request

### ISSUE THREAD

**Issue by marvellous987** [rustls/rustls#1020]
May I ask, can we do POST request using Rustls? 

I was trying to replace the GET request with the POST request in https://github.com/rustls/rustls/blob/0a5c9776345f29b79fc9fed2024b131fd70abfb3/rustls-mio/examples/tlsclient.rs#L580-L584 but seemingly it failed.

Thank you for any kindly help.

**Comment by djc** [comment]
Of course you can. The example is intended as the minimally viable HTTP request. If you want to make a POST request, you have to add some other things too. All of that is completely unrelated to rustls.
