### ISSUE TITLE
unable to do session resumption with api.devicecheck.apple.com

### ISSUE THREAD

**Issue by zh-jq** [rustls/rustls#1027]
from tokio-rs/tls/issues/103

there are two streams in the following pcap files, the first to appleid.apple.com, the second to api.devicecheck.apple.com, both use session_ticket extension.
[out.pcap.gz](https://github.com/rustls/rustls/files/8443223/out.pcap.gz)

The second failed while the first succeeded. The main difference seems to be, in stream one, packet 6 contains **Server Hello + Change Cipher Spec + Encrypted Handshake Message**, but in stream two, packet 23 only contains **Server Hello + Change Cipher Spec**, the missing **Encrypted Handshake Message** is later in packet 27, which seems to be ignored by rustls as it reply alert message and close the connection before packet 27.

tokio-rustls version 0.23.2, rustls version 0.20.4

The error returned by rustls is CorruptMessagePayload(Handshake), I'm trying to test it locally with master version of rustls to get more info.

**Comment by djc** [comment]
@complexspaces is this the same thing you were seeing before? Did you make any progress since #1016?

**Comment by zh-jq** [comment]
I can confirm that code in #1028 fixed this.

**Comment by complexspaces** [comment]
@djc I believe that this is unrelated. We heard back from someone encountering the issue and the issue seems to be coming from [this section](https://github.com/rustls/rustls/blob/main/rustls/src/conn.rs#L603-L608).

**Comment by djc** [comment]
@complexspaces probably a good idea to file a new issue about that?

**Comment by complexspaces** [comment]
@djc Yep, that sounds good. I just wanted to confirm it was unrelated to this one. I've opened https://github.com/rustls/rustls/issues/1030 for everything else.

**Comment by ctz** [comment]
Thanks for the good bug report. Fixed in a8d361c which will be released in 0.20.5 shortly.
