### ISSUE TITLE
TLS middlebox prevents session establishment during handshake

### ISSUE THREAD

**Issue by complexspaces** [rustls/rustls#1030]
We've received a few user reports where `rustls` fails to setup a TLS session when a TLS proxy is in-use (we aren't sure which brand, etc). After asking for some more logging, we've narrowed down the code section throwing an error to [here](https://github.com/rustls/rustls/blob/main/rustls/src/conn.rs#L603-L608).

Our best assumption so far is that the middlebox is returning some badly formatted data that causes `buf_contains_message` to reject it.

**Comment by complexspaces** [comment]
@djc I believe this was unknowingly fixed by https://github.com/rustls/rustls/commit/86f4695c8c05a8041807a34d691b9bb07b757df0, so thank you very much for the work.

We've heard back from a number of users who confirmed an update fixed their environment. Notably, with these apps deployed (from users who told us):
- Palo Alto Prisma
- [VM-Series Virtual Next-Generation Firewalls](https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/decryption) (Another Palo Alto product)

I'm going to close this as this specific handshake error is gone now, with `rustls` working in these environments correctly.

**Comment by djc** [comment]
Awesome to hear, thanks for reporting back!
