### ISSUE TITLE
Breaking change from 0.20.4 to 0.20.5

### ISSUE THREAD

**Issue by jgallagher** [rustls/rustls#1041]
Hi! We ran into a failure when updating rustls from 0.20.4 to 0.20.5 in https://github.com/oxidecomputer/dropshot/pull/347. It looks like the commit that introduced the change is c42c53e13dfc54495cbb62577f6bb58eddf5ff8a; specifically [this bit](https://github.com/rustls/rustls/commit/c42c53e13dfc54495cbb62577f6bb58eddf5ff8a#diff-1a5dae8e5448dde6cce460d2ddb8eb3fd6dd66e917c755a078bf9c0175e4bd76R52) that changes the type of a case in the public `Error` enum.

We have some tests that construct specific error cases, and with 0.20.5 it doesn't look like it's possible for us to construct an instance of the new `CorruptMessagePayload` type. I have a couple questions:

* Should it be possible for external callers to construct errors of that case? (We currently do this for our unit tests, but maybe it's unnecessary; I'd need to read more to know for sure.)
* Should this change either be reverted or released as 0.21.0 to avoid a semver break?

Thanks!

**Comment by djc** [comment]
Ah, sorry -- I missed that this was a breaking change.

Given the time it takes for the ecosystem to work through rustls upgrades, I think it would probably be better to revert this change for now, maybe figure out if we can rebuild it in a different way without breaking compatibility?

Or we can claim that only a small minority of downstream users are affected and it's not a big deal?

Maybe we should yank 0.20.5 while we decide?

No easy answers, I'm afraid.

**Comment by jgallagher** [comment]
Agreed on no easy answers. Personally I'd vote yank for now - I agree with the belief that only a small number of users are affected, but it's hard to know. And since we know "small number" is strictly greater than zero in this case ;), it's possible there are others that might become broken when they try to upgrade (or worse, it breaks something that has a transitive dependency on rustls).

**Comment by jgallagher** [comment]
FWIW we're going to remove our use of this error case, but that doesn't change my personal opinion on yanking.

**Comment by complexspaces** [comment]
Ouch, sorry about this indirectly for breaking your code 😓.

I'm fine with yanking 0.20.5 personally. My only nit would be that it would be _nice_ to build our code with the changes in https://github.com/rustls/rustls/commit/c42c53e13dfc54495cbb62577f6bb58eddf5ff8a (without a fork) while not stalling the main branch from being able to do releases, but those two don't go together well and the wider ecosystem is a higher priority than my one project.

Given that we've seemingly found the part of the code responsible for numerous handshake failures, I'd be fine backing out my changes until the project is ready to release a new minor version. I don't think it would point to anything new until some fix for https://github.com/rustls/rustls/issues/1030 was proposed and we could use a fork if we really needed to in the event a different handshake failure appeared.

**Comment by ctz** [comment]
Sorry for the inconvenience! Have yanked 0.20.5. Agree with backing out this change (pending the next raft of breaking changes) and then reissuing 0.20.6. Will do that this evening if @djc doesn't beat me to it.

**Comment by djc** [comment]
0.20.6 has been published, @jgallagher thanks for reporting!

**Comment by jgallagher** [comment]
Thanks!
