### ISSUE TITLE
Infallible Acceptor::new

### ISSUE THREAD

**Issue by jsha** [rustls/rustls#1044]
[Acceptor::new](https://docs.rs/rustls/latest/rustls/server/struct.Acceptor.html#method.new) returns a Result, which is somewhat surprising. Tracing through the calls, the [only error case appears to be](https://docs.rs/rustls/0.20.6/src/rustls/server/server_conn.rs.html#469) from calling the [private function CommonState::new](https://docs.rs/rustls/0.20.6/src/rustls/conn.rs.html#827).

`CommonState::new` returns an error [only when `max_fragment_size` is invalid](https://docs.rs/rustls/0.20.6/src/rustls/msgs/fragmenter.rs.html#66-73).

`Acceptor::new` passes a `max_fragment_size` of `None` (i.e. use the default), which is always valid. But the type system doesn't know that.

Can we make `Acceptor::new` infallible by calling an alternate internal `CommonState::new_with_default_fragment_size` that is infallible?

**Comment by djc** [comment]
That sounds good! Do you want to defer that change until the next incompatible release? Otherwise, we could for example implement `Default` for `Acceptor` as additional API surface, and potentially deprecate `new()` (or keep around a PR that changes `new()` later on).

**Comment by jsha** [comment]
Implementing `Default` for `Acceptor` sounds like a nice way to do it without waiting for an incompatible release. I'll send a PR.
