### ISSUE TITLE
When is Acceptor::wants_read needed?

### ISSUE THREAD

**Issue by jsha** [rustls/rustls#1045]
The [`Acceptor::wants_read`](https://docs.rs/rustls/0.20.6/rustls/server/struct.Acceptor.html#method.wants_read) method seems like it should logically always return true. The point of an Acceptor is to read bytes from the network. If no more bytes are wanted (because of an error or because a full ClientHello has been read), I would expect that to show up in the return value for [Acceptor::accept](https://docs.rs/rustls/0.20.6/rustls/server/struct.Acceptor.html#method.accept).

Implementation-wise, Acceptor delegates to CommonState::wants_read:
https://github.com/rustls/rustls/blob/c6dcb4c0c63caf503bff80f07182ded0426107ed/rustls/src/conn.rs#L1316-L1332

I think all of these conditions will always be true for Acceptor:

```rust
        self.received_plaintext.is_empty()
            && !self.has_received_close_notify
            && (self.may_send_application_data || self.sendable_tls.is_empty())
```

**Comment by djc** [comment]
Hmm, that is fair. Do you want to send a PR that deprecates the method?

**Comment by jsha** [comment]
Yep, will do!
