### ISSUE TITLE
sponsorship

### ISSUE THREAD

**Issue by jadamcrain** [rustls/rustls#1047]
Is there a way to directly sponsor rustls? I've found the ISRG stuff:

https://www.memorysafety.org/sponsor/

It looks like donations go to Prossimo more broadly. What % of these donations does rustls receive?

We donate to Tokio montly, and a Github sponsorship is pretty convenient. Rustls is essential to our products.

**Comment by bdaehlie** [comment]
Speaking for Prossimo, if you wish to direct your donation to Rustls you can do that. There may be other ways to donate to Rustls but I don't know what they are.

**Comment by jadamcrain** [comment]
Thank you for all the really awesome work. We'll just setup a monthly for Prossimo and mention rustls then.

**Comment by djc** [comment]
As one of the rustls maintainers, I do have a [GitHub Sponsors profile](https://github.com/sponsors/djc). Sponsoring me would support many projects in the Rust ecosystem, see my profile for more details.
