### ISSUE TITLE
Lowering log level of "Received a ServerHelloDone handshake message while expecting [CertificateRequest]" 

### ISSUE THREAD

**Issue by konstin** [rustls/rustls#1051]
When making parallel requests to [pypi.org](https://pypi.org/), the python package index, I'm seeing several `Received a ServerHelloDone handshake message while expecting [CertificateRequest]` warnings.

https://github.com/rustls/rustls/blob/c6dcb4c0c63caf503bff80f07182ded0426107ed/rustls/src/check.rs#L66-L69

The requests succeed and given that pypi.org is widely used and I haven't seen this reported by any other library/tool I've used, I assume this is not a misconfiguration in pypi. Would it be reasonable to lower this to a debug level message? I'm asking because I'd like to avoid swallowing warning the libraries I use, but this does not seem something that should concern users.

**Comment by djc** [comment]
I think that's #1013, can you check? Should go away if you upgrade to latest release rustls (0.20.6).

**Comment by konstin** [comment]
This indeed fixes it, thanks!
