### ISSUE TITLE
Adding more Debug implementations

### ISSUE THREAD

**Issue by jsha** [rustls/rustls#1052]
According to the Rust API Guidelines:

> [All public types implement Debug (C-DEBUG)](https://rust-lang.github.io/api-guidelines/debuggability.html#all-public-types-implement-debug-c-debug)
> If there are exceptions, they are rare.

(One notable exception here: we must make sure Debug impls do not emit secret data).

After some grepping and sedding, here's a list of concrete types that don't currently implement Debug:

ClientConfig
CipherSuiteCommon
ClientConnectionData
ClientSessionMemoryCache
NoClientSessionStorage
WriteEarlyData
Accepted
Acceptor
AllowAnyAnonymousOrAuthenticatedClient
AllowAnyAuthenticatedClient
ClientHello
NoClientAuth
NoServerSessionStorage
ReadEarlyData
ResolvesServerCertUsingSni
ServerConfig
ServerConnectionData
ServerSessionMemoryCache
CommonState
ConnectionCommon
KeyLogFile
NoKeyLogFile
Reader
ServerConfig
Ticketer
Writer
DistinguishedNames

Also, ServerConnection and ClientConnection have a stub Debug implementation that is not very useful: it prints just "ServerConnection" or "ClientConnection" when it should print the connection state, how many bytes it has buffered, whether it wants read and/or write, and whether it's received a close_notify.

I'm happy to contribute PRs adding Debug implementations to some of these. Would that be welcome?

**Comment by djc** [comment]
> I'm happy to contribute PRs adding Debug implementations to some of these. Would that be welcome?

I think so!

**Comment by TieWay59** [comment]
That will be a large work! Shell we do it one by one separately on different issues? 

And would you mind editing the types you listed above into a task list? So we can track the process and other people would know about it and reach out to help.

To learn more about task lists, see: https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

**Comment by djc** [comment]
Don't need to do one by one, it probably makes sense to group them together into a least somewhat larger PRs (especially for the ones that just need to add a derive).

**Comment by Xuanwo** [comment]
Is anyone working on this issue? I'm interested in taking this.

**Comment by djc** [comment]
No, I don't think anyone is working on this issue, and your help would be much appreciated!

**Comment by Xuanwo** [comment]
Great! I'm working on this now.

**Comment by ctz** [comment]
Is there a lint we can activate to validate/defend this?

**Comment by Xuanwo** [comment]
> Is there a lint we can activate to validate/defend this?

Yep.

Added https://github.com/rustls/rustls/pull/1111/files#diff-5f389a0b3f32fb486b1f19f58ada9a15de2d4187be9819f5a1517487d7378ebbR268
