### ISSUE TITLE
Not available on crates.io?

### ISSUE THREAD

**Issue by S3j5b0** [rustls/rustls#1054]
Hi, maybe this is just me being bad at looking for it, but it seems like this project is not available on crates.io?

Is this correct, and then why is this?

**Comment by Darkspirit** [comment]
https://crates.io/crates/rustls ?

**Comment by S3j5b0** [comment]
ah yes, thanks a lot, for some reason it did not show up in searching

**Comment by djc** [comment]
Just curious, what search term did you use.

**Comment by S3j5b0** [comment]
I just typed on rustls oncrates io. I wasnt showing on google either for some reason

**Comment by djc** [comment]
Works for me:

<img width="1301" alt="Screenshot 2022-06-01 at 16 18 37" src="https://user-images.githubusercontent.com/158471/171426655-7f5e7dfb-7c48-4e53-8045-b55b58f9a355.png">

<img width="734" alt="Screenshot 2022-06-01 at 16 19 07" src="https://user-images.githubusercontent.com/158471/171426729-57a661fa-7463-4dc2-ae12-4b40ee65cf8a.png">
