### ISSUE TITLE
Question: how to read ClientHello properly?

### ISSUE THREAD

**Issue by GlenDC** [rustls/rustls#1055]
Hi, I was trying to read the ALPN of a ClientHello for an accepted connection on the server side.

The server is written using `tokio` and as such I use `rustls` in combination with `tokio_rustls`.

Here is how I get the client hello:

```rust
let acceptor = rustls::server::Acceptor::new().unwrap(); // I do proper error handling in actual code
let lazy_acceptor = tokio_rustls::LazyConfigAcceptor::new(acceptor, socket);
let start = lazy_acceptor.await.unwrap(); // I do proper error handling in actual code
assert!(start.client_hello().alpn().is_some()); // <= this works
```

However if I try to read some data from the ALPN, I get nothing:

```rust
if let Some(alpn) = tls.alpn() {
            // this part is reached...
            for ext in alpn.filter_map(ClientExtension::read_bytes) {
                // this part never reaches... So somehow the conversion from the bytes to the ClientExtension
                // is going wrong
                match ext {
                   / ...
```

The ALPN is defined as I manage to get into that branch of the code. However nothing comes through the `alpn.filter_map`...
Anyone an idea what is going wrong here? How do I go from `::alpn().unwrap()` to something like an `Iter<ClientExtension`?

Eventually this is the kind of data I wish to extract from my ClientHello ALPN:

```rust
if let Some(alpn) = tls.alpn() {
    for ext in alpn.filter_map(ClientExtension::read_bytes) {
        match ext {
            ClientExtension::ECPointFormats(list) => {
                fp.supported_points = Some(list.iter().map(|v| v.get_u8()).collect());
            }
            ClientExtension::Protocols(list) => {
                fp.supported_protos = Some(
                    list.iter()
                        .map(|payload| {
                            let mut v = Vec::new();
                            payload.encode(&mut v);
                            String::from_utf8(v).unwrap_or_else(|_| {
                                let mut v = Vec::new();
                                payload.encode(&mut v);
                                base64::encode(v)
                            })
                        })
                        .collect(),
                );
            }
            ClientExtension::SupportedVersions(versions) => {
                fp.supported_versions =
                    Some(versions.iter().map(|v| v.get_u16()).collect());
            }
            // If I understand it correctly it seems that the client extension
            // provides no default support for EllipticCurves, so we'll get it ourselves...
            ClientExtension::Unknown(unknown_ext)
                if unknown_ext.typ == ExtensionType::EllipticCurves =>
            {
                let mut reader = CodecReader::init(&unknown_ext.payload.0[..]);
                fp.supported_curves = read_vec_u16(&mut reader);
            }
            _ => (),
        }
    }
}
```

**Comment by djc** [comment]
Your example code seems to be confused about a bunch of things. ClientHello is a TLS message, the first one that a TLS client sends. It includes a bunch of extensions. The `ClientHello` type is a short summary of some parts of the ClientHello message that is preparsed to make the relevant parts easy to access. In other words, you should not be referring to the `ClientExtension` type here at all, and the `ClientHello` interface doesn't provide you access to supported versions or elliptic curves right now. The iterator that `alpn()` returns directly contains the protocol identifiers (which are BTW not required to be UTF-8, so be careful about decoding them as such).

**Comment by GlenDC** [comment]
And can i find the desired info in these protocol identifiers? Or what info does that expose? Where do I find the docs about that?

I'm aware of the non UTF-8 guarantee, this is just some initial testing code. Thanks for pointing it out though!

**Comment by djc** [comment]
You can read RFC 7301 for more information on what ALPN is intended for. It's generally used by application using the same TCP port to distinguish between different application protocols.

EC point formats, supported versions and elliptic curves are currently not exposed in the `ClientHello` interface. What's your use case for all of that stuff?

**Comment by ctz** [comment]
https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids is a good primary source for understanding common ALPN protocol IDs.

**Comment by GlenDC** [comment]
Thank you @ctz for linking that resource, all educational content is welcome. I recently purchased "Bulletproof TLS and PKI, Second Edition: Understanding and Deploying SSL/TLS and PKI to Secure Servers and Web Applications ", which speaking of, I have to pick up at the post office. So going to add your link and related to the list to read together.

**Comment by GlenDC** [comment]
> What's your use case for all of that stuff?

@djc initially to keep track in a database for different platform/browser combinations how their relevant ClientHello properties are formed and what they contain. Such that within other projects I can emulate these clients for various purposes. In a second phase it's also for validation.

Anpther way —which is the apporach I took initially— was to add an external long running script in the mix based on tshark and the like (e.g. <https://tlsfingerprint.io/pcap> gives examples how one can collect this info as a starting point).

However this adds complexity in many forms and so I was hoping that I could achieve it all directly within my web service.

Projects such as <https://ja3er.com> and uTLS (Golang) also allow such endavours.

The information certainly is there within my process while using Rustls, it just seems that it isn't exposed. Or perhaps it is exposed but I do know how to get to it?

**Comment by djc** [comment]
I don't think it's exposed. If you want to create a PR to add some more stuff to `ClientHello`, that would probably be acceptable.

**Comment by djc** [comment]
Seems pretty straightforward:

* `ClientHello::new()` is defined [here](https://github.com/rustls/rustls/blob/main/rustls/src/server/server_conn.rs#L119)
* From there, you should be able to find the 2 library call sites and 2 test call sites
* I guess you'll want a few new methods to `ClientHello`, and so you'll need to add state to it that gives it access to the necessary data
* The necessary data should be available as part of the `ClientHelloPayload` type
* Try to avoid extra allocations
* Should probably not decrease code coverage with your changes, so you'll want to make sure the new `ClientHello` methods are called in some tests (either existing or new) and verify that the output matches what you expect

**Comment by GlenDC** [comment]
Fantastic! Going to come back to you with a PR this week :)

**Comment by GlenDC** [comment]
@djc I suppose if I want to have access to other ALPN Extensions such as `h2` than I would have to add this in a similar way, no?

**Comment by djc** [comment]
No. Please, read some code or specs so that you understand what ALPN is and how it works.

**Comment by GlenDC** [comment]
Ok will do. My apologies! Going to get a better understanding first before I come back to you.

**Comment by GlenDC** [comment]
Ok I understand it now better.

- I'll tackle the exposure of data (that is currently not exposed) from the ClientHello payload as this issue.

Regarding the ALPN (which is I now realise a different thing all together and already exposed). Would it be good if I create a new issue regarding this and perhaps make it easier to map to known ALPN constants? E.g. the typical h2 and http11 ones etc. Because currently I see most Rust projects just using these magic constants directly, wouldn't hurt to have these grouped together as part of some rustls module in regards to alpn and make it easy to check if these are defined by the client etc.

What do yo think?

**Comment by djc** [comment]
rustls is a TLS library. I don't think it makes sense for it to expose values for everything in the IANA registry, and they're relatively easy to look up: https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids.

**Comment by GlenDC** [comment]
Fair enough. Even though you wouldn't pay anything for it on runtime if you do not use it. But certainly fair enough, so I agree.


That being said, would it be within scope for a contribution to add that link with some info to https://github.com/rustls/rustls/blob/2673750e0f718656708129f58c93771d9dcc7172/rustls/src/server/server_conn.rs#L156 to help figure out people where they could look up such possible issues. Because it's only easy to look up if you actually have knowledge about it I would say.

Or perhaps it is assumed that the user is an expert in all corners of Tls, in which case I guess it is out of scope.

**Comment by djc** [comment]
Adding a link there seems reasonable, though it should be clear that the IANA registry is by no means meant to be exhaustive.

**Comment by GlenDC** [comment]
This issue can be closed. The questions have been resolved and adding these extra fields to ClientHello are apparently out of scope for this project. So I consider this issue to be resolved. Thank you all for your attention and time.
