### ISSUE TITLE
How to add the pair of `(sni, CertifiedKey)` in runtime? 

### ISSUE THREAD

**Issue by jobenye** [rustls/rustls#1059]
### Case

The admin changed configuration and ask to support new SNI and the corresponding certificate.

### The Code

``` rust
#[tokio::main]
async fn main() {
    let mut resolver = Arc::new(ResolvesServerCertUsingSni::new());

    tokio::join!(
        start_web_server(resolver.clone()),
        async {
            sleep(Duration::from_secs(3)).await;
            println!("3 seconds ...");
            println!("resolver: {}", Arc::get_mut(&mut resolver).is_some());
            // Arc::get_mut(resolver)).unwrap().add("domain.org", certkey);  ==> this is what I wanted, add the pair dynamically
        }
    );
}
```

### Question

Any bugs in my code or how to solve it or any workarounds? Should it be a new feature for the library, e.g. to use `Arc<RefCell<ResolvesServerCert>>` as the argument of `ResolvesServerCert::add()`? Thank you.

**Comment by jsha** [comment]
That's not possible with the current `ResolvesServerCertUsingSni`. You'll need some other type that implements the [`ResolvesServerCert`](https://docs.rs/rustls/latest/rustls/server/trait.ResolvesServerCert.html) trait and has the desired properties. For instance, it might look something like:

```
pub struct MyResolver(Mutex<ResolvesServerCertUsingSni>);

impl ResolvesServerCert for MyResolver {
  fn resolve(&self, client_hello: ClientHello<'_>) -> Option<Arc<CertifiedKey>> {
    self.lock().unwrap().resolve(client_hello)
  }
}

impl MyResolver {
  fn add(&self, name: &str, ck: CertifiedKey) -> Result<(), Error> {
    self.lock().unwrap().add(name, ck)
  }
}
```

Note: I haven't tested this code at all but it demonstrates the general direction.

**Comment by jobenye** [comment]
Thanks a lot. I had thought I will have to copy part of code from `ResolvesServerCertUsingSni` and create my struct. I forgot I can encapsulate it as a member.
