### ISSUE TITLE
Remove PayloadU16 from public API

### ISSUE THREAD

**Issue by jsha** [rustls/rustls#1061]
As discussed in https://github.com/rustls/rustls/issues/1036, PayloadU16 shows up in the public API in two places:

[`ServerCertVerifier`](https://docs.rs/rustls/0.20.6/rustls/client/trait.ServerCertVerifier.html) and other traits take [DigitallySignedStruct](https://docs.rs/rustls/0.20.6/rustls/internal/msgs/handshake/struct.DigitallySignedStruct.html) as a parameter. DigitallySignedStruct contains `pub sig: `[`PayloadU16`](https://docs.rs/rustls/0.20.6/rustls/internal/msgs/base/struct.PayloadU16.html).

[`DistinguishedNames`](https://docs.rs/rustls/0.20.6/rustls/type.DistinguishedNames.html) is a type alias for `VecU16OfPayloadU16`.

These are wrapper types for `Vec<u8>` and `Vec<Vec<u8>>` respectively. The stable API should expose them as `Vec<u8>` and `Vec<Vec<u8>>`, since the fact that these fields are 16-bit length prefixed in TLS is not interesting to the user.

Changing these directly would require waiting for the next breaking change, but we can make progress before then.

For `DigitallySignedStruct`, we should deprecate the public fields and provide accessors; the accessor for `sig` should return `&[u8]`.

I'm not sure what a good path forward for DistinguishedNames would be.

**Comment by djc** [comment]
See also discussion in #895.

**Comment by jsha** [comment]
In https://github.com/rustls/rustls/pull/1064 I propose a path forward for DistinguishedNames in the RootCertStore API.

DistinguishedNames is also used in the [ClientCertVerifier API](https://docs.rs/rustls/latest/rustls/server/trait.ClientCertVerifier.html):

```
    fn client_auth_root_subjects(&self) -> Option<DistinguishedNames>;
```

I'd like to add a method `root_subjects(&self) -> Option<Box<dyn Iterator<Item = &'a [u8]>>>`, implement it in terms of the existing `client_auth_root_subjects` by default, and eventually deprecate `client_auth_root_subjects`. The problem is that returning a type parameterized by the `ClientCertVerifier`'s lifetime doesn't work because `client_auth_root_subjects` returns an owned Vec, so the lifetimes don't work out.

I could do `root_subjects(&self) -> Option<Vec<Vec<u8>>>` but we could save some allocations that happen on every handshake by adopting a slice-based API. Not sure what the best approach is here.
