### ISSUE TITLE
ability to define/overwrite extensions for ClientConfig (ClientHello)

### ISSUE THREAD

**Issue by GlenDC** [rustls/rustls#1071]
The ClientConfig builder makes use of the ConfigBuilder. As such it is already possible to overwrite the Cipher Suites (only non-extension data that I want to be able to overwrite anyway) and supported protocol versions (only extension via ConfigBuilder that as far as I can see can be overwritten / manually defined as far as I can see. The ClientConfig also allows the ALPN extension to be overwritten already.

However, it is currently not yet possible to overwrite these even though I would like to be able to:

- SupportedPoints;
- SupportedCurves;
- SignatureAlgorithms;
- KeyShare;
- PSKKeyExchangeModes;

There might be some other less popular ones that I also would like to overwrite at some point. So perhaps it could be also a possibility to have an opaque way to define any kind of extension data.

Not sure where they would be part of, perhaps even as dangerous config options? I understand that this use case of mine is not the regular use case of the rustls client, but I think it is none the less a valid one.

**Comment by djc** [comment]
I think this would be at odds with rustls' design goals. If you need this feature, maybe just fork the library?

**Comment by GlenDC** [comment]
That is certainly a fair enough suggestion and one that I consider in full seriousness. This would none the less allow me to contribute acceptable changes upstream while deviating where required on our end.

Just out of curiosity though, how does this differ from the fact that it _is_ possible to define the Cipher Algorithms? For example Go's std Tls library has moved towards a hard coded safe set of algorithms (comparable to your safe defaults) not allowing for any custom list. 

I'm asking as in my mind this feature request fell in line with that existing feature.

**Comment by GlenDC** [comment]
Similar to the Server's ClientHello I can notice now that my use case is out of scope for this project. For these purposes I'll fork the project at a later time. Anything that falls within the design of the project and that may serve to be useful I can none the less propose upstream.

Thank you for your time and attention.
