### ISSUE TITLE
crate rustls-mio dev-depends on ct-logs without using it

### ISSUE THREAD

**Issue by jonassmedegaard** [rustls/rustls#1073]
Crate `rustls-mio` declares a dev-dependency on `ct-logs` but apparently does not use it anywhere.

**Comment by djc** [comment]
Thanks for reporting! Would you be able to submit a PR?

**Comment by jonassmedegaard** [comment]
I am unaware if the intent was to actually use `ct-logs`, so unsure if it would be hiding a problem to remove it.

Also, as a political principle I do not push code to Github, due to their copyleft-defusing Terms of Service.

I can happily publish a git repo somewhere else with a one-line change to simply remove the dependency, if that is not considered too much hassle.

**Comment by TieWay59** [comment]
https://github.com/rustls/rustls/blob/ed7256a316472b68506b7d1a2c2224844adc0c52/rustls-mio/Cargo.toml#L24

I found this line is recently updated on commit https://github.com/rustls/rustls/commit/ed7256a316472b68506b7d1a2c2224844adc0c52.

So, @ctz would you like to share ideas about whether to keep this dependence in rustls-mio?

**Comment by djc** [comment]
If it's unused we should ditch it.

**Comment by ctz** [comment]
This was made unused during https://github.com/rustls/rustls/commit/fcd4b9c5e2d5c32b646ae445df377d3de2f115bb#diff-bb5e0231ebe6c1e928c9de6cde6c2ff600a550e6c5fbb1811b0a54a690072487 and I agree with removing it. The SCT integration here was only partial and to be truly useful needed to be integrated into webpki.

**Comment by TieWay59** [comment]
> I agree with removing it.

Thank you @ctz for your quick reply. Do you mind reviewing it on #1085?
