### ISSUE TITLE
How to get ClientConfig from ConfigBuilder?

### ISSUE THREAD

**Issue by yeonjooo** [rustls/rustls#1080]
I added dangerous_configuration feature to prevent the client from verifying the server's certificate.
ClientConfig is required to use ClientConfig::dangerous(), but I checked that the ClientConfig::new() function is deprecated.

In the docs, it is written that you must use the builder() function to create a ClientConfig. How can I get the ClientConfig to pass as an argument to dangerous()?

**Comment by yeonjooo** [comment]
I solved using self::ClientConfig :)

**Comment by djc** [comment]
You have to create a `ClientConfig` through `ClientConfig::builder()`. Once you've properly initialized the `ClientConfig` through the [`ConfigBuilder`](https://docs.rs/rustls/latest/rustls/struct.ConfigBuilder.html), you can call `dangerous()` on it, then drop the `DangerousClientConfig` again to be able to use the `ClientConfig`.

**Comment by yeonjooo** [comment]
@djc Thank you for your reply. As answered, I created a ConfigBuilder via ClientConfig::builder(). I also understood that I can get the DangerousClientConfig via the ClientConfig that ConfigBuilder has. 

But to get DangerousClientConfig from ClientConfig object, the only way is to use danger() function, right? To do that, we need a way to get the ClientConfig from the ConfigBuilder. But I couldn't find a corresponding api in the docs. Can you help?



```
    let config = ClientConfig::builder()
        .with_safe_default_cipher_suites()
        .with_safe_default_kx_groups()
        .with_protocol_versions(rustls::ALL_VERSIONS)
        .unwrap();

    let mut dangerous_config = ClientConfig::dangerous(config); // error expected `&mut ClientConfig`, found struct `ConfigBuilder`
```
