### ISSUE TITLE
RFC 9266: Channel Bindings for TLS 1.3 support

### ISSUE THREAD

**Issue by Neustradamus** [rustls/rustls#1089]
Can you add the support of RFC 9266: Channel Bindings for TLS 1.3?
- https://datatracker.ietf.org/doc/html/rfc9266

Little details, to know easily:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3

Thanks in advance.

**Comment by djc** [comment]
It's a little unclear to me what that would look like/what it would need. We already allow [exporting the key material](https://docs.rs/rustls/latest/rustls/struct.ClientConnection.html#method.export_keying_material) which seems like an important building block, what else would you need?

**Comment by ctz** [comment]
See also the discussion on #995

**Comment by Neustradamus** [comment]
@djc, @ctz: Thanks for your comments!

It is not complete for "tls-unique" and "tls-exporter"...

There is nothing in rustls about:
- https://github.com/rustls/rustls/search?q=tls-unique
- https://github.com/rustls/rustls/search?q=rfc5929
- https://github.com/rustls/rustls/search?q=tls-exporter
- https://github.com/rustls/rustls/search?q=rfc9266

For example, it has been added in:

Bouncy Castle:
- https://github.com/bcgit/bc-java/commit/1dba3325a0085d8f000cb0ab59f41d477ead89e2
- https://github.com/bcgit/bc-java/commit/1906d5e07ed11797f0c737e3764e141e6305e233
- https://github.com/bcgit/bc-java/commit/fa01bbc2774c034616dc2ad6fbedb363454d9e16

**Comment by djc** [comment]
For RFC 9266, it seems like you should be able to just export the keying material as described in https://datatracker.ietf.org/doc/html/rfc9266#section-2 (passing in the label yourself).

**Comment by dequbed** [comment]
I'd like to note that yes, djc is correct in that implementing RFC 9266 is already possible with rustls.

If there's interest in this topic from the rustls team I'd be happy to open a PR with examples how to generate `tls-exporter` channel bindings.

But as noted in my previous issue I do not think there is currently any need for `tls-unique` support.

**Comment by Neustradamus** [comment]
For example, there were improvements in GnuTLS, glib and glib-networking about rfc9266 and tls-exporter:
- https://gitlab.com/gnutls/gnutls/-/issues/1391
- https://gitlab.gnome.org/GNOME/glib/-/issues/2710
- https://gitlab.gnome.org/GNOME/glib-networking/-/issues/191

Can you expose tls-unique (rfc5929) and tls-exporter (rfc9266)?

**Comment by djc** [comment]
I would still you to answer this question explicitly:

> We already allow [exporting the key material](https://docs.rs/rustls/latest/rustls/struct.ClientConnection.html#method.export_keying_material) which seems like an important building block, what else would you need?

**Comment by cpu** [comment]
My read of this discussion is we believe the parts required are already present. I'm going to close this issue until the original poster can reply to djc's question about what pieces the OP thinks are missing.

**Comment by Neustradamus** [comment]
Dear @rustls team,

What is the current situation?

It is possible to expose RFC supported versions in source code and Channel Binding version too?

**Comment by ctz** [comment]
> It is possible to expose RFC supported versions in source code and Channel Binding version too?

What have you tried so far?  https://rustls.dev/docs/client/struct.ClientConnection.html#method.protocol_version gives the version, and then the wire format version can be obtained via `to_array` or `u16::from`.

**Comment by djc** [comment]
@Neustradamus we are not going to implement this for you because we don't care (enough) about your use case(s). If you want to implement this and it doesn't add substantial complexity, we might be able to review a PR for it.

Please stop spamming your bullet lists all over our issue tracker/PRs and contain your feedback to this issue.

Also let's keep discussion mostly in the open issue instead of this closed one:

- https://github.com/rustls/rustls/issues/1624

**Comment by Neustradamus** [comment]
@ctz; I have requested several years ago here:
- https://github.com/rustls/rustls/issues/1089#issuecomment-1204516878

@djc: Channel Binding is linked to several tickets/PRs, it is normal to link.

The latest Channel Binding RFC is RFC 9266, this one.

Security has no price, security must be the most important part and Channel Binding is very important against MITM like it is specified at top.

**Comment by djc** [comment]
> [@djc](https://github.com/djc): Channel Binding is linked to several tickets/PRs, it is normal to link.

It is also normal to have one issue per enhancement request so that we don't have discussion in several places.

> Security has no price, security must be the most important part and Channel Binding is very important against MITM like it is specified at top.

Maintaining complexity definitely has a price and must be traded off against the security increase. rustls is mostly focused on the web PKI which doesn't need this, so support for this stuff is best effort.

**Comment by Neustradamus** [comment]
@djc: A little search:
- https://www.google.com/search?q=pki+channel+binding

A lot of companies/projects use Channel Binding like Microsoft, PostgreSQL, etc.

Several rust projects wait since several years rustls for Channel Binding.

**Comment by Neustradamus** [comment]
@djc: It is strange my previous comment has been hidden.
Can you solve it?

Have you searched?
- https://www.google.com/search?q=pki+channel+binding

It is possible to reopen it?

Several Rust projects wait the support in rustls.
