### ISSUE TITLE
Support SIDH key exchange

### ISSUE THREAD

**Issue by valarauca** [rustls/rustls#109]
This isn't _super critical_ just gotta future proof the application against quantum cryptography ;)

Related: https://blog.cloudflare.com/sidh-go/

**Comment by ctz** [comment]
IMO the right approach for rustls on this is to wait for the NIST and IRTF PQC processes to get further and select a couple of clear "winners" for PQ key exchange, and drafts for their use in TLS hybrid with traditional ECDH. When those drafts appear, I think rustls will implement them.

**Comment by quininer** [comment]
Google has tried using `newhope` before, and I think `kyber` would be a good choice.

+ [Experimenting with Post-Quantum Cryptography](https://security.googleblog.com/2016/07/experimenting-with-post-quantum.html)
+ [From NewHope to Kyber](https://cryptojedi.org/peter/data/inria-20170411.pdf)

**Comment by quininer** [comment]
Maybe we should provide a feature to custom the cipher suite.

**Comment by henrydcase** [comment]
There is also SIDH implementation in tls-tris (cloudflares tls in golang)

**Comment by bdaehlie** [comment]
Closing this on the basis ctz's comment, need to wait for appropriate standards.

**Comment by kriskwiatkowski** [comment]
Oh, please never add SIDH. It's completely broken.
