### ISSUE TITLE
no-alpn fallback behavior

### ISSUE THREAD

**Issue by FlorianUekermann** [rustls/rustls#1090]
Implementing the tls-alpn-01 validation mechanism for Let's encrypt requires treating incoming connections which offer only one specific application protocol differently than other incoming connections. However, including this protocol in the ServerConfig enforces the use of alpn as of rustls 0.20 as far as I can tell.
It would be great to have the option to ignore alpn if no protocol match can be found. Maybe this behavior could be activated by including an empty protocol name in the list of protocol names in ServerConfig.

**Comment by djc** [comment]
I'm pretty sure we have enough expressivity in the current API to support tls-alpn-01 efficiently. I recommend you check out the [`Acceptor`](https://docs.rs/rustls/latest/rustls/server/struct.Acceptor.html) API, which lets you postpone constructing/selecting the `ServerConfig` until after you've seen the Client Hello (including the client's supported ALPN protocols).

**Comment by FlorianUekermann** [comment]
Yes, that is correct. Via the Acceptor API I was able to make this work. However, it required contributing an equivalent API to the futures-rustls crate. In other libraries that build on rustls I often see the pattern of taking a `ServerConfig` to configure their behavior. This works well for non-alpn configuration, because the certificate resolver, session storage and ticket producer are replaceable using custom implementations of the respective traits. For alpn rustls does not offer this luxury, which limits composability if you care about alpn.

I think my initial take on this is not good (flag to ignore alpn if no match is found). Replacing or enhancing the `alpn_protocols` vector with a field of type `Arc<dyn SelectsAlpnProtocol>` seems better.

**Comment by FlorianUekermann** [comment]
So I guess the ecosystem around rustls should focus more on the `Acceptor` API then, instead of wrapping `ServerConfig`s. That makes sense to me. I was considering exposing a `&mut ServerConfig` in the "simple" API variant I offer in `rustls-acme`, but I'm starting to think that I should push anyone who wants to customize anything towards the lower level `Acceptor` API based API variant included in the next release ([beta docs](https://docs.rs/rustls-acme/0.4.0-beta2/rustls_acme/)) or maybe add a closure that maps from the client hello to a rustls config.

Thanks for your comments.

**Comment by djc** [comment]
I think that makes sense, please report back if you have any questions about it or if you run into limitations.
