### ISSUE TITLE
At what point in the code does a recieved ClientHello message get parsed from its raw form?

### ISSUE THREAD

**Issue by X9DF** [rustls/rustls#1092]
From the viewpoint of a server, when is `ClientHelloPayload` (which I assume is the more detailed version of `ClientHello`) get created (and then processed)? Other than looking around `ConnectionCommon::first_handshake_message` I'm pretty lost.

**Comment by djc** [comment]
You can see that `ClientHelloPayload` gets stored in the `HandshakePayload` enum, which in stored in `HandshakeMessagePayload::payload`, which is stored in a `MessagePayload` enum, which is stored in `Message::payload`. `ConnectionCommon::process_new_handshake_messages()` pulls `Message`s out of the `HandshakeJoiner`. Does that help?

**Comment by bdaehlie** [comment]
Closing as it seems like the question has been answered.
