### ISSUE TITLE
Compiling on aarch64

### ISSUE THREAD

**Issue by msuiche** [rustls/rustls#1103]
More than a note than anything else at this point, you may want to update to 0.17 as soon as it is available to allow compiling on Windows ARM64 (`aarch64-pc-windows-msvc`)

https://github.com/briansmith/ring/issues/1461#issuecomment-1063293132

**Comment by djc** [comment]
Thanks for the note! We will definitely be porting rustls to ring 0.17 as soon as it becomes available.
