### ISSUE TITLE
Change `AllowAnyAuthenticatedClient::new` to return `Self`

### ISSUE THREAD

**Issue by thalesfragoso** [rustls/rustls#1106]
This is a nice building block to implement client certificate verification, it's even used internally for another verifier in rustls.

Currently, `new` returns `Arc<dyn ClientCertVerifier>` instead of `Self`, creating unneeded indirection and overhead for outside users. Returning `Self` makes the API more flexible and consistent with `WebPkiVerifier`.

We could also go ahead and modify `AllowAnyAnonymousOrAuthenticatedClient::new` too, for consistency.

**Comment by djc** [comment]
Seems reasonable to me. Care to submit a PR? Merging it will have to wait until we start on the next semver-compatible release.
