### ISSUE TITLE
Certificate resolving by proxy protocol parameters

### ISSUE THREAD

**Issue by omer-shtivi** [rustls/rustls#1107]
Hello,
We got a Rust server that is used after a proxy service.
The proxy service support the proxy protocol
The traffic itself is TCP over TLS , and not all clients support SNI.
We wanted to implement `ResolvesServerCert` and decide which certificate to serve based on the IP/PORT that the proxy IP is listening on, information which is provided by the proxy protocol.
Is it a valid use case? I don't mind doing the code contribution.

**Comment by djc** [comment]
It's definitely a valid use case, but I don't think it's common enough that it warrants rustls maintaining a `ResolvesServertCert` implementation for it for use by downstream crates.

(BTW, at least in async code you might prefer using the [`Acceptor`](https://docs.rs/rustls/latest/rustls/server/struct.Acceptor.html) API to decide which `ServerConfig` to use -- tokio-rustls also provides an API for this.)

**Comment by omer-shtivi** [comment]
Thanks for the answer (: 
It was more of adding to the Trait signature `Option<ProxyProtocolParams>` but thanks anyway, I will take a look no the Acceptor
