### ISSUE TITLE
How to use with CRT files?

### ISSUE THREAD

**Issue by FredrikNoren** [rustls/rustls#1109]
Hi, I'm struggling to figure out how to use this with .crt files. With native-tls I got this working (for connecting to a postgres database):

```rust
let connector = native_tls::TlsConnector::builder()
        .add_root_certificate(Certificate::from_pem(include_bytes!("ca-certificate.crt")).unwrap())
        .build()
        .unwrap();
let connector = MakeTlsConnector::new(connector);
```

What's the equivalent for rustls?

**Comment by djc** [comment]
Use [rustls_pemfile](https://docs.rs/rustls-pemfile/latest/rustls_pemfile/) to parse the file, then use the contents of the resulting `rustls_pemfile::Certificate` to build a `rustls::Certificate` which you can parse to [`RootCertStore::add()`](https://docs.rs/rustls/latest/rustls/struct.RootCertStore.html#method.add) which you can use when building a `ClientConfig`, like this:

```rust
let config = rustls::ClientConfig::builder()
    .with_safe_defaults()
    .with_root_certificates(root_store)
    .with_no_client_auth();
```

**Comment by FredrikNoren** [comment]
@djc Thanks, that worked! Here's the full code for anyone else looking for it:

```rust
let mut store = rustls::RootCertStore::empty();
let cert = rustls_pemfile::certs(&mut std::io::BufReader::new(&include_bytes!("ca-certificate.crt")[..])).unwrap().pop().unwrap();
store.add(&rustls::Certificate(cert)).unwrap();
let config = rustls::ClientConfig::builder().with_safe_defaults().with_root_certificates(store).with_no_client_auth();
```
