### ISSUE TITLE
README example command lines seem to be outdated

### ISSUE THREAD

**Issue by FrancisRussell** [rustls/rustls#1118]
The README suggests:

```$ cargo run --example tlsclient -- --http mozilla-modern.badssl.com```

and elsewhere

```cargo run --example tlsserver -- --certs test-ca/rsa/end.fullchain --key test-ca/rsa/end.rsa -p 8443 echo```

but I needed to do 

```$ cargo run --bin tlsclient-mio -- --http mozilla-modern.badssl.com```

and 

```cargo run --bin tlsserver-mio -- --certs test-ca/rsa/end.fullchain --key test-ca/rsa/end.rsa -p 8443 echo```

**Comment by djc** [comment]
Right. Would you be able to submit a PR?

**Comment by FrancisRussell** [comment]
https://github.com/rustls/rustls/pull/1119
