### ISSUE TITLE
ed448 support

### ISSUE THREAD

**Issue by GunnarMorrigan** [rustls/rustls#1120]
He guys,

Is there any info on support for ed448?

It was requested back in 2017 in #52 but closed because it was for another day.
Maybe this is that other day?

Thank you :)

**Comment by djc** [comment]
What's your use case?

**Comment by GunnarPieter** [comment]
Need to move privacy sensitive information between remote devices. Currently uses Ed448 in different language but want to move to Rust. Without Ed448 its not compatible with existing infrastructure. So thought I would check in.

**Comment by djc** [comment]
That seems like a pretty unusual infrastructure choice. Anyway, our underlying crypto library *ring* doesn't support Ed448 for now: https://github.com/briansmith/ring/issues/463 (and it hasn't been getting a lot of maintenance lately).

**Comment by cpu** [comment]
I think given this is blocked on ring develop that isn't likely to occur in the short term we should close this issue. It isn't actionable for Rustls until Ring development resumes or we nail down the details of https://github.com/rustls/rustls/pull/1184
