### ISSUE TITLE
zero out cryptographic keys from memory when Rustls is done with them

### ISSUE THREAD

**Issue by bdaehlie** [rustls/rustls#1123]
I could be wrong, but I don't think Rustls is zeroing out cryptographic keys when it's done with them (e.g. after TLS 1.3 key updates). I think it's a good idea to do that in case access to memory is achieved by some mechanism.

It doesn't seem like Ring supports zeroing out keys. See [this issue](https://github.com/briansmith/ring/issues/566), but maybe I'm missing something.

Perhaps we could use [this](https://github.com/cesarb/clear_on_drop) if Ring does not support it.

**Comment by alex** [comment]
zeroize is another popular crate used for this.

**Comment by ctz** [comment]
More discussion on this: #265

**Comment by bdaehlie** [comment]
Sorry for not seeing that issue first! Closing this one.
