### ISSUE TITLE
Migration path for the openssl crate

### ISSUE THREAD

**Issue by nyurik** [rustls/rustls#1124]
Despite the significant benefits of using rustls, there is still 5.7 million recent [openssl](https://crates.io/crates/openssl) downloads vs 6.5 million of rustls. Migrating all those openssl lib users might be difficult because the API is significantly different.

I would like to propose two things:
* create a list of all common openssl APIs and the corresponding example rustls usages. It is OK for some API not to be implemented in rustls, but they should be clearly documented. Perhaps a wiki page?
* consider implementing/modifying new APIs to provide simpler migration path

**Comment by djc** [comment]
I think it might be useful to have this but it's not high priority enough for me to work on.

For Rust users, I expect the vast majority of crates are using a crate downstream of rustls itself which exposes a Cargo feature to pick native-tls vs rustls, and I think it would be more useful to advocate with downstream crates to advocate for defaulting to rustls over native-tls (to the extent that they pick defaults).

We will definitely want to improve APIs to make it easy to use rustls -- but we also definitely want to keep making it hard to do things that are insecure (unlike OpenSSL).

**Comment by nyurik** [comment]
@djc maybe we can all help?  Could you create a wiki page or a dedicated table-like markdown page that we can all edit, and we can contribute to it.

**Comment by djc** [comment]
I don't think we want to use the wiki for this. Probably it should just go in a separate Markdown file in the repo root. Do you want to start a PR?

**Comment by nyurik** [comment]
@djc thx, please take a look at https://github.com/rustls/rustls/pull/1128

**Comment by bdaehlie** [comment]
It seems like the discussion here and in PR 1128 indicates a desire to not move forward, and there hasn't been any discussion in a while. Closing this out.
