### ISSUE TITLE
Allow offering ciphersuites in the Client Hello that are not yet supported.

### ISSUE THREAD

**Issue by Hainish** [rustls/rustls#1125]
This is very edge-case-y.  A strict set and ordering of ciphersuites is required by Google's server-side authentication in order to proceed with a login: see https://stackoverflow.com/questions/22832104/how-can-i-see-hidden-app-data-in-google-drive.

Attempting to migrate https://github.com/EFForg/rs-google-play/ from `openssl`, I encountered the limitation that only supported ciphersuites are offered in the Client Hello.  Of course, this is a very reasonable assumption.  Unfortunately, in my case Google's ciphersuite strictures will limit me from migrating, as a login fails when using the `ClientConfig` to offer the ciphers supported by `rustls`.

Ideally, I would be able to specify a list of ciphers I would like to proceed with, even if they aren't supported, knowing that Google will actually pick a supported cipher in the Server Hello: TLS_AES_256_GCM_SHA384 (0x1302)

Here is my attempt at migrating, valid but login fails: https://github.com/EFForg/rs-google-play/commit/4779fde5f38cec89112c9c68bd858883c0f0adab
Corresponding issue: https://github.com/EFForg/apkeep/issues/152

**Comment by 89z** [comment]
Great issue. However its not just the cipher suites, but the TLS extensions [1] as well (Rustls might support that currently, but I would guess not).

This is a serious omission in my opinion. Other languages have had support for this for at least 5 years [2]. This is not a theoretical concern. Some popular servers, such as `android.clients.google.com` and CloudFlare are already rejecting requests today, based on TLS client hellos. Any server can choose to add TLS fingerprinting at any time, with either a whitelist or blacklist. So its important that any robust TLS client give the user healthy controls over the hello, such as cipher suites and TLS extensions.

1. https://iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml
2. https://github.com/refraction-networking/utls/commit/cd3d1c46

**Comment by djc** [comment]
@Hainish how would the client session fail if the server does pick a cipher suite that's not actually supported?

**Comment by Hainish** [comment]
@djc of course the failure mode is up to you.  I'd suggest exposing an `UnsupportedCipherSuite` API that returns a `Result<_, rustls::UnsupportedCipherEstablishedError>` when the server chooses an unsupported cipher in the Server Hello.  That way any consumer of `ClientConfig` will be forced to explicitly choose a list of ciphers they know are unsupported by `rustls`, and there will be minimal confusion if an unsupported cipher is chosen.

**Comment by ctz** [comment]
I'm very sorry, but I don't think we're going to do this. If I were you I would consider maintaining a fork of rustls that tracks Google's TLS fingerprinting requirements.

I'd probably also send a snarky ID to the TLSWG that documents Google's requirements , and mark it is obsoleting RFC8701. That would be mostly for entertainment, though, since I don't think companies the size of Google are frequently embarrassed into changing course.

**Comment by hr8** [comment]
Its not just Google. CloudFlare is already rejecting requests today, based on TLS client hellos. Any server can choose to add TLS fingerprinting at any time, with either a whitelist or blacklist. So its important that any robust TLS client give the user healthy controls over the hello, such as cipher suites and TLS extensions.

**Comment by JJTech0130** [comment]
Hrm, yes, I'm encountering this issue because some of Apple's services do fingerprinting. If the server is using a JA3 whitelist, you also have to change the extensions around. I guess I'll just fork it...

**Comment by hr8** [comment]
@JJTech0130  let me know if you do that. I will happily promote any Crate with that feature. I think it was a mistake to close this issue.

**Comment by JJTech0130** [comment]
for now it will probably be specifically tailored to my use-case (mimicking the signature of URLSession)

**Comment by hr8** [comment]
@JJTech0130 I have experience with JA3, so if you need help make an issue on your repo and ping me, or you can contact me on Discord
