### ISSUE TITLE
Guidance needed: How to use rustls based libs with custom certs

### ISSUE THREAD

**Issue by lcmgh** [rustls/rustls#1126]
Hi!

It's clear to me how to enable the rustls feature flag in various libs. But how am I supposed to add a custom certificate chain as .pem file to this setup?

I am baking on top of a https://github.com/GoogleContainerTools/distroless image.

Has this to be done on the OS level or Rust code wise in my project?

Thanks

**Comment by djc** [comment]
Do you mean custom roots for the client verification?

**Comment by lcmgh** [comment]
> Do you mean custom roots for the client's verification of the server certificate?

Yes exactly, within a corporate environment.

**Comment by djc** [comment]
You can use the rustls-pemfile crate to get DER from PEM, then call https://docs.rs/rustls/latest/rustls/struct.RootCertStore.html#method.add and pass the RootCertStore to https://docs.rs/rustls/latest/rustls/struct.ConfigBuilder.html#method.with_root_certificates.

**Comment by lcmgh** [comment]
Thanks for the hint. Is that then a global config that does not need to be injected further anymore?

**Comment by djc** [comment]
The `ConfigBuilder` setup ends up in a `ClientConfig` type, an `Arc<ClientConfig>` needs to be passed into any `ClientConnection`s (depending on how what libraries you're using) you want to set up. If you want to, I can review your changes.

**Comment by cpu** [comment]
It sounds like djc's advice will give you a path forward here. I'm going to close this issue but we can re-open if any further guidance is required, or if there are docs improvements to be made.

**Comment by lcmgh** [comment]
Just as summary how I solved this "problem". I figured out by using the rustls feature of various crates usually the certs provided by the OS are being used which was sufficient for me.
