### ISSUE TITLE
Feature request: Add option for accepting IPs in server name indication

### ISSUE THREAD

**Issue by Alvenix** [rustls/rustls#1127]
I am having issues connecting to servers which use rustls when the server is IP based. The issue occurs when using [reqwest](https://github.com/seanmonstar/reqwest/issues/1328) which use [native-tls](https://github.com/sfackler/rust-native-tls/issues/215). In this case an SNI is always sent even for IPs which is not compatible with the standard so rustls considers the message corrupted. 

There was a previous issue which was on [safari](https://github.com/rustls/rustls/issues/203) but was closed as the bug was fixed in safari. However, It may be better to add an option for this instead of waiting for other TLS implementation to comply with the standard.

**Comment by djc** [comment]
So you're saying a client using native-tls connects to a server using rustls, and the server fails the connection because the client has an IP in the SNI extension?

Since the native-tls backend depends on the platform, on which platform is the client running in your test case?

**Comment by Alvenix** [comment]
> So you're saying a client using native-tls connects to a server using rustls, and the server fails the connection because the client has an IP in the SNI extension?
> 
> Since the native-tls backend depends on the platform, on which platform is the client running in your test case?

I have been using both Ubuntu 20.04 and 22.04.

**Comment by djc** [comment]
> However, It may be better to add an option for this instead of waiting for other TLS implementation to comply with the standard.

What do you think such an option would do? I think this comment from Brian in #203 still holds:

> In general I don't think we should guess at what was intended when there was a malformed input. If there is a (business) need for supporting a lax mode then I hope it is configurable and defaults to the strict behavior.

It might make sense to file this as an issue against the openssl crate and/or the OpenSSL project. (It seems a little surprising you're getting hit by this because if this was a widespread issue this wouldn't be the first report we'd get.)

**Comment by Alvenix** [comment]
> What do you think such an option would do? I think this comment from Brian in #203 still holds:

> > In general I don't think we should guess at what was intended when there was a malformed input. If there is a (business) need for supporting a lax mode then I hope it is configurable and defaults to the strict behavior.

Maybe add option to ignore the SNI if it is IP? Or support IPs in SNI? I can try to make a pull request if the former is acceptable.

> It might make sense to file this as an issue against the openssl crate and/or the OpenSSL project. (It seems a little surprising you're getting hit by this because if this was a widespread issue this wouldn't be the first report we'd get.)

I could only speculate why they are few reports.

-They are workarounds (use rustls with no certificate validation instead or add domain to your hosts, etc..)
-rustls currently doesn’t support IPs in certificate name, maybe when the support comes more people would encounter this issue.

However, in reqwest issue, someone revived the issue saying the also encountered the problem.

**Comment by iazel** [comment]
I think it would be nice to add support for IPs, today apps and other IoT devices are a big part of the market and in that case you may not need a domain name, an IP may be enough. Granted, this is more of "nice-to-have" rather than a "must-have".

**Comment by djc** [comment]
https://github.com/rustls/rustls/issues/184 is in the process of being fixed, so we'll be able to support SNI entries for IP addresses as well.

**Comment by ctz** [comment]
I have raised https://github.com/openssl/openssl/issues/20041

**Comment by cpu** [comment]
We've landed support for IP address subjects in certificates as of v0.21.0.

My perspective is that we should continue to apply pressure on external projects that incorrectly send an IP address value in SNI and not relax this crate's processing of SNI values to allow this misuse. Is this perspective shared by the other maintainers or should we continue to hold this issue open?

**Comment by jsha** [comment]
As an FYI the Rust openssl bindings [recently landed a fix to stop sending IP addresses in SNI](https://github.com/sfackler/rust-openssl/pull/1866).

I echo @djc's surprise that this hasn't come up more often, since it seems like a very easy mistake to make in the OpenSSL API and so should be widespread. Perhaps it's because connecting via TLS bare IP addresses is relatively rare?

I'm in favor of closing this issue but inviting further comment on it (or 👍🏻) if other people run into the same problem, so we can gauge how widespread a problem it is.

**Comment by ctz** [comment]
I think we should watch for additional cases of this and see how much of a problem people find it in the field. We could, for example, slightly relax things by accepting all strings and moving the validation into `ClientHello::server_name`, `ServerConnection::server_name` and certificate selection, to continue the property that these functions only return valid DNS names. This would make buggy clients could still make connections and rustls would treat them as if they did not support SNI.
