### ISSUE TITLE
what does this error mean CertNotValidForName

### ISSUE THREAD

**Issue by EnricoMucelli** [rustls/rustls#1131]
i got this error what does it mean?
Error = Tls(Io(Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: CertNotValidForName") }))

this is my function: 

    #[cfg(feature = "use-rustls")]
    #[tokio::main]
    pub async fn test_mqtt() -> Result<(), Box<dyn Error>> {
        use rumqttc::{self, AsyncClient, Key, MqttOptions, TlsConfiguration, Transport};
    
        let mut mqttoptions = MqttOptions::new("test", "test.test.com", 1000);
        mqttoptions.set_credentials("test", test");
        mqttoptions.set_keep_alive(std::time::Duration::from_secs(5));
    
        let ca = include_bytes!("../certs/ca.crt");
        let client_cert = include_bytes!("../certs/client.crt");
        let client_key = include_bytes!("../certs/client.key");
    
        let transport = Transport::Tls(TlsConfiguration::Simple {
            ca: ca.to_vec(),
            alpn: None,
            client_auth: Some((client_cert.to_vec(), Key::RSA(client_key.to_vec()))),
        });
    
        mqttoptions.set_transport(transport);
    
        let (client, mut eventloop) = AsyncClient::new(mqttoptions, 10);

        client.subscribe("test/test/test", QoS::AtMostOnce).await.unwrap();
        client.subscribe("test/test/test/logs", QoS::AtMostOnce).await.unwrap();
        thread::spawn(move || {
                client.publish("test/test/test", QoS::AtLeastOnce, false, "test");
                client.publish("test/test/test/logs", QoS::AtLeastOnce, false, "test");
                thread::sleep(Duration::from_millis(100));
        });
    
        loop {
            match eventloop.poll().await {
                Ok(v) => {
                    println!("Event = {:?}", v);
                }
                Err(e) => {
                    println!("Error = {:?}", e);
                    break;
                }
            }
        }
    
        Ok(())
    }

**Comment by ctz** [comment]
> "test.test.com"

I don't think this is the real DNS name of the server you're connecting to? Either way the server's certificate should contain this name in it's subjectAltNames.
