### ISSUE TITLE
Passing certificate for client authentication in rustls::ClientConfig

### ISSUE THREAD

**Issue by ciclonite** [rustls/rustls#1136]
I have implemented these method and enabled "dangerous_configuration".
`struct SkipServerVerification;

impl SkipServerVerification {
    fn new() -> Arc<Self> {
        Arc::new(Self)
    }
}

impl rustls::client::ServerCertVerifier for SkipServerVerification {
    fn verify_server_cert(
        &self,
        _end_entity: &rustls::Certificate,
        _intermediates: &[rustls::Certificate],
        _server_name: &rustls::ServerName,
        _scts: &mut dyn Iterator<Item = &[u8]>,
        _ocsp_response: &[u8],
        _now: std::time::SystemTime,
    ) -> Result<rustls::client::ServerCertVerified, rustls::Error> {
        Ok(rustls::client::ServerCertVerified::assertion())
    }
}
`
Now, i want to use ClientConfig for creating a custom configuration :

`
fn configure_client() -> ClientConfig {
    let crypto = rustls::ClientConfig::builder().with_safe_defaults().with_custom_certificate_verifier(SkipServerVerification::new()).with_single_cert(client_cert.to_vec(), Key::RSA(client_key.to_vec()));
    rustls::ClientConfig::new(Arc::new(crypto))
}
`
I want to pass these certificate to ClientConfig:

`   let root_certs = include_bytes!("../certs/ca.crt");
    let client_cert = include_bytes!("../certs/client.crt");
    let client_key = include_bytes!("../certs/client.key");
`
How can i achieve this?
Thanks.

**Comment by djc** [comment]
I'm not clear on what you want to achieve, your issue has pretty bad formatting and you haven't made it clear how your current attempt fails to solve your problem -- so I'm not sure I can help you here.
