### ISSUE TITLE
Tweaking TLS

### ISSUE THREAD

**Issue by serzhiio** [rustls/rustls#1138]
Any recommendation how to tweak TLS for latency purposes? 
I have a lot of small constantly incoming packets and sometimes i see a lot of batches made by Rustls.

**Comment by djc** [comment]
How are you using the rustls API? I don't think the rustls API itself batches data. (In general, you have not provided much information about what you are doing or how you are doing it. Latency problems are not a well-known issue AFAIK.)

**Comment by serzhiio** [comment]
Sorry for not being very informative, but is it possible to control size of receive buffer at least?
What i do is just use `StreamOwned` stucture as reader and writer after i received `TcpStream`.
```
            Self::ClientSideTlsStream(tls) => {
                loop {
                    match tls.read(buf) {
                        Ok(0) => break ReadStatus::Disconnected,
                        Ok(size) => unsafe {
                            let data = buf.get_unchecked(..size);
                            //println!("===> {:?} => {}", data, std::str::from_utf8(data).unwrap());
                            callback(data);
                        }
                        Err(ref err) if err.kind() == ErrorKind::Interrupted =>
                            continue,
                        Err(ref err) if err.kind() == ErrorKind::WouldBlock => {
                            break ReadStatus::WaitNextEvent
                        }
                        Err(ref err) if err.kind() == ErrorKind::ConnectionReset => {
                            break ReadStatus::Disconnected
                        }
                        Err(_err) => {
                            break ReadStatus::Disconnected // should not happen
                        }
                    }
                }
            },
```
I know i can limit send buffer size. I just see that sometimes after one TlsRead i can receive 10 new WS packets, and another time you get one only WS packet after one TLS read. I do understand that underlying process of decryptions is complex, but is it possible to control "aggregation". Sorry for maybe silly question :)

**Comment by djc** [comment]
If you want tight control over latency you should probably just stay away from `StreamOwned` and instead feed the `ClientConnection` yourself using its lower-level APIs.

**Comment by serzhiio** [comment]
Thanks for advice, i've realized my own Stream Implementation.
How do you think is it possible to use SIMD or something to increase decryption? Or it is already built-in?

**Comment by serzhiio** [comment]
Here is a flamegraph of my app. All Tls stuff costs almost 17%.
![Снимок экрана от 2022-12-20 22-03-39](https://user-images.githubusercontent.com/10449591/208735402-3a180518-3b59-4b56-be9d-e882fb71a514.png)

**Comment by djc** [comment]
I've been working on that middle bump (reducing allocations). I think the core cryptography code (in `ring::aead`) is already pretty optimized and it's probably not easy to squeeze more performance out. There might be some inefficiencies in the rightmost bumps to address but it looks like most of the time there is spent in core networking code.

It's kind of expected that TLS is expensive relative to other parts of the network stack (we've seen this in benchmarks of our QUIC project, Quinn, as well). If you're working on Linux you might try kernel TLS support which might reduce some system call overhead.

**Comment by ctz** [comment]
If you have a large number of small messages it's quite expected that TLS's per-message processing overheads will cost more, compared to sending the same data in a smaller number of larger-length messages. An example of that in your flamegraph can be seen by comparing the size of `GFp_aesni_gcm_decrypt` (fused AES decrypt and ghash; the actual decryption part) versus the `GFp_memcmp` (which is a constant time comparison on 12 bytes; should be the order of ~hundreds of instructions per call)

**Comment by serzhiio** [comment]
> If you have a large number of small messages it's quite expected that TLS's per-message processing overheads will cost more, compared to sending the same data in a smaller number of larger-length messages. An example of that in your flamegraph can be seen by comparing the size of `GFp_aesni_gcm_decrypt` (fused AES decrypt and ghash; the actual decryption part) versus the `GFp_memcmp` (which is a constant time comparison on 12 bytes; should be the order of ~hundreds of instructions per call)

Yeah, i have tons of incoming small json messages.

**Comment by serzhiio** [comment]
So as per stats i spend 35us at tcp+tls and 10us to parse and process my msg. It would be nice to remove some micros from tcp+tls stack.

**Comment by ctz** [comment]
That does seem quite high, and ~29 thousand messages per second is poor. 

The benchmark programs in the repo show quite a lot more than this.

```
$ cargo test --no-run --release
(...)
$ BENCH_MULTIPLIER=0.1 ./target/release/examples/bench bulk TLS13_AES_128_GCM_SHA256 32 16384
bulk	TLSv1_3	TLS13_AES_128_GCM_SHA256	max_fragment_size:16384	send	75.66	MB/s
bulk	TLSv1_3	TLS13_AES_128_GCM_SHA256	max_fragment_size:16384	recv	53.47	MB/s
```

That's about 1.7 million 32-byte messages per second.

Note that this benchmarking does not include system calls, and that might be quite a large impact in your real-world case. When you call rustls's `read_tls` in your application, are you passing the TCP socket there, or have you wrapped it in a https://doc.rust-lang.org/std/io/struct.BufReader.html or similar?

**Comment by serzhiio** [comment]
I use pure `mio::net::TcpStream` but in `read_tls` but i believe it has no extra overhead.

**Comment by serzhiio** [comment]
Here is my bench, but machine is slow i believe:

> bulk	TLSv1_3	TLS13_AES_128_GCM_SHA256	max_fragment_size:16384	send	23.66	MB/s
> bulk	TLSv1_3	TLS13_AES_128_GCM_SHA256	max_fragment_size:16384	recv	21.60	MB/s
> bulk	TLSv1_3	TLS13_AES_128_GCM_SHA256	max_fragment_size:16384	send	23.67	MB/s
> bulk	TLSv1_3	TLS13_AES_128_GCM_SHA256	max_fragment_size:16384	recv	21.64	MB/s
> bulk	TLSv1_3	TLS13_AES_128_GCM_SHA256	max_fragment_size:16384	send	23.62	MB/s

**Comment by djc** [comment]
Okay, your machine is like 2-3x slower than @ctz's, but even at 22 MB/s it should be capable of handling 720k 32-byte messages per second, right? Which is closer to 1μs than 35μs, so it seems the overhead is in your I/O handling, not in the TLS code itself. Have you benchmarked your performance on the same `mio::net::TcpStream` code without TLS?

**Comment by serzhiio** [comment]
Actual data len:
![Снимок экрана от 2022-12-22 12-51-25](https://user-images.githubusercontent.com/10449591/209095618-bfe11b0d-6735-40fb-89a4-d5745633389c.png)
