### ISSUE TITLE
mips64el-unknown-linux-gnuabi64 support

### ISSUE THREAD

**Issue by cstkingkey** [rustls/rustls#1154]
cannot build this crate targeti
ng mips64el-unknown-linux-gnuabi64
first blocker is ring 0.16.20.
ring 0.17 which is not released seems working fine.

**Comment by djc** [comment]
I don't think it makes sense to keep this as an issue in this repository. This is entirely dependent on *ring*. We will upgrade to *ring* 0.17 once it is released. For now, you might be interested in #1108.
