### ISSUE TITLE
Show feature requirements in documentation

### ISSUE THREAD

**Issue by jsha** [rustls/rustls#1155]
Rustls has a number of items, like [ClientCertVerified](https://docs.rs/rustls/latest/rustls/server/struct.ClientCertVerified.html), that are available only with certain cargo features enabled (in this case, `dangerous_configuration`). These should get the "Available on crate feature `dangerous_configuration` only" annotation.

We do have some code that tries to get that annotation in place, specifically https://github.com/rustls/rustls/blob/be7b159ca66167fd9a0c20c3808c9a4d3a61ed31/rustls/src/lib.rs#L453-L455

And the corresponding code in Cargo.toml:

https://github.com/rustls/rustls/blob/be7b159ca66167fd9a0c20c3808c9a4d3a61ed31/rustls/Cargo.toml#L60-L62

However, in the end the docs that appear on docs.rs don't have the feature annotation. We should figure out why and fix it.

**Comment by jbr** [comment]
It looks like this doesn't work on the reexport, but does work on the original definition. Will open a PR moving those annotations

**Comment by jsha** [comment]
Reopening this for the `secret_extraction` and `tls12` features, which need `#[cfg_attr(docsrs, doc(cfg(feature = "secret_extraction")))]` and `#[cfg_attr(docsrs, doc(cfg(feature = "tls12")))]` annotations on all the items that they gate.

**Comment by cpu** [comment]
I think this is resolved by https://github.com/rustls/webpki/pull/123

**Comment by cpu** [comment]
Sorry, I think the relevant PR is https://github.com/rustls/rustls/pull/1395
