### ISSUE TITLE
Documented behavior was changed in patch release

### ISSUE THREAD

**Issue by thalesfragoso** [rustls/rustls#1165]
#1116 changed `read_tls` to respect a new limit imposed on the size of an internal buffer, returning an error in that situation. However, the documentation on that function implied that this couldn't happen:

> You should call process_new_packets each time a call to this function succeeds.
>
>The returned error only relates to IO on rd. TLS-level errors are emitted from process_new_packets.

With this documentation, one could expect that this function would never return an error if the provided `reader` was infallible (although that was only the case if the first sentence was respected). Now the documentation also mentions the need to empty the plaintext buffer through the connection reader, which wasn't strictly necessary before.

To be honest, I am not entirely sure that it's worth yanking the recent version over this, but nonetheless, I wanted to bring this (arguably) breaking change to light.

Another point is that rustls should probably provide a way to tune this limit now that it's enforced.

**Comment by bdaehlie** [comment]
Seems like we can close this issue.
