### ISSUE TITLE
Support SSL_set_ex_data to ServerConnection to fit async ecosystem

### ISSUE THREAD

**Issue by iamwwc** [rustls/rustls#1166]
I saw many use cases in issues that we want to have more control over rustls to integrate into async ecosystem.

Our certificates recevied from control panel, and we want to set different cert based on SNI and update at runtime. 

All certifcates maintain in `tokio::sync::RwLock`, but rustls `ResolvesServerCert` and many other trait defined in `ServerConfig` are `Sync`, which can't embed into async workflow.
https://docs.rs/rustls/latest/rustls/server/trait.ResolvesServerCert.html

Could we support openssl https://www.openssl.org/docs/man1.1.1/man3/SSL_set_ex_data.html to empower rustls callback trait?
we can set extra certificate in async workflow and then call rustls handshake, so that we can satisfy many async use case

The api should change to
```
pub trait ResolvesServerCert: Send + Sync {
    /// Choose a certificate chain and matching key given simplified
    /// ClientHello information.
    ///
    /// Return `None` to abort the handshake.
    fn resolve(&self, ssl: &mut SslConnection, client_hello: ClientHello) -> Option<Arc<sign::CertifiedKey>> {
        let cert = ssl.extra_data("certificate");
        return Some(Arc::new(cert))
    }
}
```
`client_hello` is useless for me, we have a tls client hello parse https://github.com/iamwwc/tunnel/blob/master/src/app/sniffer.rs#L91, which extract SNI from record, and then wrapper into other high level tls stream wrapper
https://github.com/iamwwc/tunnel/blob/af5ce758d74d092c9905d6c57957058f9998e61c/src/app/sniffer.rs#L186

**Comment by iamwwc** [comment]
relative issue https://github.com/rustls/rustls/issues/89

**Comment by djc** [comment]
The modern way to do this is with the [`Acceptor`](https://docs.rs/rustls/latest/rustls/server/struct.Acceptor.html). If you're using Tokio, you might want the tokio-rustls equivalent [`LazyConfigAcceptor`](https://docs.rs/tokio-rustls/latest/tokio_rustls/struct.LazyConfigAcceptor.html). This will give you a `ClientHello` type that exposes the SNI.

If you have additional constraints that mean you would like to have more methods fields on our `ClientHello` type, I'd be happy to hear your use case.

In my view, callbacks are usually not great, nor do I think that OpenSSL APIs are always the best example of how to model the solution to a problem. So we'd prefer to find a different solution to your use cases.

**Comment by iamwwc** [comment]
My use case is customize certificate verify. Every connection use different root cert store according to control panel information. In openssl, we set x509 store by set_extra_data before ssl handshake, fetch it in verify callback, then use the store in callback to complete handshake. 

How I can do this in rustls?

The only way I though to do is create serverconfig everytime, then  Arc::new(serverconfig), set it in server_connection, but it cause heap allocation in every handshake

**Comment by djc** [comment]
Did you look at the documentation for the acceptors that I linked to?

**Comment by iamwwc** [comment]
Yes, I have read all acceptor, accepted api, but I'm not sure how compose apis to implement

**Comment by iamwwc** [comment]
We are  gateway like nginx, others can  choose different domain name to use, also we can change configuration dynamically, for example, change to different root ca, different alpn decision which all cause to regenerate serverconfig everytime, serverconfig live behind Arc, I can't get mut after clond it. Full regenerate Arc<serverconfig>  isn't a good idea I think

> Making one of these can be expensive, and should be once per process rather than once per connection.

**Comment by djc** [comment]
Why don't you think it's a good idea to generate per-client ServerConfigs? It doesn't seem like a big deal to me.

**Comment by iamwwc** [comment]
I just follow docs said https://docs.rs/rustls/latest/rustls/server/struct.ServerConfig.html
> Making one of these can be expensive, and should be once per process rather than once per connection.

**Comment by djc** [comment]
If you're worrying at this level, run a benchmark and check for yourself what the performance is like. The performance will vary depending on how many of the configuration options in the `ServerConfig` you actually need to use.

I'm going to close this now, since I haven't seen any use cases that I don't think we can serve right now.
