### ISSUE TITLE
Make Codec::read return Result instead of Option

### ISSUE THREAD

**Issue by jbr** [rustls/rustls#1170]
## Motivation

Currently, `Codec::read` returns an Option, meaning that there is no way to attach failure reasons to the None path to propagate up to the calling library. This results in rustls yielding generic IO errors, like `Error: Io { source: Custom { kind: InvalidData, error: CorruptMessagePayload(Handshake) } }`

## Proposal

Making `Codec::read` and callers of `Codec::read` return Result instead of Option would allow us to attach more details to a CorruptMessagePayload, including specific error enum variants that have further documentation. Instead of the above `CorruptMessagePayload(Handshake)` error, library users might see `CorruptMessagePayload(Handshake, DecodeError::MessageTruncated)` or `CorruptMessagePayload(Handshake, DecodeError::UnusedTrailingBytes)` or `CorruptMessagePayload(Handshake, DecodeError::UnsupportedIpAddressHostname)`, each of which would have documentation on possible causes.

## Implementation approach

Initially, I propose returning a single Error enum with minimal variants. Over time, we can elaborate that enum to have more verbose and specific variants to describe Codec failure states.

## Variations

We might want to use an associated Codec::Error type, but as many higher order Codec implementations compose other `Codec::read`s, this might entail ungainly complexity.

## Relevant issues:

* This would provide a direct path towards better error reporting for #206
* This might help address the motivation behind #1043, in that the Error enum might have an attached backtrace.

**Comment by djc** [comment]
This sounds good to me.

**Comment by djc** [comment]
I think you meant to link to #1198.

**Comment by cpu** [comment]
Yes, thank you! Fixed with an edit. Copy pasta error :spaghetti:
