### ISSUE TITLE
InternalError when re-using ClientConfig

### ISSUE THREAD

**Issue by CBenoit** [rustls/rustls#1186]
Hi,

I’m having an error when attempting to re-use the same `ClientConfig` for multiple connections.

[`ClientConfig` doc](https://docs.rs/rustls/0.20.8/rustls/struct.ClientConfig.html) states the following:

> Making one of these can be expensive, and should be once per process rather than once per connection.

In order to reuse the `ClientConfig`, I decided to use `lazy_static`:
```rust
lazy_static::lazy_static! {
    static ref TLS_CLIENT_CONFIG: Arc<ClientConfig> = ClientConfig::builder()
        .with_safe_defaults()
        .with_custom_certificate_verifier(std::sync::Arc::new(
            crate::utils::danger_transport::NoCertificateVerification,
        ))
        .with_no_client_auth()
        .pipe(Arc::new);
}
```

(I’m using a custom certificate verifier but I don’t think that’s relevant here.)

And then use the config later like so:
```rust
        let dns_name = "stub_string".try_into().unwrap();
        let tls_connector = tokio_rustls::TlsConnector::from(TLS_CLIENT_CONFIG.clone());
        tls_connector.connect(dns_name, server_transport).await?
```

However, I’m getting this error:
```
AlertMessagePayload {
    level: Fatal,
    description: InternalError,
}
```

Full code available [here](https://github.com/Devolutions/devolutions-gateway/blob/4cecff2c1e96fb3478303510ad9126aeaa39c04f/devolutions-gateway/src/rdp_extension.rs).

This only happens when I reuse the `ClientConfig`. When I create a new `ClientConfig` for each connection there is no problem.

**Comment by djc** [comment]
I would say the expensive part of building a `ClientConfig` is typically building the verifier, so there might be ways to mitigate this issue by rebuilding a `ClientConfig`.

The rustls handshake state machine will always clone the `Arc<ClientConfig>` (which means it's already not rebuilding, but just increasing a reference count), so it seems quite unlikely that this alone would result in different configuration being sent to the server. Maybe you can get a pcap from a failing vs a successful connection to diagnose where the difference is coming from?

**Comment by cpu** [comment]
@CBenoit I think we're blocked here on more diagnostic information. Is that something you're able to follow up on?

**Comment by CBenoit** [comment]
Sorry for the delay. I captured the traffic in pcap files: [captures.zip](https://github.com/rustls/rustls/files/11255729/captures.zip)
I see the `Server Hello` message is significantly smaller in the second connection (197 bytes vs 1267 in the first one).

**Comment by cpu** [comment]
> I see the Server Hello message is significantly smaller in the second connection (197 bytes vs 1267 in the first one).

@CBenoit The `2.pcapng` capture shows the server resuming a session, which explains the size difference (w/ resumption the server doesn't send a certificate which constitutes most of the bytes in `1.pcapng`'s initial server reply). The client sends back a CCS message and an encrypted handshake message and the server produces the encrypted alert you observe. 

Is there anything notable about the server software? Is it also a Rustls based TLS stack? It would be interesting to know if [disabling session resumption](https://docs.rs/rustls/latest/rustls/client/struct.Resumption.html#method.disabled) allows you to re-use the client config w/o error.

**Comment by jsha** [comment]
Good question about the server stack. My understanding based on the error message @CBenoit shared is that it's actually the server sending a TLS "InternalError" alert. So something in the server is failing on session resumption - maybe it has session resumption configured incorrectly, and can't resume; or maybe it doesn't like something about how rustls presents the resumption.

One thing that's a little surprising to me is seeing "AlertMessagePayload" in a public facing error. I would have expected to see [`Error(AlertDescription(InternalError))`](https://docs.rs/rustls/latest/rustls/enum.AlertDescription.html). [`AlertMessagePayload`](https://docs.rs/rustls/latest/rustls/internal/msgs/alert/struct.AlertMessagePayload.html) is internal.

**Comment by cpu** [comment]
>  My understanding based on the error message @CBenoit shared is that it's actually the server sending a TLS "InternalError" alert. 

Agreed - that's what I meant by "the server produces the encrypted alert you observe." if it wasn't clear.

**Comment by CBenoit** [comment]
> > I see the Server Hello message is significantly smaller in the second connection (197 bytes vs 1267 in the first one).
> 
> @CBenoit The `2.pcapng` capture shows the server resuming a session, which explains the size difference (w/ resumption the server doesn't send a certificate which constitutes most of the bytes in `1.pcapng`'s initial server reply). The client sends back a CCS message and an encrypted handshake message and the server produces the encrypted alert you observe.

I have to admit, I wasn’t aware this was enabled by default. I understand this is a useful default in most cases but,

> Is there anything notable about the server software?

Yes, it is an RDP server, and TLS session resumption is explicitly _not_ supported.

This is not a rustls bug :)

Thank you all for the insight!

**Comment by CBenoit** [comment]
For reference:
![image](https://user-images.githubusercontent.com/3809077/234900275-b9e17f46-0f5d-426e-9d8d-eb2a70423784.png)
