### ISSUE TITLE
0.21.0 release planning

### ISSUE THREAD

**Issue by djc** [rustls/rustls#1191]
@ctz do you have a plan for getting to a 0.21.0 release?

Need to get out the rustls-webpki release:

- [x] https://github.com/rustls/webpki/issues/35

The following in-progress PRs have semver-incompatible changes:

- [x] #1198
- [x] #1172
- [x] #1211
- [x] #1189

These other PRs would also be good to get in:

- [x] #1199 
- [x] #1150 (no public API changes)
- [x] #1179
- [ ] #1190 (if we decide we want it)

**Comment by ctz** [comment]
I've been using github projects for this: https://github.com/orgs/rustls/projects/2/views/1 -- i've updated that with the list here.

**Comment by athola** [comment]
any timeline on when this release should be expected? don't intend on rushing your excellent work, however do want to be able to plan out our next few sprints and advise our team to use hostnames instead of IP address for SANs until we can work in this release

**Comment by djc** [comment]
@ctz we don't really have a timeline. I'd expect it to be some time between 1 and 6 weeks from now.

**Comment by athola** [comment]
thank you! please let me know if any assistance is needed with testing/documentation

**Comment by djc** [comment]
Added #1198 and #1199 to the list (and the project board).

**Comment by cpu** [comment]
>  Reworked export_keying_material interface to be safer for the end user #1159

@djc Could you replace 1159 with https://github.com/rustls/rustls/pull/1211 in the list/project board when you have a chance?

**Comment by djc** [comment]
Added https://github.com/rustls/webpki/issues/35 to the list.

**Comment by djc** [comment]
We're considering blocking the release on #1216, which changes the public API for QUIC. That should really be the final PR I'm aware of at this point.

**Comment by djc** [comment]
Release preparation in https://github.com/rustls/rustls/pull/1262.

**Comment by cpu** [comment]
We've released 0.21.0 :tada:
