### ISSUE TITLE
Internal tooling performance concerns

### ISSUE THREAD

**Issue by edwardwc** [rustls/rustls#1196]
After a flood of incoming requests, certain internal tools Rustls uses such as `GFp_bn_sqrx8x_internal`, ` mulx4x_internal` and ` _aesni_ctr32_ghash_6x`[^2] consume very unreasonable amounts of CPU[^1]. See below:
<img width="496" alt="Screen Shot 2023-02-12 at 10 38 05 AM" src="https://user-images.githubusercontent.com/76141700/218320901-c9be1e61-c75c-4332-a760-a5cc5481605f.png">

[^1]: As measured by [_pprof_](https://crates.io/crates/pprof)
[^2]: As shown in the profile in [PDF format](https://github.com/rustls/rustls/files/10716430/profile010.pdf)

**Comment by ctz** [comment]
Could you clarify how many incoming connections are covered by this profiling? If I'm interpreting this correctly, it seems like over 122.23s of profiled cpu time, we're spending 1.38s doing RSA and 0.45s doing AES-GCM? That is less than 1.5% CPU time doing TLS? Seems pretty reasonable?

**Comment by edwardwc** [comment]
Sure! There were ~4k incoming connections per second. The 122.23s is not the CPU time--it is the time, in seconds, that the profiler has been running. The CPU time measured is 7.37s. These 3 internal tools alone consumed 1.74 seconds, or approximately 25% (1.74/7.37) of CPU time consumed. Perhaps it would be helpful to understand what GFp_bn_sqrx8x_internal, mulx4x_internal and  _aesni_ctr32_ghash_6x are for?

**Comment by djc** [comment]
These are operations internal to the cryptographic primitives that are used for the handshake and encrypting the data. It would be useful to see the ClientHello stack trace expanded. What CPU architecture are you running this on? Does it have AES-NI? Have you tried enabling different key exchange groups and/or cipher suites as part of the configuration setup?

**Comment by ctz** [comment]
> Perhaps it would be helpful to understand what GFp_bn_sqrx8x_internal, mulx4x_internal and _aesni_ctr32_ghash_6x are for?

The first two are part of the server using an RSA key to sign the handshake (slight simplification) which is the most expensive operation a TLS server has to do.

The last one is CPU accelerated AES-GCM; this is extremely fast but used for all data encryption/decryption. If rustls is doing a good job at performance, this would account for all the CPU usage of it (and your data would be being encrypted/decrypted at line rate of the network connection).

Suggestions:
- Make sure your RSA key is not wildly huge (2048- to 3072-bit). RSA performance scales roughly with the square of the bit length (so reconsider a 4096-bit or 8192-bit key if you are concerned about performance)
- Check clients are resuming sessions where possible, as this is much cheaper for the server. We can do ~hundreds of full handshakes per core, but ~tens of thousands of resumptions per core.

**Comment by cpu** [comment]
@edwardwc Were the suggestions above enough to address your performance concerns?

**Comment by cpu** [comment]
I'm going to close this issue for now since there are outstanding suggestions to consider and it doesn't appear actionable from our side at this time.
