### ISSUE TITLE
bench.rs improvements

### ISSUE THREAD

**Issue by cpu** [rustls/rustls#1205]
Let's chat about the future of `bench.rs` and with the goal of splitting out smaller tasks.

### Background

In https://github.com/rustls/rustls/pull/1203 we discussed the [admin/bench-range](https://github.com/rustls/rustls/blob/1ee4a2ba92befd02386341c9036d5e872a47a3c4/admin/bench-range) tool (written in bash) and concluded its functionality could be folded into the [rustls/examples/internal/bench.rs](https://github.com/rustls/rustls/blob/main/rustls/examples/internal/bench.rs) tool.

### Discussion

Adding support for this feature to `bench.rs` as written is certainly possible, but the complexity of the [`selected_tests`](https://github.com/rustls/rustls/blob/1ee4a2ba92befd02386341c9036d5e872a47a3c4/rustls/examples/internal/bench.rs#L571-L640) function is getting larger. Concurrently, the Prossimo initiative updated [the Rustls work plan](https://www.memorysafety.org/initiative/rustls/rustls-work-plan/) to include "Comprehensive performance benchmarking", a goal that is likely to include more development of `bench.rs`.

It may be worth evaluating separating the benchmark example into its own crate, and having that new create depend on an external 3rd party crate (maybe [clap](https://github.com/clap-rs/clap)?) that can offer richer command line argument semantics. This would let us clean up the `selected_tests` function, making it easier to express submodes and optional parameters specific to certain modes and focusing our efforts on the benchmarking specific code. 

Is that something the maintainers would appreciate or should we keep things simple and lift `bench-range`'s functionality into the existing code without larger rework? I'm newer to the broader Rust ecosystem and might be underestimating the challenge of introduce a benchmark specific crate, or the cost of a dependency like clap.

**Comment by djc** [comment]
Using clap is great, but it pushes the MSRV (minimum supported Rust version) fairly aggressively so keeping it in the same crate/repo makes doing CI that checks the (more conservative) MSRV for the library a little harder.

I think we should discuss what the goals are for "Comprehensive performance benchmarking"? I think there are two:

* Assessing how rustls performance is changing over time, to make sure rustls doesn't get substantially slower over time (and ideally becomes faster)
* Assessing how rustls performance compares to other implementations, probably specifically OpenSSL (see [openssl-bench](https://github.com/ctz/openssl-bench))

Presumably for some (potential) users, lower latencies (especially on handshakes) and lower memory usage are potentially interesting selling points.

The ideal state here would be some setup (which probably warrants using a separate repo) that can pull in the rustls bench tools and [openssl-bench](https://github.com/ctz/openssl-bench) to build tables and/or charts with minimal effort, so we can regularly create performance reports.

**Comment by cpu** [comment]
> Using clap is great, but it pushes the MSRV (minimum supported Rust version) fairly aggressively so keeping it in the same crate/repo makes doing CI that checks the (more conservative) MSRV for the library a little harder

That's a good point :+1: 

> I think we should discuss what the goals are for "Comprehensive performance benchmarking"? I think there are two:

I haven't spoken with @bdaehlie on this topic but I think these two goals are in-line with the spirit of the goal.

> The ideal state here would be some setup (which probably warrants using a separate repo) that can pull in the rustls bench tools and [openssl-bench](https://github.com/ctz/openssl-bench) to build tables and/or charts with minimal effort, so we can regularly create performance reports.

This is sounding good to me. One Q: Are you imagining that the Rustls bench tool will remain in this repo? I think to be able to make the tooling more ergonomic we'll want to pull it into the separate repo. I took a casual look and it seems like the `bench.rs` code is only using public imports. It also doesn't look like it's invoked in any of the existing CI workflows.

**Comment by bdaehlie** [comment]
The two bullet points from @djc very accurately encapsulate our/my interest in the benchmarking system.

**Comment by ctz** [comment]
> It also doesn't look like it's invoked in any of the existing CI workflows.

https://github.com/rustls/rustls/actions/runs/4322398028/jobs/7544765833 - We have a "smoke test" of it, but that is mainly to ensure the program doesn't rot to the extent that it starts panicking (etc) and nothing is done with the results.

**Comment by djc** [comment]
> This is sounding good to me. One Q: Are you imagining that the Rustls bench tool will remain in this repo? I think to be able to make the tooling more ergonomic we'll want to pull it into the separate repo. I took a casual look and it seems like the `bench.rs` code is only using public imports. It also doesn't look like it's invoked in any of the existing CI workflows.

Moving it to a separate repo could make sense to me. Maybe rename the openssl-bench repo to tls-bench, and make it the focal point of our benchmark infrastructure?

**Comment by aochagavia** [comment]
I have created https://github.com/rustls/rustls/issues/1385 as a spin-off of this issue, concentrated on djc's first bullet point. Initial research gives me a strong impression that each bullet point needs a different benchmarking approach. I'll be investigating further and report my findings here.

**Comment by djc** [comment]
> Does this sound reasonable?

Sounds like a good start to me!

**Comment by ctz** [comment]
>  Does this sound reasonable?

Yes, definitely. There is `admin/bench-range` and `admin/bench-measure.mk` from back then which may (or mostly likely not) be useful. Please feel free to delete them if they become superceded!

**Comment by jsha** [comment]
In addition to the above good plan, it would be good to start benchmarking concurrent operation which I think is what most end-users care about in practice. For instance, per https://github.com/rustls/rustls/issues/1200 there may be performance problems in the default ServerSessionMemoryCache that can only be exercised in concurrent operation. And there may be other interesting effects on CPU caches when many connections are handled together.

One approach to this might be: use a web server like `hyper` that supports both rustls and openssl, and send traffic to it using an HTTP benchmarking tool like [wrk2](https://github.com/giltene/wrk2). This would make for a more holistic benchmark that could cover both handshakes and transfer. Though from a quick peek at wrk2 it's not clear to me whether it supports session resumption; that would be something to add in.

**Comment by aochagavia** [comment]
@jsha now you mention it, concurrent operation sounds like a very interesting addition to @ctz's original benchmarks. At the same time, it will be challenging to come up with a setup that is resistant to noise and produces actionable insights. I'll give it some thought in the coming days.

In the specific case of #1200 I think a microbenchmark that only exercises the cache might yield more insights and allow us to compare alternative implementations with confidence. I'll be experimenting with that approach and see how it goes!

**Comment by cpu** [comment]
I think the more detailed issues @aochagavia has been filing are a better place to carry future benchmarking discussion forward. This one predates that work and I'm not sure it remains actionable.
