### ISSUE TITLE
feature flag additionality problem for ClientSessionStore

### ISSUE THREAD

**Issue by jsha** [rustls/rustls#1224]
The ClientSessionStore introduced in #1145 [defines remove_tls12_session as optional](https://github.com/rustls/rustls/blob/fb9e181a1a777bc2f42bd7c172be1ebddb3b68fa/rustls/src/client/client_conn.rs#L65-L71) for `not(feature = "tls12")` and required for `feature = "tls12"`. Given the additivity of feature flags, that can result in this bad scenario:

 - a binary depends on rustls with `no-default-features` and provides an implementation of ClientSessionStore that doesn't define `remove_tls12_session`.
 - the binary comes to (transitively) depend on some other crate that depends on rustls with the default features.
 - the binary no longer compiles, because `remove_tls12_session` is required.

[The cargo book says](https://doc.rust-lang.org/cargo/reference/features.html?#feature-unification):

> A consequence of this is that features should be additive. That is, enabling a feature should not disable functionality, and it should usually be safe to enable any combination of features. A feature should not introduce a [SemVer-incompatible change](https://doc.rust-lang.org/cargo/reference/features.html?#semver-compatibility).

There's a similar (actually worse) problem with `set_tls12_session` and `tls12_session`. For non-tls12 builds, they are not part of the trait and so are forbidden. But if the tls12 feature is added into the build, they become required.

I think the most straightforward fix would be to make `set_tls12_session`, `tls12_session,` and `remove_tls12_session` required regardless of feature flags. An implementation that does not want to deal with TLS 1.2 can make it a no-op.

**Comment by cpu** [comment]
> I think the most straightforward fix would be to make set_tls12_session, tls12_session, and remove_tls12_session required regardless of feature flags. An implementation that does not want to deal with TLS 1.2 can make it a no-op.

:thinking:  Without making a change to the return types I think we might end up having to chase the `tls12` feature down through the interface to make this workable. Right now the TLS 1.2 portions of the trait relies on `Tls12ClientSessionValue`, which in turn has a `Tls12CipherSuite` member. Both of those types are also behind the tls 1.2 feature flag.

**Comment by ctz** [comment]
i'd suggest we keep `Tls12ClientSessionValue` as a type irrespective of the feature, but remove its methods and cipher suite member (to cut off the contagion of the feature past that point).
