### ISSUE TITLE
Use a pkcs12 / pfx cert bundle...

### ISSUE THREAD

**Issue by svanharmelen** [rustls/rustls#1271]
I noticed this format isn't supported, but do you maybe know of a crate that can read the cert, key and CA cert that we have in our bundles so that we can use them with `ruslts`?

Only way I currently think this could (maybe) be done, is by using the `openssl` crate to first read and parse the bundle, then export them individually (to der encoded bytes) and then read/parse them again using `rustls`.

Sound a bit nasty and inefficient so wondered if there's a better way...

**Comment by djc** [comment]
Maybe review https://github.com/rustls/pemfile/issues/17 for solutions?

**Comment by svanharmelen** [comment]
Thanks for the pointer! Having a look/chat there as well 😄

**Comment by cpu** [comment]
Let's consolidate discussion on this topic in rustls/pemfile since it seems most germane to that repository.
