### ISSUE TITLE
OSS-Fuzz corpus improvement

### ISSUE THREAD

**Issue by guidovranken** [rustls/rustls#1287]
I've done some fuzzing of your `client` fuzzer and improved the corpus to the extent that its code coverage has increased by ~10%.

I want to do the following:

- Create a Github repo
- Upload the upgraded corpus to this repo
- Update the build script for rustls on OSS-Fuzz to dowload the corpus, and use it as a seed corpus
- Your OSS-Fuzz code coverage should now be ~10% higher, which makes it more likely to hit bugs

Do you agree that I do this?

**Comment by djc** [comment]
Sounds like a nice improvement! Does this mean the repo-hosted corpus increases in size? By how much?

**Comment by guidovranken** [comment]
> Sounds like a nice improvement! Does this mean the repo-hosted corpus increases in size? By how much?

The corpus is 38MB uncompressed. I've stored it here: https://github.com/guidovranken/rustls-fuzzing-corpora. I can transfer it to your organization if you want.

A PR has been made to OSS-Fuzz which enacts this corpus upgrade.

**Comment by guidovranken** [comment]
Done.

Old coverage:
- URL: https://storage.googleapis.com/oss-fuzz-coverage/rustls/reports/20230428/linux/report.html
- Total line coverage: 28.11%

New coverage:
- URL: https://storage.googleapis.com/oss-fuzz-coverage/rustls/reports/20230429/linux/report.html
- Total line coverage: 31.06%

31.06 / (28.11 / 100.0) = 110.49, e.g. a 10%+ increase in line coverage.

**Comment by djc** [comment]
Great, thanks!
