### ISSUE TITLE
Adding NIST PQ algorithms?

### ISSUE THREAD

**Issue by mouse07410** [rustls/rustls#1294]
Not a bug report, but a question.

When do you plan to add NIST KEM and Signature algorithms (at least, Kyber and Dilithium) to the codebase?

E.g., for OpenSSL, there's [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) repo.

**Comment by cpu** [comment]
Hi,

Rustls doesn't provide any cryptographic algorithms on its own. It uses *ring* for this. I see you already opened an issue for this request there: https://github.com/briansmith/ring/issues/1452 I don't believe any progress has been made on that ticket.

Likely the most realistic way for Rustls to get PQ support is via https://github.com/rustls/rustls/pull/1184 and supporting an alternative cryptographic backend that has support already.

**Comment by cpu** [comment]
> Something similar in the idea to OpenSSL Provider API?

In spirit if not in mechanism, yes.

I'm going to close this issue since it isn't something we can accomplish in Rustls and there are already tracking issues for *ring* PQ support, and for pluggable backends in Rustls.

Thanks!

**Comment by mouse07410** [comment]
Sure. Where is the API for rustls plugins ("providers" in OpenSSL lingo) described? Are there examples of such plugins to serve as tutorials?

**Comment by djc** [comment]
That is not implemented yet. See #521 and #1184.
