### ISSUE TITLE
`Iterator` support for `RootCertStore::add_parsable_certificates()`

### ISSUE THREAD

**Issue by daxpedda** [rustls/rustls#1304]
I've noticed that a couple of implementations out there, when trying to use [`rustls_native_certs::load_native_certs()`](https://docs.rs/rustls-native-certs/0.6.2/rustls_native_certs/fn.load_native_certs.html), write their own [`RootCertStore::add_parsable_certificates()`](https://docs.rs/rustls/0.21.1/rustls/struct.RootCertStore.html#method.add_parsable_certificates) because `rustls_native_certs::load_native_certs()` doesn't return `[Vec<u8>]` but rather `[Certificate]`. See [`reqwest` for example](https://github.com/seanmonstar/reqwest/blob/06c8e5b0b008afee8114fb979b85cd8b73415391/src/async_impl/client.rs#L399-L424).

I think this could be easily addressed by improving the API to take an `Iterator` instead of a `&[Vec<u8>]`. Though this is a breaking change, so I will leave this here to be addressed in the next version.

**Comment by djc** [comment]
Maybe we should support any `impl AsRef<[u8]>`?

**Comment by daxpedda** [comment]
Indeed, I just realized that both [`RootCertStore::add()`](https://docs.rs/rustls/0.21.1/rustls/struct.RootCertStore.html#method.add) and [`RootCertStore::add_parsable_certificates()`](https://docs.rs/rustls/0.21.1/rustls/struct.RootCertStore.html#method.add_parsable_certificates) don't actually need ownership of the bytes.

It might also be good to adjust the API of `RootCertStore::add()` to take `AsRef<[u8]>` as well then.

**Comment by djc** [comment]
We can probably change `add_parsable_certificates()` to take `&[impl AsRef<[u8]>]` instead of `&[Vec<u8>]` today, since `Vec<u8>` implements `AsRef<u8>`. Maybe restricting `add()` to the more strongly typed `key::Certificate` might still have some utility?

**Comment by daxpedda** [comment]
> We can probably change `add_parsable_certificates()` to take `&[impl AsRef<[u8]>]` instead of `&[Vec<u8>]` today, since `Vec<u8>` implements `AsRef<u8>`.

Sure, I can make a PR for that.

> Maybe restricting `add()` to the more strongly typed `key::Certificate` might still have some utility?

The only annoying thing about `key::Certificate` is that it requires ownership because `key::Certificate` requires a `Vec`. But personally I don't have a stake in this, my only concern was with `rustls-native-certs` which is solved by the above.

**Comment by cpu** [comment]
Based on the above comments I think this can be closed. If I'm wrong and there's more work to consider please comment and I can reopen!

**Comment by daxpedda** [comment]
#1305 changes `RootCertStore::add_parsable_certificates()` to take a `&[impl AsRef<[u8]>]`. This was done to avoid any breaking changes.

The issue was still left open because we ultimately want to change it to `impl Iterator<Item = &[u8]>`.

**Comment by cpu** [comment]
Thanks, my mistake :-)

> The issue was still left open because we ultimately want to change it to `impl Iterator<Item = &[u8]>`.

Since there's already a breaking change in `main` (removal of the SCT code), could this land now in preparation for a release? Would you be interested in writing the PR?

**Comment by daxpedda** [comment]
Done in #1339.
