### ISSUE TITLE
LazyConfigAcceptor does not allow access to io stream after acceptor.await error result

### ISSUE THREAD

**Issue by jacott** [rustls/rustls#1308]
tokio_rustls: 0.24.0

I Need a way to retrieving the `io` stream if an error occurs on `acceptor.await`.

An example of this is when a client tries to connect to an TLS socket expecting it to be plain text connection. In this case I would like to be able to send a 400 response, "_The plain HTTP request was sent to HTTPS port_", back to the client.

Maybe the `io` field could be attached to the error result?

**Comment by jacott** [comment]
Or maybe a callback could be supplied to `LazyConfigAcceptor` that is called only on error and has the moved `io` as an argument?

**Comment by jacott** [comment]
As a hack I changed the `Output` type to return a tuple on error: `type Output = Result<StartHandshake<IO>, (io::Error, IO)>;` and this allowed me to respond to the client correctly.

**Comment by djc** [comment]
Thanks for your feedback. Want to submit a PR for the `Output` type change? It sounds reasonable to me.

**Comment by jacott** [comment]
I've realized that I have created this issue on the wrong repository 🤦🏻 

I have created  https://github.com/tokio-rs/tls/pull/144 

I will close this issue since it is in the wrong repo.
