### ISSUE TITLE
rustls incorrectly reports UnknownIssuer instead of Unsupported Signature

### ISSUE THREAD

**Issue by rwthompsonii** [rustls/rustls#1335]
Steps to reproduce:

1) innocently use a cert in your chain
2) have that cert use 512 algorithm
3 ) cry in your beer when it reports UnkonwnIssuer and sends you on a wild goose chase for days

**Comment by ctz** [comment]
I think we've recently fixed this in https://github.com/rustls/webpki/issues/79

**Comment by cpu** [comment]
+1 - that work hasn't been brought over to Rustls quite yet but I expect it will be soon :tm:

**Comment by cpu** [comment]
Webpki was updated to 0.101.x with Rustls v/0.21.3. I believe we should now surface a better error for this case.
