### ISSUE TITLE
hyper UnsupportedNameType error

### ISSUE THREAD

**Issue by Masber** [rustls/rustls#1337]
Hi, I have a hyper client with rustls which is throwing the error below... is this related to the fact that the client does not have access to the CA root which signed the server certificates?
```
Err(
    HyperError(
        hyper::Error(
            Connect,
            Ssl(
                Error {
                    code: ErrorCode(
                        1,
                    ),
                    cause: Some(
                        Ssl(
                            ErrorStack(
                                [
                                    Error {
                                        code: 337047686,
                                        library: "SSL routines",
                                        function: "tls_process_server_certificate",
                                        reason: "certificate verify failed",
                                        file: "ssl/statem/statem_clnt.c",
                                        line: 1919,
                                    },
                                ],
                            ),
                        ),
                    ),
                },
                X509VerifyResult {
                    code: 20,
                    error: "unable to get local issuer certificate",
                },
            ),
        ),
    ),
)
```

**Comment by djc** [comment]
Those errors are not from rustls -- I guess you're actually using native-tls instead?

**Comment by Masber** [comment]
probably I configured the hyper-socks2 incorrectly...

I tried this instead:

```
hyper-socks2 = { version = "0.7.0", default-features = false, features = ["rustls"] } # needed by kube-rs (to operate with kube api) 
```

And now I am getting something different

```
Err(
    HyperError(
        hyper::Error(
            Connect,
            Custom {
                kind: Other,
                error: Custom {
                    kind: InvalidData,
                    error: UnsupportedNameType,
                },
            },
        ),
    ),
)
```
Is this a rustls error?

**Comment by djc** [comment]
Yes: https://docs.rs/rustls/latest/rustls/enum.Error.html#variant.UnsupportedNameType.

**Comment by ctz** [comment]
rustls no longer produces that error, because (as of 0.21.0) all name types that can be written are supported. I guess you are on 0.20.x and are using IP address names -- upgrade to 0.21.x and things will start working.

**Comment by Masber** [comment]
ok, I have updated my dependencies and they use `rustls v0.21.2`, now I see this new error:

```
thread 'shasta::kubernetes::test::my_test' panicked at 'called `Result::unwrap()` on an `Err` value: LoadCertificateAuthority(DecodeBase64(InvalidPadding))', src/shasta/kubernetes.rs:283:14
```
I am using self-signed certificates (local CA) and mutual TLS to communicate my rust client with the k8s API server, my CA root cert is just a string of chars, I believe this is not DEF format, also the CA cert neither includes `-----BEGIN CERTIFICATE-----` nor `-----END CERTIFICATE-----`

**Comment by cpu** [comment]
@Masber could you share the CA certificate file you're providing to your code? It won't be sensitive to share without the corresponding private key.

**Comment by Masber** [comment]
I found the issue, as the error says, the CA cert I am passing does not have the padding. I tested this:

```
echo "--CA CERT--" | base64 -d # outputs the valid cert but noticed the command also says `base64: invalid input`
```

If I do 

```
echo "--CA CERT--" | base64 -d | base64
```

Then I get the same CA cert base64 string but with padding (`==`) as a suffix, so I believe the problem is that I copied the CA cert from the kubeconfig file which does not have the padding, I could add the padding manually but this won't scale, is there a method I can use to automatically add the padding to the base64 encoded string?

**Comment by cpu** [comment]
You can probably handle this programmatically by re-encoding with the [`base64` crate](https://docs.rs/base64/latest/base64/) and an engine config something like this (untested): 

```rust
let fix_padding_config = engine::GeneralPurposeConfig::new()
    .with_decode_padding_mode(engine::DecodePaddingMode::Indifferent);
    .with_encode_padding(true)
 ```
 
 I think perhaps the scope of your problem has moved beyond Rustls at this point?

**Comment by Masber** [comment]
Not yet :)

Now I get another error (after fixing the padding)

```
Err(
    HyperError(
        hyper::Error(
            Connect,
            Custom {
                kind: Other,
                error: Custom {
                    kind: InvalidData,
                    error: InvalidCertificate(
                        UnknownIssuer,
                    ),
                },
            },
        ),
    ),
)
```

To simplify things, here is the certificate:

```
LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EVXpNVEE0TXpjME9Gb1hEVE15TURVeU9EQTRNemMwT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGVXClJwS0w1anlYZitVMzlqbkJOUmVPTzRmQm0wUWY2WGVmUFc2dC85MXBVcE5WL3JuRmF1L3RTcnpjQzZQL2xSUkcKU0ZUV0RkQmJoK1haQ1BlL3Fvc091UUZReGV0THNjZDJvMjJmekoxZ2RQQXVITDBXYi9zL0F1KzBRN3djOTQ0ZgpEQXZBeXFIWER0aE1Oa1A3KzFRS0ZBY0FtN0c2N1VTaWpYMEpzeTkvM2p6c3V0b05RQlVYMjkvb1YwZHdsK3dlCnBXT2lteE8reGpGM0lIL0FJcWlobXNHMHAzbkl3dUdmR0hYejJHNERxc2w4S1BRaHhlWmpOcG5FaFFWMktZYk4KMEFmVkNhbWIwcGdDVmR3MGg0MjF4c3I5d0JDQURvZWpQeFUyS0xwSHc1VUxmblkrZUZlOUZwTjdpQlo0K3gyMAplVmNvdkZ5WVU4eU5RbjgySEZrQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZIT3dYTnZHQm01bmpMZDY1WGlaaWxabzJ3NDVNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBNXJEWHdsWEt1cExxNXdRV0R0RkJPdmJPWEZ0RExTYkxaYjdLVC9GWldoclpUMmIvSwowbUczd0ZFUWs1WUhyNy9VR1RkNWUycnVtM1hNTWRwbFhVTFJTNVFMTkNWQmhrNEJOTStDcE93VlFGc0NvTjJyCmlFalNsTlR0aFZ0U3ZrajFKaERXQjFCNnNDbGdzTFhuMnVyQ3VHTXFHakYyaTl5bUJoRmxIM3FpTGFsTnpZT00KcDd4K3JPVkRvQUl3V0ZqQy9EWXNscTVoZ0JQaXl5VGN3SGxBd05sVXMvMmNBZXBDNjk5a3UyYXRwYzYyb1Vhbwp5dnZSWVA3YWhXK00wSStLMGgyUmR6SVAxUXQ2OXRwZ0lMZDFiVTNwdVltWjhyZzFObjhQOTArUktjbEN5VlhGCmdnd0N5R2tIeEhmc0g3dUF4amkyVkF0OFBPVHBRVkZjeU5nNQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
```

**Comment by cpu** [comment]
It's hard to diagnose your problem without seeing any of the code you're using to construct the hyper client. I suspect your hyper client is defaulting to using webpki-roots, or the system trusted roots for its TLS client config. Neither of those will know about your self-signed issuer and so the `UnknownIssuer` error is produced.

You probably need to build a `rustls::ClientConfig` that specifies your self-signed issuer as a trusted root, and then build an `HttpsConnector` using that `ClientConfig`. You might be able to adapt [the code in the example client](https://github.com/rustls/hyper-rustls/blob/1c8811a72d089aae0ed05e5416ae4ece21f97828/examples/client.rs#L46-L74) from [`hyper-rustls`](https://github.com/rustls/hyper-rustls/tree/main) that does something similar.

**Comment by Masber** [comment]
thank you @cpu you have helped me a lot, I actually have to create a HtttpsConnector out of a SocksConnector out of a HttpConnector, I need to use socks5 and the only crate I found was https://crates.io/crates/hyper-socks2/0.8.0 which does not provide a way to inject my own CA certs...

I will try to see if I can understand how to create an HttpsConnector and see I can get to the bottom of this.

thank you very much again for your help :)

**Comment by cpu** [comment]
Happy to help! If you get stuck on anything else let us know.
