### ISSUE TITLE
Ergonomics of ConfigBuilder

### ISSUE THREAD

**Issue by jsha** [rustls/rustls#1372]
In https://github.com/rustls/rustls/pull/1365#issuecomment-1645569939, @cpu asked for more of my thoughts on the ergonomics of ConfigBuilder's typestate-based API. I figured I'd hoist them into their own issue.

## Docs

rustdoc [doesn't do a good job of rendering types that have multiple impl blocks](https://github.com/rust-lang/rust/issues/85492). For instance, in ConfigBuilder's docs, there's are two entries in the sidebar named `with_client_auth_cert`: [1](https://docs.rs/rustls/latest/rustls/struct.ConfigBuilder.html#method.with_client_auth_cert) [2](https://docs.rs/rustls/latest/rustls/struct.ConfigBuilder.html#method.with_client_auth_cert-1). When you click on them, there's no indication that they are on different types (`ConfigBuilder<ClientConfig, WantsTransparencyPolicyOrClientCert>` vs `ConfigBuilder<ClientConfig, WantsClientCert>`), unless you scroll up or collapse the doc sections. This is a problem for rustdoc to fix, but speaking as a rustdoc maintainer it's a bit challenging - I haven't thought of a great way to do it yet.

## All or Nothing

As a user I think of a config as having various defaults, any of which I can change independently. The default ClientConfig is built like:

```
ClientConfig::builder()
    .with_safe_defaults()
    ...
```

But if I want to set "only use TLS 1.3," I have to not only call the `with_protocol_versions` accessor, I have to expand the list to include two settings I _don't_ want to change:

```
ClientConfig::builder()
    .with_safe_default_cipher_suites()
    .with_safe_default_kx_groups()
    .with_protocol_versions(&[rustls::version::TLS13])
...
```

And the selection of those settings feels arbitrary. Why do those two settings become mandatory when I choose to override the protocol versions? Why not `alpn_protocols` or `resumption`? I happen to know that it's because they control code paths that the linker may optimize away if the user doesn't want them, but it feels like a lot of implementation details being exposed.

## Order dependency

The above example is valid, but this is not:

```
ClientConfig::builder()
    .with_protocol_versions(&[rustls::version::TLS13])
    .with_safe_default_cipher_suites()
    .with_safe_default_kx_groups()
...
```

That feels arbitrary, and it's hard to remember what order things go in. This could maybe be solved with better verbiage in the documentation. For instance we could explain up top "If you wish to customize the protocol versions, cipher suites, or key exchange groups, you must set them in this order: 1. cipher suites 2. key exchange groups 3. protocol versions."

## Error messages

With the above invalid example is compiled, this is the error:

```
error[E0599]: no method named `with_protocol_versions` found for struct `ConfigBuilder<ClientConfig, WantsCipherSuites>` in the current scope
 --> src/main.rs:3:10
  |
2 | /     rustls::ClientConfig::builder()
3 | |         .with_protocol_versions(&[rustls::version::TLS13])
  | |         -^^^^^^^^^^^^^^^^^^^^^^ method not found in `ConfigBuilder<ClientConfig, WantsCipherSuites>`
  | |_________|
  | 
  |
  = note: the method was found for
          - `ConfigBuilder<S, WantsVersions>`
```

This is... remarkably good on rustc's part, actually. But it still doesn't precisely explain the nature of the problem: these methods must be called in a certain order, and the order is wrong.

## Compile time validation vs runtime validation

The typestate system allows us to lean on compile-time checking for a lot of properties, which is nice. But we can't cover them all at compile time; there are still `Result` returns in `ConfigBuilder`. If we relied more on runtime checking, we could give more useful error messages. And since configs are _usually_ constructed the same way during each run of a program, I think this is not much of a sacrifice in ability to catch problems ahead of time.

## Multiple unwraps

In the ServerConfig example:

```
ServerConfig::builder()
    .with_safe_default_cipher_suites()
    .with_safe_default_kx_groups()
    .with_safe_default_protocol_versions()
    .unwrap()
    .with_no_client_auth()
    .with_single_cert(certs, private_key)
    .expect("bad certificate/key");
```

This looks like a single chain of settings on a builder; it's not clear to me why there is an unwrap in the middle and at the end, rather than a single unwrap at the end that checks all the relevant settings.

## State machines

State machines are a powerful tool for reducing complexity in thinking about protocols. They allow clearly ruling out invalid states and invalid transitions. But I think introducing a state machine to people's mental model of a config builder actually _increases_ complexity. Most of the states in the machine don't have inherent meaning. And our correctness requirements are a property of the final bundle of settings, not of the transitions between intermediate states.

**Comment by djc** [comment]
This is a good list of limitations of the current approach. I think we could solve the "All or Nothing" and "Order" problems by adding more states, but adding more states might make some of these other things harder?

I think the main constraints here are:

* Some callers would prefer not to link all key exchange groups/cipher suites, so there must be a way to build a config that doesn't call any functions relying on the default sets of exchange groups/cipher suites.
* Clients must configure a server verifier
* Servers must provide a server certificate resolver

My intuition is that most callers don't use the key exchange group/cipher suite selection (that is, they rely on the safe default), so I think in terms of ergonomics we should make sure that we still have a fast path to work with those.

Within those constraints, we could make it more dynamic. We can probably also defer the initial `Result` to the end.

**Comment by jsha** [comment]
> callers would prefer not to link all key exchange groups/cipher suites, so there must be a way to build a config that doesn't call any functions relying on the default sets of exchange groups/cipher suites.

Yep. BTW this reminds me: we should check whether alternate cryptographic backends we're considering have the same property that ring has: that unused items can be eliminated at link time. By the way for historical context I think this was the issue that first discussed dead-code elimination as an alternative to crate features: https://github.com/rustls/rustls/issues/633. And here was the PR that introduced a version of this API that is friendly to dead-code elimination: https://github.com/rustls/rustls/pull/564

Here's one approach that reduces the number of typestates while preserving the dead-code elimination property (and also the all-or-nothing problem): We could have two entrypoints to make a ConfigBuilder:

```rust
ServerConfig::builder()
ServerConfig::builder_narrowed(protocols, cipher_suites, kx_groups)
```

The `builder` path would use the defaults, causing them all to be linked in. The `builder_narrowed` path would use only the mentioned values, causing the non-mentioned ones to be eliminated. This removes three type states. Another way of thinking about it is that it moves the "must set all three" requirement from a series of states to a single function call (since functions always require all of their arguments).

This also has the nice side effect of reducing the boilerplate of `with_safe_defaults()`. So a simplified ServerConfig call could be:

```rust
ServerConfig::<Ring>::builder()
    .with_no_client_auth()
    .with_single_cert(certs, private_key)
    .expect("bad certificate/key");
```

Instead of:

```rust
ServerConfig::<Ring>::builder()
    .with_safe_defaults()
    .with_no_client_auth()
    .with_single_cert(certs, private_key)
    .expect("bad certificate/key");
```

As a side note: far and away the most common configuration of TLS is with no client authentication required and none sent. Right now we treat `with_no_client_auth()` as required configuration, which winds up as boilerplate. We could instead treat `with_no_client_auth()` as the default. This would reduce the required configuration to "what certificate to send" (on the server side) or "how to verify" (on the client side).

**Comment by djc** [comment]
> Here's one approach that reduces the number of typestates while preserving the dead-code elimination property (and also the all-or-nothing problem): We could have two entrypoints to make a ConfigBuilder:
> 
> ```rust
> ServerConfig::builder()
> ServerConfig::builder_narrowed(protocols, cipher_suites, kx_groups)
> ```
> 
> The `builder` path would use the defaults, causing them all to be linked in. The `builder_narrowed` path would use only the mentioned values, causing the non-mentioned ones to be eliminated. This removes three type states. Another way of thinking about it is that it moves the "must set all three" requirement from a series of states to a single function call (since functions always require all of their arguments).

Yup, I think this would be an improvement (though I don't think `builder_narrowed()` is a good name for it).

> As a side note: far and away the most common configuration of TLS is with no client authentication required and none sent. Right now we treat `with_no_client_auth()` as required configuration, which winds up as boilerplate. We could instead treat `with_no_client_auth()` as the default. This would reduce the required configuration to "what certificate to send" (on the server side) or "how to verify" (on the client side).

That would be a simplification, but it's also a change to "failing open": the implicit default would be to allow unauthenticated clients. In many other scenarios we've defaulted to "failing closed". I think you're saying that in this case that's okay because the expectation for most people is that client authn is disabled anyway, but it's still a bit of a departure from our usual design philosophy.

(I'm inclined to agree that this would be an improvement.)

**Comment by cpu** [comment]
> Here's one approach that reduces the number of typestates while preserving the dead-code elimination property (and also the all-or-nothing problem): We could have two entrypoints to make a ConfigBuilder:
>
> ServerConfig::builder()
> ServerConfig::builder_narrowed(protocols, cipher_suites, kx_groups)

I think the second form would need an additional argument for the `&'static dyn CryptoProvider` as of https://github.com/rustls/rustls/pull/1448 being in-tree.

A "builder" constructor that takes four separate function arguments is starting to feel like it isn't a builder anymore :-/

**Comment by cpu** [comment]
>> ServerConfig::builder_narrowed(protocols, cipher_suites, kx_groups)
>
> I think the second form would need an additional argument for the &'static dyn CryptoProvider as of https://github.com/rustls/rustls/pull/1448 being in-tree.

This also seems like it's perpetuates the "All or Nothing" aspect of the original problem description. If I'm a user that wants to customize only the protocol version I will have to also explicitly provide a crypto provider, cipher suites, and kx groups.

**Comment by ctz** [comment]
I think I'm in agreement that we should do this, though probably in the next release rather than this one. Another rough plan to add to those above:

- turn `CryptoProvider` into a struct, sharing it via an `Arc`
- the struct has sets of cipher suites, kx groups, etc.
- the struct can be constructed with customisations atop an existing one, like `CryptoProvider { thing_i_want_to_customise: (...), ..RING }` or thereabouts.
- we'll have to drop `fill_random` and `load_private_key` into their own traits
- `ServerConfig::builder()` gets you the defaults
- `ServerConfig::builder_with_provider(Arc<CryptoProvider>)` works as currently
- the `.with_safe_defaults()`, `.with_safe_default_cipher_suites()`, `.with_safe_default_kx_groups()`, `.with_safe_default_protocol_versions()` etc. all fall away. Though the "next level down" still needs to exist (choosing client/server identity, specifying client auth requirements).

I am hoping that with fewer intermediate typestates in the builder, we could maybe use concrete types that might be easier in terms of documentation, IDE support, error messages etc. but without causing a large number of types that need to be given names?

**Comment by cpu** [comment]
That sounds like a good direction to me. :+1:

**Comment by cpu** [comment]
> Another rough plan to add to those above ...

I have a branch with a struct based `CryptoProvider` working end to end. It needs some cleanup but the idea seems workable with a couple small tweaks. I think we could do it for the 0.22 release and I think the API ends up being nicer overall.

**Comment by cpu** [comment]
Here's a PR implementing the described `CryptoProvider` changes: https://github.com/rustls/rustls/pull/1628

**Comment by cpu** [comment]
I think we can close this given the [plan discussed earlier](https://github.com/rustls/rustls/issues/1372#issuecomment-1816537477) was implemented.
