### ISSUE TITLE
Redundant type names via re-exports

### ISSUE THREAD

**Issue by jsha** [rustls/rustls#1386]
With a breaking release coming up, it might be a good time to address this minor issue. For several types, there are multiple names in the public API they can be referred to. This is a problem because someone reading the code doesn't automatically know that `rustls::ServerConfig` is the same as `rustls::server::ServerConfig`. I think each of the items listed under [Re-exports](https://docs.rs/rustls/latest/rustls/#reexports) at the top level has this property:

```
pub use client::ClientConfig;
pub use client::ClientConnection;
pub use client::ServerName;
pub use server::ServerConfig;
pub use server::ServerConnection;
```

The unreleased version in `main` adds more types with this property:

```
pub use crate::crypto::ring::Ticketer;
pub use crate::crypto::ring::SupportedKxGroup;
pub use crate::crypto::ring::ALL_KX_GROUPS;
pub use crypto::ring::kx_group;
```

I think in each of these cases it makes sense to remove the single-type re-export in favor of having users use the fully-qualified name.

**Comment by djc** [comment]
I think I set it up this way; I haven't ever noticed that this was a problem for people. Personally I think re-exports at the top level are useful (less typing for the most common use cases). I put out a poll that seems to mostly agree that this is problematic, though: https://hachyderm.io/@djc/110824267001415573.

> I think in each of these cases it makes sense to remove the single-type re-export in favor of having users use the fully-qualified name.

I guess it's fine, though I don't find the prospect of forcing everyone to write an extra module name enticing.

**Comment by aochagavia** [comment]
I'm obviously biased because of having used Rust for a long time, but I consider re-exports a Rust idiom to indicate the most interesting types in a crate (i.e. the types that I'm likely to need as a user). Even the standard library uses re-exports:

![image](https://github.com/rustls/rustls/assets/5196584/77a6383c-a72a-4f29-be26-4329f13bfd8b)

From the types mentioned above, I'd think we can keep the original ones, but that the new ones shouldn't be re-exported at the top level (for instance, there might be multiple `ALL_KG_GROUPS` constants, one per crypto implementation, and you probably don't want to privilege one of them).

**Comment by djc** [comment]
> From the types mentioned above, I'd think we can keep the original ones, but that the new ones shouldn't be re-exported at the top level (for instance, there might be multiple `ALL_KG_GROUPS` constants, one per crypto implementation, and you probably don't want to privilege one of them).

That would also be my preference.

**Comment by jsha** [comment]
It makes sense to have the most important types in a crate be at the top level. But then why additionally have them at a lower level? Should advise users as to which is the preferred path?

Also, I looked at the logs and you're right @djc; you made the initial move in https://github.com/rustls/rustls/pull/781 and added the re-export at the top level.

**Comment by djc** [comment]
> It makes sense to have the most important types in a crate be at the top level. But then why additionally have them at a lower level? Should advise users as to which is the preferred path?

The idea was that the `server` and `client` module documentation is useful to get a complete look at the items that are useful to one side. Not sure if that's worth it in practice (or, indeed, how much confusion the re-export would cause).

**Comment by jsha** [comment]
@aochagavia I was thinking about this some more:

> I consider re-exports a Rust idiom to indicate the most interesting types in a crate (i.e. the types that I'm likely to need as a user). Even the standard library uses re-exports

There are two conflicting idioms:

 1. A crate may contain multiple, different, types with the same name.
 2. A crate may contain multiple, identical, types with the same name.

The most obvious example of (1) is of course `Result`. Another example: flate2 has multiple types named `GzDecoder`:

flate2::bufread::GzDecoder
flate2::read::GzDecoder
flate2::write::GzDecoder

The problem is, how is a user supposed to figure out the difference between idiom (1) and idiom (2)? The documentation for identical types will be identical, but it requires close reading to be sure of that. It seems best to avoid (2) whenever possible.

**Comment by djc** [comment]
Feels like (2) is pretty rare, maybe rare enough that it shouldn't dissuade us from doing (1)?

**Comment by aochagavia** [comment]
I guess it boils down to a matter of taste / project convention. I'm sligthly in favor of having a single exported name instead of two.

**Comment by cpu** [comment]
It's not clear to me if there's consensus in this discussion on a path forward, yet this issue has been pulled into the 0.22 release planning so we need to make some kind of decision in the near future.

As a starting point to get things moving here's a branch that removes **all** of the re-exports: https://github.com/rustls/rustls/pull/1477

>> From the types mentioned above, I'd think we can keep the original ones, but that the new ones shouldn't be re-exported at the top level (for instance, there might be multiple ALL_KG_GROUPS constants, one per crypto implementation, and you probably don't want to privilege one of them).
>>
> That would also be my preference.

If the preference expressed by @djc and @aochagavia is the way folks would prefer to go I can restore the `client`/`server` module exports in #1477. Personally I think we should either agree that re-exports are useful and keep them all, or agree re-exports are confusing and remove them all. A middle ground where we re-export some names but not others seems like it's a subpar state unless we also update the style guide to give some guidance on when re-exports are appropriate.

**Comment by djc** [comment]
I wrote down some thoughts in the PR.
