### ISSUE TITLE
rustls prevents executable from being compiled with `target-feature=+crt-static`

### ISSUE THREAD

**Issue by Evian-Zhang** [rustls/rustls#1387]
As a minimal working example:

```rust
// src/main.rs
use rustls::*;
fn main() {}
```

```toml
[dependencies]
rustls = "0.21"
```

Compile the above rust project with

```shell
RUSTFLAGS='-C target-feature=+crt-static' cargo build --release
```

Cannot produce statically-linked executable. However, after removing the `use` sentence in `main.rs`, the above instruction could lead to statically-linked executable.

* Rustc version: 1.71.0
* Platform: Ubuntu 22.04, x86_64

**Comment by djc** [comment]
(Clarified the title, because I'm pretty sure that "statically linking" with something like a musl target does work.)

I'm not really sure what `+crt-static` is/does or why you'd want to use it. I suppose it could be because rustls has `static` "constants"? Can you try whether it works when compiling with just the ring crate?

**Comment by Evian-Zhang** [comment]
@djc Thank you for your response!

> why you'd want to use it.

Using `+crt-static` could normally generate a statically-linked binary (using `file` command could check that), which could just be `cp`-ed to any compatible environment without managing dependencies (and in practice, the "compatible" just means nothing, the Linux kernel has a good ABI compatibility and glibc's breaking change usually does not have much to do with Rust binary). Moreover, it could avoid libc's hooking, and has much more functionalities.

Managing dependencies of dynamically-linked binaries is a nightmare, and this is one of the reasons why rustls is much more favarable than native-tls, openssl, opentls, etc., which depends on additional shared libraries.

 > I suppose it could be because rustls has static "constants"?

As far as I know, using `static` keyword does not have an effect on `+crt-static`, since it just adds an entry in some certain sections of binary.

> Can you try whether it works when compiling with just the ring crate?

I declare `ring` dependency `0.16.20`, and yes, `use ring::*;` prevents the `+crt-static` things.

**Comment by djc** [comment]
What about if you import rustls from https://github.com/rustls/rustls/pull/1319 while disabling the *ring* feature? Does that still work?

**Comment by Evian-Zhang** [comment]
`Cargo.toml`:

```toml
rustls = { git="https://github.com/rustls/rustls", branch="jbp-cpu-djc-crypto++", default-features = false, features = [] }
```

This does not compile:

<details>

```plaintext
error[E0308]: mismatched types
  --> /home/xxx/.cargo/git/checkouts/rustls-29bde2ca1adbde2d/fd0b948/rustls/src/webpki/verify.rs:45:13
   |
39 |         .verify_for_usage(
   |          ---------------- arguments to this method are incorrect
...
45 |             &[], // no CRLs
   |             ^^^ expected `Option<RevocationOptions<'_>>`, found `&[_; 0]`
   |
   = note:   expected enum `Option<RevocationOptions<'_>>`
           found reference `&[_; 0]`
note: method defined here
  --> /home/xxx/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/rustls-webpki-0.102.0-alpha.0/src/end_entity.rs:92:12
   |
92 |     pub fn verify_for_usage(
   |            ^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/xxx/.cargo/git/checkouts/rustls-29bde2ca1adbde2d/fd0b948/rustls/src/webpki/verify.rs:314:17
    |
308 |             .verify_for_usage(
    |              ---------------- arguments to this method are incorrect
...
314 |                 &crls,
    |                 ^^^^^ expected `Option<RevocationOptions<'_>>`, found `&Vec<&...>`
    |
    = note:   expected enum `Option<RevocationOptions<'_>>`
            found reference `&Vec<&dyn webpki::CertRevocationList>`
note: method defined here
   --> /home/xxx/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/rustls-webpki-0.102.0-alpha.0/src/end_entity.rs:92:12
    |
92  |     pub fn verify_for_usage(
    |            ^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rustls` (lib) due to 2 previous errors
```
</details>

**Comment by djc** [comment]
You could try using Cargo patches to pin rustls-webpki to 97f841de7060aa34a02c2f989de7fe2b3f41e49f, maybe?

**Comment by Evian-Zhang** [comment]
`Cargo.toml`:

```toml
[dependencies]
rustls = { git="https://github.com/rustls/rustls", branch="jbp-cpu-djc-crypto++", default-features = false, features = [] }

[patch.crates-io]
rustls-webpki = { git = "https://github.com/rustls/webpki", rev = "97f841de7060aa34a02c2f989de7fe2b3f41e49f" }
```

This compiles, but still generates a dynamically-linked binary under `+crt-static` flag.

Using a clean build, we can see Cargo's output:

```plaintext
    Updating git repository `https://github.com/rustls/rustls`
   Compiling libc v0.2.147
   Compiling untrusted v0.7.1
   Compiling spin v0.5.2
   Compiling rustls v0.22.0-alpha.0 (https://github.com/rustls/rustls?branch=jbp-cpu-djc-crypto++#fd0b9485)
   Compiling subtle v2.5.0
   Compiling cc v1.0.81
   Compiling ring v0.16.20
   Compiling rustls-webpki v0.102.0-alpha.0 (https://github.com/rustls/webpki?rev=97f841de7060aa34a02c2f989de7fe2b3f41e49f#97f841de)
```

Still compiles the `ring` crates.

**Comment by djc** [comment]
Ah yes, on that branch rustls does not disable webpki's default features so it still includes *ring*. Still, I guess you should be able to figure out from here how to get a rustls + webpki combo to compile that doesn't depend on *ring* at all. Then, with an alternative crypto implementation (that doesn't also have the same problem) you might be able to get a `+crt-static` build with no dynamically-linked libraries.

Unfortunately *ring* does not appear to get much maintenance at this time so it's unlikely it will be fixed up to support this scenario.

**Comment by Evian-Zhang** [comment]
Ok, thank you. I will close this issue:)

**Comment by thalesfragoso** [comment]
It's worth noting that glibc doesn't support static linking. There aren't many cases where you want to use `crt-static` for that matter, you usually want to use the musl targets instead.

**Comment by ctz** [comment]
> Ah yes, on that branch rustls does not disable webpki's default features so it still includes _ring_.

Just fixed that, and for me this seems to work and produces a static executable:

```shell
~/rustls/provider-example$ RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --example client --target x86_64-unknown-linux-gnu
(...)

~/rustls/provider-example$ file ../target/x86_64-unknown-linux-gnu/release/examples/client 
../target/x86_64-unknown-linux-gnu/release/examples/client: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), static-pie linked, BuildID[sha1]=9af3a248e9911218dec74f0cc8e556ff0018e5e5, for GNU/Linux 3.2.0, with debug_info, not stripped

~/rustls/provider-example$ ../target/x86_64-unknown-linux-gnu/release/examples/client | head
Current ciphersuite: TLS13_CHACHA20_POLY1305_SHA256
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 19670
Connection: close
Server: Rocket
X-Frame-Options: SAMEORIGIN
Permissions-Policy: interest-cohort=()
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Strict-Transport-Security: max-age=63072000
```
