### ISSUE TITLE
doc: update "can be expensive" on configs

### ISSUE THREAD

**Issue by jsha** [rustls/rustls#1403]
On both [ClientConfig](https://docs.rs/rustls/latest/rustls/client/struct.ClientConfig.html) and [ServerConfig](https://docs.rs/rustls/latest/rustls/server/struct.ServerConfig.html) we have:

> Making one of these can be expensive, and should be once per process rather than once per connection.

I think that is less true than it once was. And in particular with the Acceptor API we are _encouraging_ creating a ServerConfig per connection (or one per CRL refresh at least).

We should add some nuance to this, explaining for instance that loading a bundle of roots from disk may be slow, so ClientConfigs/ServerConfigs that use that method should be reused to the extent possible. And perhaps going into even more detail, that the slowness specifically lives in [`ConfigBuilder::with_root_certificates`](https://docs.rs/rustls/latest/rustls/struct.ConfigBuilder.html#method.with_root_certificates) (and the steps that come before that, to load the RootCertStore).

**Comment by djc** [comment]
Yes! I've seen people mention this regularly, whereas I think it's really only an issue in the specific case of loading native certificates.
