### ISSUE TITLE
Timeline to backport HRR fix (echoed session ID)?

### ISSUE THREAD

**Issue by cjpatton** [rustls/rustls#1424]
This was fixed on main (https://github.com/rustls/rustls/pull/1374), but the fix has not been backported to release branches. I was wondering if this is planned, and if so, when we could expect the release? I'm primarily interested in 0.21, but 0.20 would be great as well.

This is currently breaking interop with Go. In my particular situation, HRR is hard to avoid because it's unlikely that the Go client will send, in the initial CH, a key share for a KX group that the rustls server supports.

**Comment by djc** [comment]
Would you be able to submit the backport PR? Can get this out tomorrow. 👍

**Comment by djc** [comment]
Ah, I see we have a PR already!

**Comment by cjpatton** [comment]
:) Thanks for the quick response! This is a huge help.

**Comment by cpu** [comment]
I'm looking at doing the same for 0.20.x but the API drift requires a little bit more adjustment.

**Comment by djc** [comment]
@cjpatton any particular reason you care about 0.20?

**Comment by cjpatton** [comment]
I didn't realize 0.20 was so close to EOL. In that case, don't worry about backporting.

**Comment by cjpatton** [comment]
FWIW the reason is the "usual" reason: My company has some code that uses 0.20, and bumping 0.20.8 -> 9 might be an easier lift than 0.20.8 -> 0.21.7.

**Comment by cpu** [comment]
@djc @cjpatton I had already finished backporting to the 0.20.x stream before I caught up on this thread: https://github.com/rustls/rustls/pull/1426

WDYT? Close that PR or push one last point release for that release stream before it's EOL?

**Comment by djc** [comment]
Technically we recently changed the security policy with the effect that the 0.20 release is supported shorter than it would have been before, so if you have feedback on that we could discuss it. I'm a bit surprised doesn't have everything ported to 0.21 yet... https://github.com/rustls/rustls/commit/0b86e5e6f46babfb358f2e7663b73ad718d4a85f

**Comment by cjpatton** [comment]
@cpu I'd be grateful if 0.20 were patched, but I'd understand perfectly well if y'all decided that your security policy rules this out.

**Comment by cpu** [comment]
> @cpu I'd be grateful if 0.20 were patched

Just pushed a 0.20.9 release. 

FWIW if you're looking for a reason to prioritize an upgrade the 0.20.x release stream is presently vulnerable to https://rustsec.org/advisories/RUSTSEC-2023-0053.html - it uses the original `webpki` crate the Rustls team doesn't maintain.

We're going to evaluate releasing a 0.20.10 with [rustls/webpki](https://github.com/rustls/webpki) but it's a little tricky because the first release of our fork isn't strictly semver compatible with the webpki version used by 0.20.x.

**Comment by cpu** [comment]
> We're going to evaluate releasing a 0.20.10 with [rustls/webpki](https://github.com/rustls/webpki)

Leaving a breadcrumb here that we didn't end up needing to do this. [briansmith/webpki v0.22.1](https://crates.io/crates/webpki/0.22.1) was released with the fix for the vulnerability
