### ISSUE TITLE
Does this crate support http proxies?

### ISSUE THREAD

**Issue by thefirstofthe300** [rustls/rustls#1434]
For context, I'm working on a problem where a user is attempting to use an HTTP proxy with our certificate validation software built on this crate. We're seeing an issue where no client certificates are returned which makes me think that the TLS connection may not be properly tunneled through their proxy.

**Comment by ctz** [comment]
This crate doesn't do IO, so is pretty agnostic as to whether the data it processes goes over a HTTP CONNECT proxy over TCP, or first hop to a HTTP proxy, or straight TCP, or anything else. So I guess the answer is "no", but there is certainly no reason it won't work if you find parts external to this crate to correctly do the IO.
