### ISSUE TITLE
impl `std::error::Error` for `ClientCertVerifierBuilderError`

### ISSUE THREAD

**Issue by tottoto** [rustls/rustls#1454]
`std::error::Error` is not implemented for [`ClientCertVerifierBuilderError`](https://docs.rs/rustls/0.22.0-alpha.2/rustls/server/enum.ClientCertVerifierBuilderError.html). It might be convenient for users who want to convert types between types which implement `std::error::Error` trait.

**Comment by djc** [comment]
Makes sense, would you be able to send a PR?
