### ISSUE TITLE
Question about disposing rustls::StreamOwned

### ISSUE THREAD

**Issue by darind** [rustls/rustls#1457]
I have the following:

```
{ // begin scope
    let fd: i32 = ... this file descriptor is coming from a calling C++ code which created the TCP socket
    let stream: std::net::TcpStream = unsafe { std::net::TcpStream::from_raw_fd(fd) };
    let conn = rustls::ClientConnection::new(Arc::new(config), server_name);
    let tls = rustls::StreamOwned::new(conn, stream);
    .... do some I/O on the TLS stream
    std::mem::forget(tls);
} // end scope
```

In this example I create a TCP stream from an existing file descriptor. As the documentation of the `from_raw_fd` states, this will take ownership of the file descriptor and automatically dispose it.

To prevent double disposal, I explicitly call `mem::forget` on the tls stream. This works but I would like to know if it wouldn't cause any memory leaks. Are there some other resources used by `StreamOwned` that I might not be properly disposing in this case?

**Comment by ctz** [comment]
I don't think we want to make that guarantee. Instead I think we should provide a function that consumes the Stream and gives back the underlying stream and connection?

**Comment by darind** [comment]
Yes, it would be great if such function existed so that I can `forget` only the wrapped `TcpStream`
