### ISSUE TITLE
Question about ServerCertVerifier

### ISSUE THREAD

**Issue by darind** [rustls/rustls#1468]
I am using a `ServerCertVerifier` to perform some custom validation logic on the presented server certificate:

```
let mut config = ClientConfig::builder()
    .with_safe_defaults()
    .with_custom_certificate_verifier(Arc::new(verifier))
    // .with_root_certificates(root_store)
    .with_no_client_auth();
```

I would like to know if it is possible in my custom verifier to first apply the default validation logic and if it succeeds, perform my custom logic.

Here's what I did but I am not sure if it is correct:

```
use rustls::client::{
    ServerCertVerifier,
    ServerCertVerified,
    verify_server_cert_signed_by_trust_anchor,
    verify_server_name
};

struct CertVerifier{
    roots: RootCertStore,
}

impl ServerCertVerifier for CertVerifier {
    fn verify_server_cert(
        &self,
        end_entity: &Certificate,
        intermediates: &[Certificate],
        server_name: &ServerName,
        scts: &mut dyn Iterator<Item = &[u8]>,
        ocsp_response: &[u8],
        now: std::time::SystemTime,
    ) -> Result<rustls::client::ServerCertVerified, rustls::Error> {
        // First perform the default certificate validation
        let cert = ParsedCertificate::try_from(end_entity)?;
        verify_server_cert_signed_by_trust_anchor(&cert, &self.roots, intermediates, now)?;
        verify_server_name(&cert, server_name)?;

        // Apply some additional custom logic here
        ......

        Ok(ServerCertVerified::assertion())
    }
} 
````

Is this a correct way to validate the server certificate using the default logic (as if I had used `with_root_certificates(root_store)` in my config builder)

**Comment by djc** [comment]
Yup, that's basically right. I think it should be possible to store a `WebPkiVerifier` inside your `CertVertifier` and explicitly call its `ServerCertVerifier` methods, and then add additional checks before returning?

**Comment by darind** [comment]
@djc, perfect, thanks. The `WebPkiVerifier::new` seems to take as second argument some `ct_policy`. What that would be for the default validation logic?

**Comment by djc** [comment]
It is usually `None`, so just passing that is fine.
