### ISSUE TITLE
Crypto provider feature guards are not additive

### ISSUE THREAD

**Issue by djc** [rustls/rustls#1472]
I have VS Code configured to compile code with `--all-features` by default. After landing #1405 this is showing compilation failures in the new provider-example crate:

* `Tls13CipherSuite` has `pub(crate)` fields that are only enabled for `#[cfg(feature = "quic")]`. This means that other crypto providers can't create `Tls13CipherSuite` values when the `quic` feature is enabled.
* `Tls12AeadAlgorithm` and `Tls13AeadAlgorithm` have `extract_keys()` methods that only appear for `#[cfg(feature = "secret_extraction")]`. This means that also downstream implementations of these traits will also need to guard these trait methods.

This happens because my Rust-Analyzer setup is compiling rustls with all features enabled, but the provider-example crate cannot deal with the additional features -- it can only be compiled when rustls doesn't have these features enabled, but that can never be guaranteed in Cargo's feature-additive dependency graphs.

**Comment by ctz** [comment]
I suggest we address this by:

- making those fields always included; they are not specific to quic. `record_layer` should be enforcing them also; though I'd like to make it enforce them more stringently so it is possible run a test in CI that exercises that code.
- deleting the `secret_extraction` gate feature in accordance with #1437, and make it fallible so providers who don't implement aes-128-gcm, aes-256-gcm, or chacha20poly1305 can refuse.

**Comment by djc** [comment]
> * making those fields always included; they are not specific to quic. `record_layer` should be enforcing them also; though I'd like to make it enforce them more stringently so it is possible run a test in CI that exercises that code.

I agree for the limits. For the `quic: crate::quic::Algorithm` field, that certainly seems specific to QUIC? Do we want to support cipher suite implementations that don't have QUIC support? I think allowing that is reasonable.

> * deleting the `secret_extraction` gate feature in accordance with #1437, and make it fallible so providers who don't implement aes-128-gcm, aes-256-gcm, or chacha20poly1305 can refuse.

Instead, could we replace `ConnectionTrafficSecrets` with a type that contains things more like `HashOutput`? Again the question is, do we want to support cipher suite implementations that don't support secret extraction?
