### ISSUE TITLE
Insecure server verifier

### ISSUE THREAD

**Issue by stevefan1999-personal** [rustls/rustls#1476]
We could use this to achieve something like `curl --insecure` settings
```rust
struct NoopServerVerifier;

impl ServerCertVerifier for NoopServerVerifier {
    fn verify_server_cert(
        &self,
        _end_entity: &CertificateDer<'_>,
        _intermediates: &[CertificateDer<'_>],
        _server_name: &ServerName,
        _ocsp_response: &[u8],
        _now: pki_types::UnixTime,
    ) -> Result<ServerCertVerified, rustls::Error> {
        Ok(ServerCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        _message: &[u8],
        _cert: &CertificateDer<'_>,
        _dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        Ok(HandshakeSignatureValid::assertion())
    }

    fn verify_tls13_signature(
        &self,
        _message: &[u8],
        _cert: &CertificateDer<'_>,
        _dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        Ok(HandshakeSignatureValid::assertion())
    }

    fn supported_verify_schemes(&self) -> Vec<SignatureScheme> {
        vec![
            SignatureScheme::RSA_PKCS1_SHA1,
            SignatureScheme::ECDSA_SHA1_Legacy,
            SignatureScheme::RSA_PKCS1_SHA256,
            SignatureScheme::ECDSA_NISTP256_SHA256,
            SignatureScheme::RSA_PKCS1_SHA384,
            SignatureScheme::ECDSA_NISTP384_SHA384,
            SignatureScheme::RSA_PKCS1_SHA512,
            SignatureScheme::ECDSA_NISTP521_SHA512,
            SignatureScheme::RSA_PSS_SHA256,
            SignatureScheme::RSA_PSS_SHA384,
            SignatureScheme::RSA_PSS_SHA512,
            SignatureScheme::ED25519,
            SignatureScheme::ED448,
        ]
    }
}
```
Should we add this?

**Comment by cpu** [comment]
> Should we add this?

This has come up in the past (e.g. https://github.com/rustls/rustls/pull/1197, https://github.com/rustls/rustls/issues/578), and the answer has been No: this shouldn't be something built-in. 

I believe the project position is that each insecure use-case should implement `ServerCertVerifier` as needed. We've been open to exposing bits and pieces that make this job easier (e.g. things like https://github.com/rustls/webpki/pull/119) but have avoided providing an out-of-box experience for something we feel is inherently dangerous.

**Comment by cpu** [comment]
Going to close this since I think there's consensus, but if I'm wrong we can always re-open and discuss further.

**Comment by mouse07410** [comment]
Since this is a fairly typical use case, I think we should reconsider.

**Comment by stevefan1999-personal** [comment]
> Going to close this since I think there's consensus, but if I'm wrong we can always re-open and discuss further.

As a DRY guy, I think this (and other builder methods around it) should be included as a feature, whether behind `dangerous_configuration` or even a new `dangerous_insecure` feature. But it is alright to copy a few of these in my test suites nonetheless
