### ISSUE TITLE
ring 1.17.0 compatibility

### ISSUE THREAD

**Issue by donmor** [rustls/rustls#1510]
ring 1.17.0 has come out these days, but rustls still using 1.16.20. I wonder if rustls can work with ring 1.7.0, and if it works, an update that accepts both 1.16.20 and 1.17.0 as dependency is appreciated.

**Comment by cpu** [comment]
Hi there,

> I wonder if rustls can work with ring 1.7.0

This is underway in https://github.com/rustls/rustls/pull/1508

**Comment by donmor** [comment]
Oops I see.
