### ISSUE TITLE
Possibly outdated documentation on `TLS_FALLBACK_SCSV`

### ISSUE THREAD

**Issue by Shnatsel** [rustls/rustls#1513]
The manual states that `TLS_FALLBACK_SCSV` is not necessary:

https://github.com/rustls/rustls/blob/23e1273d22fb70d665b368bf4cfdbd4a426e4e8e/rustls/src/manual/tlsvulns.rs#L122-L123

However, the documentation seems to have been written when rustls only supported TLS 1.2, but not 1.3.

This may be a dumb question, but: shouldn't `TLS_FALLBACK_SCSV` be implemented now that rustls supports two TLS versions? Or are there some other mechanisms in place to prevent downgrades from TLS 1.3 to 1.2?

**Comment by ctz** [comment]
> Or are there some other mechanisms in place to prevent downgrades from TLS 1.3 to 1.2?

Yes, see https://www.rfc-editor.org/rfc/rfc8446#section-4.1.3 (paragraph starting "TLS 1.3 has a downgrade protection mechanism")

**Comment by cpu** [comment]
The manual text was clarified in https://github.com/rustls/rustls/pull/1514 - Thanks!
