### ISSUE TITLE
Has there been consideration to use `bytes::Bytes` without `std` feature for no-std support?

### ISSUE THREAD

**Issue by divagant-martian** [rustls/rustls#1530]
searching the issue for `bytes::Bytes` is just giving me everything with the word `bytes` in it so forgive me if this has been asked before

**Comment by djc** [comment]
See #1399 and #1420. No consideration of using `Bytes` specifically, but I don't think it in particular helps with no_std.

**Comment by divagant-martian** [comment]
since the crates provides no-std support via an opt out `std` feature I would hope it does, but that's barely a hunch. Thanks for the references. That would probably still be incompatible with a caller-managed buffer api (very surprised vi that one)

**Comment by ctz** [comment]
I have looked from time to time at replacing our `Codec`/`Reader` code with something external (that is perhaps more flexible and/or higher performance without using unsafe) but where it usually falls down is supporting 24-bit integers (seems like `bytes` can do this albeit widening them to u64), or having odd/missing error handling. `bytes` seems to fall into the latter bucket, see https://github.com/tokio-rs/bytes/issues/254

**Comment by djc** [comment]
> That would probably still be incompatible with a caller-managed buffer api (very surprised by that one)

What exactly surprises you?

**Comment by cpu** [comment]
@divagant-martian Did you have thoughts on Djc's questions and Ctz's comments on the state of the `bytes` crate? I think without further input we're likely to close this issue as something we can't take action on.
