### ISSUE TITLE
Revocation checking by clients

### ISSUE THREAD

**Issue by ctz** [rustls/rustls#1541]
This appears to be a hard requirement in SP800-52.

We could reuse the CRL support we already have (to the extent that CRLs are useful or tractable in this context), or add support for verifying stapled OCSP responses (to the extent that is well deployed), or start fetching OCSP responses/CRLs from elsewhere. Crumbs!

**Comment by cpu** [comment]
I agree CRLite is interesting :+1:

That said, I'm not enough of a FIPS-head to be able to guess at whether checking an aggregate view generated by a central entity is a fit to the SP800-52 requirement. Might be a tough sell? I believe in the CRLite technology and why it's trustworthy but in my experience with similar audits sometimes you want to be able to point to something that will already be familiar to the auditor, like boring direct CRL support. The language ctz linked in #1538 is fairly specific about the revocation information sources :-/ 

I think it would be helpful if I put together a branch that brings the existing CRL support used in the `WebPkiClientVerifier` to the `WebPkiServerVerifier`. The webpki API is already there, we just haven't [wired it up](https://github.com/rustls/rustls/blob/3b8a7c3afbc0a90a048316584a8b7f27bb87995e/rustls/src/webpki/verify.rs#L44) for the client-checking-server context. 

After that I'd be keen on trying to look at how feasible something like CRLite could be. I think its an interesting idea. Maybe it would be worth trying to sketch out an RFC for that. WDYT?

**Comment by cpu** [comment]
Veering mildly off-topic for this ticket but I refreshed myself a bit on CRLite and Firefox's impl. builds on top of both SCT verification and their [intermediate preloading](https://blog.mozilla.org/security/2020/11/13/preloading-intermediate-ca-certificates-into-firefox/) technology. Both would be pretty decent sized chunks of work if we needed those as pre-reqs.

**Comment by djc** [comment]
> That said, I'm not enough of a FIPS-head to be able to guess at whether checking an aggregate view generated by a central entity is a fit to the SP800-52 requirement. Might be a tough sell? I believe in the CRLite technology and why it's trustworthy but in my experience with similar audits sometimes you want to be able to point to something that will already be familiar to the auditor, like boring direct CRL support. The language ctz linked in #1538 is fairly specific about the revocation information sources :-/

I was envisioning there might be a complete Rust library toolchain to build the CRLite database/filter and consume it, so that people could self-host it maybe if they need the FIPS stuff? IIRC some parts of it are already provided in Rust.

**Comment by gibbz00** [comment]
Just wanted to let you know that I'm taking a look at revocation checking through OCSP stapling 😊

**Comment by ctz** [comment]
I've opened rustls/webpki#217 to record the desire for OCSP verification by rustls clients that use the default verifier.

Aside from that, I think we've met the goal of this issue so we can close it.
