### ISSUE TITLE
cargo audit, webpki, and high severity vulnerability

### ISSUE THREAD

**Issue by ptdecker** [rustls/rustls#1554]
Hello!

I ran `cargo audit` against our code base and the only vulnerability it flagged is a severity `high` in rustls-webpki 0.101.2 (see below). Our project does not have a direct dependency on it.  Instead, it comes through our usage of the current axum-server (v0.5.1) which used rustls (v0.21.5) which in tern is the one using rustls-webpki (v0.101.2).

I looked in the current open issues and didn't see anything logged to correct this so I thought I'd put something in the queue.

Thank you!

cargo audit report:

```
Crate:     rustls-webpki
Version:   0.101.2
Title:     rustls-webpki: CPU denial of service in certificate path building
Date:      2023-08-22
ID:        RUSTSEC-2023-0053
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0053
Severity:  7.5 (high)
Solution:  Upgrade to >=0.100.2, <0.101.0 OR >=0.101.4
Dependency tree:
rustls-webpki 0.101.2
└── rustls 0.21.5
    ├── tokio-rustls 0.24.1
    │   ├── rbdc 4.4.1
    │   │   ├── rbdc-sqlite 4.4.0
    │   │   │   └── securikey-server 1.7.0
    │   │   └── rbatis 4.4.2
    │   │       └── securikey-server 1.7.0
    │   └── axum-server 0.5.1
    │       └── securikey-server 1.7.0
    ├── rbdc 4.4.1
    └── axum-server 0.5.1

error: 1 vulnerability found!
```

cargo tree report indicating how it is pulled into my project:

```
 14 ├── axum-server v0.5.1
 13 │   ├── arc-swap v1.6.0
 12 │   ├── bytes v1.5.0
 11 │   ├── futures-util v0.3.28 (*)
 10 │   ├── http v0.2.9 (*)
  9 │   ├── http-body v0.4.5 (*)
  8 │   ├── hyper v0.14.27 (*)
  7 │   ├── pin-project-lite v0.2.13
  6 │   ├── rustls v0.21.5
  5 │   │   ├── log v0.4.20
  4 │   │   ├── ring v0.16.20
  3 │   │   │   └── untrusted v0.7.1
  2 │   │   │   [build-dependencies]
  1 │   │   │   └── cc v1.0.79
204 │   │   ├── rustls-webpki v0.101.2
  1 │   │   │   ├── ring v0.16.20 (*)
  2 │   │   │   └── untrusted v0.7.1
  3 │   │   └── sct v0.7.0
  4 │   │       ├── ring v0.16.20 (*)
  5 │   │       └── untrusted v0.7.1
  6 │   ├── rustls-pemfile v1.0.3
  7 │   │   └── base64 v0.21.4
  8 │   ├── tokio v1.33.0 (*)
  9 │   ├── tokio-rustls v0.24.1
 10 │   │   ├── rustls v0.21.5 (*)
 11 │   │   └── tokio v1.33.0 (*)
 12 │   └── tower-service v0.3.2
```

**Comment by djc** [comment]
rustls-webpki is maintained by the same team as rustls, so we're definitely aware. There are no open issues because this issue has been fixed in a subsequent rustls-webpki release, see here:

https://github.com/rustls/webpki/releases

**Comment by cpu** [comment]
In particular the vulnerability in question has been resolved fully since [0.101.5](https://github.com/rustls/webpki/releases/tag/v%2F0.101.5), and the most substantial aspect in [0.101.4](https://github.com/rustls/webpki/releases/tag/v%2F0.101.4).

**Comment by ctz** [comment]
As mentioned in the vuln report you posted, this was fixed in rustls-webpki v0.101.3 (there are further fixes in v0.101.5 and I would strongly recommend updating to that version). That is semver compatible with v0.101.2, so all that should be needed on your side is `cargo update -p rustls-webpki`.

**Comment by ptdecker** [comment]
Thank you @ctz @cpu and @djc .   `cargo update` resolved my issue as you all knew it would.  Excuse my ignorance being  about a 18 months new to Rust.  I came from a world where it was pretty taboo to change dependencies of packages upon which I indirectly use via my top-level dependencies.  Again the Rust system is nicer and safer.  And, I learned something new .  Thanks again

**Comment by cpu** [comment]
Happy to help!
