### ISSUE TITLE
Debug bounds for customization traits

### ISSUE THREAD

**Issue by jsha** [rustls/rustls#1555]
A quick review of some of our customization traits:

```
pub trait CryptoProvider: Send + Sync + Debug + 'static {
pub trait KeyLog: Send + Sync {
pub trait ClientSessionStore: Send + Sync {
pub trait Signer: Send + Sync {
pub trait ResolvesServerCert: Send + Sync {
```

Our newest customization trait (CryptoProvider) has a Debug bound, which is great. Most of our others don't.

That means some of our internal structs, like ServerConfig, implement a custom Debug that doesn't mention these traits:

https://github.com/rustls/rustls/blob/829471689e6c414b1bc2d51aef541d2ed1a31335/rustls/src/server/server_conn.rs#L340

Implementing a custom Debug isn't by itself a problem; we also do that in places to hide data that shouldn't wind up in logs. But when print the Debug format of a server config, for instance, it would be useful to know the type of the `CryptoProvider`, `KeyLog`, etc.

Since we have a breaking change coming up, it might be a useful time to add Debug bounds on these. The idea being that most implementations would implement something very simple, like the name of the implementing type. For instance, right now `struct Ring;` has `#[derive(Debug)]` so it just prints `Ring`.

**Comment by cpu** [comment]
Adding the `Debug` bound to the `ResolvesServerCert` seems like a good idea to me :+1:  For `KeyLog`, `ClientSessionStore`, and `Signer` I'm slightly hesitant.

As you mention, you need to take care implementing `Debug` for types that might contain sensitive data. I think most 
implementations of these traits are going to fall into that category. Adding a `Debug` bound will force downstream implementations to add code to satisfy the new requirement and I worry it will be tempting to `#[derive(Debug)]` as part of tidying up an upgrade's breaking changes without considering the potential for leaking something sensitive. We can call out the risk explicitly but I'm not sure I'm 100% convinced the reward is worth the risk. WDYT?

**Comment by cpu** [comment]
While we're considering this, I think to drop the custom `Debug` impl on `ServerConfig` and `ClientConfig` we'd also need to add a `Debug` bound on `StoresServerSessions`, `ProducesTickets`, and `ResolvesClientCert`

**Comment by jsha** [comment]
Yeah, I think your logic about not requiring Debug for types at high risk of containing secrets makes sense. `KeyLog` probably doesn't contain secrets in general, but also I suspect most users will use one of the built-ins (`KeyLogFile` or `NoKeyLog`).

> I think to drop the custom Debug impl on ServerConfig and ClientConfig we'd also need to add a Debug bound on StoresServerSessions, ProducesTickets, and ResolvesClientCert

Yep. I didn't review all the traits but we can check them out here: https://docs.rs/rustls/latest/rustls/all.html#traits

BTW I don't think removing the custom Debug impl on ServerConfig needs to be a goal, but it's one place I noticed where we are omitting several fields because we can't print anything about them.

**Comment by djc** [comment]
I think adding `Debug` bounds for all traits outside of `internals` makes sense.

**Comment by cpu** [comment]
> KeyLog probably doesn't contain secrets in general, but also I suspect most users will use one of the built-ins (KeyLogFile or NoKeyLog).

Maybe not in general, but `KeyLogFile` holds a `KeyLogFileInner` that itself has a [buf](https://github.com/rustls/rustls/blob/169671fbc11c13df009a2d7ff3d0db5a492005d1/rustls/src/key_log_file.rs#L17) that looks like it could [hold secret data](https://github.com/rustls/rustls/blob/169671fbc11c13df009a2d7ff3d0db5a492005d1/rustls/src/key_log_file.rs#L66-L70). Looking at it, maybe also a candidate for `Zeroize` ala https://github.com/rustls/rustls/pull/1492?

**Comment by cpu** [comment]
> I think adding Debug bounds for all traits outside of internals makes sense.

I'll put up a PR like this and we can figure out which to keep/drop in review.
