### ISSUE TITLE
rustls 0.21.8 still depends on ring 0.16

### ISSUE THREAD

**Issue by littledivy** [rustls/rustls#1557]
https://github.com/rustls/rustls/blob/v/0.21.8/rustls/Cargo.toml#L21

Hey, `rustls` 0.21.8 depends on `sct` 0.7.0 which pulls in `ring` 0.16. `sct` should probably be bumped to 0.7.1?

**Comment by ctz** [comment]
Please see https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio

Just running `cargo update` should be sufficient.
