### ISSUE TITLE
Need more general error used in trait `SupportedKxGroup`

### ISSUE THREAD

**Issue by Taowyoo** [rustls/rustls#1569]
## Background
I am implementing crypto provider for `rustls` by using [rust-mbedtls](https://github.com/fortanix/rust-mbedtls). When implementing [`rustls::crypto::SupportedKxGroup`](https://docs.rs/rustls/0.22.0-alpha.3/rustls/crypto/trait.SupportedKxGroup.html) the return error type of `fn start` is restricted to [GetRandomFailed](https://docs.rs/rustls/0.22.0-alpha.3/rustls/crypto/struct.GetRandomFailed.html), so the impl cannot return other error if underlying error is not related to RNG.

## Proposed solution

Update function signature to
```rust
fn start(&self) -> Result<Box<dyn ActiveKeyExchange>, rustls::Error>;
```

## Additional Notes

- Also want to check the ideal of add one more variant in `rustls::Error`  like `rustls::CertificateError::Other(Arc<dyn StdError + Send + Sync>)` so error from underlying crypto provider can be exposed. (Will create another issue if this makes sense)

**Comment by djc** [comment]
Yup, changing the return type of the trait method makes sense to me, and so does adding an `Other` variant to `rustls::Error` (no need to make another issue). Would you be able to submit a PR?

**Comment by Taowyoo** [comment]
Sure, I will create a PR for this.

**Comment by Taowyoo** [comment]
PR created ^
