### ISSUE TITLE
DHE KeyExchangeAlgorithm Support

### ISSUE THREAD

**Issue by Taowyoo** [rustls/rustls#1576]
## Background

In my use case, I want to use `rustls` with my custom crypto provider to support DHE based TLS 1.2 cipher suites.

## Proposal

I noticed in `NamedGroup`, there are `FFDHE` groups.
DHE also has perfect forward secrecy but just slower.

So, I wondering if it possible to support DHE? I could help with adding this feature.

**Comment by ctz** [comment]
I think we could make it work for named groups (ie, https://www.rfc-editor.org/rfc/rfc7919 and TLS1.3), though it'd need a good rationale due to the general poor quality of DH implementations compared to ECDH.

I don't think I ever want to see code to support generic DHE; the design is just too broken to ever implement safely.

**Comment by Taowyoo** [comment]
I see. It makes sense.
Thank you for quick reply.

**Comment by Taowyoo** [comment]
> I think we could make it work for named groups (ie, https://www.rfc-editor.org/rfc/rfc7919 and TLS1.3),

I could help adding support of this. If I understand correctly, FFDHE (https://www.rfc-editor.org/rfc/rfc7919) with TLS 1.2 is acceptable, right?

**Comment by ctz** [comment]
I would accept a PR that makes it possible for downstream `CryptoProvider` to define and use `SupportedKxGroup`s for `NamedGroup::FFDHE2048` (and alike).

This, I think, is:

- adds a `Dhe` variant to `ServerKeyExchangePayload`
- adds a `DHE` variant to `KeyExchangeAlgorithm`
- implements ciphersuite filtering for TLS1.2 (probably be extended/generalising `usable_for_signature_algorithm`)
- tests that validate it at the rustls public API level (these can just be pre-generated values, it shouldn't need to do a modexp)

But it isn't:

- non-RFC7919 DHE support
- adding it to the default key exchanges offered by the built-in _ring_/aws-lc-rs providers

**Comment by s-arash** [comment]
Thanks @ctz, this is very helpful. We'll try and open a PR in the next couple of weeks.
