### ISSUE TITLE
Allow `ClientCertVerifier`s to check the SNI when deciding whether to require client authentication

### ISSUE THREAD

**Issue by s-arash** [rustls/rustls#1580]
A custom `ClientCertVerifier` has the option of asking for (or demanding) client authentication. With SNI, a server can serve traffic for different hostnames. But currently, there is no way for the `ClientCertVerifier` to know what hostname a client is trying to connect to. 

For example, a server can serve two different host names: `foo.com` and `foo-admin.com`, and we'd like clients connecting to `foo-admin.com` to be authenticated. 

I propose that we modify `ClientCertVerifier` so that `client_auth_mandatory()` and `offer_client_auth()` can inspect the provided SNI.

I can open a PR for this proposal if this looks like a good idea.

**Comment by ctz** [comment]
The paved path for achieving this is the [`Acceptor` API](https://docs.rs/rustls/latest/rustls/server/struct.Acceptor.html). You get the entire ClientHello contents, and can choose different `ClientCertVerifier`s depending on the SNI details.

**Comment by cpu** [comment]
There's also [a small example](https://github.com/rustls/rustls/blob/main/examples/src/bin/server_acceptor.rs) using this API available for reference in case you find that helpful.

**Comment by s-arash** [comment]
Thank you both for the quick responses. I'll look into the Acceptor API!
