### ISSUE TITLE
Invalidating TLS 1.2 session tickets

### ISSUE THREAD

**Issue by Geal** [rustls/rustls#1617]
apologies in advance because the issue is still unclear to me

we have some hyper-rustls clients that were connecting to a TLS 1.2 endpoint. At some point, those connections started failing in a loop, until they were restarted, and then it worked fine.

When looking at the traffic, a handshake was started by the client with TLS 1.2 session tickets, the server responded with its hello, change cipherspec and the handshake message. And right there the client sends a "Bad Record MAC" alert. The server answers with an encrypted alert, then the connection is closed by the client.

The session ticket was created by that server and should have been ok to reuse, but we don't control the server and don't have much info on its internals or what happened on the server side.

My wild guess is that there was something wrong with the ticket, maybe it was modified on the network and that server does not verify it, or maybe it's deserialized in a different way. But that would in the server using a different TLS state than the client, sending a message with it that the client cannot verify, so the client returns "Bad Record MAC".
And the issue I think is in rustls is that it does not remove tickets from the store, so on the next connection, it tries the same ticket and it fails reliably. It looks like the session ticket implementation was meant to be driven by the server, which would send a new session ticket to overwrite the old one.
But shouldn't the store delete the old ticket if there was an issue with the handshake?

**Comment by djc** [comment]
Hmm, interesting edge case. It seems reasonable to discard a ticket if it was tried and led to a handshake error.

**Comment by Geal** [comment]
Would you accept a PR for it? I'm still not 100% sure this is the cause of the bug, but it still looks like a problem that could happen

**Comment by djc** [comment]
Yes, would be happy to review a PR for this.

**Comment by Geal** [comment]
the PR is up! I tried to make it as small as possible but it has to break the abstraction a bit, because the state machine works on valid messages, and here we must handle an invalid one
