### ISSUE TITLE
Investigate throughput performance gap with OpenSSL

### ISSUE THREAD

**Issue by aochagavia** [rustls/rustls#1626]
This week I finally got around to running the throughput benchmarks (reproducing @ctz's [experiments from 2019](https://jbp.io/2019/07/01/rustls-vs-openssl-performance.html)). They revealed a big performance gap with OpenSSL in data transfers, so we'll probably want to look into that and figure out what's going on.

### Methodology

I tested the following versions:

- rustls [6a47cd5c](https://github.com/ctz/rustls/tree/6a47cd5cb411042d9a8acc591203ede10632ea2e) (the same version @ctz tested in 2019)
- rustls [1db4506d](https://github.com/rustls/rustls/tree/1db4506dcfeb4a08b5517eafba84f16084321786) (head of the main branch a few days ago), using the ring backend.
- OpenSSL [fdbb3a86](https://github.com/openssl/openssl/tree/fdbb3a86) (the same version @ctz tested in 2019)
- OpenSSL 3.1.4 (most recent stable release until yesterday)

For each version, I ran the benchmarks 30 times on the bare-metal server and took the median of the results per scenario. I followed the instructions in the original blog post, but used `BENCH_MULTIPLIER=8` for faster iteration (also relevant for anyone who wants to reproduce: the rust benchmarks need to be built using `cargo build`, not `cargo test --no-run`).

Additional details about toolchains and hardware:

- GCC 12.2.0
- Rust 1.74.0
- CPU: Xeon E-2386G (hyper-threading disabled, dynamic frequency scaling disabled)

### Observations

_See the tables after this section for the detailed results._

1. When comparing old OpenSSL vs old rustls I saw different results than those reported [here](https://jbp.io/2019/07/01/rustls-vs-openssl-performance.html#results). More specifically, the rustls benchmarks yield somewhat similar results, but the OpenSSL benchmarks show much higher throughput (maybe GCC got extra optimizations in the meantime?). According to these results, __old rustls is slower than old OpenSSL for data transfers, but faster for handshakes__.
2. Comparing old vs current OpenSSL, the current version shows a steep speedup in data transfers when using AES (1.5x to 1.7x for all AES benchmarks). ChaCha20 throughput remained stable and handshake throughput had mixed changes.
3. Comparing old vs current rustls, the current version shows roughly the same performance characteristics for all benchmarks.
5. Since OpenSSL became faster (see 2) and rustls didn't (see 3), there is a noticeable performance gap between both libraries. This is most visible for data transfers using AES, where __rustls shows between 0.3x and 0.6x the throughput of OpenSSL__.
6. Rustls still beats OpenSSL in most of the handshake benchmarks.

### All results

The numbers below represent throughput (MB/s in the case of bulk benchmarks and handshakes/s in the case of handshake benchmarks). The "Factor" column shows the factor by which the right column has a speed up (or slow down) compared to the left column (e.g. 2x means twice as fast, 0.5x means half as fast).

#### Current OpenSSL vs current rustls

|Scenario|OpenSSL (3.1.4)|Rustls (current)|Factor|
|-|-:|-:|-:|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_sent|6568.69|2235.2|0.34x|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_received|7160.79|4112.01|0.57x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_sent|6168.09|2102.88|0.34x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_received|6688.51|3667.54|0.55x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_sent|3046.36|1274.79|0.42x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_received|3124.93|1736.57|0.56x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_sent|6068.36|1713.87|0.28x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_received|6602.5|3686.79|0.56x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|2169.57|3524.74|1.62x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|2158.11|1424.86|0.66x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|24536.4|46134.38|1.88x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|26229.9|41920.45|1.60x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|24101.0|44291.85|1.84x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|22080.4|38325.5|1.74x|
|handshake_TLS13_AES_256_GCM_SHA384_client|1957.89|3867.71|1.98x|
|handshake_TLS13_AES_256_GCM_SHA384_server|1914.24|1370.22|0.72x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_client|3218.32|11758.9|3.65x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_server|3290.57|7012.11|2.13x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_client|5397.22|11786.39|2.18x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_server|4907.12|6980.71|1.42x|

#### Old OpenSSL vs old rustls

|Scenario|OpenSSL (old)|Rustls (old)|Factor|
|-|-:|-:|-:|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_sent|4289.53|2304.03|0.54x|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_received|4551.49|4172.97|0.92x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_sent|3811.32|2151.65|0.56x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_received|4024.58|3712.32|0.92x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_sent|3060.3|1297.45|0.42x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_received|3169.78|1738.69|0.55x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_sent|3640.46|1741.82|0.48x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_received|3898.31|3712.5|0.95x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|3173.82|3528.66|1.11x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|1335.75|1426.53|1.07x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|26022.7|47309.52|1.82x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|27671.4|42671.66|1.54x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|25548.9|45171.03|1.77x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|23952.6|39021.35|1.63x|
|handshake_TLS13_AES_256_GCM_SHA384_client|2568.59|3902.0|1.52x|
|handshake_TLS13_AES_256_GCM_SHA384_server|1245.25|1372.1|1.10x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_client|3736.8|11941.19|3.20x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_server|2531.84|7060.31|2.79x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_client|5331.78|11968.67|2.24x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_server|5768.57|7046.78|1.22x|

#### Old OpenSSL vs current OpenSSL

|Scenario|OpenSSL (old)|OpenSSL (3.1.4)|Factor|
|-|-:|-:|-:|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_sent|4289.53|6568.69|1.53x|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_received|4551.49|7160.79|1.57x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_sent|3811.32|6168.09|1.62x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_received|4024.58|6688.51|1.66x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_sent|3060.3|3046.36|1.00x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_received|3169.78|3124.93|0.99x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_sent|3640.46|6068.36|1.67x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_received|3898.31|6602.5|1.69x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|3173.82|2169.57|0.68x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|1335.75|2158.11|1.62x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|26022.7|24536.4|0.94x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|27671.4|26229.9|0.95x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|25548.9|24101.0|0.94x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|23952.6|22080.4|0.92x|
|handshake_TLS13_AES_256_GCM_SHA384_client|2568.59|1957.89|0.76x|
|handshake_TLS13_AES_256_GCM_SHA384_server|1245.25|1914.24|1.54x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_client|3736.8|3218.32|0.86x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_server|2531.84|3290.57|1.30x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_client|5331.78|5397.22|1.01x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_server|5768.57|4907.12|0.85x|

#### Old rustls vs current rustls

|Scenario|Rustls (old)|Rustls (current)|Factor|
|-|-:|-:|-:|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_sent|2304.03|2235.2|0.97x|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_received|4172.97|4112.01|0.99x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_sent|2151.65|2102.88|0.98x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_received|3712.32|3667.54|0.99x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_sent|1297.45|1274.79|0.98x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_received|1738.69|1736.57|1.00x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_sent|1741.82|1713.87|0.98x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_received|3712.5|3686.79|0.99x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|3528.66|3524.74|1.00x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|1426.53|1424.86|1.00x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|47309.52|46134.38|0.98x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|42671.66|41920.45|0.98x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|45171.03|44291.85|0.98x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|39021.35|38325.5|0.98x|
|handshake_TLS13_AES_256_GCM_SHA384_client|3902.0|3867.71|0.99x|
|handshake_TLS13_AES_256_GCM_SHA384_server|1372.1|1370.22|1.00x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_client|11941.19|11758.9|0.98x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_server|7060.31|7012.11|0.99x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_client|11968.67|11786.39|0.98x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_server|7046.78|6980.71|0.99x|

### Bonus 1: current rustls (ring) vs current rustls (aws-lc-rs)

|Scenario|Rustls (ring)|Rustls (aws-lc-rs)|Factor|
|-|-:|-:|-:|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_sent|2235.2|2824.7|1.26x|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_received|4112.01|6032.33|1.47x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_sent|2102.88|2766.78|1.32x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_received|3667.54|5725.1|1.56x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_sent|1274.79|1294.21|1.02x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_received|1736.57|1726.11|0.99x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_sent|1713.87|1726.64|1.01x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_received|3686.79|5973.35|1.62x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|3524.74|4940.22|1.40x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|1424.86|1482.05|1.04x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|46134.38|48015.86|1.04x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|41920.45|41279.67|0.98x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|44291.85|45543.75|1.03x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|38325.5|35775.98|0.93x|
|handshake_TLS13_AES_256_GCM_SHA384_client|3867.71|4641.32|1.20x|
|handshake_TLS13_AES_256_GCM_SHA384_server|1370.22|1358.53|0.99x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_client|11758.9|11003.55|0.94x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_server|7012.11|7264.81|1.04x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_client|11786.39|11040.41|0.94x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_server|6980.71|7238.9|1.04x|

#### Bonus 2: current OpenSSL vs current rustls (aws-lc-rs)

|Scenario|OpenSSL (3.1.4)|Rustls (aws-lc-rs)|Factor|
|-|-:|-:|-:|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_sent|6568.69|2824.7|0.43x|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_received|7160.79|6032.33|0.84x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_sent|6168.09|2766.78|0.45x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_received|6688.51|5725.1|0.86x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_sent|3046.36|1294.21|0.42x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_received|3124.93|1726.11|0.55x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_sent|6068.36|1726.64|0.28x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_received|6602.5|5973.35|0.90x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|2169.57|4940.22|2.28x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|2158.11|1482.05|0.69x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|24536.4|48015.86|1.96x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|26229.9|41279.67|1.57x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|24101.0|45543.75|1.89x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|22080.4|35775.98|1.62x|
|handshake_TLS13_AES_256_GCM_SHA384_client|1957.89|4641.32|2.37x|
|handshake_TLS13_AES_256_GCM_SHA384_server|1914.24|1358.53|0.71x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_client|3218.32|11003.55|3.42x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_server|3290.57|7264.81|2.21x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_client|5397.22|11040.41|2.05x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_server|4907.12|7238.9|1.48x|

**Comment by djc** [comment]
cc @briansmith this might be of interest.

**Comment by aochagavia** [comment]
> (Please be more specific about the meaning of the numbers in these tables? Are these all throughput numbers? Do they measure bytes or handshakes or different things for bulk vs handshake? What is the factor exactly?)

Just added a clarification, right under the "All results" title

**Comment by briansmith** [comment]
> CPU: Xeon E-2386G

Off the top of my head:

Xeon E-2386G has AVX-512. OpenSSL has AVX-512 AES-GCM and an analogous one for AAarch64 that has a very large code size. Upstream BoringSSL didn't want to accept the code the way it is currently written. So far *ring* hasn't diverged from BoringSSL regarding such things. I expect that BoringSSL will find a solution for getting the optimizations without the huge increase in code size.

So far, BoringSSL upstream hasn't introduced any AVX-512 code, AFAICT.

Additionally, there are issues with the AVX-512 register saving logic in macOS, where it isn't fully compatible with what BoringSSL does for CPUID. Since X86-64 Macs seem like a dead-end, we probably should just not even try to do anything AVX-512 on macOS.

**Comment by ctz** [comment]
That makes a lot of sense. We can confirm that by re-running the openssl performance tests without AVX-512: https://www.openssl.org/docs/manmaster/man3/OPENSSL_ia32cap.html

**Comment by aochagavia** [comment]
Here's a table comparing our existing results for old OpenSSL against a new run for 3.1.4 with AVX-512 disabled. It seems to confirm that the speedup is due to using AVX-512 in the AES path!

|Scenario|OpenSSL (old)|OpenSSL (3.1.4, no AVX 512)|Factor|
|-|-:|-:|-:|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_sent|4289.53|4059.44|0.95x|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_received|4551.49|4324.18|0.95x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_sent|3811.32|3655.15|0.96x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_received|4024.58|3810.17|0.95x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_sent|3060.3|1683.44|0.55x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_received|3169.78|1716.99|0.54x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_sent|3640.46|3589.8|0.99x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_received|3898.31|3777.87|0.97x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|3173.82|2156.14|0.68x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|1335.75|1290.12|0.97x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|26022.7|24288.8|0.93x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|27671.4|25899.2|0.94x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|25548.9|23735.5|0.93x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|23952.6|21781.5|0.91x|
|handshake_TLS13_AES_256_GCM_SHA384_client|2568.59|1926.57|0.75x|
|handshake_TLS13_AES_256_GCM_SHA384_server|1245.25|1184.12|0.95x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_client|3736.8|3153.84|0.84x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_server|2531.84|2362.43|0.93x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_client|5331.78|5374.09|1.01x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_server|5768.57|4889.43|0.85x|

You can reproduce these results locally by running the benchmarks with `OPENSSL_ia32cap=:~0xC0230000`. The hex number is a bit mask where each bit represents a CPU feature we are disabling (the meaning of each bit is explained [here](https://www.openssl.org/docs/manmaster/man3/OPENSSL_ia32cap.html); the indexes are zero-based starting from the right).

**Comment by briansmith** [comment]
> GCC 12.2.0

*ring* will be much slower at doing X25519/Ed25519 if you use GCC. It will be much faster if you use Clang, which we already know.

**Comment by briansmith** [comment]
In general, the schedole of OpenSSL and *ring* don't line up 1:1 so there are going to be times where OpenSSL performance improves and then plateaus, and similarly for *ring*.

There are some small changes pending in *ring* that will improve these performance figures without requiring any API changes or new APIs in *ring*. Happy to discuss that in the *ring* issue tracker if people are interested in helping with that work. Similarly, there are bigger changes (e.g. finding a solution for using AVX-512 for bulk encryption; avoiding the getrandom syscall in ECDSA signing); again, if people are interested in actually helping, I am open to discussing that.

Similarly, there are API changes that we need to make to *ring* that will also improve performance by allowing Rustls to do things more efficiently. The hacks Rustls does for EcdsaKeyPair are one example of this; A single EcdsaKeyPair needs to be able to support more than one digest algorithm. People who are working on Rustls on a daily basis should be able to identify these easily; it would be nice to actually receive at least bug reports about these. (I would guess that maybe out-of-place AEAD encryption/decryption would be another one.)

The way the benchmarks above are presented aren't ideal for understanding the performance differences.

My understanding is that OpenSSL 3 has scalability issues because of its internal locking. Maybe that just got fixed recently? I think a C10k-style benchmark is much more interesting.

In general I feel like *ring* has an inherent advantage over OpenSSL in terms of overhead, due to design. Not all of those advantages are fully realized yet but it is a matter of time. OpenSSL has a lot of contributors who give it lots of low-level optimizations that take time to make it through the various QA layers as they trickle down to *ring*. When we can afford to spend a few person-months on performance in *ring* we'll be in a very good place.

**Comment by briansmith** [comment]
I noticed that Rustls seems to be much slower at "sending" than "receiving" in the above table for both *ring* and the AWS thing. So it seems likely a lot of performance difference is in the record layer.

FYI, I also released *ring* 0.17.6 that has a few RSA verification tweaks.

**Comment by briansmith** [comment]
aws-lc-rs may also have the AVX-512 AES-GCM (at least), IIUC.

I am not sure it makes sense to benchmark on an AVX-512 system where the use of AVX-512 instructions is disabled, to understand non-AVX-512 performance. non-AVX-512 performance increasingly will matter more for clients than for servers, and for AMD systems more than Intel systems, I'm guessing. If one has an Intel system that is AVX-512 enabled, then those AVX-512 optimizations are probably worthwhile, even given the code size increase.

I also think it makes sense to prioritize what we're measuring. It may be easy to measure "every cipher suite" but there are a few combinations that matter a lot. Namely, X25519 for key exchange + RSA for signatures (since most people seem to use RSA certs) + AES-128-GCM for bulk encryption, as pretty much every connection with a modern client and a modern server is going to pick that combination. X25519 + ECDSA P-256 + AES-128-GCM would be the next priorty, IMO. I'm not saying other combinations don't matter, but the marginal utility drops fast and then improving the feature set or other aspects of performance (scalability, memory usage, etc.) probably are more worthwhile to focus on. All IMHO, of course.

**Comment by aochagavia** [comment]
Regarding the throughput difference between writes and reads in the bulk benchmarks, the [results from 2019](https://jbp.io/2019/07/02/rustls-vs-openssl-bulk-performance.html) show a much less pronounced difference than what we are seeing now (< 50 MB/s back then vs. up to 2 GB/s now). Since the Xeon processor is so different than the processor used to run the original benchmarks, I set up a bare-metal machine with a consumer-grade processor (i5-13500) and observed that the difference is less pronounced there (up to 400 MB/s). Not sure about what this means exactly, but I'm mentioning it here in case anyone has ideas. I'll go through the benchmarking code once again to see if I become any wiser. Below are the results:

|Scenario|OpenSSL (3.1.4, i5-13500)|Rustls (current, i5-13500)|Factor|
|-|-:|-:|-:|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_sent|1686.33|1127.41|0.67x|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_received|1947.3|1580.04|0.81x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_sent|1563.83|1064.31|0.68x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_received|1789.23|1465.01|0.82x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_sent|443.58|521.92|1.18x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_received|457.783|610.14|1.33x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_sent|1539.0|615.11|0.40x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_received|1449.62|1470.27|1.01x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|778.786|743.96|0.96x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|335.621|324.67|0.97x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|9349.11|5839.48|0.62x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|9770.53|5658.7|0.58x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|9212.43|5565.42|0.60x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|8506.5|5300.31|0.62x|
|handshake_TLS13_AES_256_GCM_SHA384_client|720.014|709.02|0.98x|
|handshake_TLS13_AES_256_GCM_SHA384_server|321.212|298.23|0.93x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_client|1250.69|1788.85|1.43x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_server|702.464|1255.53|1.79x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_client|2345.98|1777.78|0.76x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_server|2107.95|1238.5|0.59x|

Regarding the way of benchmarking, I'm definitely open to improving the current setup. Maybe @ctz can chime in with a bit more background on how he arrived at the current benchmarks (e.g. selection of cipher suites, division in bulk vs handshake scenarios, etc).

Finally, I ran the rustls benchmarks under Clang and saw increased performance for handshakes and unchanged performance for bulk transfers (as expected). Here are the results against AVX-512-enabled OpenSSL, in case anyone is interested:

|Scenario|OpenSSL (3.1.4)|Rustls (current, clang)|Factor|
|-|-:|-:|-:|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_sent|6568.69|2239.41|0.34x|
|bulk_TLS12_ECDHE-RSA-AES128-GCM-SHA256_1048576_received|7160.79|4115.52|0.57x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_sent|6168.09|2107.09|0.34x|
|bulk_TLS12_ECDHE-RSA-AES256-GCM-SHA384_1048576_received|6688.51|3674.78|0.55x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_sent|3046.36|1277.16|0.42x|
|bulk_TLS12_ECDHE-RSA-CHACHA20-POLY1305_1048576_received|3124.93|1738.4|0.56x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_sent|6068.36|1715.02|0.28x|
|bulk_TLS13_AES_256_GCM_SHA384_1048576_received|6602.5|3677.24|0.56x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|2169.57|3937.43|1.81x|
|handshake_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|2158.11|1489.06|0.69x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|24536.4|46368.06|1.89x|
|handshake-resume_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|26229.9|41833.9|1.59x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_client|24101.0|44958.54|1.87x|
|handshake-ticket_TLS12_ECDHE-RSA-AES256-GCM-SHA384_server|22080.4|38930.16|1.76x|
|handshake_TLS13_AES_256_GCM_SHA384_client|1957.89|3947.53|2.02x|
|handshake_TLS13_AES_256_GCM_SHA384_server|1914.24|1429.56|0.75x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_client|3218.32|12534.3|3.89x|
|handshake-resume_TLS13_AES_256_GCM_SHA384_server|3290.57|8897.89|2.70x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_client|5397.22|12500.2|2.32x|
|handshake-ticket_TLS13_AES_256_GCM_SHA384_server|4907.12|8841.24|1.80x|

**Comment by briansmith** [comment]
Some suggestions for improving the presentation:
* Separate benchmark type, server/client, sent/received aspects into separate columns.
* Make the table sortable (Google Sheets?)
* If we move this out of Google sheets, we can put all the results in a single table (well, maybe separate ones for bulk vs handshake).
* Is there some way we can make explicit the key sizes (for signing/verifying) and key exchange curve?

Regarding sending vs. receiving performance: I guess we should verify that within *ring*, encrypt and decrypt performance is the same (within noise). *ring* has its own benchmarks, bench/aead.rs, that would help with that. If they are different then that is a bug in *ring*. Then we should look at the Rustls record layer logic for sending. It seems there must be something in the Rustls record layer or some common issue between *ring* and aws-lc-rs because Rustls exhibits a similar difference in send vs. receive performance.

**Comment by djc** [comment]
Looks like https://github.com/rustls/rustls/pull/1640/files might help with some of the write-side performance issues.

**Comment by aochagavia** [comment]
I benchmarked both ring and aws-lc using their own suites and observed that the difference in read/write performance should be very small. This suggests that there is something wrong with the rustls benchmarks or that rustls itself has asymmetric performance at the moment. I'll keep investigating.

**Comment by aochagavia** [comment]
Today I implemented a no-op crypto backend and benchmarked it on the server. Could anyone with knowledge of rustls internals double-check it's doing the right thing? Here's the [relevant diff](https://github.com/aochagavia/rustls/commit/5246612587198b53f09825f49bdf19bb5c48ba7f).

Results:

- send: 3681.95 MB/s
- receive: 9622.67 MB/s

Interestingly, running it locally yields a different picture (AMD Ryzen 5 PRO 5650U):

- send: 4417.53 MB/s
- receive: 1660.33 MB/s

I'll be thinking about the results, but wanted to post them here in the meantime so you can check the code behind them is sound.

**Comment by briansmith** [comment]
> I'm considering implementing the benchmarks on top of the https://github.com/rustls/rustls/pull/1583

I think first we should benchmark the Kernel TLS configuration and get things so that we're winning that benchmark, ideally with zero or few allocations. For people who really need the best performance, kernel TLS is likely what they want. I think then we should optimize the io_uring case. And then afterwards optimize the naive case. If we do things in a different order we're likely going to paint ourselves into a corner w.r.t. kernel TLS and/or io_uring performance.

**Comment by aochagavia** [comment]
I did some more digging to figure out why the results for TLS 1.3 didn't improve after the allocator change and discovered an error in my table-generating code. I have updated the tables in my last comment and you can now see that the TLS 1.3 path also got a boost from the jemalloc switch.

I'm not terribly experienced with this stuff, but I think the boost in throughput is due to a massive decrease in page faults. Specifically, `perf stat -e page-faults` reports a drop from 1876648 to 8707 after switching to jemalloc (for a `bulk TLS13_AES_256_GCM_SHA384` run with `BENCH_MULTIPLIER=8`). In case you want to see more details, here you can find a flamegraph for [the run using malloc ](https://github.com/rustls/rustls/assets/5196584/a6746166-04d7-4a98-ade8-0b46a0fd83a8) and 
[the run using jemalloc](https://github.com/rustls/rustls/assets/5196584/a044b5d0-6ded-49db-811f-e1b69ae9eafa).

With these results I think the current performance gap with OpenSSL is explained, which was my goal when I opened the issue. There is of course still work to do, as @briansmith points out, but I'd rather leave that to a future effort (there are a bunch of other things I need to finish before the end of the month, as my contract is about to end). I'll make sure to summarize our findings in a friendly format, to prevent people from having to wade through this issue's numerous comments.
