### ISSUE TITLE
`CryptoProvider` `ActiveKeyExchange` can't access secret when implementing `Prf` outside of the crate

### ISSUE THREAD

**Issue by janrueth** [rustls/rustls#1632]
**Checklist**
* [X] I've searched the issue tracker for similar bugs.

**Describe the bug**
When implementing the `tls12::Prf` in an external crate one needs to complete the key exchange.
The return type of that is `SharedSecret` however, to perform the PRF one subsequently needs access to the secret bytes (`secret_bytes()`).
The type however restricts access to the corresponding bytes to `pub (crate)` which means one cannot safely access them.

See: https://github.com/janrueth/boring-rustls-provider/blob/d38412a3bd7601d405a8ec3b9a15ec1981a46cb4/boring-rustls-provider/src/prf.rs#L24-L29

**To Reproduce**
Try to implement `tls12::Prf` externally to the crate

**Applicable Version(s)**
0.22.0-alpha.5

**Expected behavior**
The types required to implement all CryptoProvider traits should allow accessing the data required to implement the functionality.

**Additional context**
None

**Comment by ctz** [comment]
This is definitely an oversight.

**Comment by djc** [comment]
@janrueth want to send a PR to make `secret_bytes()` `pub`?

**Comment by janrueth** [comment]
sure!

**Comment by janrueth** [comment]
https://github.com/rustls/rustls/pull/1633
