### ISSUE TITLE
rustls 0.22.0-alpha.6 cycle in dependency graph

### ISSUE THREAD

**Issue by GlenDC** [rustls/rustls#1647]
**Checklist**
* [x] I've searched the issue tracker for similar bugs.

**Describe the bug**

Trying to update either `rustls` (from alpha-4 to alpha-6) or `tokio-rustls` (from alpha-2 to alpha-4) or both (preferred), results in all cargo commands giving a panic due to a cycle in the dependency graph. Unfortunotely I cannot seem to get more info on that, neither with backtrace on.

This is the diff on my monorepo:

```diff
diff --git a/rama-rt/Cargo.toml b/rama-rt/Cargo.toml
index 4d70e24..9dae0c0 100644
--- a/rama-rt/Cargo.toml
+++ b/rama-rt/Cargo.toml
@@ -13,8 +13,8 @@ authors = { workspace = true }
 # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

 [dependencies]
-rustls = "0.22.0-alpha.4"
+rustls = "0.22.0-alpha.6"
 tokio = { version = "1.33", features = ["net", "io-util", "rt-multi-thread"] }
 tokio-graceful = "0.1"
-tokio-rustls = "0.25.0-alpha.2"
+tokio-rustls = "0.25.0-alpha.4"
 tokio-test = "0.4.3"
```

Which results in the following output:

```
cargo check
    Updating crates.io index
thread 'main' panicked at src/cargo/util/graph.rs:149:20:
the only path was a cycle, no dependency graph has this shape
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**

1. clone repo https://github.com/plabayo/rama on commit `39b647692299fc544dde4d66be72b29338d7419f`
2. apply the above diff
3. enjoy the obscure output

**Applicable Version(s)**

```
rustls = "0.22.0-alpha.6"
tokio-rustls = "0.25.0-alpha.4"
```

**Expected behavior**

That my commands just succeed instead of a cyclic dependency.

**Additional context**

I thought https://github.com/rustls/tokio-rustls/pull/31 would fix this,
thanks to @djc for the fast merge and publish.

It does however not fix the original issue I was trying to fix. Weird thing is that even
if I wipe my `target dir` and `cargo.lock` file, it still gives immediately the same error.

**Comment by djc** [comment]
Can you file a Cargo bug as well? Clearly they should have a better error message for this.

**Comment by ctz** [comment]
Yeah, I think this is 100% a cargo error handling bug.

(You will need to also adjust your `rustls-pki-types` version spec to match the version required by the pre-release `rustls` version.)

I would also recommend using `=` version specs for pre-releases.

**Comment by djc** [comment]
Cargo should improve its error handling for this case but you probably also have an issue in your dependency graph.

**Comment by GlenDC** [comment]
FYI the cargo team has already fixed the issue. I confirmed by updating my nightly version. It now gives decent error outputs to the quality I came to expect of rust error messages. When I now check the same commit version:

```
cargo check
    Updating crates.io index
error: failed to select a version for `rustls-pki-types`.
    ... required by package `rustls v0.22.0-alpha.6`
    ... which satisfies dependency `rustls = "^0.22.0-alpha.6"` of package `rama-rt v0.2.0 (/Users/glendc/code/github.com/plabayo/rama/rama-rt)`
    ... which satisfies path dependency `rama-rt` (locked to 0.2.0) of package `rama v0.2.0 (/Users/glendc/code/github.com/plabayo/rama)`
    ... which satisfies path dependency `rama` (locked to 0.2.0) of package `rama-rt-macros v0.2.0 (/Users/glendc/code/github.com/plabayo/rama/rama-rt-macros)`
versions that meet the requirements `^0.2.2` are: 0.2.3, 0.2.2

all possible versions conflict with previously selected packages.

  previously selected package `rustls-pki-types v0.2.1`
    ... which satisfies dependency `pki-types = "=0.2.1"` of package `rama v0.2.0 (/Users/glendc/code/github.com/plabayo/rama)`
    ... which satisfies path dependency `rama` (locked to 0.2.0) of package `rama-rt-macros v0.2.0 (/Users/glendc/code/github.com/plabayo/rama/rama-rt-macros)`

failed to select a version for `rustls-pki-types` which could resolve this conflict
```
