### ISSUE TITLE
ShangMi (SM) Cipher Suites

### ISSUE THREAD

**Issue by cherinyy** [rustls/rustls#1680]
**Checklist**

* [x] I've searched the issue tracker for similar requests

**Is your feature request related to a problem? Please describe.**

This Issue is about ShangMi (SM) Cipher Suites support. ShangMi Cipher Suites are national standards established by the Chinese government. It does not currently have global universality, but I think it can be given appropriate attention.

**Describe the solution you'd like**

[RFC 8998 - ShangMi (SM) Cipher Suites for TLS 1.3](https://datatracker.ietf.org/doc/html/rfc8998 "RFC 8998 - ShangMi (SM) Cipher Suites for TLS 1.3")

**Describe alternatives you've considered**

- [GB/T 38636-2020 - Information security technology—Transport layer cryptography protocol（TLCP）](https://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=778097598DA2761E94A5FF3F77BD66DA "国家标准|GB/T 38636-2020 - 信息安全技术 传输层密码协议（TLCP）") _(Chinese)_
- GM/T 0024-2014 - SSL VPN specification _(Chinese)_

**Additional context**

Standards for third-party collection: https://github.com/guanzhi/GM-Standards _(Chinese)_

OpenSSL branch with ShangMi Cipher Suites support: https://github.com/guanzhi/GmSSL _(Chinese)_

**Comment by ctz** [comment]
It's unlikely we'll accept support for nation-state cryptography into mainline rustls, especially when it has very little use outside its originating country. This isn't specific to China (SM), but also covers Russia (GOST), Germany (weird obsession with brainpool curves), South Korea (ARIA), etc. 

However, now 0.22 is released, I fully expect that you can implement all the desired SM functions in your own [`CryptoProvider`](https://docs.rs/rustls/latest/rustls/crypto/struct.CryptoProvider.html). Please file issues if you have trouble doing that, as this is one of the features we want to enable to happen (but not do ourselves).
