### ISSUE TITLE
Revisit benchmarks in the repository

### ISSUE THREAD

**Issue by aochagavia** [rustls/rustls#1685]
With the benchmarking push nearing its end, I've tried to make an inventory of the current usage of benchmarks:

- `ci-bench`: subcrate for CI benchmarks, measuring data transfer and handshake throughput. Uses CPU instruction counts and wall-clock time as units. We currently run them through GitHub Actions _and_ on a bare-metal server (through the code in [this repository](https://github.com/rustls/rustls-bench-app/)).
- `rustls/examples/internal/bench.rs`: binary for manually measuring throughput (MiB/s; handshakes/s) and memory usage (KiB/s), so we can compare against other TLS implementations. Used by @ctz in 2019 to benchmark against OpenSSL (see [results](https://jbp.io/2019/07/01/rustls-vs-openssl-performance.html)) and by myself this month (see [throughput results](https://github.com/rustls/rustls-bench-app/tree/757244898e89be8c10bd5abdcf5d03c4c0d62471) and [memory results](https://gist.github.com/aochagavia/e9d179735f311deb174c993ca2b9199a)).
- `#[bench]` benchmarks spread throughout the codebase. Based on [this comment](https://github.com/rustls/rustls/issues/1478#issuecomment-1765063117), they seem to require a nightly compiler. I'm not sure whether they are actively being used.

With that in mind, we should probably do the next three things:

1. Phase out the GitHub Actions runner for the icount benchmarks, once we have confidence that the bare-metal server is working properly (e.g. a few days from now). ~I'm planning to open a PR for this.~ __Status__: done in #1696.
2. Write some documentation in a top-level `BENCHMARKING.md` file on our approach to benchmarking, including some explanation about the split between `ci-bench` and `rustls/examples/internal/bench.rs`. Explain how to run the latter in a reliable way (e.g. building, using the makefile, recommended OS configuration, recommended amount of runs for low-noise results, link to the OpenSSL [counterpart](https://github.com/ctz/openssl-bench) for comparison, etc). I can also open a PR for this.
3. Remove `#[bench]` benchmarks, or otherwise clarify why we have them and include that in `BENCHMARKING.md`.

What do you think? Are there any additional benchmarks I'm missing?

**Comment by ctz** [comment]
I think we should keep the `#[bench]` benchmarks even if we don't do anything systematic with the results. I find them very useful for understanding the performance of smaller parts of code (one or two functions), which is difficult to see when the unit-of-benchmark is an entire handshake.

**Comment by aochagavia** [comment]
Closed after #1699 (somehow it wasn't automatically picked up)
