### ISSUE TITLE
Certificate without SNI

### ISSUE THREAD

**Issue by atik7** [rustls/rustls#1686]
Hi, 

is there any example how to connect a server that have certificate with no SNI.

Thanks

**Comment by atik7** [comment]
I used a certificate that doesn't have SNI,  and has CN = ABC

So how to use server name here?

let server_name = "www.rust-lang.org".try_into().unwrap();

**Comment by cpu** [comment]
> I used a certificate that doesn't have SNI, and has CN = ABC

server name indication (SNI) is a property of the TLS handshake and not the server certificate, so I think we can set that part of the question aside.

Can you share the server certificate PEM? It would be easier to answer your question that way.

In short, if the certificate doesn't have at least one subject alternate name (SAN) with a domain name value, you won't be able to connect to a server using that certificate with Rustls without disabling certificate validation (unsafe) or implementing a custom certificate validator.

**Comment by atik7** [comment]
Thanks, I will check same for custom validation,
