### ISSUE TITLE
Experimental support for X25519Kyber768Draft00

### ISSUE THREAD

**Issue by ctz** [rustls/rustls#1687]
We should -- experimentally and optionally -- support [X25519Kyber768Draft00](https://datatracker.ietf.org/doc/draft-tls-westerbaan-xyber768d00/) and track the drafts through standardisation.

We could perhaps do this in a separate crate which exports a `CryptoProvider` based on the default one, an additional `SupportedKxGroup`, or probably both.

requires #1512
ref #1294

**Comment by skmcgrail** [comment]
aws-lc-rs has an API that we are looking to get merged into our main branch relatively soon, which will provide the necessary functionality needed to use Kyber round-3 768. https://github.com/aws/aws-lc-rs/pull/260 I have time scheduled with our team to review if there are any remaining blockers preventing us from moving forward with the APIs.

Additionally, once NIST finalizes the specification for ML-KEM we will incorporate it as a separate algorithm that may be selected and used with the API.

**Comment by ctz** [comment]
> aws-lc-rs has an API that we are looking to get merged into our main branch relatively soon

Thanks! Using that I have some prototype-level code that successfully talks to `pq.cloudflareresearch.com`:

```shell
$ cargo run --example client
(...)
          <div id="connInfo"><p>You are using <em>X25519Kyber768Draft00</em> which
              is <strong class="ok">post-quantum secure</strong>.</p></div>
(...)
```
