### ISSUE TITLE
mtls doesn't prompt browser for certificate

### ISSUE THREAD

**Issue by RaniSharim** [rustls/rustls#1691]
**Checklist**
* [V] I've searched the issue tracker for similar bugs.

**Describe the bug**
Started the demo server `tlsserver-mio` with the `--auth` option, entered the url in edge. Was expecting a prompt to select a certificate, but got none. The page just displayed.

**To Reproduce**
Create a ca certificate using open ssl and add it to the windows certificate store.
Use it to sign a client certificate and add it to the windows certificate store.
Use `mkcert` to generate localhost server certificates.

Run
```
$ cargo run --bin tlsserver-mio -- --certs localhost.pem --key localhost-key.pem --auth ca.pem -p 8080 http
```
Browse to `https://localhost:8080` ---> Page displays without requesting certificate

Run
```
$ cargo run --bin tlsserver-mio -- --certs localhost.pem --key localhost-key.pem --auth ca.pem --require-auth -p 8080 http
```
Browse to `https://localhost:8080` ---> Page does not display with `ERR_BAD_SSL_CLIENT_AUTH_CERT` without letting me choose a certificate

**Applicable Version(s)**
`0.22.1` with `edge 120.0.2210.61` on windows 11.

**Expected behavior**
The browser should prompt me with a selection of client certificate from the store.

**Additional context**
Same certificate works with other server implementations (go-lang)

**Comment by ctz** [comment]
```
$ cargo run --bin tlsserver-mio -- --certs localhost.pem --key localhost-key.pem --auth ca.pem --require-auth -p 8080 http
```

Please clarify what `ca.pem` is in this case? Is it issuer of the client cert, or the server's issuer?

**Comment by RaniSharim** [comment]
`ca.pem` is the issuer of the client certificate.

**Comment by ctz** [comment]
I'm not in a position to test this on Edge/Windows, but with Firefox this works as I'd expect:

![image](https://github.com/rustls/rustls/assets/579363/4284419a-b401-4fa4-b10a-50966f3ab51d)

**Comment by cpu** [comment]
@RaniSharim Can you try your reproduction on Windows but using Firefox? It would be interesting to know whether it prompts for a client certificate.

**Comment by RaniSharim** [comment]
Well I tested chrome again and it's suddenly working. I can't really explain it, perhaps some caching issue.
Firefox doesn't, but it doesn't surprise me, it has more strict rules about the certificate it's willing to work with, always had issues with self signed ones.
I'm closing the issue, there doesn't seem to be an actual server side problem.

Thanks everyone.

**Comment by cpu** [comment]
Thanks for reporting back :-)

**Comment by ctz** [comment]
I have a feeling that -- on Windows -- the certificates available are tied to a login session. So it might need a log-out/log-in cycle to work (or a reboot).
