### ISSUE TITLE
PrivateKeyDer support for pkcs11 / ccid

### ISSUE THREAD

**Issue by Firstyear** [rustls/rustls#1703]
**Checklist**
* [ x ] I've searched the issue tracker for similar requests

**Is your feature request related to a problem? Please describe.**

With the ability to specify custom key providers ( https://docs.rs/rustls/latest/rustls/crypto/trait.KeyProvider.html ) people may wish to use PKCS11 HSMs on the server side, or PIV on the client side. To do this, both need different methods to provide their private keys to their backends. However the PrivateKeyDer api can't easily express this today ( https://docs.rs/rustls/latest/rustls/pki_types/enum.PrivateKeyDer.html ) 

**Describe the solution you'd like**
It would be good to have PKCS11 uri's from rfc7512 as a supported Private Key type. Most PIV cards can be used via the opensc pkcs11 interface to ccid. 

https://www.rfc-editor.org/rfc/rfc7512

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ctz** [comment]
`PrivateKeyDer` is intended for DER encodings of private keys loaded from a file. It isn't intended to refer to keys held in HSMs or physical tokens.

See https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#customising-private-key-usage for how this is intended to work. There's an example in https://github.com/rustls/rustls-cng/blob/dev/src/signer.rs#L51 of this being done for CNG, where keys are referred to by opaque handles.

**Comment by Firstyear** [comment]
Should you link to this part of the manual from the keyprovider api then?

**Comment by cpu** [comment]
> Should you link to this part of the manual from the keyprovider api then?

https://github.com/rustls/rustls/pull/1724

Pull requests for doc improvements are always welcome.
