### ISSUE TITLE
Client handshake succeeds in TLS 1.3 even though the server has rejected the certificate

### ISSUE THREAD

**Issue by jadamcrain** [rustls/rustls#1707]
Here's a reproducible test case:

https://github.com/jadamcrain/tokio-rustls-client-verifier

The output is: 

```
TLS 1.2 - Without client rejection
client: Ok(TlsStream { io: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:38473, peer: 127.0.0.1:38472, socket: 404 }) }, session: ClientConnection, state: Stream })
server: Ok(TlsStream { io: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:38472, peer: 127.0.0.1:38473, socket: 420 }) }, session: ServerConnection, state: Stream })
TLS 1.2 - With client rejection
client: Err(Custom { kind: InvalidData, error: AlertReceived(HandshakeFailure) })
server: Err(Custom { kind: InvalidData, error: General("Client rejected for custom reason") })
TLS 1.3 - Without client rejection
client: Ok(TlsStream { io: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:38477, peer: 127.0.0.1:38476, socket: 448 }) }, session: ClientConnection, state: Stream })
server: Ok(TlsStream { io: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:38476, peer: 127.0.0.1:38477, socket: 396 }) }, session: ServerConnection, state: Stream })
TLS 1.3 - With client rejection
client: Ok(TlsStream { io: PollEvented { io: Some(TcpStream { addr: 127.0.0.1:38479, peer: 127.0.0.1:38478, socket: 420 }) }, session: ClientConnection, state: Stream })
server: Err(Custom { kind: InvalidData, error: General("Client rejected for custom reason") })
```

^ The client thinks the handshake was a success, but the server sees failure.

@cpu did an analysis of the handshake using wireshark and had this to say on discord:

>At the protocol level, looking through Wireshark, the TLS 1.2 and TLS 1.3 rejection cases look almost identical. In both cases I see the  >server sends an alert: (Level: Fatal, Description: Handshake Failure).
>
>So I think the question is what happens in the client code that results in that alert not being surfaced as an error when you're using TLS >1.3.
>My suspicion is that it's something in tokio-rustls since it returns the Ok result with "state: Stream" after connect().await. If I modify your >example to take the Ok client result and then try to do a read on it, then I get the expected error: Custom { kind: InvalidData, error: >AlertReceived(HandshakeFailure) }
>
> I'm not very familiar with Tokio or the tokio-rustls adapter, so it's hard for me to guess why the error is surfaced by connect for TLS 1.2, but not until a first read with TLS 1.3. 

So, in any real system this doesn't really cause an issue, but it is a bit of an oddity. I ran into this because I was writing integration tests for some custom certificate verification we're doing w/ mTLS.

**Comment by cpu** [comment]
>  It seems that inconsistent behavior occurs in rustls, which ends the handshaking state before returning peer_has_closed

Thanks @quininer - I've moved this issue to the Rustls repo for further debugging :+1:

**Comment by ctz** [comment]
I think this is correct behaviour. To borrow and alter a diagram from RFC8446:

```
       Client                                           Server

Key  ^ ClientHello
Exch | + key_share*
     | + signature_algorithms*
     | + psk_key_exchange_modes*
     v + pre_shared_key*       -------->
                                                  ServerHello  ^ Key
                                                 + key_share*  | Exch
                                            + pre_shared_key*  v
                                        {EncryptedExtensions}  ^  Server
                                        {CertificateRequest*}  v  Params
                                               {Certificate*}  ^
                                         {CertificateVerify*}  | Auth
                                                   {Finished}  v
                               <--------  [Application Data*]
     ^ {Certificate*}
Auth | {CertificateVerify*}
     v {Finished} (1)          -------->
                               <--------  [Alert] (2)
```

At (1), the client has completed the handshake from its point of view, as reflected in `is_handshaking()`. At (2) the server has received the final flight of the client's handshake, and rejects it with an alert.

And, yes, the behaviour differs for TLS1.2 because the handshake is finished by the server explicitly confirming the client's final flight.

**Comment by cpu** [comment]
This makes sense to me, thanks for clarifying! I think it's reasonable to close this.
