### ISSUE TITLE
How can I explicitly disable TLS 1.3 in the config builder API and/or improve logging?

### ISSUE THREAD

**Issue by svanharmelen** [rustls/rustls#1734]
The docs for the `tls12` crate feature mentions:

```
tls12: enables support for TLS version 1.2. This feature is in the default set. Note that, due
to the additive nature of Cargo features and because it is enabled by default, other crates
in your dependency graph could re-enable it for your application. If you want to disable
TLS 1.2 for security reasons, consider explicitly enabling TLS 1.3 only in the config builder API.
```

Yet I would like (for mTLS debugging purposes) to force the server to use TLS 1.2 only. But I cannot see how I can do that. Trying to use a specific protocol or cypher suite seems to give errors in the builder (I tried a few combinations but all result in similar errors):

<img width="701" alt="image" src="https://github.com/rustls/rustls/assets/4171547/3b90b97f-1e01-4427-aed5-803a936f4da3">

Additionally, is there an option to let de server log more details? As currently it doesn't mention what the actual error is and just drops the connection which makes debugging a challenge (note that the logs are ordered descending):

<img width="1592" alt="image" src="https://github.com/rustls/rustls/assets/4171547/e4dd1940-fa6a-43a8-8e61-4480065a19cf">

In success cases I see a message `client CertificateVerify OK`  after the message `Dropping CCS`, but in error cases it doesn't show anything after `Dropping CCS`, instead the client just retries to establish the connection resulting in the same set of logs over and over...

Thanks!

**Comment by ctz** [comment]
(Assuming this is for an old version? Please clarify.)

> Trying to use a specific protocol or cypher suite seems to give errors in the builder (I tried a few combinations but all result in similar errors):

The first step would be replacing the `.with_safe_defaults()` line with it's equivalent:

```
    .with_safe_default_cipher_suites()
    .with_safe_default_kx_groups()
    .with_safe_default_protocol_versions()
    .unwrap()
```
([source](https://docs.rs/rustls/0.21.10/rustls/struct.ConfigBuilder.html)]

From there, you can replace `.with_safe_default_protocol_versions()` with `.with_protocol_versions(&[rustls::version::TLS12])`.

> but in error cases it doesn't show anything after

Generally we don't log errors that are also returned as a [`rustls::Error`](https://docs.rs/rustls/0.21.10/rustls/enum.Error.html), on the assumption that the next layer up will log that with the additional context only it knows.

**Comment by svanharmelen** [comment]
Yes, I'm indeed still on `0.21.10`, but your suggestions worked perfectly for restricting the config. Thanks!

So for the error, I guess I swallow the error myself then somewhere. That is unexpected and not intended, so I will dive into that one.

Thanks a lot for your quick response again!
