### ISSUE TITLE
TLS1.3 performance problem

### ISSUE THREAD

**Issue by zh-jq-b** [rustls/rustls#1751]
See https://bytedance.larkoffice.com/docx/NEqXdDyq8op8mwx0XTWcwgionnf.

The tls1.3 performance isn't as good as OpenSSL 1.1.x when testing at high concurrency.

**Comment by djc** [comment]
Why are you not testing aws-lc-rs support? Are your results in line with https://github.com/aochagavia/rustls-bench-results?

**Comment by zh-jq-b** [comment]
I also add tls1.2 test result here https://bytedance.larkoffice.com/docx/NEqXdDyq8op8mwx0XTWcwgionnf.
The rustls 1.2 performance is better than tls1.3 & openssl (which is expected).
There are no much RPS difference between rustls 0.21 & rustls 0.22 ring & rustls 0.22 aws-lc in our test.

**Comment by djc** [comment]
There have been some recent changes on the main branch. Would it be hard to try this with current rustls main?

**Comment by zh-jq-b** [comment]
> There have been some recent changes on the main branch. Would it be hard to try this with current rustls main?

The max RPS (ring) is still around 54000.

I just bump the version here https://github.com/bytedance/g3/commit/0c2feafecb28e7d7c7c9b4186f52752dbb9c787c without any API changes.

**Comment by cpu** [comment]
Are you building with gcc or clang?

**Comment by zh-jq-b** [comment]
> Are you building with gcc or clang?

I didn't set a custom CC, so it should be gcc.

**Comment by briansmith** [comment]
> I didn't set a custom CC, so it should be gcc.

recent clang should be faster.

**Comment by zh-jq** [comment]
The boringssl performance is much better so I don't think it's the problem I reported here.
I will have an updated test with clang next week.

**Comment by zh-jq-b** [comment]
Hi, I do a test with CC set to clang-18 today, the problem is still the same:
![image](https://github.com/rustls/rustls/assets/127708320/bc692e17-f84d-45c7-81e8-1bdf05877513)

**Comment by zh-jq-b** [comment]
I have done a full test yesterday with an updated OS/clang, with the result updated in https://bytedance.larkoffice.com/docx/NEqXdDyq8op8mwx0XTWcwgionnf.
The TLS 1.2 performance of rustls is awesome, while the TLS 1.3 performance is still fall behind.

**Comment by ctz** [comment]
Thanks for keeping this updated with the latest measurements. Do you have an idea of whether these results would be reproducible by me? I guess it would, and doesn't really require 96 cores, and the graph will just be a compressed along the x axis?

**Comment by zh-jq-b** [comment]
> Do you have an idea of whether these results would be reproducible by me? I guess it would, and doesn't really require 96 cores, and the graph will just be a compressed along the x axis?

It's reproducible by limiting worker thread number to 32 in g3tiles main.yaml, so I guess you can try a 32 core machine. The rustls performance is slightly better than when running with 96 cores.

I also tried 16 cores and the performance is near, which is surely unreproducible.

**Comment by ctz** [comment]
Couple of notes:

- It may be worth experimenting with a similar change to https://github.com/rustls/rustls/pull/2167 (this is something your code needs to do when building a `ServerConfig`)
- https://github.com/rustls/rustls/pull/2168 is a minor improvement in this area (included in 0.23.16)

We now have a 80 core ARM benchmarking machine which should result in some improvements to how rustls scales in multithreaded uses.

**Comment by zh-jq-b** [comment]
Yes it's the fastest now after change the ticket number to 2. I have updated the doc. Close this issue now.
