### ISSUE TITLE
Request for Information on Dedicated discussion Channel for Rustls like Element.io or Discord Alternatives?

### ISSUE THREAD

**Issue by sarath3192** [rustls/rustls#1752]
I am searching for a communication channel similar to Element.io or Discord specifically for discussions related to Rustls. If such a platform exists, could someone please provide me with the relevant links or information?

**Comment by cpu** [comment]
Hi @sarath3192 

There is a Discord server you can join here: https://discord.gg/shBXZ8NP4c

Rustls related activity happens in the #rustls channel of that Discord.

Does that meet your needs?

**Comment by sarath3192** [comment]
Thank you.
