### ISSUE TITLE
Randomly getting `InappropriateHandshakeMessage`

### ISSUE THREAD

**Issue by elichai** [rustls/rustls#1776]
**Describe the bug**
I have a test where I launch a `warp` server with websockets, and connect dozens of connections to it with `reqwest` and `tokio-tungstenite`, and I keep getting the following error, each time from a different test/location:

```rust
Error(Io(Custom { kind: InvalidData, error: InappropriateHandshakeMessage { expect_types: [ServerHello, HelloRetryRequest], got_type: ClientHello } }))
```
Which seems to be originating from `rustls` as I see the following:
```
 WARN rustls::check: Received a ClientHello handshake message while expecting [ServerHello, HelloRetryRequest]
 ```
**To Reproduce**
Still working on an MRE

**Comment by ctz** [comment]
This would happen if you attempt to get two TLS clients to talk to each other; including if you point a TLS client at a TCP echo server.
