### ISSUE TITLE
0.23 release preparation

### ISSUE THREAD

**Issue by cpu** [rustls/rustls#1777]
Let's collect up a burndown list of tasks to be completed for a 0.23 release that includes FIPS support and the new choice for default crypto provider.

* [x] https://github.com/rustls/rustls/pull/1798
* [x] https://github.com/rustls/rustls/pull/1811
* [x] https://github.com/rustls/rustls/pull/1502 (maybe)
* [x] https://github.com/rustls/rustls/pull/1774
* [x] https://github.com/rustls/rustls/pull/1640
* [x] https://github.com/rustls/rustls/pull/1784
* [x] https://github.com/rustls/rustls/pull/1789
* [x] https://github.com/rustls/rustls/pull/1780

**Comment by cpu** [comment]
I've proposed a handful of items to consider blocking on.

I think #1640 is very close and probably uncontroversial. I'm not sure if we want to roll #1774 in as well.

It feels important to tie a bow on the outstanding changes Quinn needs in #1741. 

I think we're missing an issue to link for switching the default provider.

**Comment by djc** [comment]
This list looks good to me!

**Comment by cpu** [comment]
Added https://github.com/rustls/rustls/pull/1784 to the list.

**Comment by ctz** [comment]
Yes, unfortunately I think any change to the default feature list is a breaking change :(

**Comment by cpu** [comment]
Thanks for confirming. I put it in the list as a nice-to-have. Looking forward I think pt2 _could_ be landed without breaking changes so it would be ideal if we could fit pt1 into this release, but if it doesn't happen it would be OK knowing there's further work to be done in either case.

**Comment by djc** [comment]
Would be nice to get #1811 in.

**Comment by cpu** [comment]
> Would be nice to get https://github.com/rustls/rustls/pull/1811 in.

Added to the list. It's in the merge queue now.

**Comment by cpu** [comment]
[v0.23.0](https://github.com/rustls/rustls/releases/tag/v%2F0.23.0) was published this morning :rocket:
