### ISSUE TITLE
Support for some clipersuite to connect Microsoft-IIS 8.5 server

### ISSUE THREAD

**Issue by anatawa12** [rustls/rustls#1779]
**Checklist**
* [x] I've searched the issue tracker for similar requests

**Is your feature request related to a problem? Please describe.**

an user of my tool says unable to https://server.macchiato.kr/vpm/vpm.json. I found the server is Microsoft-IIS 8.5 and all clipersuite the server returns is not supported by rustls.

**Describe the solution you'd like**

I want some clipersuite for Microsoft-IIS 8.5.

**Describe alternatives you've considered**

**Additional context**

Downstream issue: anatawa12/vrc-get#318

**Comment by djc** [comment]
Unfortunately rustls doesn't support weak cipher suites out of the box.

<img width="960" alt="Screenshot 2024-02-09 at 10 42 58" src="https://github.com/rustls/rustls/assets/158471/c37d465f-147c-4304-b348-b6cd8afb46a4">

(As I understand it, IIS 8.5 is EOL.)

**Comment by anatawa12** [comment]
Is there documentation to know if the cliper suite is weak or not?

**Comment by djc** [comment]
I think this is the closest we have: https://docs.rs/rustls/latest/rustls/#non-features.

**Comment by anatawa12** [comment]
Thank you

**Comment by ctz** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=server.macchiato.kr is a good resource too for evaluating server quality.

**Comment by djc** [comment]
(@ctz already linked above. :))
