### ISSUE TITLE
Current main fails to compile aws-lc-sys

### ISSUE THREAD

**Issue by mouse07410** [rustls/rustls#1788]
**Checklist**
* [X] I've searched the issue tracker for similar bugs.

**Describe the bug**
```text
Unable to generate bindings.: ClangDiagnostic("/Users/ur20980/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.13.0/aws-lc/include/openssl/err.h:112:10: fatal error: 'stdio.h' file not found\n")
```

**To Reproduce**
1. Clone this repo `git clone --recurse-submodules https://github.com/rustls/rustls.git`
2. `cd rustls`
3. Do `cargo test --release`
4. Observe the error:

```text
$ git clone --recurse-submodules https://github.com/rustls/rustls.git
Cloning into 'rustls'...
remote: Enumerating objects: 26917, done.
remote: Counting objects: 100% (4049/4049), done.
remote: Compressing objects: 100% (1112/1112), done.
remote: Total 26917 (delta 3270), reused 3122 (delta 2912), pack-reused 22868
Receiving objects: 100% (26917/26917), 10.23 MiB | 2.53 MiB/s, done.
Resolving deltas: 100% (18838/18838), done.
$ cd rustls
$ cargo test --release; date                                         
   Compiling libc v0.2.153
   Compiling proc-macro2 v1.0.78
   Compiling unicode-ident v1.0.12
   Compiling glob v0.3.1
   Compiling rustix v0.38.31
   Compiling prettyplease v0.2.16
   Compiling memchr v2.7.1
   Compiling regex-syntax v0.8.2
   Compiling minimal-lexical v0.2.1
   Compiling either v1.10.0
   Compiling cfg-if v1.0.0
   Compiling bitflags v2.4.2
   Compiling libloading v0.8.1
   Compiling bindgen v0.69.4
   Compiling home v0.5.9
   Compiling itertools v0.12.1
   Compiling lazy_static v1.4.0
   Compiling rustc-hash v1.1.0
   Compiling nom v7.1.3
   Compiling clang-sys v1.7.0
   Compiling lazycell v1.3.0
   Compiling shlex v1.3.0
   Compiling log v0.4.20
   Compiling dunce v1.0.4
   Compiling fs_extra v1.3.0
   Compiling paste v1.0.14
   Compiling aho-corasick v1.1.2
   Compiling regex-automata v0.4.5
   Compiling aws-lc-rs v1.6.1
   Compiling untrusted v0.9.0
   Compiling cexpr v0.6.0
   Compiling rustls-pki-types v1.2.0
   Compiling mirai-annotations v1.12.0
   Compiling zeroize v1.7.0
   Compiling base64 v0.21.7
   Compiling rustls v0.23.0-alpha.0 (/Users/ur20980/src/rustls/rustls)
   Compiling once_cell v1.19.0
   Compiling regex v1.10.3
   Compiling is-terminal v0.4.12
   Compiling subtle v2.5.0
   Compiling termcolor v1.4.1
   Compiling humantime v2.1.0
   Compiling quote v1.0.35
   Compiling syn v2.0.48
   Compiling rustls-pemfile v2.0.0
   Compiling webpki-roots v0.26.1
   Compiling autocfg v1.1.0
   Compiling powerfmt v0.2.0
   Compiling bencher v0.1.5
   Compiling deranged v0.3.11
   Compiling num-traits v0.2.18
   Compiling num-bigint v0.4.4
   Compiling time-core v0.1.2
   Compiling cc v1.0.83
   Compiling errno v0.3.8
   Compiling num-conv v0.1.0
   Compiling serde v1.0.196
   Compiling cmake v0.1.50
   Compiling time v0.3.34
   Compiling which v4.4.2
   Compiling getrandom v0.2.12
   Compiling ring v0.17.7
   Compiling spin v0.9.8
   Compiling yasna v0.5.2
   Compiling pem v3.0.3
   Compiling socket2 v0.5.5
   Compiling env_logger v0.10.2
   Compiling num-integer v0.1.46
   Compiling mio v0.8.10
   Compiling pin-project-lite v0.2.13
   Compiling strsim v0.10.0
   Compiling bytes v1.5.0
   Compiling serde_derive v1.0.196
   Compiling tokio-macros v2.2.0
   Compiling tokio v1.36.0
   Compiling aws-lc-sys v0.13.0
   Compiling rcgen v0.12.1
error: failed to run custom build command for `aws-lc-sys v0.13.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/ur20980/src/rustls/target/release/build/aws-lc-sys-de27243413207beb/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=use_bindgen_generated

  --- stderr
  /Users/ur20980/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.13.0/aws-lc/include/openssl/err.h:112:10: fatal error: 'stdio.h' file not found
  thread 'main' panicked at /Users/ur20980/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.13.0/builder/bindgen.rs:151:10:
  Unable to generate bindings.: ClangDiagnostic("/Users/ur20980/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.13.0/aws-lc/include/openssl/err.h:112:10: fatal error: 'stdio.h' file not found\n")
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
     1: core::panicking::panic_fmt
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
     2: core::result::unwrap_failed
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
     3: core::result::Result<T,E>::expect
     4: build_script_main::bindgen::generate_bindings
     5: build_script_main::generate_bindings
     6: build_script_main::main
     7: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
Tue Feb 13 16:35:59 EST 2024
$
```

**Applicable Version(s)**
Current main. A few days ago it compiled OK and passed the tests.

**Expected behavior**
Successful compilation, and passing of all the tests.

**Additional context**

- Apple Silicon M2, MacOS Sonoma 14.3.1.
- Xcode-15.2.
- Cargo 1.76.0, Rust-1.76.0.
- `bindgen` 0.69.4.

### Update
1. Works correctly on Intel-based Mac (same versions of everything).
2. https://github.com/aws/aws-lc.git installs OK and passes all the tests on Apple Silicon - so the problem seems to be with `aws-lc-rs` and/or `aws-lc-sys` crates:
```text
$ build/crypto/crypto_test
.  .  .
[----------] Global test environment tear-down
[==========] 1780 tests from 111 test suites ran. (20971 ms total)
[  PASSED  ] 1780 tests.

  YOU HAVE 3 DISABLED TESTS
```

**Comment by djc** [comment]
> Current main. A few days ago it compiled OK and passed the tests.

The rustls default was switched from *ring* to aws-lc-rs recently (in #1780) which might be why you're seeing this now? The *ring* crypto provider is still provided so it should be easy to switch back using Cargo features.

On my M1 Max, I can build 3179b925c2becc8d19eb83078590e412dff4ed28 with `cargo build --release` in the `rustls` directory of the repo, with the same compiler toolchain.

**Comment by ctz** [comment]
I think it might be more fruitful to report this at https://github.com/aws/aws-lc-rs 

There is also similar reports in the bindgen repo https://github.com/rust-lang/rust-bindgen/discussions/2401

**Comment by mouse07410** [comment]
> I think it might be more fruitful to report this at https://github.com/aws/aws-lc-rs

Reported - but it looks like some parameters for the `aws-lc-rs` as a dependency build would need to go into this project's `Cargo.toml`.

**Comment by cpu** [comment]
>  it looks like some parameters for the aws-lc-rs as a dependency build would need to go into this project's Cargo.toml.

I believe the suggestion in [the aws-lc-rs thread](https://github.com/aws/aws-lc-rs/issues/342) was for you to take a direct dependency on `aws-lc-rs` and add the required feature flag. This will activate it for Rustls' copy of the dependency as well.

Have you tried that approach?

**Comment by justsmth** [comment]
It looks like [mouse07410](https://github.com/mouse07410) found a way to reproduce the problem directly using bindgen: https://github.com/rust-lang/rust-bindgen/discussions/2401#discussioncomment-8473708

**Comment by mouse07410** [comment]
> > it looks like some parameters for the aws-lc-rs as a dependency build would need to go into this project's Cargo.toml.
> 
> I believe the suggestion in [the aws-lc-rs thread](https://github.com/aws/aws-lc-rs/issues/342) was for you to take a direct dependency on `aws-lc-rs` and add the required feature flag. This will activate it for Rustls' copy of the dependency as well.
> 
> Have you tried that approach?

I don't understand how to do that, given that I don't build `aws-lc-rs` separately, and that's it's a library that I cannot actually install.

**Comment by cpu** [comment]
> I don't understand how to do that, given that I don't build aws-lc-rs separately, and that's it's a library that I cannot actually install.

Ah I see, you're building Rustls but not actually consuming it as a dependency in a Rust project of your own? Is that an accurate summary?

**Comment by mouse07410** [comment]
> Ah I see, you're building Rustls but not actually consuming it as a dependency in a Rust project of your own? Is that an accurate summary?

For now - yes it is.

**Comment by djc** [comment]
@mouse07410 what are you actually building? Is it a Rust project that somehow includes rustls (and thus aws-lc-rs) in its transitive dependency graph? If so, you can add a direct dependency on aws-lc-rs with the `bindgen` feature and that should make it work. If not, what is it that you're trying to do?

**Comment by mouse07410** [comment]
> what is it that you're trying to do?

First, right now I'm preparing for getting `rustls` into a project. There are several moving parts, including PQ crypto, so it takes time. Yes, in its more mature stage it will include rustls in its dependency graph.

Second, it would be great if somebody (you?) actually **showed** what the direct dependency on aws-lc-rs should look like, even though it must be obvious for many readers. _I'd also like to hear why you think that specifying some feature for aws-lc-rs would help, given that independent bindgen failure was demonstrated._

**Comment by djc** [comment]
Well, I was going off of this comment from the aws-lc-rs thread:

> One possible work-around is to take a direct dependency on `aws-lc-rs` and enable the "bindgen" feature. This may also require the installation of libclang/llvm. Our [User Guide](https://aws.github.io/aws-lc-rs/requirements/macos.html) provides basic instructions for this.

But, I think the more interesting question is why neither @justsmth nor I can reproduce this, in similar Apple Silicon environments?

**Comment by mouse07410** [comment]
> I was going off of this comment from the aws-lc-rs thread

And the User Guide they referred to indeed showed how to install libclang/llvm using HomeBrew. In other words, not very helpful, especially given that they were already installed.

Doesn't give a simple unambiguous help like
```text
[dependencies]
.  .  .
"aws-lc-rs = [ version = "1.2.3", features = "broken, bindgen, whatever" ] 
.  .  .
```

> the more interesting question is why neither @justsmth nor I can reproduce this, in similar Apple Silicon environments?

My suspicion is - presence or absence on the system of other Clang versions (see my comments in the bindgen issue). But I can't be sure. If we all had "pristine" machines with only MacOS, Xcode, Rust-1.76.0, and rustls clone - it would've been nice and simple...

**Comment by djc** [comment]
> My suspicion is - presence or absence on the system of other Clang versions (see my comments in the bindgen issue). But I can't be sure. If we all had "pristine" machines with only MacOS, Xcode, Rust-1.76.0, and rustls clone - it would've been nice and simple...

`which -a clang` reports only `/usr/bin/clang` for me, installed on Feb 2 (same as all the other `c*` binaries in `/usr/bin`).

**Comment by mouse07410** [comment]
Well, you have only one Clang, presumably from Xcode (or it's CommandLineTools). In my case
```sh
$ which -a clang
/opt/local/bin/clang
/usr/bin/clang
$ port installed | grep clang
  clang-17 @17.0.6_0+analyzer (active)
  clang_select @2.2_1 (active)
  gcc12-libcxx @12.3.0_4+clang17 (active)
  gcc13-libcxx @13.2.0_4+clang17 (active)
  py311-clang @10_0+clang17 (active)
$ 
```
and that's _after_ I pruned (removed) other unnecessary versions of Clang that I suspected could interfere with `bindgen`.

**Comment by skmcgrail** [comment]
@mouse07410 

I believe your finding is correct that this is a MacPorts llvm-16 issue. I also use MacPorts but did not have llvm-16 version installed. I uninstalled all my clang and llvm installations from MacPorts, and then only installed clang/llvm 16. If I then force binding generation of x86-64 architecture I get the following error as well:

```
error: failed to run custom build command for `aws-lc-sys v0.13.2 (/workspace/aws-lc-rs/aws-lc-sys)`

Caused by:
  process didn't exit successfully: `/workspace/aws-lc-rs/target/debug/build/aws-lc-sys-e03fe402074ee5a3/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=macos_x86_64

  --- stderr
  /workspace/aws-lc-rs/aws-lc-sys/aws-lc/include/openssl/err.h:112:10: fatal error: 'stdio.h' file not found
  thread 'main' panicked at aws-lc-sys/builder/bindgen.rs:151:10:
  Unable to generate bindings.: ClangDiagnostic("/workspace/aws-lc-rs/aws-lc-sys/aws-lc/include/openssl/err.h:112:10: fatal error: 'stdio.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So I don't think this is a specific issue to Apple M2, but more an issue with llvm-16 on MacPorts if bindgen attempts to use it.

**Comment by djc** [comment]
Which is a little strange, since I think 1.76 is supposed to be compatible with LLVM 16?

https://github.com/rust-lang/rust/pull/117947/

**Comment by cpu** [comment]
Is there any action to take in the Rustls repo for this situation? It seems like there's consensus the problem is with tooling unrelated to Rustls itself.

**Comment by mouse07410** [comment]
> Is there any action to take in the Rustls repo for this situation? 

I don't think so. Except, perhaps, mention in the README or such that LLVM-16 with Clang-16 are problematic.

> It seems like there's consensus the problem is with tooling unrelated to Rustls itself.

I concur.

**Comment by tn233** [comment]
@mouse07410 
thanks, I ran into a similar problem while cross-compiling my project from macOS to Windows ('stdlib.h' file not found) but compiling to Linux and Android works. I tried to find the solution but failed, I'll give up cross-compile and prepare to compile it on a Windows machine if the problem is due to the tool unrelated to rustls. (or switch the feature back to ring)
