### ISSUE TITLE
When accepting new TLS connection with Accepted::into_connection(config) no TLS alert is sent

### ISSUE THREAD

**Issue by vartiait2** [rustls/rustls#1792]
**Checklist**
* [X] I've searched the issue tracker for similar bugs.

**Describe the bug**
When using `Accepted::into_connection(config)`, no TLS alert is sent when an error occurs during the handshake.
E.g. TLS protocol version mismatch, a server is configured to support only TLS 1.3 and a client supports only TLS 1.2.
```rust
let mut acceptor = Acceptor::default();
let accepted = loop {
    acceptor.read_tls(stream)?;
    if let Some(accepted) = acceptor.accept()? {
        break accepted;
    }
};
// Use a fixed config
let mut conn = accepted.into_connection(config)?;
let (_bytes_read, _bytes_written) = conn.complete_io(&mut stream)?;
```

When using `ServerConnection::new(config)`, TLS alert is sent.
```rust
// Use a fixed config
let mut conn = ServerConnection::new(config)?;
let (_bytes_read, _bytes_written) = conn.complete_io(&mut stream)?;
```

**To Reproduce**
1. Accept new TLS connections with `Accepted::into_connection(config)` (e.g. with a config supporting only TLS 1.3)
2. Try to do a handshake supporting only TLS 1.2
`openssl s_client -connect 127.0.0.1:8443 -tls1_2`
3. No TLS alert is received
`CONNECTED(00000003)
C0C71E44F87F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:304:`

When accepting connections with `ServerConnection::new(config)`, TLS alert is sent
`CONNECTED(00000003)
C0C71E44F87F0000:error:0A00042E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:ssl/record/rec_layer_s3.c:1586:SSL alert number 70`

**Applicable Version(s)**
0.22.2

**Expected behavior**
TLS alert is sent to a client.

**Comment by djc** [comment]
I spent some time looking at this on Saturday. It's not obvious to me why this happens from looking at the `Acceptor`/`Accepted`/server handshake code, but maybe it's an interaction with how `complete_io()` calls things?

**Comment by vartiait2** [comment]
Is it because `Accepted::into_connection(config)` returns with an error result after calling `ExpectClientHello::with_certified_key(self, ...)` at [src/server/server_conn.rs#L796](https://github.com/rustls/rustls/blob/f6cd567fc2798c88f9eefc7b8747a89f4f621a27/rustls/src/server/server_conn.rs#L796)?
The error itself is propagated from [src/server/hs.rs#L278](https://github.com/rustls/rustls/blob/main/rustls/src/server/hs.rs#L278)

**Comment by djc** [comment]
Hmm, yes. So if an error occurs in `process_new_packets()`, `complete_io()` will still call `write_tls()` (exactly for the purpose of getting out the alert). However, in your acceptor-based code, you'd get an error value from `Accepted::into_connection()`, and you'd likely not call `complete_io()` after that.

**Comment by ctz** [comment]
If an alert is queued for sending during `Accepted::into_connection` I think there is no way for a caller to get it? They don't have the original `Accepted`, and don't get a `ServerConnection` because they get an error instead. Maybe the `Err` return type of that should be `struct ErrorAndAlert(Error, Vec<u8>)` or something.

**Comment by djc** [comment]
I suppose the `Err` type could be a wrapper around the `ConnectionCommon<ServerData>` exposes a `write_alert()` method in addition to the actual `Error`?

**Comment by djc** [comment]
Sketched out a fix in #1811.

**Comment by vartiait2** [comment]
@djc Thanks a lot!

Isn't returning `AcceptedAlert` along an error from `Acceptor::accept()` a bit too soon as `Acceptor` does not 
have `ServerConfig`?

In an example code snippet below, TLS alert should be send because local `ServerConfig` is configured _not_ to support TLS 1.2 (which the client is trying to use).

```rust
let mut acceptor = Acceptor::default();
let accepted = loop {
    acceptor.read_tls(stream)?;
    if let Some(accepted) = acceptor.accept()? {
        break accepted;
    }
};
// Use a fixed config
let mut conn = accepted.into_connection(config)?;
let (_bytes_read, _bytes_written) = conn.complete_io(&mut stream)?;
```

**Comment by djc** [comment]
That's fair -- I revised the PR to also change the error type for `Accepted::into_connection()`.

**Comment by cpu** [comment]
@vartiait2 Thanks for the detailed bug report. This should be fixed with #1811.

**Comment by vartiait2** [comment]
@cpu @djc Thank You very much for fixing this! 👍🏻  I'm actually using `tokio_rustls::LazyConfigAcceptor` and `tokio_rustls::StartHandshake` so have to wait until the updated function signatures are used there.

**Comment by vartiait2** [comment]
Sure 👍🏻

**Comment by ctz** [comment]
Oops! Sorry about that.

**Comment by vartiait2** [comment]
No problem! 😄 Thanks a lot @ctz for a quick integration update! 👍🏻
