### ISSUE TITLE
Is there any benchmark comparison of existing TLS libraries in other languages like java, C++ and python etc. with Rustls ?

### ISSUE THREAD

**Issue by sarath3192** [rustls/rustls#1796]
If there is one, can one please share the link.

Thank you in advance.

**Comment by ctz** [comment]
I'm not aware of a general one. Though most other libraries do their own benchmarking, they tend to measure different things so aren't comparable.

https://github.com/ctz/openssl-bench is one that is intended to be comparable with the rustls benchmarking program.

**Comment by djc** [comment]
Since you asked a pretty general question, to avoid [XY problem](https://en.wikipedia.org/wiki/XY_problem) -- what information are you actually looking for?

**Comment by sarath3192** [comment]
> I'm not aware of a general one. Though most other libraries do their own benchmarking, they tend to measure different things so aren't comparable.
> 
> https://github.com/ctz/openssl-bench is one that is intended to be comparable with the rustls benchmarking program.

Thank this is helpful

**Comment by sarath3192** [comment]
> Since you asked a pretty general question, to avoid [XY problem](https://en.wikipedia.org/wiki/XY_problem) -- what are you actually trying to achieve?
 
Thank you for your response, I am looking into comparision of security vulnerabilities.

**Comment by cpu** [comment]
I think the openssl-bench repo linked above is the best reply we have to offer here. I'm going to close this issue for now. Thanks,
