### ISSUE TITLE
Random with 0 system entropy - workarounds?

### ISSUE THREAD

**Issue by Ragnt** [rustls/rustls#1803]
Hey!

I have an embedded system that goes into a never-ending block whenever a random source is requested. The Kernel is 3.17 (no getrandom()) and the Arch is MIPS, the 74Kc variant. The system sits at 0 entropy, forever. This results in a block while trying to get some bytes from /dev/random. I can't change the target system at all, so I'm stuck trying to work around this.

My requirement doesn't need to be super-secure. It is used in a closed environment, but it does need to still be TLS for simulated purposes. Because of this, I've opted to try and implement a Custom Provider with my own source:

```
fn custom_provider() -> rustls::crypto::CryptoProvider {
    rustls::crypto::CryptoProvider {
        secure_random: &CustomRandom,
        ..ring::default_provider()
    }
}

#[derive(Debug)]
struct CustomRandom;

impl SecureRandom for CustomRandom {
    fn fill(&self, buf: &mut [u8]) -> Result<(), GetRandomFailed> {
        let mut file = File::open("/dev/urandom").map_err(|_| GetRandomFailed)?;
        file.read_exact(buf).map_err(|_| GetRandomFailed)?;

        let epoch_time = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("Time went backwards")
            .as_micros();

        for byte in buf.iter_mut() {
            *byte ^= epoch_time as u8;
        }

        Ok(())
    }
}
```

Unfortunately I am still hitting a block, where I assume ring is still trying to generate a random somewhere (probably also using getrandom).

I'm wondering If I am missing something here that will save me a lot of time in trying to work around this, so I figured I would post here to make sure I'm not overlooking anything.

Thanks!

**Comment by ctz** [comment]
Have you considered adding entropy, by writing to `/dev/random` and then calling the entropy update ioctl?

**Comment by Ragnt** [comment]
I haven't! I didn't know that was an option. Could I just (in theory) pipe /dev/urandom into /dev/random to add entropy?
