### ISSUE TITLE
Be able to get the not_before and not_after through some API in CertifiedKey or CertificateDer<'_>.

### ISSUE THREAD

**Issue by milen-denev** [rustls/rustls#1804]
Be able to get the not_before and not_after through some API in CertifiedKey or CertificateDer<'_>.

**Comment by ctz** [comment]
What is your end goal?

**Comment by milen-denev** [comment]
> What is your end goal?

To be able to check if the Certificate (from Let's Encrypt) is close to expiration so I can renew it. I wasn't able to find an API withing the rustls ecosystem that allows that.

**Comment by ctz** [comment]
Fair enough. It looks like rustls-acme uses the https://docs.rs/x509-parser/latest/x509_parser/ crate for this, but also that there's a new ACME API being standardised so renewals can be controlled more by issuers (for load and revocation reasons): https://datatracker.ietf.org/doc/draft-ietf-acme-ari/

**Comment by milen-denev** [comment]
Ok thank you, I have found out how to do it. For anyone or anything interested in the code:

```rust
use x509_parser::nom::AsBytes;
use x509_parser::pem::parse_x509_pem;
use x509_parser::parse_x509_certificate;
use std::time::SystemTime;
use std::time::UNIX_EPOCH;
use tokio::fs::File;
use tokio::io::{AsyncReadExt, AsyncWriteExt, BufReader, BufWriter};

use crate::helpers;

pub async fn cert_is_valid(cert_file: &str) -> bool {
    let file_bytes =  helpers::read_file_full(cert_file).await.unwrap();
    let bytes_pem: &[u8] = file_bytes.as_bytes();
    let res = parse_x509_pem(bytes_pem);

    match res {
        Ok((_, pem)) => {
            let (_, cert) = parse_x509_certificate(&pem.contents).unwrap();
            let not_after = cert.validity().not_after;
            let timespamp = not_after.timestamp();
            let difference = timespamp - helpers::get_time_in_seconds() as i64;
            if difference <= 86400 {
                return false;
            } else {
                return true;
            }
        },
        _ => panic!("PEM parsing failed: {:?}", res),
    }
}
//helpers.rs
pub fn get_time_in_seconds() -> u64 { 
    let start = SystemTime::now();
    let since_the_epoch = start
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_secs();

    return since_the_epoch;
}

pub async fn read_file_full(file_path: &str) -> Option<Vec<u8>> {
    let std_path = path::Path::new(&file_path);

    if path::Path::exists(std_path) {     
        let mut buffer = Vec::new();
        let file = File::open(file_path).await.unwrap();
        let mut file_reader = BufReader::new(file);
        _ = file_reader.read_to_end(&mut buffer).await;
        return Some(buffer);
    }
    else {
        None
    }
}
```

**Comment by Vagelis-Prokopiou** [comment]
@milen-denev for your `cert_is_valid` function, the [`is_valid_at`](https://docs.rs/x509-parser/latest/x509_parser/certificate/struct.Validity.html#method.is_valid_at) API seems simpler. Something like:
```
cert.validity().is_valid_at(ASN1Time::from_timestamp().unwrap() + 86400)
```

**Comment by milen-denev** [comment]
> @milen-denev for your `cert_is_valid` function, the [`is_valid_at`](https://docs.rs/x509-parser/latest/x509_parser/certificate/struct.Validity.html#method.is_valid_at) API seems simpler. Something like:
> 
> ```
> cert.validity().is_valid_at(ASN1Time::from_timestamp(timestamp + 86400).unwrap())
> ```

Oh ok ευχαριστώ, έπρεπε να τσεκάρω καλύτερα τα APIs.
