### ISSUE TITLE
ServerConnection data lost

### ISSUE THREAD

**Issue by lestofante** [rustls/rustls#1805]
I have a ServerConnection that accept a client and expect a single message to be received. 
The client will connect, send a byte representing the messate type, the message, and disconnect right away (making sure to flush and close the socket properly).
The server does receive the first byte, next loop it will see the client disconnect, but NO DATA.

**To Reproduce**

Create a simple ServerConnection, that accept a connection, and poll data at 100hz
```
let mut buf = [0; 1024*8]; // should more than enough to contain any message
let mut index = 0;
loop{
   let mut disconnect = false;

    if conn.complete_io(&mut stream).is_err(){
        println!("Client in error state");
        disconnect = true;
    };

    match conn.reader().read(&mut buf[index..]){
        Ok(len) => {
            if len == 0{
                disconnect = true;
            }else{
                index += len; 
            }
        },
        Err(_) => {},
    };

    println!("readed: {}", index);

    //handle partial reception
    try_to_parse_message(buf[0..index]);

    if index >= buf.len(){
        println!("Invalid data, disconnect");
        break;
    }else if disconnect{
        println!("Client disconnected");
        break;
    }else{
        thread::sleep(time::Duration::from_millis(10));
    }
}
```

Client side (android application, using javax.net.ssl.SSLSocket) i connect, send 1 byte, then the message, and disconnect right away, (forcing a flush to make sure data is sent):
```
    byte type[] = new byte[1];
    type[0] = 0;
    out.write(type);
    out.write(info.toByteArray());
    out.flush();
```

OUTPUT:

readed: 1
Client in error state
readed: 1
Client disconnected

EXPECTED OUTPUT (obtained by adding 100ms delay before closing the connection on client side):

readed: 1
readed: 101
readed: 0
Client disconnected

**Comment by ctz** [comment]
If you are using straightforward blocking IO, I would suggest the entire above snippet can be replaced with [`Stream`](https://docs.rs/rustls/latest/rustls/struct.Stream.html), and then calling [`read_to_end()`](https://doc.rust-lang.org/nightly/std/io/trait.Read.html#method.read_to_end) on it.

Would suggest getting a packet capture to verify what the client is actually sending before the TCP close.

**Comment by lestofante** [comment]
> Would suggest getting a packet capture to verify what the client is actually sending before the TCP close.

I am using generate_simple_self_signed() that seems to generate an ECDSA, and I cant find a way to load the key into Wireshark; seems like i need the session key, probably from dangerous_extract_secrets(), but i cant find anything about how to export in a format wireshark will like

Anyway, looking at the raw TCP messages, i see only 1 data message getting written instead of 3 when i add a timeout; so i assume the issue is android side, closing

**Comment by djc** [comment]
You can use the KeyLogFile interface to write Wireshark-compatible keys to a file.
