### ISSUE TITLE
`ServerHelloPayload` re-export inquery/request

### ISSUE THREAD

**Issue by 5Dev24** [rustls/rustls#1815]
**Checklist**
* [x] I've searched the issue tracker for similar requests

**Is your feature request related to a problem? Please describe.**
Prior to the 0.22.x release(s) (0.21.10 and before), I used `rustls::internal::msgs::handshake::ServerHelloPayload` to extract information in relation to the connection made by rustls at a low level. Accessing this data was simple by taking it from a `rustls::msgs:message::Message` containing the handshake. This struct is not longer re-exported and all the fields were made pub(crate) too.

I do understand that the internal classes are not part of the stable interface from rustls. However, it would be appreciated if this could be made public again instead of having to maintain a fork with such a minor change.

**Describe the solution you'd like**
Make the fields of the `ServerHelloPayload` pub again and re-export it once more in the lib.rs.

**Describe alternatives you've considered**
I've considered and made a fork the re-exports this struct. It's a simple patch fork that is just applied after each release. Major drawback being that `cargo outdated` won't catch using an outdated version and yanked, bad versions won't automatically affect the fork.

**Additional comments**
If there's an underlying reason that it wasn't re-exported anymore, I couldn't find the discussion made on this repository. If you know there was one or know how to better look for it, please let me know.

If there's an alternative way to access this information through the stable interface, I'd love to hear it as it was difficult to find the previously mentioned struct as-is.

I don't mind making the small PR to change this, but I'd like to hear what others think before doing so.

Thank you for your time and consideration.

**Comment by djc** [comment]
What were you trying to do with the ServerHelloPayload data? What goal are you trying to achieve?

**Comment by djc** [comment]
I think we'd probably merge a PR that makes the fields public again, want to submit one?

Out of curiosity, what are you using the JA3 fingerprints for?

**Comment by ctz** [comment]
I think you are better off writing your own parser that outputs the JA3 pre-hash format, or relying on a crate that has TLS message parsing as its goal (`tls_parser`). I would like to land #1475 in our next release (not the one that is imminent tomorrow) and this will break any code that computes JA3 (because it does not maintain extension order in its internal representation).

**Comment by 5Dev24** [comment]
@djc I can do that. They are used to fingerprint tls connections made to servers, that is all. Just gives a better view of what infrastructure you may be connected to if the hash is a known one.

@ctz The PR you linked seems to be effecting client hello payload (from my brief reading). I'm after just the server side hash (JA3S, not JA3) so I don't believe I'd be affected. I imagine others would probably like a way to get the original order of extensions though. Having to MITM a rustls connection and then use another crate to parse that connection sounds quite frustrating. Sorry if I've misunderstood your comment. I appreciate your concern.

**Comment by ctz** [comment]
> The PR you linked seems to be effecting ClientHelloPayload's extensions (from my brief reading).

I intend that the same internal representation style would be used by every type of extension.

**Comment by 5Dev24** [comment]
I'll go ahead and close this issue then with those planned changes. Thank you for y'all's help. I ended up setting up just switching from rustls to just using openssl and tokio.
