### ISSUE TITLE
optimize receiving data with TLS 1.2 and aes-128-gcm

### ISSUE THREAD

**Issue by bdaehlie** [rustls/rustls#1828]
We ran the Rustls benchmarking tool with the Rustls v0.23 release and Rustls appears to be a bit slower than OpenSSL 3.2.0 when receiving data with TLS 1.2 and aes-128-gcm. We should optimize until we are faster than OpenSSL in this benchmark.

**Comment by SimonTate** [comment]
I believe I can reproduce with openssl-bench ( https://github.com/ctz/openssl-bench.git @ ea4f92bb969d151b8cedf10083819b980d19e533) on M3 Pro MacBook with latest master of openssl and rustls.

OpenSSL: dc9bc6c8e1bd329ead703417a2235ab3e97557ec
rustls: 38573b26d56af2e1f1f5dc15e9daf70b58efdea7

rustls:

```
make -f admin/bench-measure.mk measure
target/release/examples/bench bulk TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
bulk    TLSv1_2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256   max_fragment_size:default       send    6842.16 MB/s
bulk    TLSv1_2 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256   max_fragment_size:default       recv    4874.97 MB/s
```

openssl with openssl-bench:

```
state@BTM-FQV52JYD09:~/Developer/openssl-bench(master)
$ make measure
env LD_LIBRARY_PATH=../openssl ./bench bulk ECDHE-RSA-AES128-GCM-SHA256 1048576
negotiated TLSv1.2 with ECDHE-RSA-AES128-GCM-SHA256
send: 7001.01 MB/s
recv: 7779.95 MB/s
```

Is this the test you're referring to @bdaehlie ?

**Comment by ctz** [comment]
See https://github.com/rustls/rustls/issues/1830#issuecomment-2393303437 for latest measurements -- for this scenario we are equal.

It also shows the comparative improvement available when using the unbuffered API, though I'd caution against  comparing our unbuffered API with openssl's buffered one.

**Comment by ctz** [comment]
This was improved in https://github.com/rustls/rustls/pull/2155 -- see https://docs.google.com/spreadsheets/d/1lmU9VdiQMujOhHiz94_4hMFfkDChTYDcpZmO_OI48M0/edit?usp=sharing for the raw results and https://github.com/rustls/rustls/wiki/Performance-measurements-(2024%E2%80%9010%E2%80%9018) for the reproduction steps.
