### ISSUE TITLE
optimize receiving data with TLS 1.3 and aes-256-gcm

### ISSUE THREAD

**Issue by bdaehlie** [rustls/rustls#1829]
We ran the Rustls benchmarking tool with the Rustls v0.23 release and Rustls appears to be a bit slower than OpenSSL 3.2.0 when receiving data with TLS 1.3 and aes-256-gcm. We should optimize until we are faster than OpenSSL.

**Comment by ctz** [comment]
See https://github.com/rustls/rustls/issues/1830#issuecomment-2393303437 for latest measurements. We are now ahead in this scenario.
