### ISSUE TITLE
optimize server-side full handshakes for TLS 1.2 and 1.3

### ISSUE THREAD

**Issue by bdaehlie** [rustls/rustls#1830]
We ran the Rustls benchmarking tool with the Rustls v0.23 release and Rustls appears to be a bit slower than OpenSSL 3.2.0 on server-side full handshakes for TLS 1.2 and 1.3. We should optimize until we are faster than OpenSSL.

**Comment by ctz** [comment]
Possible investigation ideas:
- add ECDSA or ED25519 support to the openssl-bench tool, and use that to see if it boils down to RSA signing performance, or something else.
- compare using `rustls-libcrypto` (a rustls `CryptoProvider` on top of OpenSSL `libcrypto`) to control for crypto library (nb. does not exist at the time of writing)

**Comment by ctz** [comment]
Had a brief look at this just now:

boringssl and aws-lc have a RSA performance deficit to openssl:

```
$ openssl version
OpenSSL 3.0.13 30 Jan 2024 (Library: OpenSSL 3.0.13 30 Jan 2024)

$ openssl speed rsa2048
(...)
                  sign    verify    sign/s verify/s
rsa 2048 bits 0.000181s 0.000012s   5513.3  82933.9
```

boringssl bssl bench:
```
$ ./tool/bssl speed -filter RSA
Did 2158 RSA 2048 signing operations in 1004019us (2149.4 ops/sec)
Did 70000 RSA 2048 verify (same key) operations in 1001803us (69874.0 ops/sec)
```

aws-lc bssl bench:
```
$ ./tool/bssl speed -filter RSA
Did 2420 RSA 2048 signing operations in 1077586us (2245.8 ops/sec)
Did 73000 RSA 2048 verify (same key) operations in 1001564us (72886.0 ops/sec)
```

At the rust level (somewhat unsurprisingly) the raw performance is attainable:

(at aws-lc-rs level)
```
manual/rsa2048-pkcs1-sha256-sign
                        time:   [425.55 µs 426.17 µs 426.86 µs]
                        thrpt:  [2.3427 Kelem/s 2.3465 Kelem/s 2.3499 Kelem/s]
```

(at rustls level, with ring included)
```
test crypto::aws_lc_rs::sign::benchmarks::bench_rsa2048_pkcs1_sha256      ... bench:     435,072.60 ns/iter (+/- 24,104.41)
test crypto::ring::sign::benchmarks::bench_rsa2048_pkcs1_sha256           ... bench:     431,601.60 ns/iter (+/- 2,453.81)
```

The difference between boringssl and openssl is AVX512 support, probably AVX512IFMA, and disabling those has openssl matching boringssl performance:

```
$ OPENSSL_ia32cap=:~0x80230000 openssl speed rsa2048
(...)
CPUINFO: OPENSSL_ia32cap=0x7ef8320b078bffff:0x405fde719c97a9 env::~0x80230000
                  sign    verify    sign/s verify/s
rsa 2048 bits 0.000442s 0.000012s   2262.4  80098.8
```

**Comment by ctz** [comment]
https://docs.google.com/spreadsheets/d/14CabMA83zgZ0Xy8s5NRfwY_fVm26ce9d2qbGaScIGuY/edit?usp=sharing

Shows the result of [aws/aws-lc#1273](https://github.com/aws/aws-lc/pull/1273) in this setting.

Raw numbers:

  | openssl 3.2.0 | rustls 0.23.13+-buffered | diff % | diff text | rustls 0.23.13+-unbuffered | diff % | diff text
-- | -- | -- | -- | -- | -- | -- | --
transfer, 1.2, aes-128-gcm, sending | 6462.8 | 7221.47 | 111.74% | 1.12x (faster) | 8255.71 | 127.74% | 1.28x (faster)
transfer, 1.2, aes-128-gcm, receiving | 7130.47 | 7153.16 | 100.32% | 1.00x (faster) | 9365.34 | 131.34% | 1.31x (faster)
transfer, 1.3, aes-256-gcm, sending | 5975.35 | 6807.2 | 113.92% | 1.14x (faster) | 7666.55 | 128.30% | 1.28x (faster)
transfer, 1.3, aes-256-gcm, receiving | 6539.02 | 7019.02 | 107.34% | 1.07x (faster) | 9324.8 | 142.60% | 1.43x (faster)
  | openssl 3.2.0 | rustls 0.23.13+-buffered | diff % | diff text | rustls 0.23.13+-unbuffered | diff % | diff text
full handshakes, 1.2, rsa, client | 3093.87 | 7493.47 | 242.20% | 2.42x (faster) | 8417.68 | 272.08% | 2.72x (faster)
full handshakes, 1.2, rsa, server | 2105.28 | 2761.87 | 131.19% | 1.31x (faster) | 2855.36 | 135.63% | 1.36x (faster)
full handshakes, 1.2, ecdsa, client | 2025.32 | 4151.69 | 204.99% | 2.05x (faster) | 4428.34 | 218.65% | 2.19x (faster)
full handshakes, 1.2, ecdsa, server | 4951.38 | 11262.61 | 227.46% | 2.27x (faster) | 13015.99 | 262.88% | 2.63x (faster)
resumed handshakes, 1.2, client | 21266.9 | 41545.72 | 195.35% | 1.95x (faster) | 65264.87 | 306.88% | 3.07x (faster)
resumed handshakes, 1.2, server | 22938.2 | 43868.83 | 191.25% | 1.91x (faster) | 71642.67 | 312.33% | 3.12x (faster)
full handshakes, 1.3, rsa, client | 2688.78 | 6301.07 | 234.35% | 2.34x (faster) | 6788.07 | 252.46% | 2.52x (faster)
full handshakes, 1.3, rsa, server | 1865.2 | 2373.55 | 127.25% | 1.27x (faster) | 2424 | 129.96% | 1.30x (faster)
full handshakes, 1.3, ecdsa, client | 1810.75 | 3764.91 | 207.92% | 2.08x (faster) | 3944.5 | 217.84% | 2.18x (faster)
full handshakes, 1.3, ecdsa, server | 3758.05 | 6714.21 | 178.66% | 1.79x (faster) | 7305.27 | 194.39% | 1.94x (faster)
