### ISSUE TITLE
Error: badRecordMac

### ISSUE THREAD

**Issue by peyman1992** [rustls/rustls#1836]
Hello
After a few poll_write with tokio-rustls  get a badRecordMac alert message in poll_read from server side
This error only happens on the Apple platform and the program works correctly on Windows

**Comment by cpu** [comment]
What version of rustls and tokio-rustls are you using? Is the client using Rustls as well, or a different library? Do you have a minimal reproduction you can share? What Apple/Windows OS versions are you running?

**Comment by peyman1992** [comment]
> What version of rustls and tokio-rustls are you using? Is the client using Rustls as well, or a different library? Do you have a minimal reproduction you can share? What Apple/Windows OS versions are you running?

hello
1-When I used the latest commit on GitHub, the problem was solved But there was this problem in the version available in crates
2-The server side uses GoLang tls and the client uses rustls and tokio-rustls
3-At this time, the problem is solved and I cannot reproduce it
3-There was no problem in Windows 11, but in macOS 14 and iOS 17 this problem existed before using last commit

**Comment by ctz** [comment]
I think this is likely a similar cause to #1762 -- would be good to have a repro case for this, especially if tokio-rustls doesn't handle it correctly.

**Comment by cpu** [comment]
> 3-At this time, the problem is solved and I cannot reproduce it

I think given the lack of a reproducer & the problem being resolved for the OP we're unlikely to make progress here. I'm going to close this for now and we can revisit if there's more information to consider.
