### ISSUE TITLE
Can't connect to a server presenting a certificate with an IP address in its common name

### ISSUE THREAD

**Issue by jbg** [rustls/rustls#184]
`ClientSession` requires a `DNSNameRef` for the `hostname` argument, but a `DNSNameRef` cannot be constructed from an IP address.

In some situations (in my case, connecting to a PostgreSQL server) the server presents a valid certificate, signed by a trusted CA, for a specific IP address. As far as I can tell this is a valid use of TLS certificates, but it doesn't seem possible to support it with rustls at present.

**Comment by briansmith** [comment]
The underlying webpki library doesn't support IP addresses yet; see https://github.com/briansmith/webpki/issues/54.

**Comment by qiujiangkun** [comment]
I have my own 'fork' for supporting ip address. However, it was a huge poor refactorization for both rustls and webpki. I even did not actually fork, but I simply copy the content of both the crates. I would not recommend anyone use my version.
Here's a simple example for you reference.
```rust
use crate::ChannelBuilder;
use crate::*;
use rustls::ClientConfig;
use rustls::ClientSession;
use serde::Deserialize;
use serde::Serialize;
use std::io::Read;
use std::io::Write;
use std::net::Shutdown;
use std::net::SocketAddr;
use std::net::TcpStream;
use std::net::ToSocketAddrs;
use std::sync::Arc;
use std::time::Duration;
use utils::now;
use utils::UnsafeArc;

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct TlsChannelBuilder {
    pub domain:       String,
    pub port:         u32,
    pub ip:           String,
    pub verification: bool,
}

impl ChannelBuilder for TlsChannelBuilder {
    type Channel = TlsChannel;

    fn connect_delayed(&self) -> Result<Self::Channel, Error> {
        Ok(TlsChannel {
            stream:    UnsafeArc::empty(),
            builder:   self.clone(),
            connected: false,
        })
    }
}
pub struct TlsChannel {
    stream:    UnsafeArc<rustls::StreamOwned<ClientSession, TcpStream>>,
    builder:   TlsChannelBuilder,
    connected: bool,
}

impl TlsChannel {
    pub fn connect(address: &str, port: u32) -> Result<TlsChannel, Error> {
        if utils::is_valid_ip(address) {
            Self::connect_no_verification(address, port)
        } else {
            Self::connect_domain(address, port)
        }
    }

    /// Connect to a domain but with pre-fetched ip address to work around DNS
    pub fn connect_domain_with_ip(domain: &str, port: u32, ip: &str) -> Result<TlsChannel, Error> { Self::connect_with_options(domain, port, ip, true) }

    /// Connect to a domain
    pub fn connect_domain(domain: &str, port: u32) -> Result<TlsChannel, Error> { Self::connect_with_options(domain, port, "", true) }

    /// Connect to an ip address without a domain
    /// The certification must be signed for the ip address
    pub fn connect_no_verification(ip_address: &str, port: u32) -> Result<TlsChannel, Error> { Self::connect_with_options(ip_address, port, ip_address, false) }

    pub fn connect_with_options(domain: &str, port: u32, ip: &str, verification: bool) -> Result<TlsChannel, Error> {
        let address = match ip.len() {
            0 => domain,
            _ => ip,
        };
        let addr: SocketAddr = (address, port as u16).to_socket_addrs().unwrap().next().unwrap();
        debug!("Connecting to {} with TCP", addr);
        let socket = TcpStream::connect_timeout(&addr, Duration::from_secs(2))?;
        let mut config = ClientConfig::new();

        debug!("TCP Connected. New ClientSession {}", addr);
        if !verification {
            config.dangerous().set_certificate_verifier(Arc::new(rustls::NullVerifier));
        }
        config.root_store.add_server_trust_anchors(&webpki::trusted_certs::TLS_SERVER_ROOTS);
        let dns_name = webpki::DnsName::try_from_punycode(domain)?;
        let client = rustls::ClientSession::new(&Arc::new(config), dns_name);

        socket.set_nonblocking(true)?;
        socket.set_nodelay(true)?;

        let mut tls_stream = rustls::StreamOwned::new(client, socket);
        let begin = now();
        let timeout = 3e9 as TimeDiff;
        // process handshaking
        loop {
            if now() as TimeDiff - begin as TimeDiff > timeout {
                return Err(Error::Timeout);
            }
            match tls_stream.as_stream().complete_prior_io() {
                Ok(()) => break,
                Err(err) => {
                    if err.raw_os_error() != Some(libc::EWOULDBLOCK) {
                        return Err(err)?;
                    }
                },
            }
        }

        debug!("TLS handshaken {}", addr);
        Ok(TlsChannel {
            stream:    UnsafeArc::new(tls_stream),
            builder:   TlsChannelBuilder {
                domain: domain.to_string(),
                port,
                ip: ip.to_owned(),
                verification,
            },
            connected: true,
        })
    }

    pub fn delayed_connect(address: &str, port: u32) -> Result<TlsChannel, Error> {
        if utils::is_valid_ip(address) {
            Self::delayed_connect_no_verification(address, port)
        } else {
            Self::delayed_connect_domain(address, port)
        }
    }

    /// Connect to a domain but with pre-fetched ip address to work around DNS
    pub fn delayed_connect_domain_with_ip(domain: &str, port: u32, ip: &str) -> Result<TlsChannel, Error> { Self::delayed_connect_with_options(domain, port, ip, true) }

    /// Connect to a domain
    pub fn delayed_connect_domain(address: &str, port: u32) -> Result<TlsChannel, Error> { Self::delayed_connect_with_options(address, port, "", true) }

    /// Connect to an ip address without a domain
    /// The certification must be signed for the ip address
    pub fn delayed_connect_no_verification(ip_address: &str, port: u32) -> Result<TlsChannel, Error> { Self::delayed_connect_with_options(ip_address, port, ip_address, false) }

    pub fn delayed_connect_with_options(domain: &str, port: u32, ip: &str, verification: bool) -> Result<TlsChannel, Error> {
        Ok(TlsChannel {
            stream:    UnsafeArc::empty(),
            builder:   TlsChannelBuilder {
                domain: domain.to_string(),
                port,
                ip: ip.to_string(),
                verification,
            },
            connected: false,
        })
    }
}
make_recoverable_channel!(TlsChannel);

impl std::io::Write for TlsChannel {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        loop {
            match self.stream.write(buf) {
                Ok(n) => return Ok(n),
                Err(err) => {
                    if err.raw_os_error() != Some(libc::EWOULDBLOCK) {
                        return Err(err);
                    }
                },
            }
        }
    }

    fn flush(&mut self) -> std::io::Result<()> { self.stream.flush() }
}

impl SetNonblocking for TlsChannel {
    fn set_nonblocking(&mut self, nonblocking: bool) -> std::io::Result<()> { self.stream.get_mut().set_nonblocking(nonblocking) }
}

impl std::io::Read for TlsChannel {
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        if let Some(stream) = self.stream.as_option() {
            stream.read(buf)
        } else {
            Err(std::io::Error::new(std::io::ErrorKind::NotConnected, "Reconnecting"))
        }
    }

    fn read_to_end(&mut self, buf: &mut Vec<u8>) -> std::io::Result<usize> {
        if let Some(stream) = self.stream.as_option() {
            stream.read_to_end(buf)
        } else {
            Err(std::io::Error::new(std::io::ErrorKind::NotConnected, "Reconnecting"))
        }
    }
}

impl Channel for TlsChannel {
    fn is_open(&self) -> bool { self.connected && !self.stream.is_null() }

    fn close(&mut self) -> Result<(), Error> {
        self.connected = false;
        if !self.stream.is_null() {
            let stream = self.stream.take_nut();
            let _ = stream.sock.shutdown(Shutdown::Both);
        }
        Ok(())
    }

    fn read_buf(&mut self, buf: &mut ChannelData) -> Result<usize, Error> {
        let mut temp_buf = [0u8; 1024];
        match self.read(&mut temp_buf) {
            Ok(x) => {
                buf.set_time(now());
                buf.get_data_mut().write_slice(&temp_buf[..x]);
                Ok(x)
            },
            Err(err) => {
                let err = Error::from(err);
                if !err.ignorable() {
                    self.connected = false;
                }
                Err(err)?
            },
        }
    }

    fn write_buf(&mut self, buf: &mut ChannelData) -> Result<usize, Error> {
        match self.write(buf.get_data_mut().read_slice()) {
            Ok(n) => Ok(n),
            Err(err) => {
                let err = Error::from(err);
                if !err.ignorable() {
                    self.connected = false;
                }
                Err(err)
            },
        }
    }

    fn flush_channel(&mut self) -> Result<(), Error> {
        self.flush()?;
        Ok(())
    }

    fn reconnect_begin(&mut self) -> Result<(), Error> {
        let _ = self.close();
        let channel = Self::connect_with_options(&self.builder.domain, self.builder.port, &self.builder.ip, self.builder.verification)?;
        self.stream = channel.stream;
        Ok(())
    }

    fn reconnect_end(&mut self) { self.connected = true; }
}

unsafe impl Send for TlsChannel {}

#[cfg(test)]
pub(crate) mod tests {
    use crate::error::timed_loop;
    use crate::error::timed_thread_loop;
    use crate::ChannelFactory;
    use crate::*;
    use rustls::Session;
    use std::io::Read;
    use std::io::Write;
    use std::net::TcpStream;
    use std::str;
    use std::sync::Arc;

    #[test]
    fn baidu_tls_raw() {
        let mut config = rustls::ClientConfig::new();
        config.root_store.add_server_trust_anchors(&webpki::trusted_certs::TLS_SERVER_ROOTS);

        let dns_name = webpki::DnsNameRef::try_from_punycode("www.baidu.com").unwrap();
        let mut client = rustls::ClientSession::new(&Arc::new(config), dns_name);
        let mut socket = TcpStream::connect("www.baidu.com:443").unwrap();
        socket.set_nonblocking(true).expect("set_nonblocking call failed");
        socket.set_nodelay(true).expect("set_nodelay call failed");

        client.write(b"GET / HTTP/1.0\r\n\r\n").unwrap();
        client.write_tls(&mut socket).unwrap();
        let mut running = true;
        while running {
            if client.wants_read() {
                match client.read_tls(&mut socket) {
                    Ok(_n) => {
                        client.process_new_packets().unwrap();

                        let mut plaintext = Vec::new();
                        match client.read_to_end(&mut plaintext) {
                            Ok(_x) => {
                                if plaintext.len() > 0 {
                                    unsafe {
                                        println!("{}", str::from_utf8_unchecked(&plaintext));
                                        running = false;
                                    }
                                }
                            },
                            Err(_err) => {
                                // println!("{}", err);
                            },
                        }
                    },

                    Err(_err) => {
                        // println!("{}", err);
                    },
                }
            }

            if client.wants_write() {
                client.write_tls(&mut socket).unwrap();
            }
        }
    }
    #[test]
    fn baidu_tls_nonblocking() {
        let mut config = rustls::ClientConfig::new();
        config.root_store.add_server_trust_anchors(&webpki::trusted_certs::TLS_SERVER_ROOTS);

        let dns_name = webpki::DnsNameRef::try_from_punycode("www.baidu.com").unwrap();
        let client = rustls::ClientSession::new(&Arc::new(config), dns_name);
        let socket = TcpStream::connect("www.baidu.com:443").unwrap();

        let mut tls_stream = rustls::StreamOwned::new(client, socket);
        tls_stream.get_mut().set_nonblocking(true).expect("set_nonblocking call failed");
        tls_stream.get_mut().set_nodelay(true).expect("set_nodelay call failed");

        let mut buf = [0u8; 1000];
        loop {
            match tls_stream.write(b"GET / HTTP/1.0\r\n\r\n") {
                Ok(n) => {
                    println!("Sent {}", n);
                },
                Err(err) => {
                    if err.raw_os_error() != Some(libc::EWOULDBLOCK) {
                        panic!("Error {}", err);
                    }
                },
            }
            match tls_stream.read(&mut buf) {
                Ok(n) => {
                    println!("Read {} bytes", n);
                    break;
                },
                Err(err) => {
                    if err.raw_os_error() != Some(libc::EWOULDBLOCK) {
                        panic!("Error {}", err);
                    }
                },
            }
        }
    }

    #[test]
    fn tls_channel_baidu() {
        let mut channel = ChannelFactory::new_tls_channel("www.baidu.com", 443, "GET / HTTP/1.0\r\n\r\n").unwrap();
        let mut running = 1;
        while running > 0 {
            let _ = channel.flush_channel();
            let mut buf = ChannelData::default();
            match channel.read_buf(&mut buf) {
                Ok(n) => {
                    if n > 0 {
                        println!("{}", buf.get_data_mut().get_str());
                        running -= 1;
                    }
                },
                Err(err) => {
                    if !err.ignorable() {
                        panic!("err: {}", err);
                    }
                },
            }
            if !channel.is_open() {
                channel.reconnect_begin().unwrap();
                channel.write_buf(&mut ChannelData::text("GET / HTTP/1.0\r\n\r\n".to_owned())).unwrap();
                channel.reconnect_end();
            }
        }
    }

    #[test]
    fn reconnect_baidu() {
        let mut tls = ChannelFactory::new_tls_channel("www.baidu.com", 443, "GET / HTTP/1.0\r\n\r\n").unwrap();
        let mut cnt = 0;
        timed_loop(10_000_000_000, || {
            let _ = tls.flush();
            let mut buf = ChannelData::default();
            match tls.read_buf(&mut buf) {
                Ok(n) => {
                    if n > 0 {
                        println!("Read {} bytes: {}", n, buf.get_data_mut().get_str());
                        tls.close()?;
                        tls.reconnect_begin()?;
                        tls.write_buf(&mut ChannelData::text("GET / HTTP/1.0\r\n\r\n".to_owned()))?;
                        tls.reconnect_end();
                        cnt += 1;
                    }
                },
                Err(err) => {
                    if !err.ignorable() {
                        println!("Error {}", err);
                    }
                },
            }
            return Ok(cnt <= 10);
        })
        .unwrap();
    }

    #[test]
    fn multithread_reconnect_baidu() {
        let mut tls = UnsafeArc::new(TlsChannel::delayed_connect("www.baidu.com", 443).unwrap());
        let mut tls2 = UnsafeArc::clone(&tls);
        let (tx, rx) = crossbeam::channel::bounded(1);
        tx.send(()).unwrap();
        let tx2 = tx.clone();
        let _reconnect = timed_thread_loop(5_000_000_000, move || {
            if let Ok(()) = rx.try_recv() {
                println!("reconnect");
                if let Err(err) = tls.reconnect_begin() {
                    println!("Reconnect Error {}", err);
                    tx2.send(()).unwrap();
                }

                println!("TCP reconnected");
                match tls.write_buf(&mut ChannelData::text("GET / HTTP/1.0\r\n\r\n".to_owned())) {
                    Ok(_x) => {
                        println!("Sent headers");
                    },
                    Err(err) => {
                        println!("Failed sending headers {}", err);
                        tx2.send(()).unwrap();
                    },
                }
                tls.reconnect_end();
            }
            Ok(true)
        });
        let mut cnt = 0;
        timed_loop(5_000_000_000, || {
            if tls2.is_open() {
                let _ = tls2.flush();
                let mut buf = ChannelData::default();
                assert!(tls2.is_open());
                match tls2.read_buf(&mut buf) {
                    Ok(n) => {
                        if n > 0 {
                            println!("Read {} bytes: {}", n, buf.get_data_mut().get_str());
                            tls2.close()?;
                            tx.send(()).unwrap();
                            cnt += 1;
                        }
                    },
                    Err(err) => {
                        if !err.ignorable() {
                            tls2.close()?;
                            tx.send(()).unwrap();
                            println!("Error {}", err);
                        }
                    },
                }
            }
            Ok(cnt <= 5)
        })
        .unwrap();

        // reconnect.join().expect("Thread panicked");
        assert_eq!(cnt, 6);
    }

    #[test]
    fn baidu_read() {
        let mut channel = TlsChannel::connect("www.baidu.com", 443).unwrap();

        channel.write(b"GET / HTTP/1.0\r\n\r\n").unwrap();

        let mut running = true;
        while running {
            let mut buf = [0u8; 100000];
            match channel.read(&mut buf) {
                Ok(n) => unsafe {
                    if n > 0 {
                        println!("{}", str::from_utf8_unchecked(&buf[..n]));
                        running = false;
                    }
                },
                Err(_err) => {
                    // println!("{}", err);
                },
            }

            channel.flush().unwrap();
        }
    }

    #[test]
    pub(crate) fn tls_bitmex() {
        let mut channel = TlsChannel::connect("www.bitmex.com", 443).unwrap();

        const HEADER: &[u8] = concat!(
            "GET /realtime?subscribe=instrument,orderBook:XBTUSD HTTP/1.1\r\n",
            "Host: www.bitmex.com\r\n",
            "Upgrade: websocket\r\n",
            "Connection: Upgrade\r\n",
            "Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\n",
            "Sec-WebSocket-Version: 13\r\n",
            // "Connection: close\r\n",
            // "Accept-Encoding: identity\r\n",
            "\r\n"
        )
        .as_bytes();
        println!("Sending headers");
        channel.write(HEADER).unwrap();
        println!("Headers sent");

        // let websocket = WebSocketDecoder::new();
        let mut running = true;
        while running {
            let mut buf = ChannelData::default();
            match channel.read_buf(&mut buf) {
                Ok(n) => {
                    if n > 0 {
                        println!("Read {} bytes", n);
                        println!("{}", buf.get_data_mut().get_str());
                        // let x = websocket.parse(&mut buf).unwrap();
                        // for _ in 0..x {
                        //     match websocket.get_packet() {
                        //         WSPacket::Text(s) => {
                        //             let _js: Value = serde_json::from_slice(s.as_slice()).unwrap();
                        //             // println!("got json: {}", js)
                        //         }
                        //         _ => {}
                        //     }
                        // }
                        running = false;
                    }
                },
                Err(_err) => {
                    // println!("err {}", err);
                },
            }
            channel.flush_channel().unwrap();
        }
        assert_eq!(running, false);
    }

    #[test]
    fn tls_channel_1_1_1_1() {
        let mut channel = TlsChannel::connect("1.1.1.1", 443).unwrap();
        loop {
            match channel.write(b"GET / HTTP/1.1\r\n\r\n") {
                Ok(_) => break,
                Err(_err) => {},
            }
        }

        let mut running = 1;
        while running > 0 {
            let mut buf = ChannelData::default();
            match channel.read_buf(&mut buf) {
                Ok(n) => {
                    if n > 0 {
                        println!("Read {}", buf.get_data_mut().get_str());
                        running -= 1;
                    }
                },
                Err(_err) => {
                    // println!("err: {}, but: {}", err, buf.as_str());
                },
            }

            channel.flush_channel().unwrap();
        }
    }

    #[test]
    fn tls_channel_1_1_1_1_no_verification() {
        let mut channel = TlsChannel::connect_no_verification("1.1.1.1", 443).unwrap();
        loop {
            // When it's 1.0, returns 403 Forbidden
            // when it's 1.1, returns slowly then 400 Bad Request
            match channel.write(b"GET / HTTP/1.1\r\n\r\n") {
                Ok(_) => break,
                Err(_err) => {},
            }
        }

        let mut running = 1;
        while running > 0 {
            let mut buf = ChannelData::default();
            match channel.read_buf(&mut buf) {
                Ok(n) => {
                    if n > 0 {
                        println!("Read {}", buf.get_data_mut().get_str());
                        running -= 1;
                    }
                },
                Err(_err) => {
                    // println!("err: {}, but: {}", err, buf.as_str());
                },
            }

            channel.flush_channel().unwrap();
        }
    }
}

```
[patched.zip](https://github.com/briansmith/webpki/files/6175406/patched.zip)

**Comment by tkaitchuck** [comment]
@briansmith Is this because webpki is no longer maintained? This seems like a very basic feature which is is blocking common things (like using tokio to connect based on an IP address) and it has not been fixed in 5 years. Should rustls find an alternative library?

**Comment by thalesfragoso** [comment]
@tkaitchuck You can already define your own certificate verifiers and not use any webpki code for a while now.

**Comment by jbg** [comment]
@thalesfragoso "just manually parse the certificate and implement your own verification logic" isn't a solution, which is why this issue is still open.

**Comment by thalesfragoso** [comment]
@jbg They specially mentioned that it was blocking specific implementations, it isn't.

And, someone will have to "manually parse the certificate and implement their own verification logic", and with that, create a better solution before rustls can think of moving away from webpki. Either you like it or not, webpki is the best currently available option.

And a little tip, you can use webpki itself when implementing your own verifier, it can do the heavy lifting verification for you and you can choose if you want to verify the domain name or not, it's a separate function.

**Comment by jbg** [comment]
> And, someone will have to "manually parse the certificate and implement their own verification logic", and with that, create a better solution before rustls can think of moving away from webpki. Either you like it or not, webpki is the best currently available option.

As I'm sure you know, there is a huge difference between someone carefully implementing verification logic once in a crate like webpki, and every user of rustls who wants to use a feature missing from webpki having to hack it together themselves. It's strange to imply that they are equivalent somehow.

> Either you like it or not, webpki is the best currently available option.

I agree, it is, and I'm aware of the magnitude of the task to replace webpki. Honestly though, a rewrite isn't necessary or desired. The problems are with maintainership, so it's a good example of a situation where forking could make sense. I would be happy to donate time to such an effort, but I don't have the time to lead it.

> And a little tip, you can use webpki itself when implementing your own verifier, it can do the heavy lifting verification for you and you can choose if you want to verify the domain name or not, it's a separate function.

You can, but you have (at least last I looked, which admittedly was years ago) to get hold of the IPAddress SAN separately since webpki doesn't understand them. So implementations I've seen end up using another crate for X.509 parsing and then implementing the verification manually. It was deemed too much risk at $work and thus we use OpenSSL instead for those projects that need IPAddress SANs. (And now I get pressure to drop rustls from the rest for standardisation.)

**Comment by thalesfragoso** [comment]
What I meant was that someone will have to do a very hard and sensitive work (and do it good) before this discussion of dropping webpki starts to make sense.

Anyway, I don't think this specific discussion is leading anywhere, so I will refrain myself from continuing it.

**Comment by farcaller** [comment]
I completely agree with @jbg that it is a reasonable situation to fork webpki and move forward, and later merge the changes once the owner has more time on their hands. I appreciate their support of rust community for maintaining webpki and ring but at this point rustls seems to be hindered by a lagging downstream.

**Comment by sehz** [comment]
We are in the same situation.  Would love to use rustl but forced to use OpenSSL due to webpki/ring issue

**Comment by farcaller** [comment]
I guess what I want to hear from rustls maintainers is: are you willing to switch to a fork of webpki until the original repo catches up? Also, are you willing to do some code reviews for the changes that will unblock highly requested rustls features? My company uses rust internally so the latter isn't as crucial, I got engineers qualified in rust and security systems to do some code reviews, but it's all futile if you're not willing to switch to a work.

**Comment by djc** [comment]
If the goal is to get a viable solution to supporting IP addresses in SAN then I think that starts with a PR to webpki. We can then gather feedback from anyone (including the maintainer of webpki) and figure out a way forward. Additionally, it would allow interested parties to use the branch for that PR by using Cargo's patching functionality.

Whether rustls choses to depend on such a branch "officially" is merely the last decision. In my view, building this work as a PR to/branch of the webpki project seems reasonably either way, and we can figure out a way forward from there. It should be obvious that the rustls maintainers are not going to commit upfront to pulling in any kind of fork or branch in the future, without being able to actually look at the changes involved as well as the process used to get to the end state of that branch (including who has been able to review the branch and what the feedback has been).

So while I definitely empathize with concerns about the progress of the webpki project, I think the solution here is to start actually building the changes we want to see rather than complaining about the current situation. I personally don't have a use case for this particular feature, which makes it harder for me to gather resources to build it. However, I will commit to reviewing any work towards this because obviously I'd like to see rustls grow support for common use cases like this.

**Comment by ereslibre** [comment]
I have created a PR for webpki (https://github.com/briansmith/webpki/pull/260) that addresses this issue.

I will open the PR for adapting `rustls` if the proposed `webpki` PR happens to be accepted and merged.

**Comment by djc** [comment]
For people following this, you might also be interested in #1032.

**Comment by jhartzell42** [comment]
> @jbg They specifically mentioned that it was blocking specific implementations, it isn't.

It was until my most recent patch. The assumption that it would be a webpki-parseable domain name was enforced even if webpki-based validation was disabled. Fixed in #1032 . There was, prior to that, absolutely no work-around.

**Comment by ctz** [comment]
[feat-ip-address](https://github.com/rustls/rustls/tree/feat-ip-address) is a feature branch for this suitable for testing purposes. This is against @ereslibre's webpki PR.

**Comment by ctz** [comment]
This is now on main and will be part of the forthcoming 0.21.0 release. Testing before then is gratefully received; please raise any issues found. Thanks to @ereslibre again!

**Comment by ereslibre** [comment]
Thanks to you folks!

**Comment by elioengcomp** [comment]
I know this is an old thread, but I don't see a reference for this issue on the 0.21.0 release notes and I'm seeing the following error when trying to connect to a server using a self signed certificate that points to the IP.
```
2024-02-08T22:47:50.562829Z  WARN ThreadId(02) proxy{version=HTTP/1.1 method=CONNECT uri=35.188.145.54:443 client_addr=127.0.0.1:56767}:process_connect: rustls::msgs::handshake: Illegal SNI hostname received "35.188.145.54"
```
Was this really fixed?

**Comment by ctz** [comment]
Yes, this was really fixed. That issue is different -- it is a client-side interop bug. As far as we know, it affected Apple and OpenSSL clients. Apple fixed theirs very quickly after we reported to them and is no longer an issue. Unfortunately there is little movement on the OpenSSL side.

- https://github.com/rustls/rustls/issues/1127
- https://github.com/openssl/openssl/issues/20041

**Comment by ereslibre** [comment]
Hello @elioengcomp

Yes, the release notes include it (https://github.com/rustls/rustls/releases/tag/v%2F0.21.0), it's the first bullet point.

However, what you are experiencing is a different thing. This issue and the release note I mentioned is about using IP addresses in Subject Alternative Names (SAN) in certificates. This information is present in the certificate itself, and interpreted by rustls.

What you are mentioning is about SNI. There is no indication of SNI on certificates themselves. I's a mechanism in which you can use the same IP address for multiple host names. With SNI you ask for a certain hostname, and the server will choose a certificate to be served to you. It is not valid to ask for an IP address with SNI.

Just for adding the whole context, based on the [RFC](https://datatracker.ietf.org/doc/html/rfc3546#page-8):

> Literal IPv4 and IPv6 addresses are not permitted in "HostName".

**Comment by elioengcomp** [comment]
Sorry for the noise. I looked for the issue number on the release notes and did not find it.

**Comment by alsms** [comment]
> Hello @elioengcomp
> 
> Yes, the release notes include it (https://github.com/rustls/rustls/releases/tag/v%2F0.21.0), it's the first bullet point.
> 
> However, what you are experiencing is a different thing. This issue and the release note I mentioned is about using IP addresses in Subject Alternative Names (SAN) in certificates. This information is present in the certificate itself, and interpreted by rustls.
> 
> What you are mentioning is about SNI. There is no indication of SNI on certificates themselves. It's a mechanism in which you can use the same IP address for multiple host names. With SNI you ask for a certain hostname, and the server will choose a certificate to be served to you. It is not valid to ask for an IP address with SNI.
> 
> Just for adding the whole context, based on the [RFC](https://datatracker.ietf.org/doc/html/rfc3546#section-3.1):
> 
> > Literal IPv4 and IPv6 addresses are not permitted in "HostName".

This seems still to be something many clients seem to do, even reqwest, isahc/curl (crate), etc. Instead of flat out refusing operation, would it be feasible to ignore incorrect SNI hostnames?

**Comment by jbg** [comment]
FWIW, I don't think it's appropriate for a TLS library to silently ignore invalid input. The code trying to send IP addresses in SNI should be fixed, and the current behaviour is desirable because it makes the misuse obvious rather than hiding it.

**Comment by alsms** [comment]
The current behavior is a major blocker for me though, as I cannot use rustls with hyper this way, as it refuses HTTPS requests from many HTTP clients just for this reason. At least it should be configurable to be less strict in this regard. In the end, the SNI hostname is an optional extension that clients may choose to send.

**Comment by helgoboss** [comment]
What about a non-default compile-time feature flag that relaxes this requirement? I find myself in the same position as @alsms. dart-lang's HTTP client also does this wrong :(

I'm forced to use forks (either from Dart or from rustls) to make it work at all, which I find worse security-wise than having a "less-strict" configuration option.

**Comment by ssokolow** [comment]
\*nod* Tension between *de jure* standards and deviations so pervasive that they become *de facto* standards has a long history (from what I remember, IRC suffers from it in a big way) and the historical answer has been "Unless you've got enough of a market share majority to dictate terms, you grit your teeth and start reverse-engineering and mimicking the *de facto* standard," so the question resolves to a simple one of "How much market share does the wrong answer have? How much market share does the one who wants to dictate compliance with the correct answer have?"

**Comment by alsms** [comment]
I think being strict is a good default, but it should be possible to let users opt-out and be less strict when the de facto standard is not yet ready for strictness.

**Comment by djc** [comment]
> Sending the IP as SNI hostname still seems to be something that many clients seem to do, even reqwest, isahc (curl), etc. Instead of flat out refusing operation, would it be feasible to ignore incorrect SNI hostnames?

Have you filed bugs against all of these?

**Comment by djc** [comment]
(We now have #1878 to discuss this issue -- thanks, @alexliesenfeld.)
