### ISSUE TITLE
Cipher suites configured through WebPkiServerVerifier::builder_with_provider  is not working. Client hello contains more cipher suites then it configured.

### ISSUE THREAD

**Issue by pranaw215** [rustls/rustls#1851]
I have configured the cipher suites using below code.

```rust
let builder = WebPkiServerVerifier::builder_with_provider(
        server_auth_root.clone().into(),
        CryptoProvider {
            cipher_suites: vec![
                cipher_suite::TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
                cipher_suite::TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
            ],
            kx_groups: vec![
                provider::kx_group::X25519,
                provider::kx_group::SECP256R1,
                provider::kx_group::SECP384R1,
            ],
            //signature_verification_algorithms: SUPPORTED_SIG_ALGS,
            ..default_provider()
        }
        .into(),
    )
    with_crls(crls.clone());
```

But in client hello the cipher suit showing more then intended.

Snip is attached with the mail.

Please let me know whether It's a bug or any coding issue. Ring is a provider by default.
![Cipher_suites](https://github.com/rustls/rustls/assets/43856066/97fecc0b-9121-45a2-9aac-d52419a37ef7)

**Checklist**
* [ ] I've searched the issue tracker for similar bugs.
* [ ] Yes

**Describe the bug**

**To Reproduce**
1. Use one of the examples to connect to `....` 
2. ...
3. See error

**Applicable Version(s)**
A list of versions and platforms you've tested with.

**Expected behavior**

**Additional context**

**Comment by cpu** [comment]
Hi there,

> I have configured the cipher suites using below code.
> let builder = WebPkiServerVerifier::builder_with_provider(...

The crypto provider used by the `WebPkiServerVerifier` is not the one that determines the ciphersuites offered in the client hello of a TLS handshake. The verifier's crypto provider cipher_suites are specific to validating the signatures of presented certificate chains.

Try using [`ClientConfig::builder_with_provider`](https://docs.rs/rustls/latest/rustls/client/struct.ClientConfig.html#method.builder_with_provider) to ensure that the `ClientConfig` uses the same customized crypto provider.

**Comment by pranaw215** [comment]
> Hi there,
> 
> > I have configured the cipher suites using below code.
> > let builder = WebPkiServerVerifier::builder_with_provider(...
> 
> The crypto provider used by the `WebPkiServerVerifier` is not the one that determines the ciphersuites offered in the client hello of a TLS handshake. ~The verifier's crypto provider cipher_suites are specific to validating the signatures of presented certificate chains.~ Edit: Sorry, misspoke. This field would be ignored by the verifier, I was thinking of the `signature_verification_algorithms`.
> 
> Try using [`ClientConfig::builder_with_provider`](https://docs.rs/rustls/latest/rustls/client/struct.ClientConfig.html#method.builder_with_provider) to ensure that the `ClientConfig` uses the same customized crypto provider. There's a complete example of doing this in [limitedclient.rs](https://github.com/rustls/rustls/blob/main/examples/src/bin/limitedclient.rs) if that's helpful.

Hi  ,

I used [ClientConfig::builder_with_provider] and the configured cipher is working there , But I want the CRL support also.
Can you please point the example where CRL support is also there in the example.

**Comment by djc** [comment]
@pranaw215 you can use the custom provider for both -- it's just that you weren't customizing the `CryptoProvider` used for the `ClientConfig` (directly) previously which would cause this issue.

**Comment by cpu** [comment]
> Can you please point the example where CRL support is also there in the example.

We only have an example using CRLs for verifying client certificates as a server. It looks like you're trying to do the inverse and have a client check revocation status for the server.

Something like this diff to `limitedclient.rs` should be a good starting point for using a custom provider for both the client config and the verifier:

```diff
diff --git a/examples/src/bin/limitedclient.rs b/examples/src/bin/limitedclient.rs
index 62443cae..fcaeafa3 100644
--- a/examples/src/bin/limitedclient.rs
+++ b/examples/src/bin/limitedclient.rs
@@ -2,6 +2,7 @@
 //! so that unused cryptography in rustls can be discarded by the linker.  You can
 //! observe using `nm` that the binary of this program does not contain any AES code.

+use rustls::client::WebPkiServerVerifier;
 use std::io::{stdout, Read, Write};
 use std::net::TcpStream;
 use std::sync::Arc;
@@ -15,18 +16,22 @@ fn main() {
             .cloned(),
     );

-    let config = rustls::ClientConfig::builder_with_provider(
-        CryptoProvider {
-            cipher_suites: vec![provider::cipher_suite::TLS13_CHACHA20_POLY1305_SHA256],
-            kx_groups: vec![provider::kx_group::X25519],
-            ..provider::default_provider()
-        }
-        .into(),
-    )
-    .with_protocol_versions(&[&rustls::version::TLS13])
-    .unwrap()
-    .with_root_certificates(root_store)
-    .with_no_client_auth();
+    let provider = Arc::new(CryptoProvider {
+        cipher_suites: vec![provider::cipher_suite::TLS13_CHACHA20_POLY1305_SHA256],
+        kx_groups: vec![provider::kx_group::X25519],
+        ..provider::default_provider()
+    });
+
+    let custom_verifier =
+        WebPkiServerVerifier::builder_with_provider(root_store.into(), provider.clone())
+            .build()
+            .unwrap();
+
+    let config = rustls::ClientConfig::builder_with_provider(provider)
+        .with_protocol_versions(&[&rustls::version::TLS13])
+        .unwrap()
+        .with_webpki_verifier(custom_verifier)
+        .with_no_client_auth();

     let server_name = "www.rust-lang.org".try_into().unwrap();
     let mut conn = rustls::ClientConnection::new(Arc::new(config), server_name).unwrap();
```

**Comment by cpu** [comment]
I'm going to close this since we've figured out the problem causing the unexpected cipher suites in the hello. If you have any further questions feel free to comment or open a new issue.

Thanks!

**Comment by pranaw215** [comment]
Thanks cpu , Its working .  I have added the crl support at client side also in custom_verifier below to check the revocation status of server cert chain. 




    let custom_verifier =
        WebPkiServerVerifier::builder_with_provider(server_auth_root.into(), provider.clone())
            **.with_crls(crls.clone())**
            .build()
            .unwrap();

    let config = rustls::ClientConfig::builder_with_provider(provider)
        .with_protocol_versions(&[&rustls::version::TLS13])
        .unwrap()
        .with_webpki_verifier(custom_verifier)
        .with_no_client_auth();
