### ISSUE TITLE
expose more information in ClientHello

### ISSUE THREAD

**Issue by GlenDC** [rustls/rustls#1857]
**Checklist**
* [x] I've searched the issue tracker for similar requests

**Is your feature request related to a problem? Please describe.**

The information of the ClientHello (<https://docs.rs/rustls/latest/rustls/server/struct.ClientHello.html>)
is currently incomplete. Most information is found within Extensions (e.g. supported versions, compression methods, compress certificate, supported groups, ... and more).

**Describe the solution you'd like**

In the ideal case it could be nice if all extensions can be exposed, but of not that, at least the ones for which
there is already support in `rustls`.

**Describe alternatives you've considered**

Alternatives is not use `rustls` for this purpose and instead work with something like `boring` or `openssl` and expose it myself over FFI.

**Additional context**

N/A

**Comment by ctz** [comment]
If this is a network introspection/fingerprinting use case, I think my comment on a similar ticket might be relevant: https://github.com/rustls/rustls/issues/1815#issuecomment-1969237810

**Comment by GlenDC** [comment]
Fair enough. Thank you very much. I respect that decision. I had a feeling that would be the answer, but given I couldn't find anything specific to ClientHello I gave it a shot anyway. Thank you for your time!

**Comment by djc** [comment]
Should we add some notes about this policy/idea, for example in the `ClientHello` docstring?

**Comment by GlenDC** [comment]
Makes sense to add a note about it yes.
I would also make it a lot clearer in the README of the project.
Because while the goals of rustls are clear, it is less clear that those also have to mean that it cannot be used for purposes such as the ones above.

I fully respect the choices you make here though, not to worry. More saying, might not hurt to as you suggest yourself to make this clearer in the README and other places (such as clienttHello).
