### ISSUE TITLE
Support using rustls without using specific ring or aws-lc-rs apis

### ISSUE THREAD

**Issue by Alvenix** [rustls/rustls#1875]
**Checklist**
* [x] I've searched the issue tracker for similar requests

**Is your feature request related to a problem? Please describe.**
Crates like [Rocket](https://github.com/rwf2/Rocket/pull/2758) which use rustls have to support either ring or aws-lc-rs, as they need to use rustls::crypto::ring or rustls::crypto::aws_lc_rs APIs.

**Describe the solution you'd like**
Add new module rustls::crypto::generic with the following APIs (or more):

- rustls::crypto::generic::default_provider()
- rustls::crypto::generic::Ticketer::new()
- rustls::crypto::generic::cipher_suite
- rustls::crypto::generic::sign::any_supported_type

These api would have cfg inside that chose either aws_lc_rs, ring, or fail to compile if none of the features are enabled.

This way rocket can use these apis and can let the feature be enabled by the end user of the crate.

I also suggest when aws-lc-rs is enabled it take priority over ring. So crates like Rocket which are more comfortable with ring build requirement can enable ring by default. However, the end user of the crate can enable aws_lc_rs feature on rustls to override this.

**Describe alternatives you've considered**
Adding features on Rocket to choose between ring and aws_lc_rs but I feel that is unnecessarily complex.

I am not sure this is a good idea but it may be helpful.

**Comment by djc** [comment]
I think the intention was that library crates should use https://docs.rs/rustls/latest/rustls/crypto/struct.CryptoProvider.html#method.get_default. Does that fit Rocket's needs?
