### ISSUE TITLE
Option to Relax SNI Host Name Validation for IP Addresses

### ISSUE THREAD

**Issue by alexliesenfeld** [rustls/rustls#1878]
**Checklist**
* [x] I've searched the issue tracker for similar requests

**Is your feature request related to a problem? Please describe.**
Many HTTP clients seem to send the host IP in the [SNI host name extension](https://en.wikipedia.org/wiki/Server_Name_Indication) of the ClientHello message. This has been observed in cases where users only provide an IP address rather than a hostname for establishing a connection. At the moment, when clients send an IP address as the SNI, rustls refuses to process the ClientHello message with an `InvalidServerName` error (see [here](https://github.com/rustls/rustls/blob/074ced1fd5cbc06309d811c51c125707a7e17013/rustls/src/msgs/handshake.rs#L237)), preventing servers from serving requests for such clients. [This example project](https://gist.github.com/alexliesenfeld/1c366c8d30cff769a59cf74c6aaba9cc) demonstrates this issue with some Rust-based HTTP clients, but users observe this behavior with [other clients](https://github.com/rustls/rustls/issues/184#issuecomment-2022272735) as well. 

**Describe the solution you'd like**
Even though IP addresses are not allowed in the SNI, as per [RFC 6066](https://datatracker.ietf.org/doc/html/rfc6066#section-3) the SNI extension also seems to be optional for both sides, the client and server. Here is an excerpt highlighting this:

>   It is RECOMMENDED that clients include an extension of type
>
>    "server_name" in the client hello whenever they locate a server by a
>    supported name type.
> 
>    A server that receives a client hello containing the "server_name"
>    extension MAY use the information contained in the extension to guide
>    its selection of an appropriate certificate to return to the client,
>    and/or other aspects of security policy.  In this event, the server
>    SHALL include an extension of type "server_name" in the (extended)
>    server hello.  The "extension_data" field of this extension SHALL be
>    empty.

To be able to serve requests for as many clients as possible, it is desirable to have a possibility to relax the strictness in this regard.

At a first look, one option could be to let the [`cert_resolver`](https://docs.rs/rustls/latest/rustls/server/trait.ResolvesServerCert.html) handle this case (currently configured via [`ServerConfig`](https://docs.rs/rustls/latest/rustls/server/struct.ServerConfig.html)), since the SNI extension seems to be primarily concerned with certificate resolution. This way, users could opt-out of the strict host name validation and use their own validation logic.

Another idea from https://github.com/rustls/rustls/issues/184 was to simply ignore IP addresses as SNI. 

**Describe alternatives you've considered**

I did not find any alternative solutions to this as of now.

**Comment by ctz** [comment]
Thanks for the reproducer. For me all the test cases work as expected, in the sense that none of them demonstrate a client that is rejected by rustls:

```
running 3 tests
thread 'tests::test_with_isahc' panicked at src/lib.rs:14:9:
we will not get here
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tests::test_with_isahc' panicked at src/lib.rs:55:59:
called `Result::unwrap()` on an `Err` value: Error { kind: ConnectionFailed, context: None, source: Some(Error { description: "SSL connect error", code: 35, extra: None }), source_type: Some("curl::error::Error"), local_addr: Some(127.0.0.1:43942), remote_addr: Some(127.0.0.1:65432) }
test tests::test_with_isahc - should panic ... ok
thread 'tests::test_with_reqwest' panicked at src/lib.rs:14:9:
we will not get here
thread 'tests::test_with_curl' panicked at src/lib.rs:14:9:
we will not get here
thread 'tokio-runtime-worker' panicked at src/lib.rs:70:28:
called `Result::unwrap()` on an `Err` value: Error { description: "SSL connect error", code: 35, extra: Some("OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:65433 ") }
thread 'tests::test_with_reqwest' panicked at src/lib.rs:42:55:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(65431), path: "/", query: None, fragment: None }, source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(5), cause: None }, X509VerifyResult { code: 0, error: "ok" })) }
thread 'tests::test_with_curl' panicked at src/lib.rs:71:18:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(4), ...)
test tests::test_with_reqwest - should panic ... FAILED
test tests::test_with_curl - should panic ... ok

failures:

---- tests::test_with_reqwest stdout ----
note: panic did not contain expected string
      panic message: `"called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: \"https\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(65431), path: \"/\", query: None, fragment: None }, source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(5), cause: None }, X509VerifyResult { code: 0, error: \"ok\" })) }"`,
 expected substring: `"decoding error"`

failures:
    tests::test_with_reqwest

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.07s
```

(I think the `we will not get here` panics all point to the rustls-based server seeing a valid clienthello, and this panic happens after that.)

This was on Debian 12.5.

It is possible that other platforms have a different behaviour: certainly curl+openssl and reqwest+openssl are known to work correctly nowadays (specifically, curl and the openssl rust crate successfully avoid the defects in this area in openssl).

**Comment by alexliesenfeld** [comment]
That's interesting @ctz. I'm on macOS Sonoma (14.0), toolchain stable-aarch64-apple-darwin - rustc 1.77.0 (aedd173a2 2024-03-17), and I get this instead:

```
Finished test [unoptimized + debuginfo] target(s) in 0.05s
Running unittests src/lib.rs (target/debug/deps/rustls_sni-c672cb6c9b6a3263)
thread 'tests::test_with_curl' panicked at src/lib.rs:27:43:
called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: InvalidMessage(InvalidServerName) }
stack backtrace:
  ...
thread 'tokio-runtime-worker' panicked at src/lib.rs:71:28:
called `Result::unwrap()` on an `Err` value: Error { description: "SSL connect error", code: 35, extra: Some("Decode failed") }
stack backtrace:
 ...
thread 'tests::test_with_curl' panicked at src/lib.rs:72:18:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(4), ...)
stack backtrace:
 ...
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'tests::test_with_isahc' panicked at src/lib.rs:27:43:
called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: InvalidMessage(InvalidServerName) }
stack backtrace:
  ...
thread 'tests::test_with_isahc' panicked at src/lib.rs:56:59:
called `Result::unwrap()` on an `Err` value: Error { kind: ConnectionFailed, context: None, source: Some(Error { description: "SSL connect error", code: 35, extra: None }), source_type: Some("curl::error::Error"), local_addr: Some(127.0.0.1:49684), remote_addr: Some(127.0.0.1:65432) }
stack backtrace:
 ...
thread 'tests::test_with_reqwest' panicked at src/lib.rs:27:43:
called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: InvalidMessage(InvalidServerName) }
stack backtrace:
 ...
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'tests::test_with_reqwest' panicked at src/lib.rs:43:55:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(65431), path: "/", query: None, fragment: None }, source: hyper::Error(Connect, Error { code: -9833, message: "decoding error" }) }
stack backtrace:
 ...
```

**Comment by djc** [comment]
To unpack this a little bit:

* isahc (no commits in the last 2 years) is effectively a curl wrapper, so we should expect it to have the same results
* I think curl will use OpenSSL as the TLS stack in the default configuration?
* On my macOS Sonoma machine, the system curl identifies as `libcurl/8.4.0 (SecureTransport) LibreSSL/3.3.6`
* reqwest defaults to native-tls, which I think would pick OpenSSL on Linux and SecureTransport on macOS

**Comment by ctz** [comment]
> We previously reported that to Apple in 2018

This was #203

**Comment by ctz** [comment]
> * On my macOS Sonoma machine, the system curl identifies as `libcurl/8.4.0 (SecureTransport) LibreSSL/3.3.6`

So LibreSSL 3.6.1 introduced [a change](https://github.com/libressl/openbsd/commit/e7fdd9de6f9def3087be965eae19cc67a8da47dd) that correctly avoids sending an invalid SNI extension; Apple seems to be significantly behind the upstream LibreSSL though. @chris-wood any thoughts?

**Comment by ctz** [comment]
This was done in #1881
