### ISSUE TITLE
The support for "mipsel-unknown-linux-musl" has failed.

### ISSUE THREAD

**Issue by n454149301** [rustls/rustls#1883]
**Checklist**
* [ ] I've searched the issue tracker for similar bugs.

**Describe the bug**
Compiling any simple example works fine if I use: cargo build -r. However, when I use: cross build -Z build-std=std --target mipsel-unknown-linux-musl -r, the following error occurs:

```
error: failed to run custom build command for `aws-lc-sys v0.13.3`

Caused by:
  process didn't exit successfully: `/target/release/build/aws-lc-sys-465cdaecc731b9d6/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=use_bindgen_generated

  --- stderr
  thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.13.3/builder/main.rs:286:5:
  aws-lc-sys build failed. Please enable the 'bindgen' feature on aws-lc-rs or aws-lc-sys
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**To Reproduce**

**Applicable Version(s)**
[dependencies]
axum = { version = "0.7.5", features = ["ws"] }
futures-util = "0.3.30"
hyper = { version = "1.2.0", features = ["full"] }
hyper-util = { version = "0.1.3", features = ["http1", "http2"] }
rustls-pemfile = "2.1.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["full"] }
tokio-rustls = "0.26.0"
tower-service = "0.3.2"
rustls="0.23.4"

**Expected behavior**

**Additional context**

**Comment by n454149301** [comment]
The last version that could be compiled successfully is: rustls@0.21.10.

Starting from the version "rustls@0.22.0", all new versions fail to compile.

**Comment by djc** [comment]
You'll need to use `ring` crypto provider and make sure to avoid the aws-lc-rs dependency. This can be done via appropriate tweaking of the Cargo features.
