### ISSUE TITLE
Linux compilation is slow and seems unable to store compilation results

### ISSUE THREAD

**Issue by aadog** [rustls/rustls#1890]
Linux compilation is slow and seems unable to store compilation results

**Comment by djc** [comment]
Did you miss the contents of the bug report template? It asks for steps to reproduce and a bunch of questions about your environment. As is, there isn't much we can do with your issue because it is too vague.

**Comment by ctz** [comment]
Please reopen with `cargo build --timings` outputs for:

1. the version you found compiled acceptably quickly, 
2. the version you found to be slow.

**Comment by aadog** [comment]
@ctz Thanks for your reply, compiling it on linux doesn't seem to cache the results and recompiles every time
