### ISSUE TITLE
Incompatible License 

### ISSUE THREAD

**Issue by jjnicola** [rustls/rustls#1893]
Hello, 
I found an issue with our GPL2+ license that happens to be based on a license change of one of your dependencies. One of the Rustls dependencies has changed from ISC AND (Apache-2.0 OR ISC) to ISC AND (Apache-2.0 OR ISC) AND OpenSSL. 

Since the project I am working on is GPL compatible and it has Rustls as dependency, I suppose that the indirect dependency makes Rustls incompatible with our project.

Therefore, I have some questions. Are you aware of this? Is it an issue for you, and if yes, how are you handling it ? Do you think on changing the license or the dependency? 

Thanks in advance.
Best regards.

**Comment by ctz** [comment]
We have optional dependencies on both *ring* and aws-lc-rs. Both have their roots in BoringSSL, and BoringSSL was forked from OpenSSL _before_ their license change. So the situation you are describing has existed forever in this crate, any recent SPDX metadata changes notwithstanding.

I would suggest if you have a unequivocal requirement for GPL compatibility you could opt-out of these dependencies (and use `cargo deny` to ensure that) and provide a `CryptoProvider` from elsewhere that uses only GPL-compatible dependencies. I don't have an example of such a thing that I would feel comfortable suggesting, but that's the general idea.
