### ISSUE TITLE
Rustls w/ aws-lc-rs on Windows requires NASM

### ISSUE THREAD

**Issue by Diggsey** [rustls/rustls#1913]
The entire reason half the ecosystem is using rustls rather than openssl is because it "just works" without any dependencies.

Having upgraded to the latest version, I get the following error:
> error: failed to run custom build command for `aws-lc-sys v0.15.0`
> ...
> Missing dependency: nasm

It's very frustrating that `aws-lc` has been added to the default dependency list as many intermediate dependencies forget to add "default-features = false", making it in practice a hard dependency of rustls.

Please reconsider making `aws-lc` the default backend. The default backend should require *fewer* dependencies, not more. Any minor performance difference is a secondary concern.

**Comment by djc** [comment]
Switching back to *ring* is still pretty straightforward -- have you tried it?

**Comment by djc** [comment]
Which version of aws-lc-rs do you have in your tree? AIUI aws-lc-rs 1.7 requires fewer extra dependencies than before on the most common platforms at least.

**Comment by Diggsey** [comment]
1.7

**Comment by cpu** [comment]
> AIUI aws-lc-rs 1.7 requires fewer extra dependencies than before

Indeed, but I think there's still a ways to go for Windows in particular w.r.t the `nasm` requirement. 

Hopefully these improvements continue!

> NASM is not listed as a required dependency anywhere that I could see.

The [0.23.0](https://github.com/rustls/rustls/releases/tag/v%2F0.23.0) release notes that brought the change to aws-lc-rs as default mentions it:  "Note that this has some implications on [platform support and build-time tool requirements](https://aws.github.io/aws-lc-rs/requirements/index.html) such as cmake on all platforms and **nasm on Windows.**"

Since then the `cmake` requirement has been relaxed in many cases but `nasm` is still req'd on Windows.

**Comment by Diggsey** [comment]
Please also consider users who are installing tools via `cargo install`. Now they are expected to find this build requirement from https://aws.github.io/aws-lc-rs/requirements/, download a random ZIP file from https://www.nasm.us/pub/nasm/releasebuilds/?C=M;O=D, and then go an manually configure an environment variable to point to the installed files?

This change has a huge negative impact across the whole Rust ecosystem. Please revert to using ring, or other pure rust implementation by default.

**Comment by DaOneLuna** [comment]
> Agreed that this is a negative change, though in the meantime for my use case at least I was able to get around this with `default-features = false` - maybe this will help.

Didnt expect to run into you here haha. This also fixed it for my use case.

**Comment by Rigidity** [comment]
> > Agreed that this is a negative change, though in the meantime for my use case at least I was able to get around this with `default-features = false` - maybe this will help.
> 
> Didnt expect to run into you here haha. This also fixed it for my use case.

Small world :)

**Comment by Diggsey** [comment]
> I was able to get around this with default-features = false - maybe this will help.

Unfortunately that doesn't help when intermediate dependencies don't specify this which is the case for eg. `ureq` and others. (Unsurprising since this crate didn't used to have default features afaik)

**Comment by algesten** [comment]
FWIW, I don't really know how to deal [with this situation in ureq](https://github.com/algesten/ureq/issues/751). I absolutely need to support windows users and rustls has so far been brilliant in how little dependencies and complexity it introduced. 

In ureq we also want as few dependencies as possible, however `rustls-webpki` still seem to use `ring` as its default provider, which means I either need to override the default feature flags or accept that I get both `ring` and `aws-lc-rs` as deps. I can obviously solve that with feature flags, but as a library author, I prefer not to do that, since every feature flag I require on ureq's deps takes away some choice for the user of ureq.

For now I hope I can just stall on upgrading rustls until the dust settles, but so far life seemed simpler when it was just ring…

**Comment by djc** [comment]
Why do you have a direct dependency on rustls-webpki? In either case, it seems like you can simply use `default-features = false` for your rustls-webpki dependency. For that matter, you could declare both your rustls and rustls-webpki dependency with `default-features = false` and then add back the crypto provider you prefer (sounds like it might be *ring*).

**Comment by algesten** [comment]
> Why do you have a direct dependency on rustls-webpki?

LOL. I don't know! Just realize it seems to work without it 🤦 … Thanks! 

> For that matter, you could declare both your rustls and rustls-webpki dependency with default-features = false and then add back the crypto provider you prefer (sounds like it might be ring).

Sure, I can do that, but that also means I take a stand for/against some default choices rustls has made for me, and you are the experts on this. From my perspective FIPS is an enterprise compliance requirement – the kind of entities that can afford to spend more time tinkering with their builds.

I understand aws-lc-rs is required for FIPS, and there is a small performance gain, but are there more reasons rustls decided to change the default? Maybe there's a discussion somewhere I missed?

**Comment by djc** [comment]
> I understand aws-lc-rs is required for FIPS, and there is a small performance gain, but are there more reasons rustls decided to change the default? Maybe there's a discussion somewhere I missed?

We have found aws-lc-rs has a number of features that *ring* does not support, and upstream is generally more responsive/moving faster. Things like P-521 support, RSA keygen support, better support for SEC-1 keys, support for the PQC KYBER key exchange mechanism, support for HPKE (which is a prerequisite for Encrypted ClientHello support) are now supported in aws-lc-rs but not in *ring* (even though there have been long-standing feature requests). We've also seen fairly rapid support in the build system requirement from aws-lc-rs (and note that *ring* effectively ships pre-built binary code for Windows to avoid these issues -- which has other problems).

Due to this issue we've been having a discussion about how to better communicate the advantages of the aws-lc-rs choice, and this is something we expect to work on soon, but please assume the choice is well-motivated.

That said, the more cumbersome build process is a downside for the time being. IMO for your minimal-dependencies use case it is fine to stick with *ring* for the time being -- and I don't think you're the only library making that choice.

**Comment by algesten** [comment]
@djc thank you for elaborating!

> but please assume the choice is well-motivated.

I apologize if I came across as questioning your motives. That was not my intent.

> That said, the more cumbersome build process is a downside for the time being. IMO for your minimal-dependencies use case it is fine to stick with ring for the time being -- and I don't think you're the only library making that choice.

Sounds good! I'll make a PR to that today. Thank you!

**Comment by Diggsey** [comment]
> We have found aws-lc-rs has a number of features that ring does not support

That's great as a motivation for users to enable the `aws-lc` feature in order to get access to the new functionality, but IMO it's not a rationale for making `aws-lc` required by default.

> We've also seen fairly rapid support in the build system requirement from aws-lc-rs

That's great, and when the build system requirements are as low as ring, then it might make sense to switch.

>  (and note that ring effectively ships pre-built binary code for Windows to avoid these issues -- which has other problems).

It's fairly normal to ship binary code on Windows. The source can still be reviewed and the build can be reproduced, so I don't see a huge difference from a security perspective (and most people aren't reviewing the source code before running `cargo install` anyway...)

**Comment by cpu** [comment]
> but IMO it's not a rationale for making aws-lc required by default.

Diggsey: It sounds like you're prioritizing minimal build time requirements as the most important factor in a cryptography provider dependency. That's reasonable and we hear you, but I don't think you've made a case for why that should be the default prioritization for everyone. 

As @djc outlined there are several concurrent factors that make aws-lc-rs appealing as a default even though for Windows users it requires an additional build dependency. The fact that several classes of users all have their own justifiable prioritizations (build reqs, performance, post-quantum ciphersuites, FIPS mode, national ciphersuites, a pure Rust impl (note: not ring), etc) is why the backend is now selectable. There's no one provider that could make everyone happy.

I think it's expected there will be some bumps in the road short-term that make it harder to opt-in to using `*ring*` and not `aws-lc-rs` than it should be, such as with `ureq`, but these are problems that can and are being solved.  I think the best path forward is to make that choice ergonomic.  Concurrently the challenges from build tool requirements will continue to get better with time.

> since this crate didn't used to have default features afaik

This crate has had default features for a very long time. At least back to 0.10.0.

**Comment by Diggsey** [comment]
> It sounds like you're prioritizing minimal build time requirements as the most important factor in a cryptography provider dependency. That's reasonable and we hear you, but I don't think you've made a case for why that should be the default prioritization for everyone.

Rustls is not just any cryptography provider - we already had the openssl crate which worked just fine. What made rustls special was precisely the minimal build dependencies.

> but I don't think you've made a case for why that should be the default prioritization for everyone.

It seems pretty clear to me: opting into aws-lc is easy, but opting out is essentially impossible when it's provided under a default feature. Therefore the question is not whether to prioritise build requirements vs say performance, but whether to prioritize giving people a choice vs not giving them the choice.

**Comment by djc** [comment]
> > It sounds like you're prioritizing minimal build time requirements as the most important factor in a cryptography provider dependency. That's reasonable and we hear you, but I don't think you've made a case for why that should be the default prioritization for everyone.
> 
> Rustls is not just any cryptography provider - we already had the openssl crate which worked just fine. What made rustls special was precisely the minimal build dependencies.

I hardly think that's the only thing (or even necessarily most important) thing that makes rustls an attractive option.

> > but I don't think you've made a case for why that should be the default prioritization for everyone.
> 
> It seems pretty clear to me: opting into aws-lc is easy, but opting out is essentially impossible when it's provided under a default feature. Therefore the question is not whether to prioritise build requirements vs say performance, but whether to prioritize giving people a choice vs not giving them the choice.

It's not "essentially impossible" -- get the intermediate libraries to fix their feature usage, and/or advocate for/contribute to [Cargo efforts](https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618) to improve general handling of the feature situation.

**Comment by Diggsey** [comment]
> I hardly think that's the only thing (or even necessarily most important) thing that makes rustls an attractive option.

Have you surveyed your users? I promise you, the only thing most people care about is having a TLS library that just works.

To quote someone else, who phrases it better than I can:

> I always thought Rustls ambition was to provide a "pure Rust" TLS implementation. The original README said "Rustls is a modern TLS library written in Rust". However, I clearly read things into that which was never stated.
>
> With ring, it was of course never pure (it's a mix of asm/C/Rust) and from my limited understanding of crypto, many of the optimizations required for modern crypto primitives are hand written assembly, which will take a long time, if ever, to replace with any Rust equivalent (or at least the asm! macro). However I used to believe Rustls ambition was to aim towards a pure Rust TLS library.

This is the way a lot of people feel, myself included, and the way rustls has been portrayed.

Also 
> It's not "essentially impossible" -- get the intermediate libraries to fix their feature usage, and/or advocate for/contribute to [Cargo efforts](https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618) to improve general handling of the feature situation.

As a user, those things are not in my control. hence "essentially impossible". Sure, I can go and fork every intermediate crate to fix the feature usage - is that practical? No.

**Comment by cpu** [comment]
If your goal is a true "pure Rust" TLS implementation top-to-bottom then it seems as though the recent work has improved Rustls for you. Unlike before when the cryptography provider was not a choice you can now build rustls without `aws-lc-rs` _or_ `*ring*` so that a cryptography provider like [rustls-rustcrypto](https://github.com/RustCrypto/rustls-rustcrypto) can be used. Unlike `*ring*`, `aws-lc-rs`, BoringSSL, or any other OpenSSL derived cryptography libraries (_they all share the same common heredity_) it includes **only** Rust code. A world where *ring* is the implied default does not meet the goal of pure Rust and so you will still require intermediate dependencies adjust to the "no default" world so you can slot in your pure Rust choice. I continue to believe helping those intermediate deps. make this ergonomic is the best solution both for you, and our other users.

In general it seems like this is becoming an unproductive conversation. I would characterize your attitude as rather combative from the outset and the goal posts keep being moved as we explain our decisions. It's clear you're unhappy with the decision and you've made the reasons why understood. Perhaps we should call that a conclusion and let this thread lie unless there are new perspectives to weigh?

**Comment by gimbling-away** [comment]
Why use `nasm` specifically? Major compiler toolchains already include an assembler (gcc, clang, msvc with masm64) why can't that be used to prevent an external dependency?

**Comment by djc** [comment]
@gimbling-away this is a question for the aws-lc-rs folks, please follow-up with them upstream.

**Comment by Diggsey** [comment]
And so it begins... https://corteximplant.com/@0x0/112331561273951072

**Comment by izolyomi** [comment]
I've also just hit this issue trying to `cargo install` tools depending on rustls. I fully agree that requiring extra binaries installed for a default build is bad choice in general.

**Comment by clairewood** [comment]
Here's what fixed the nasm errors for me, in case this helps anyone else:

```
[dependencies]
ring = "0.17.8"
rustls = { version = "0.22.4", default-features = false }
webpki = "0.22.4"
webpki-roots = "0.26.1"
```

**Comment by goenning** [comment]
@clairewood I think you fixed it because on version 0.22.4 aws-lc is not used

I have this on my cargo.toml:
```
rustls = { version = "=0.23.5", default-features = false, features = ["ring"]}
```

However, `aws-lc-rs` is still present on the lock file.

```
[[package]]
name = "rustls"
version = "0.23.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "afabcee0551bd1aa3e18e5adbf2c0544722014b899adb31bd186ec638d3da97e"
dependencies = [
 "aws-lc-rs",
 "log",
 "once_cell",
 "ring",
 "rustls-pki-types",
 "rustls-webpki",
 "subtle",
 "zeroize",
]
```

Anyone know why?

**Comment by djc** [comment]
> Anyone know why?

Other crates in your dependency graph might be pulling in rustls with default features? Or maybe https://github.com/rust-lang/cargo/issues/10801?

**Comment by justsmth** [comment]
This is an issue that is being discussed, but we want to be cautious.

Ring seems to get around this requirement by pregenerating/embedding the NASM object files into the crate:
```
❯ cargo download ring > ring.tar.gz
INFO: cargo-download v0.1.2
INFO: Latest version of crate ring=* is 0.17.8
INFO: Crate `ring==0.17.8` downloaded successfully

❯ tar ztf ring.tar.gz | egrep '\.o$'
ring-0.17.8/pregenerated/aesni-gcm-x86_64-nasm.o
ring-0.17.8/pregenerated/aesni-x86-win32n.o
ring-0.17.8/pregenerated/aesni-x86_64-nasm.o
ring-0.17.8/pregenerated/chacha-x86-win32n.o
ring-0.17.8/pregenerated/chacha-x86_64-nasm.o
ring-0.17.8/pregenerated/chacha20_poly1305_x86_64-nasm.o
ring-0.17.8/pregenerated/ghash-x86-win32n.o
ring-0.17.8/pregenerated/ghash-x86_64-nasm.o
ring-0.17.8/pregenerated/p256-x86_64-asm-nasm.o
ring-0.17.8/pregenerated/sha256-x86_64-nasm.o
ring-0.17.8/pregenerated/sha512-x86_64-nasm.o
ring-0.17.8/pregenerated/vpaes-x86-win32n.o
ring-0.17.8/pregenerated/vpaes-x86_64-nasm.o
ring-0.17.8/pregenerated/x86-mont-win32n.o
ring-0.17.8/pregenerated/x86_64-mont-nasm.o
ring-0.17.8/pregenerated/x86_64-mont5-nasm.o
```

**Comment by decorahensisire** [comment]
Yeah.  Ok well I'm going to stick with older versions till someone decides to make a rustls that's actually rustls.  If I had known that in 2024 I'd still be running into issues building tls dependencies I'd have been a carpenter.

**Comment by narodnik** [comment]
I have a sub-crate which uses rustls and specifies aws-lc-rs. I cannot get it to build on android.

**Comment by cpu** [comment]
@narodnik Since your problem is unrelated to Windows/NASM I think it deserves a separate discussion. Please open a new issue, filling out the issue template with as much information as you have. We would need many more details than you've provided in order to help.

**Comment by cpu** [comment]
Folks following this issue may be interested in providing feedback on this upstream PR that offers a route to using pre-generated assembly artifacts for `aws-lc-rs` on Windows, similar to how `*ring*` avoids a `nasm` build-time dependency: https://github.com/aws/aws-lc-rs/pull/491

**Comment by praveenperera** [comment]
`aws-lc` does not work on iOS and Android, so anyone making packages that will be used in mobile apps needs, to update the deps all the way up the tree

- https://github.com/bitcoindevkit/rust-electrum-client/pull/135
  - https://github.com/bitcoindevkit/bdk/commit/74b24d3d1000b3a50101466b92cf7ef751a9c543

What was the reasoning of changing the default that was working fine to something that is LESS compatible?

**Comment by ctz** [comment]
> What was the reasoning of changing the default that was working fine to something that is LESS compatible?

Performance, maintainability, support for future features. I think those were covered above, but happy to restate them for your benefit.

**Comment by djc** [comment]
Note that [aws-lc-rs 1.9.0](https://github.com/aws/aws-lc-rs/releases/tag/v1.9.0) was released 3 days ago, which includes support for [using prebuilt NASM objects](https://github.com/aws/aws-lc-rs/blob/main/aws-lc-rs/README.md#use-of-prebuilt-nasm-objects).

**Comment by discord9** [comment]
I need to switch to ring, and do not compile `aws-lc-sys`. And I have a large numbers of intermediate dependencies crate(luckily they all seem to use default features of `rustls`).
  Is it ok to fork `rustls`(and maybe `tokio-rustls` too, is there more crates that default to `aws-lc-sys` under `rustls` org?) and change it to default to use `ring`(Will it cause any unforeseeable problems)? I need to be able to compile on older version of `glibc`, but it seems `aws-lc-sys`'s [fix](https://github.com/aws/aws-lc-rs/pull/526) on that havn't being release and it's CI is also failing so will switch later when they are stabilized a bit more.

**Comment by djc** [comment]
> The reason here is that I need to be able to compile with older version of `gcc`, but it seems `aws-lc-sys`'s [fix](https://github.com/aws/aws-lc-rs/pull/526) on that haven't being release and it's CI is also failing so wouldn't want to switch until they are stabilized a bit more or release that fix.

I'd suggest asking for a speedy release, the aws-lc-rs folks are usually pretty responsive.

(Also I don't think this post is really on-topic for this issue.)

**Comment by discord9** [comment]
> > The reason here is that I need to be able to compile with older version of `gcc`, but it seems `aws-lc-sys`'s [fix](https://github.com/aws/aws-lc-rs/pull/526) on that haven't being release and it's CI is also failing so wouldn't want to switch until they are stabilized a bit more or release that fix.
> 
> I'd suggest asking for a speedy release, the aws-lc-rs folks are usually pretty responsive.
> 
> (Also I don't think this post is really on-topic for this issue.)

Thanks for reply, may I open a new issue in rustls for adding instruction to changing default to `ring` if have to for all intermediate dependencies(Maybe just one sentence in readme?)? The problem is that I also have to build for various platform and currently `aws-lc-sys`'s issue list already show 8 unresolved building problem and I fear I might have to deal with them again

**Comment by ctz** [comment]
AIUI GCC 8 is now thoroughly past end of support, as is (I think) any OS that shipped it as the default host compiler. Would be interested in the reason you are stuck on it (mainly so I can understand how many users would have the same problem).

**Comment by discord9** [comment]
> AIUI GCC 8 is now thoroughly past end of support, as is (I think) any OS that shipped it as the default host compiler. Would be interested in the reason you are stuck on it (mainly so I can understand how many users would have the same problem).

Yes I understand that many of such os is out of support, but some of our end users still run CentOS 7.... So we have to support them, I understand that is not ideal, and are pushing them to upgrade whenever possible. But for simplistic sake, we are not cross building but directly building in a centos 7 image(Now that encounter those problem might require us to rethink supporting old version or consider cross compile for older(and possibly out of support) glibc version

**Comment by Diggsey** [comment]
@discord9 You're not the first person to have this problem. Unfortunately the rustls team is not receptive to anything that allows aws-lc to be disabled. I can only assume AWS are paying them.

I have a fork of rustls which removes this https://github.com/Diggsey/rustls

**Comment by discord9** [comment]
> > Thanks for reply, may I open a new issue in rustls for adding instruction to changing default to `ring` if have to for all intermediate dependencies(Maybe just one sentence in readme?)?
> 
> I don't think that's really appropriate for our README. We strongly suggest working with your intermediate dependencies to add support for aws-lc-rs.

We have too many intermediate dependencies that depending on `rustls` and seemingly unaware of this change of default.... if given more time to allow those crate to update, this might be possible, but this change seems to be moving too fast to allow ecosystem to update it.... see this depend tree we are having by running( `cargo tree -i rustls@0.23 -e features > rustls.tree` ):
[rustls.tree.txt](https://github.com/user-attachments/files/17095342/rustls.tree.txt)
and this file have 1127 lines....
For now we can only opt to use our fork that changed default and wait until `aws-lc-sys` fixes building problem on all commom platform before switch back.
Anyway thanks for clarify, this can be a long term solution, but would certainly take some time

**Comment by djc** [comment]
The other long-term solution is to have global feature support in Cargo, see https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618.

**Comment by discord9** [comment]
> The other long-term solution is to have global feature support in Cargo, see https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618.

Thanks! This RFC do sound interesting, we surely lack a more intricate way to control those features, and no unification do sound nice, I'm just glad patch depends still works as a temporal solution, would like to switch once all those building problem is fixed

**Comment by discord9** [comment]
> The mentioned RFC will take quite a bit of time before it ends up merged (if it ends up merged?).
> 
> `aws-lc-sys`fails on MacOS as well (on the Apple Silicon hardware).
> 
> An addition to README that explains how to switch away from `aws-lc` is necessary.
> 
> P.S. I will explore the`rustls` fork mentioned above, because this team does not seem to be hearing the complaints of the users.

FYI I just fork and change default which seems working?
https://github.com/GreptimeTeam/tokio-rustls
https://github.com/GreptimeTeam/hyper-rustls
https://github.com/GreptimeTeam/rustls

**Comment by justsmth** [comment]
> aws-lc-sys fails on MacOS as well (on the Apple Silicon hardware).

This is interesting. We're developing `aws-lc-rs` and `aws-lc-sys` using Mac's w/ Apple Silicon hardware (and also w/ x86 hardware), and we're not aware of any build issues for this platform.

If you you can provide information on how to reproduce these failures, please [let us know](https://github.com/aws/aws-lc-rs/issues/new/choose)! This is an important platform for us.

**Comment by justsmth** [comment]
> ... it seems aws-lc-sys's https://github.com/aws/aws-lc-rs/pull/526 on that haven't being release.

@discord9 -- I apologize for this. We had to partially revert our use of `-ffile-prefix-map=` due to it causing building failures when using older compilers. For most platforms, this only affects build environments that set `AWS_LC_SYS_CMAKE_BUILDER=1` to force our build to use CMake. Our default "cc" builder [still uses it](https://github.com/aws/aws-lc-rs/blob/main/aws-lc-sys/builder/cc_builder.rs#L133) for optimized builds (if the compiler supports it).

We're prioritizing getting this corrected soon.

**Comment by praveenperera** [comment]
> > What was the reasoning of changing the default that was working fine to something that is LESS compatible?
> 
> Performance, maintainability, support for future features. I think those were covered above, but happy to restate them for your benefit.

Maybe consider taking feeeback from everyone having trouble in this thread. 

None of that matters if it doesn’t work, and breaks previously working builds.

**Comment by justsmth** [comment]
> aws-lc does not work on iOS and Android, so anyone making packages that will be used in mobile apps needs to update the deps all the way down the tree

Oh, sorry I didn't see this earlier.  

AFAIK, the `aws-lc-sys` build supports Android platforms. Our [CI actively tests several Android targets](https://github.com/aws/aws-lc-rs/blob/main/.github/workflows/cross.yml#L29) and I know of several teams that use aws-lc-rs for Android products.

Please [let us know](https://github.com/aws/aws-lc-rs/issues/new/choose) about any build issues you have for Android. We'd be happy to get them fixed.

**Comment by praveenperera** [comment]
> > aws-lc does not work on iOS and Android, so anyone making packages that will be used in mobile apps needs to update the deps all the way down the tree
> 
> @praveenperera, sorry I didn't see this earlier.
> 
> AFAIK, the `aws-lc-sys` build supports Android platforms. Our [CI actively tests several Android targets](https://github.com/aws/aws-lc-rs/blob/main/.github/workflows/cross.yml#L29) and I know of several teams that use aws-lc-rs for Android products.
> 
> Please [let us know](https://github.com/aws/aws-lc-rs/issues/new/choose) about any build issues you have for Android. We'd be happy to get them fixed.

There’s no point in me trying to get it working just for android builds when it doesn’t for iOS.

It’s fine that it doesn’t, but rustls should never have switched the DEFAULT to it when it supports LESS platforms than what was already working before.

That decision has confused many people.

**Comment by justsmth** [comment]
> .. it doesn’t for iOS.

Our [CI also test building](https://github.com/aws/aws-lc-rs/blob/main/.github/workflows/cross.yml#L106) for iOS. 😊

Finding the iPhone simulator on the GitHub runners is a little messy.  We have the [script for the test here](https://github.com/aws/aws-lc-rs/blob/main/scripts/ci/ios-simulator-runner.sh).

**Comment by djc** [comment]
I'm locking this thread. If you have issues with building aws-lc-rs for your use case, consider filing an issue against their repo -- they tend to be pretty responsive, and have already solved many issues (including the original complaint from this thread, that building it on Windows requires NASM to be installed).

If you have new arguments/considerations, please file a new issue. The rustls team is aware that this has been a controversial change, and for the next semver-breaking release we will definitely consider other solutions. However, the cost of shipping another semver-incompatible change is substantial given that it means the entire ecosystem then has to upgrade again. One incremental improvement which we will definitely consider might be to avoid enabling any crypto provider implementations as part of the `default` feature set. Alternatively we might figure out new ways of splitting the crate or redefining how the global crypto provider works (ideally with the [help of Cargo](https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618)).

In the meantime, it does seem reasonable to also report your issues to the intermediate dependencies that aren't offering you the choice of crypto provider that you need.
