### ISSUE TITLE
Making impl ClientHelloPayload public ?

### ISSUE THREAD

**Issue by dawid-nowak** [rustls/rustls#1915]
In our application we would like to make a decision based on contents of SNI in ClientHelloPayload without necessary affecting the how rustls flow. So we peek some bytes from the stream and initialize Reader and then use Reader to produce ClientHelloPayload. Everything works as expected and it is great that these two are part of the public API. Unfortunately, getting the SNI extension is not as straightforward since those APIs are not part of public API. 

If would be also very helpful if other methods on ClientHelloPayload such as sni_extension, sni_extension, find_extension were added to public API. It seems that they were but now they visibility is only within the crate. 

So the question really is if it makes sense to make ```impl ClientHelloPublic``` part of the public API from rustls perspective?

**Comment by cpu** [comment]
:wave: Hi there,

> In our application we would like to make a decision based on contents of SNI in ClientHelloPayload

Have you looked at using the `Acceptor` API? The [Accepted::client_hello()](https://docs.rs/rustls/latest/rustls/server/struct.Accepted.html#method.client_hello) fn's return type offers a [server_name](https://docs.rs/rustls/latest/rustls/server/struct.ClientHello.html#method.server_name) fn for accesing the SNI value to make a decision. 

If you look in the issue tracker I believe there have been previous discussions about exporting internal message types and this hasn't been something the project has been keen to support. In this case I'm not sure it's necessary at all given the `Acceptor` API.

**Comment by dawid-nowak** [comment]
Thanks for a quick response. I think our use case is slightly different. 
I would like to check if the incoming TCP stream is TLS. If it is TLS then I can pass the stream to rustls for proper processing. If the stream is not then we would like to process it as TCP. 

The main problem with using the Acceptor (I am actually using [LazyConfigAcceptor](https://docs.rs/tokio-rustls/latest/tokio_rustls/struct.LazyConfigAcceptor.html) ) is that we can't get back the consumed bytes. 

That's why I resolved to [peeking](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.peek) bytes from TCP stream and then deserializing ```ClientHelloPayload``` myself. In this respect if I can successfully deserialize ClientHelloPayload and get SNI, I can pass the stream to rustls acceptor and if I can't then I can treat it as a TCP stream.

**Comment by djc** [comment]
We've since added a trait for this in #269, so I'm going to consider this solved.

**Comment by djc** [comment]
I also just submitted #1916, maybe it could help?

**Comment by djc** [comment]
Perhaps we could also add an `into_bytes()` method on `Acceptor` that takes out the receive buffer, if that helps.

**Comment by dawid-nowak** [comment]
If I understand it correctly with ```into_bytes()```,  I would still need to deserialize ```ClientHelloPayload```? 
I get that my use case is pretty awkward :) but if you wanted to make changes to ```Acceptor```` then I think you would need to expose some extra methods on the ```Acceptor``` to allow the application to peek at client hello before calling ```accept``` and/or to get back the full tcp stream if the information in the client hello doesn't match the needs.

**Comment by djc** [comment]
Okay, I see how that doesn't work.

So maybe we should move the `deframer_buffer.buf` into `AcceptedAlert`, to allow you to recover the received bytes from there? Then if it fails to parse a `ClientHello` you can get the bytes and turn them into a plaintext connection?

**Comment by dawid-nowak** [comment]
That could work... Still think that making ```impl ClientHelloPublic``` would be easier and less error prone.  Could you help me understand the rationale here ?

**Comment by djc** [comment]
Why do you think it would be easier and less error prone?

**Comment by dawid-nowak** [comment]
Sure :) just for the conversations sake 
I look at it from perspective of a user who is outside of the normal path and is happy to use low level building blocks provided to create something different. 

```ClientHelloPayload``` is public and also ```Reader``` is public so these two basic blocks are already available to the end user to start tinkering. The methods to find extensions are there but hidden. And since these methods are used internally, they are tested and verified. Exposing those methods is probably not a problem. 

Yes, the application has a dependency on rustls low level building blocks which could change but at the same time it can trust that these blocks are sound. 

Additionally, the normal flow of rustls is not affected. There are no changes to the APIs so the existing applications will work as normal. 

That would be my thinking but I am happy to go with whichever way.

**Comment by djc** [comment]
`Reader` and `ClientHelloPayload` are only public (AFAICT) via `internals`:

> Internal classes that are used in integration tests. The contents of this section DO NOT form part of the stable interface.

**Comment by cpu** [comment]
I left a comment with [a WIP branch](https://github.com/rustls/rustls/compare/main...cpu:rustls:cpu-acceptor-plaintext?expand=1) on https://github.com/rustls/rustls/pull/1916 but I think it makes more sense to discuss here.

Using the acceptor API and the fns on an accepted `rustls::server::ClientHello` seems like it meets the need of the TLS side (mainly, dispatch by SNI/ALPN) without any new API surface/exports or cumbersome external deserialization. 

I think what's lacking is a way to accept a plaintext connection in some cases. To solve that, what if instead of returning the deframer buffer and having the caller need to figure out if its TLS we do the reverse and have the acceptor return the buffer when it has already decided it isn't TLS as part of a returned error? 

I think that strikes a good balance. Existing TLS focused users can continue exactly as they do now, treating accept errors of any kind as fatal, sending an alert and closing. Users that want to dispatch non-TLS data can match on the new error type and unpack the data that Rustls couldn't deframe as the expected first TLS message. Does that seem workable?

**Comment by djc** [comment]
Your WIP branch makes sense to me, though I'm not sure I understand the need for `OtherError(Arc::new(..))` wrapping the internal error. Could it just be a boxed `Error`? I think we could stick the buffer in `AcceptedAlert` instead of in `Error`, which seems simpler if a little bit weird. Also we should maybe file an issue for a simplifying revision the next time we decide to release a semver-incompatible API.

**Comment by ctz** [comment]
> I think what's lacking is a way to accept a plaintext connection in some cases. To solve that, what if instead of exposing the deframer buffer and having the caller need to figure out if its TLS we do the reverse and have the acceptor return the buffer when it has already decided it isn't TLS as part of a returned error?

My feeling on this is: it is very clear within the first few bytes whether the conversation is TLS or not. It seems quite reasonable to have downstream code that wants to do plaintext and TLS on the same stream port to read the bytes and do the demultiplexing up-front?

**Comment by cpu** [comment]
> Could it just be a boxed Error? 

Yup! That's a better idea, not sure why I didn't think of that initially. I will change it out.

>  I think we could stick the buffer in AcceptedAlert instead of in Error, which seems simpler if a little bit weird.

I thought about this approach but it felt fairly unnatural. I'm not sure I understand what makes it simpler, except that it avoids adding a new variant to the `Error` enum that's specific to the `Acceptor` and not used elsewhere.

>  Also we should maybe file an issue for a simplifying revision the next time we decide to release a semver-incompatible API.

Yeah, that sounds like a good idea :+1: 

> It seems quite reasonable to have downstream code that wants to do plaintext and TLS on the same stream port

@ctz Sorry, I'm having trouble mapping your response to an indicator of support/dissent for the proposal I have in mind. Are you thinking the demultiplexing shouldn't be done in Rustls and we should continue to expect it to be done donwstream ala the approach used in https://github.com/rustls/tokio-rustls/issues/54#issuecomment-2027496525 ?

**Comment by ctz** [comment]
> Are you thinking the demultiplexing shouldn't be done in Rustls and we should continue to expect it to be done donwstream ala the approach used in [rustls/tokio-rustls#54 (comment)](https://github.com/rustls/tokio-rustls/issues/54#issuecomment-2027496525) ?

Yeah that's the sort of thing I had in mind.

**Comment by ctz** [comment]
wrong butan

**Comment by cpu** [comment]
> Yeah that's the sort of thing I had in mind.

OK, I won't pursue turning the WIP branch into a PR in that case :+1: 

Should this issue be closed?

**Comment by dawid-nowak** [comment]
I am happy to close this for time being. 

There seem to be two radically different approaches here and we can't get a consensus :

1. Let rustls try to figure out if the stream is the TLS stream and if it is not then return back the consumed data (or stream) so the user can re-store the stream. 
2. Let the user try to figure out if the stream is TLS and then either use rustls or not. 

I think Option 2 makes sense if for example the basic blocks to parse ClientHello are available as a public API. That would save people from having to re-invent the logic here and since those blocks are part of rustls then there is trust that the logic is good. 

Option 1 is tighlty integrated into rustls. Think to consider here is that the new API would need to be exposed via higher level adapters such as tokio-rustls.

**Comment by cpu** [comment]
> There seem to be two radically different approaches here and we can't get a consensus

From my read I think Option 3, the status quo, is where maintainer consensus is today.

Solutions outside of the crate are possible without change here (as demonstrated in the tokio-rustls issue). I think the parts required to do it reliably are already exposed under the `internals` API namespace. Option 2 feels like elevating those parts out of that namespace in order to offer explicit support & semver consideration. That's a fair request, but I don't think its likely at this time. I liked Option 1, but since that wasn't unanimous and it isn't a use case myself or the folks funding my work feel strongly about I was swayed towards inaction :-)

**Comment by kotx** [comment]
Is it possible to read the TLS handshake and also get those bytes back? For instance, a server that proxies to the SNI in the handshake, passing through the initial handshake data.

**Comment by djc** [comment]
No. The intermediate server could just store a side-buffer with all the incoming data which it could then send on wherever it wants?

**Comment by kotx** [comment]
You're right, I used an `InspectReader` from `tokio-util` and was able to preserve the incoming data when using `tokio-rustls`. Thanks!
