### ISSUE TITLE
Illegal instruction on arm-a72

### ISSUE THREAD

**Issue by Arne91** [rustls/rustls#1939]
**Checklist
* I've searched the issue tracker for similar bugs.

**Describe the bug
A bug in the `ring` crate version 0.17.8 causes a crash. We are using a Cortex-A72 on a Raspberry Pi CM4.

This behavior is tracked in the `ring' crate:
[https://github.com/briansmith/ring/issues/1858](https://github.com/briansmith/ring/issues/1858)

The solution is in a pull request (https://github.com/briansmith/ring/pull/2046)

**Comment by Arne91** [comment]
Yes, it is just informational.

**Comment by briansmith** [comment]
See https://github.com/briansmith/ring/issues/1858#issuecomment-2093675988. I think we can close this.
