### ISSUE TITLE
Add RustCrypto cryptographic backend

### ISSUE THREAD

**Issue by wiktor-k** [rustls/rustls#1945]
**Checklist**
* [x] I've searched the issue tracker for similar requests

**Is your feature request related to a problem? Please describe.**

I want to cross-compile an application that transitively links to rustls on an arm architecture and the dependency of a C/C++ aws-lc library (which, [from the description](https://github.com/aws/aws-lc) looks like an OpenSSL derivative) is making it more complicated than necessary.

**Describe the solution you'd like**
I believe using pure Rust libraries, such as the ones from the RustCrypto project would make cross-compilation easier. I'd use a RustCrypto backend even if it is implementing a small set of only modern cipher suites.

**Describe alternatives you've considered**
I've spent a great deal of time trying to cross-compile my application and it's probably possible to complete that work.

I could switch to the ring backend.

I could use rustls 0.20 as [other libraries apparently do](https://github.com/actix/actix-web/blob/master/awc/Cargo.toml#L27).

I'd still like to know if a RustCrypto-backend (or any other pure Rust cryptographic backend) is in scope of rustls (especially given that #521 is completed).

**Additional context**

```
$ cargo tree
...
├── rustls v0.23.5
│   ├── aws-lc-rs v1.7.1
│   │   ├── aws-lc-sys v0.16.0
│   │   │   ├── libc v0.2.154
│   │   │   └── paste v1.0.15 (proc-macro)
│   │   │   [build-dependencies]
│   │   │   ├── cc v1.0.97 (*)
│   │   │   ├── cmake v0.1.50
│   │   │   │   └── cc v1.0.97 (*)
│   │   │   ├── dunce v1.0.4
│   │   │   └── fs_extra v1.3.0
│   │   ├── mirai-annotations v1.12.0
│   │   ├── paste v1.0.15 (proc-macro)
│   │   └── zeroize v1.7.0
$ cargo build
...
32.61 error: failed to run custom build command for `aws-lc-sys v0.16.0`
32.61 
32.61 Caused by:
32.61   process didn't exit successfully: `/app/target/release/build/aws-lc-sys-97ad944c4aa9eab6/build-script-main` (exit status: 101)
32.61   --- stdout
32.61   cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREFIX
32.61   cargo:rerun-if-env-changed=AWS_LC_SYS_INTERNAL_BINDGEN
32.61   cargo:rerun-if-env-changed=AWS_LC_SYS_EXTERNAL_BINDGEN
32.61   cargo:rerun-if-env-changed=AWS_LC_SYS_NO_ASM
32.61   cargo:rustc-cfg=aarch64_unknown_linux_musl
32.61   cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE_BUILDER
32.61   cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC
32.61   default_for Target: 'aarch64-unknown-linux-musl'
32.61   cargo:rerun-if-env-changed=CARGO_FEATURE_SSL
32.61   default_for Target: 'aarch64-unknown-linux-musl'
32.61   cargo:rerun-if-env-changed=CARGO_FEATURE_SSL
32.61   cargo:root=/app/target/aarch64-unknown-linux-musl/release/build/aws-lc-sys-79203cf280865e80/out
32.61   default_for Target: 'aarch64-unknown-linux-musl'
32.61   OPT_LEVEL = Some("3")
32.61   TARGET = Some("aarch64-unknown-linux-musl")
32.61   HOST = Some("x86_64-unknown-linux-gnu")
32.61   cargo:rerun-if-env-changed=CC_aarch64-unknown-linux-musl
32.61   CC_aarch64-unknown-linux-musl = None
32.61   cargo:rerun-if-env-changed=CC_aarch64_unknown_linux_musl
32.61   CC_aarch64_unknown_linux_musl = Some("clang")
32.61   cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
32.61   cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
32.61   CRATE_CC_NO_DEFAULTS = None
32.61   DEBUG = Some("false")
32.61   cargo:rerun-if-env-changed=CFLAGS_aarch64-unknown-linux-musl
32.61   CFLAGS_aarch64-unknown-linux-musl = None
32.61   cargo:rerun-if-env-changed=CFLAGS_aarch64_unknown_linux_musl
32.61   CFLAGS_aarch64_unknown_linux_musl = None
32.61   cargo:rerun-if-env-changed=TARGET_CFLAGS
32.61   TARGET_CFLAGS = None
32.61   cargo:rerun-if-env-changed=CFLAGS
32.61   CFLAGS = None
32.61 
32.61   --- stderr
32.61   thread 'main' panicked at /app/vendor/aws-lc-sys/builder/cc_builder.rs:225:9:
32.61   COMPILER: "clang"ARGS: ["-O3", "-ffunction-sections", "-fdata-sections", "-fPIC", "--target=aarch64-unknown-linux-musl", "-Wall", "-Wextra", "/app/vendor/aws-lc-sys/aws-lc/tests/compiler_features_tests/memcmp_invalid_stripped_check.c", "-Wno-unused-parameter", "-o", "/app/target/aarch64-unknown-linux-musl/release/build/aws-lc-sys-79203cf280865e80/out/memcmp_invalid_stripped_check"]EXECUTED: trueERROR: In file included from /app/vendor/aws-lc-sys/aws-lc/tests/compiler_features_tests/memcmp_invalid_stripped_check.c:4:
32.61   /usr/include/stdio.h:27:10: fatal error: 'bits/libc-header-start.h' file not found
32.61   #include <bits/libc-header-start.h>
32.61            ^~~~~~~~~~~~~~~~~~~~~~~~~~
32.61   1 error generated.
32.61   OUTPUT: Failed to compile memcmp_invalid_stripped_check
```

Edit: I've found a [RustCrypto example provider](https://github.com/rustls/rustls/blob/main/provider-example/Cargo.toml) would that be something you're willing to develop further and include in the project more closely?

**Comment by djc** [comment]
I don't think the Rustls project will develop a first-party RustCrypto-based provider, but others have already started on that as part of the RustCrypto project.

For the time being I would recommend just using the first-party ring provider if that works on your platform.

**Comment by cpu** [comment]
> Describe the solution you'd like
> I believe using pure Rust libraries, such as the ones from the RustCrypto project would make cross-compilation easier. I'd use a RustCrypto backend even if it is implementing a small set of only modern cipher suites.

I think the solution you're describing exists today: https://github.com/RustCrypto/rustls-rustcrypto

It's a crate in the Rust Crypto org and I think that's the best place for it to live. The Rust Crypto developers are better positioned to support that crate than we would be in the Rustls org.

**Comment by wiktor-k** [comment]
Ok!

Thanks a lot for the comments and references. Even though I believe pure Rust backend would be better in several ways I understand the engineering time to maintain multiple backends here would be significant.

👋

**Comment by cpu** [comment]
We're certainly supportive of the goal of a pure rust cryptography backend. Much of the motivation for the cryptography provider interface work was to enable everyone to choose a backend to use based on their own prioritization weights.  

>  I understand the engineering time to maintain multiple backends here would be significant.

It's worth noting we don't meaningfully maintain the underlying cryptography provider options that are built-in either, just the surface points for where they meet Rustls. `aws-lc-rs` has a team at Amazon that maintains it and `*ring*` (also an OpenSSL derivative like `aws-lc-rs`) is maintained by Brian Smith. We'll work closely with the Rust Crypto team to help maintain an end-to-end solution that works for folks, but in all cases the Rustls team is collaborating with third parties.

**Comment by wiktor-k** [comment]
That's reassuring to hear. Thanks for the explanation! :pray:
