### ISSUE TITLE
Build rustls v0.23.5 with musl

### ISSUE THREAD

**Issue by incker** [rustls/rustls#1947]
Hello is it possible to build rustls v0.23.5 with musl?
Forward thank you!

**Comment by djc** [comment]
It should be. Have you tried it? Why not?

**Comment by incker** [comment]
All is good
`rustls` requires `aws-lc-rs`
And when I have found what requires `aws-lc-rs` my code finaly worked
https://aws.github.io/aws-lc-rs/requirements/linux.html

Thank you!
