### ISSUE TITLE
UnbufferedConnectionState

### ISSUE THREAD

**Issue by pascaldekloe** [rustls/rustls#1957]
**Checklist**
* [ ] I've searched the issue tracker for similar bugs.

**Describe the bug**

**To Reproduce**
1. Use one of the examples to connect to `....` 
2. ...
3. See error

**Applicable Version(s)**
A list of versions and platforms you've tested with.

**Expected behavior**

**Additional context**

**Comment by djc** [comment]
Please fill in the answers to the template questions.

**Comment by pascaldekloe** [comment]
Sorry @djc. I must have misclicked somewhere. This submission was accidental.
