### ISSUE TITLE
Support Encrypted ClientHellos (ECH, formerly ESNI)

### ISSUE THREAD

**Issue by candrews** [rustls/rustls#199]
Encrypted SNI is on the standards track and is already being deployed by big players.

Draft RFC: https://tools.ietf.org/html/draft-ietf-tls-esni

Championed by the EFF: https://www.eff.org/deeplinks/2018/09/esni-privacy-protecting-upgrade-https
Deployed by Cloudflare: https://blog.cloudflare.com/esni/
Cloudflare's technical details post: https://blog.cloudflare.com/encrypted-sni/
Supported by Firefox: https://blog.mozilla.org/security/2018/10/18/encrypted-sni-comes-to-firefox-nightly/
Supported by NSS: https://bugzilla.mozilla.org/show_bug.cgi?id=1495120
ESNI is specifically being pushed by Sen. Ron Wyden (D-OR): https://gizmodo.com/sen-wyden-urges-dhs-to-adopt-new-encryption-tech-to-pr-1830001179
picptls work in progress: https://github.com/h2o/picotls/issues/187
gnutls status: https://gitlab.com/gnutls/gnutls/issues/595
OpenSSL status: https://github.com/openssl/openssl/issues/7482

**Comment by ShadowJonathan** [comment]
Is this waiting for the draft to get finalised, or what's holding up progress here?

**Comment by ShadowJonathan** [comment]
Ah, i took a look at some articles and the draft itself, it has entirely pivoted away from ESNI, and towards Encrypted ClientHello, some more info on that in this blog post; https://blog.cloudflare.com/encrypted-client-hello/

**Comment by djc** [comment]
I think #508 has the latest status.

**Comment by stevefan1999-personal** [comment]
Now that Cloudflare is slowly and progressively enabling ECH to the public, we will need to think about putting this on schedule too

**Comment by darind** [comment]
+1 for this feature

**Comment by stevefan1999-personal** [comment]
> +1 for this feature

_Please refrain from using "+1", and there is a thumb up emoji exactly for emphasizing that, unless you have more points to add._

**Comment by djc** [comment]
Firefox announcement: https://blog.mozilla.org/en/products/firefox/encrypted-hello/
Cloudflare announcement: https://blog.cloudflare.com/announcing-encrypted-client-hello/

**Comment by cjpatton** [comment]
FYI, The TLS WG at IETF is hoping to close out remaining design questions for ECH. If anyone out there wanted to take a stab at implementing in rustls, now would be the ideal time to start.

**Comment by cpu** [comment]
Client-side ECH support has landed in `main` based on draft-18 :tada: We'll track server-side support separately in https://github.com/rustls/rustls/issues/1980

Thanks folks
