### ISSUE TITLE
X25519 might not be FIPS compliant for use in key exchange

### ISSUE THREAD

**Issue by RobMor** [rustls/rustls#1992]
**Checklist**
* [X] I've searched the issue tracker for similar bugs.

**Describe the bug**
_Prefacing this with the fact that I am not a compliance expert, apologies if this is not an issue._

`rustls` built with `features = ["fips"]` uses `X25519` as a `kx_group` despite `X25519` not being allowed for use with key exchange under FIPS, at least according to these discussions: https://github.com/openssl/openssl/discussions/22054, https://stackoverflow.com/questions/75875136/about-use-of-secp256r1-and-x25519

**To Reproduce**

```rust
fn main() {
    let provider = rustls::crypto::aws_lc_rs::default_provider();

    println!("FIPS enabled: {}", provider.fips());

    println!("Key exchange groups:");
    for group in provider.kx_groups {
        println!("  {:?}: {}", group, group.fips());
    }
}
```

Output:
```
FIPS enabled: true
Key exchange groups:
  X25519: true
  secp256r1: true
  secp384r1: true
```

**Applicable Version(s)**
Tested on `0.23.8`

**Expected behavior**
The provided discussion links lead me to believe that `X25519` should not be included in the list of `kx_groups` when operating under FIPS. 

**Additional context**
We noticed this when using a FIPS rustls client to talk to a non-rustls FIPS server. The server did not like the `X25519` passed in the TLS 1.3 ClientHello. It responded with a HelloRetryRequest recommending `secp256r1`. This extra round trip defeats the purpose of TLS 1.3.

For now we've worked around this by configuring our own CryptoProvider without `X25519` in the list of kx_groups.

**Comment by ctz** [comment]
Thanks for the clear report, we will fix this.
