### ISSUE TITLE
can anyone show an example on how to use ktls with rustls?

### ISSUE THREAD

**Issue by sprappcom** [rustls/rustls#2018]
as mentioned here as well. how to use?
https://github.com/rustls/rustls/issues/198

**Comment by cpu** [comment]
Perhaps the [integration test](https://github.com/bearcove/ktls/blob/main/tests/integration_test.rs) from the [`ktls` crate](https://github.com/bearcove/ktls) would be a helpful starting point.

**Comment by cpu** [comment]
I think this is sufficiently complicated that we don't want to maintain an end-to-end example in-repo. I'm going to close this issue for now but if someone disagrees we can revisit.
