### ISSUE TITLE
rustls tls full handshake is too slow when compared with openssl

### ISSUE THREAD

**Issue by fangkaiwodexigua** [rustls/rustls#2030]
**Checklist**
* [x] I've searched the issue tracker for similar bugs.

https://github.com/rustls/rustls/issues/1830
https://github.com/rustls/rustls/issues/1751

**Describe the bug**

Thanks to the excellent rustls project for providing the Rust TLS infrastructure.  We have 100 million requests per day and want to use rustls instead of openssl to do tls handshake, but the performance of rustls is so poor compared to openssl that we can't convince others to do it. I guess rustls don't support avx directive

**To Reproduce**
http echo with Connection: close
### rustls 
```
wrk -c 100 -t16 -d 10s https://www.example.org:4454 -H "Connection: close"
Running 10s test @ https://www.example.org:4454
  16 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.62ms    4.18ms  33.75ms   78.40%
    Req/Sec   458.92     45.35   600.00     68.54%
  73789 requests in 10.10s, 5.28MB read
  Socket errors: connect 0, read 73788, write 0, timeout 0
Requests/sec:   7305.70
Transfer/sec:    535.09KB
```
perf top
<img width="976" alt="image" src="https://github.com/rustls/rustls/assets/24379039/b882b68d-4cca-48f8-ac8b-3acdc824c915">

### nginx openssl avx enable. 

```
wrk -c 100 -t16 -d 10s https://www.example.org:4441 -H "Connection: close"
Running 10s test @ https://www.example.org:4441
  16 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.47ms    1.12ms  25.01ms   62.71%
    Req/Sec     1.13k    60.08     1.50k    75.50%
  181841 requests in 10.10s, 23.41MB read
Requests/sec:  18005.04
Transfer/sec:      2.32MB
```
perf top
<img width="904" alt="image" src="https://github.com/rustls/rustls/assets/24379039/072c7e94-158c-4db6-8810-e0398797ca3d">
### nginx-openssl avx disable
```
wrk -c 100 -t16 -d 10s https://www.example.org:4463 -H "Connection: close"
Running 10s test @ https://www.example.org:4463
  16 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.21ms    1.72ms  52.86ms   73.33%
    Req/Sec   770.69     71.67     0.94k    79.70%
  123965 requests in 10.10s, 26.36MB read
Requests/sec:  12274.00
Transfer/sec:      2.61MB
```
perf top
<img width="924" alt="image" src="https://github.com/rustls/rustls/assets/24379039/6caf83a5-754f-4af6-97e1-2a41cd0c2bb4">

Even with openssl no-asm and avx turned off, nginx is still much faster than rustls-server

tiny rustls tls server to tested
https://gist.github.com/fangkaiwodexigua/e7f0a598f11904e35636d1d672188a27

**Comment by ctz** [comment]
Thanks for the report.

I would expect performance measurement of a server using an RSA key for TLS1.3 with resumption switched off would spend most of its time doing the RSA private operation. That is shown clearly in the rustls perf output (about 67%), but not in either of the nginx+openssl traces. Are you sure that resumption is also switched off in nginx?

**Comment by fangkaiwodexigua** [comment]
yes, `ssl_session_cache: off;`
```
user root root;
worker_processes auto;
worker_cpu_affinity auto;
worker_rlimit_nofile 100000;
worker_rlimit_core 2048M;
worker_shutdown_timeout 10m;

events {
    worker_connections  65536;
    use epoll;
}

http {

    ##
    # Basic Settings
    ##
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    server_tokens off;
    include       mime.types;
    underscores_in_headers on;
    server_names_hash_bucket_size 128;
    server_names_hash_max_size 1024;
    proxy_read_timeout 60s;
    proxy_connect_timeout 10s;
    proxy_send_timeout 60s;

    ##
    # Gzip/Br Settings
    ##
    gzip on;
    gzip_comp_level 2;
    gzip_types text/plain text/css application/xml application/x-javascript application/json application/javascript text/xml text/json;
    gzip_buffers 4 64k;
    gzip_http_version 1.1;
    gzip_min_length 512;

    #brotli on;
    #brotli_comp_level 2;
    #brotli_types text/xml text/plain text/css application/javascript application/x-javascript application/rss+xml application/atom+xml application/xml application/json;

    ##
    # Proxy Settings
    ##
    proxy_ssl_server_name on;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_buffers 16 8k;
    proxy_buffer_size 8k;
    client_max_body_size 30M;
    client_header_buffer_size 16k;
    proxy_headers_hash_max_size 1024;
    proxy_headers_hash_bucket_size 128;
    proxy_next_upstream error timeout http_500 http_502;
    proxy_next_upstream_tries 3;

    
    
    ##
    # SSL
    ##
    ssl_prefer_server_ciphers on;
    # ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256;
    ssl_session_cache off;
    ssl_protocols TLSv1.3;
    access_log off;
    
    ssl_certificate /root/www.example.org.cert.pem;
    ssl_certificate_key /root/www.example.org.key.pem;
    default_type text/plain;
    
    server {
        listen 4441 backlog=65536 reuseport default ssl;
        # Path to certs
        location / {
            proxy_pass http://10.4.47.9:4441;
        }
        location /1 {
            try_files /1.txt =404;
        }
        location /1k {
            try_files /1k.txt =404;
        }
        location /10k {
            try_files /10k.txt =404;
        }
        location /1m {
            try_files /1m.txt =404;
        }
        location /10m {
            try_files /10m.txt =404;
        }
    }
}
```

**Comment by ctz** [comment]
I think you may also need `ssl_session_tickets off` too.

**Comment by fangkaiwodexigua** [comment]
It's strange, if we disable session ticket, rustls and nginx similar performance, if we enable, rustls has 50% loss compared nginx

rustls
```
16 threads and 100 connections
 Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.48ms   18.65ms 107.51ms   84.67%
    Req/Sec   733.94    211.27     1.61k    68.60%
  97021 requests in 8.30s, 12.49MB read
Requests/sec:  11686.65
Transfer/sec:      1.50MB
```
nginx
```
16 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.84ms    0.92ms  18.24ms   66.11%
    Req/Sec     1.51k    95.26     2.71k    87.37%
  240852 requests in 10.10s, 31.01MB read
Requests/sec:  23846.99
Transfer/sec:      3.07MB
```

**Comment by ctz** [comment]
Yes, resumed connections in TLS are 5-10 times quicker than full connections.

Going to close this as #1830 covers the remaining work.

**Comment by fangkaiwodexigua** [comment]
Do you mean rustls tls resume slow than openssl about double?

**Comment by ctz** [comment]
Difficult to understand what you are measuring now. Our comparative benchmarks show this sort of ballpark:

| | OpenSSL | rustls |
|---|---|---|
| TLS1.2, resumption with tickets | 19981 ops/s | 34674 ops/s |
| TLS1.3, resumption with tickets | 4501 ops/s | 8733 ops/s |

From your results, are you comparing openssl with TLS1.2 vs rustls with TLS1.3?

**Comment by earce-clearstreet** [comment]
Hi team, trying to get an understanding of realistic performance for this library (and making sure I am not missing something).

I have some code calling x.handshake() in a polling fashion and can see the last call finalizing the handshake spikes to over 900us-1ms sometimes spiking to 1.5ms+, is that a realistic range? I read a bit about session resumption and looking at the library it appears as thought the default is enabled with a small cache? 

Is there any way to write this or call this in a way where I can incrementally do work on this without blocking the process over a millisecond?

**Comment by djc** [comment]
@earce-clearstreet this is interesting feedback. I would suggest you file a new issue with more context about your use case/goals. Particularly, what `handshake()` method are you referring to exactly, are you in an async or synchronous environment, what are your throughput and latency goals and what version are you using.

Our best performance metrics (from rustls 0.23.31) are here:

https://rustls.dev/perf/

That page reports 6.6k handshakes per second per core for rustls itself (which excludes I/O costs) for resumption or 2.3k handshakes per second per core for full handshakes, so your 1ms probably includes a bunch of other work?
