### ISSUE TITLE
Pack multiple handshake messages into single TLS message

### ISSUE THREAD

**Issue by ctz** [rustls/rustls#2041]
At the moment each handshake message we send is contained in its own outer TLS message. This means:

- handshakes take a little more data that is actually necessary, due to repeated encryption overhead.
- there is likely some performance left on the table (since N encryptions of M bytes will be slower than one encryption of N * M bytes).

**Comment by zliucd** [comment]
This is a nice feature.  Can we use a compile flag to enable/disable the option?

**Comment by cpu** [comment]
> Can we use a compile flag to enable/disable the option?

What would motivate wanting to disable this behaviour?
