### ISSUE TITLE
Update Meilisearch from rustls-v1.21 to rustls-v1.23

### ISSUE THREAD

**Issue by irevoire** [rustls/rustls#2048]
**Checklist**
* [x] I've searched the issue tracker for similar requests.

Hello, I’m trying to update Meilisearch from rustls-v0.21.11 to the latest version of rustls.
I was able to do most of it alone, thanks to your changelogs and documentation, but I’m stuck on these two changes you made between the v0.21 and v0.22:
![image](https://github.com/user-attachments/assets/fea0d7bd-bfd2-4016-97dc-ee86d087cc38)

Could you provide some help on what to do in this case?
Here's the PR I currently opened; feel free to open a new one that finishes the work if it's easier this way: https://github.com/meilisearch/meilisearch/pull/4806

**Comment by djc** [comment]
Hi, sorry for the limited documentation! I think you'll want to use [`WebPkiClientVerifier`](https://docs.rs/rustls/latest/rustls/server/struct.WebPkiClientVerifier.html) and its `builder()` method to build an `Arc<dyn ClientCertVerifier>` which you can pass to `with_client_cert_verifier()`. Let me know if that helps!

**Comment by cpu** [comment]
The `tlsserver-mio.rs` example might also be a helpful reference point as you look at the new API, particularly in [`make_config()`](https://github.com/rustls/rustls/blob/e58aaa8487fd4c0b8408ee2d9fe9ff31dfc47b54/examples/src/bin/tlsserver-mio.rs#L581-L602).

**Comment by irevoire** [comment]
Hey, thanks for your answers. That helps!
But I’m still not sure to get which options I should give to the `WebPkiClientVerifier` to match the [`rustls::server::AllowAnyAnonymousOrAuthenticatedClient`](https://docs.rs/rustls/0.21.12/rustls/server/struct.AllowAnyAnonymousOrAuthenticatedClient.html) or the [`rustls::server::AllowAnyAuthenticatedClient`](https://docs.rs/rustls/0.21.12/rustls/server/struct.AllowAnyAuthenticatedClient.html).

For example, the documentation of the `AllowAnyAuthenticatedClient` states:
> A ClientCertVerifier that will ensure that every client provides a trusted certificate, without any name checking. Optionally, client certificates will have their revocation status checked using the DER encoded CRLs provided.

But nothing in the documentation of the `WebPkiClientVerifier` talks about « name checking », for example.

Sorry this may be obvious but I’m a huge noob and struggle to find options matching the old documentation 😓

**Comment by ctz** [comment]
[rustls::server::AllowAnyAnonymousOrAuthenticatedClient](https://docs.rs/rustls/0.21.12/rustls/server/struct.AllowAnyAnonymousOrAuthenticatedClient.html) is equivalent to calling [allow_unauthenticated()](https://docs.rs/rustls/latest/rustls/server/struct.ClientCertVerifierBuilder.html#method.allow_unauthenticated) on the builder.

[rustls::server::AllowAnyAuthenticatedClient](https://docs.rs/rustls/0.21.12/rustls/server/struct.AllowAnyAuthenticatedClient.html) is equivalent to not calling that, it is the default for a new [builder()](https://docs.rs/rustls/latest/rustls/server/struct.WebPkiClientVerifier.html#method.builder).

**Comment by irevoire** [comment]
Thanks, everyone, that was awesome!
