### ISSUE TITLE
early data questions

### ISSUE THREAD

**Issue by tahmid-23** [rustls/rustls#2085]
I have some questions about TLS1.3 early data.

1. Let's say I want to process all the early data on a connection, before the handshake is complete.
I would need to know when all the early data has finished reading. Can there ever be a situation where you process packets on the `ServerConnection`, `ReadEarlyData::read()` yields 0 bytes, yet there is still more early data that can be read? If so, then how can I tell when I am fully done reading the early data without waiting for handshake to complete?

2. I noticed that the tlsserver-mio example was recently updated to accommodate early data. However, when testing with OpenSSL s_client in echo mode, s_client says that the early data was rejected. Does tlsserver-mio really support early data? I believe that early data has to be read separately via `ReadEarlyData`, which doesn't seem to be used in the example code. If I'm mistaken, then is there an example of testing early data with tlsserver-mio?

3. I think that an analogous server example to simple_0rtt_client would be very useful. I would love to submit one, but my first point confuses me.

**Comment by ctz** [comment]
Answering these in order:

1. At the moment the only signal is when the handshake ends, which (from the server's point of view) is the next message after the early data finishes. It would probably be sensible for an early data read to return EOF only when the `EndOfEarlyData` message has been processed.

2. Yes, AIUI the purpose of that change was to allow early data to be accepted, but not actually do anything with the data. It would make more sense to read the data too (in http mode: expect the request there, in echo mode: echo the early data, in forward mode: send the early data to the backend connection).

3. Yes, and it would be great if `simple_0rtt_client` could work with that.
