### ISSUE TITLE
Unbuffered client `ConnectionState::ReadTraffic` behavior

### ISSUE THREAD

**Issue by serzhiio** [rustls/rustls#2121]
Playing more with Unbuffered client, i stuck with some strange situation when periodically client is not able to collect full HTTP response (300kb+) under some conditions. 

After some time i realized that if i put `ConnectionState::ReadTraffic` in a loop and toggle it until i get `ConnectionState::WriteTraffic` no more stuck occured. Without loop it stucks if tcp recvs very small packets 100-200b.

Is it normal behavior?

P.S.: i must admit i use IoUring engine.

**Comment by serzhiio** [comment]
The primitive design is:
```
=> recv data
loop{
        let UnbufferedStatus { mut discard, state } = connection.process_tls_records(data);
        let result = match state.unwrap() {
              ConnectionState::ReadTraffic(mut traffic) => {
                  while let Some(d) = traffic.next_record() {
                        match d {
                            Ok(AppDataRecord{discard: _, payload}) => {
                                // make something with payload
                            }
                            Err(e) => {
                                // ...
                            }
                        }
                    }
                    // ... continue loop
              }
              ConnectionState::WriteTraffic(mut traffic) => {
                     // try write
                     break
              }
              _ => {}
       }
}
```
Is it normal practice to do like this?

**Comment by cpu** [comment]
Do you have a minimal reproduction to share?

**Comment by cpu** [comment]
I read this issue again and I think I misunderstood the situation when I asked for a reproducer. Apologies.

> Is it normal practice to do like this?

Yes, it's normal to call `next_record()` on the `ReadTraffic<_>` state until it yields `None` indicating there are no more available app-data records.

Your `ConnectionState::ReadTraffic` match arm aligns with what the [`unbuffered-client.rs`](https://github.com/rustls/rustls/blob/75ecfffc872cf7171a600f694f2733f0a74c9a80/examples/src/bin/unbuffered-client.rs) example [is doing](https://github.com/rustls/rustls/blob/75ecfffc872cf7171a600f694f2733f0a74c9a80/examples/src/bin/unbuffered-client.rs#L65-L87)
