### ISSUE TITLE
Using an mTLS connection with TPM stored credentials

### ISSUE THREAD

**Issue by MuratUrsavas** [rustls/rustls#2128]
Hi,

First of all, thank you for creating such a fantastic and reliable library. I really appreciate the hard work that’s gone into it.

I'm using reqwest for API integration, with rustls as the cryptographic backend. I successfully implemented file-based mTLS with rustls, but things get complicated when the credentials (private key and certificate) are stored in a TPM device. There’s very little information available on how to handle this scenario.

I believe this is the right place to ask. Could you provide some guidance on how to move forward?

My goal is to implement this feature and create a solid example, either here or in the reqwest repo.

**Comment by SAMBILI** [comment]
maybe this will help
https://bit.ly/3TzaAQd

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by ctz** [comment]
Take a look at https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#customising-private-key-usage as a first step.

**Comment by djc** [comment]
That documentation seems to be a little out of date -- it's referring to [`ResolvesServerCertUsingSni`] which no longer exists. I think generally you'll want to look at `ResolvesServerCert` and/or `ResolvesClientCert` which will have you look into wiring up a `SigningKey` impl.

(https://lib.rs/crates/rustls-cng might be useful/relevant.)

**Comment by MuratUrsavas** [comment]
Great! Thanks guys. I'll be following the leads and I guess it will take a little bit of time :)

**Comment by cpu** [comment]
Feel free to re-open if you run into anything you need more guidance with (or drop by the Discord). Thanks!
