### ISSUE TITLE
Don't use Debug representation that much

### ISSUE THREAD

**Issue by stevefan1999-personal** [rustls/rustls#2138]
Currently this innocent looking line may not be that much:

https://github.com/rustls/rustls/blob/211eabfa61d8af7643300e1e81dc33ce598e15f8/rustls/src/builder.rs#L245

But this needs the entire enum to implement Debug, and its representation can be huge, especially with CipherSuite:
https://github.com/rustls/rustls/blob/211eabfa61d8af7643300e1e81dc33ce598e15f8/rustls/src/enums.rs#L116-L491

I added a simple hack to suite_name:
```rust
            let suite_name = cs.common().suite;
            let suite_name: u16 = suite_name.into();
            return Err(Error::General(alloc::format!(
                "Ciphersuite {suite_name:?} requires {cs_kx:?} key exchange, but no {cs_kx:?}-compatible \
                key exchange groups were present in `CryptoProvider`'s `kx_groups` field",
            )));
```
This immediately shaved 7KB off the binary. 

Unfortunately, not all code can be eliminated like this, such as unwrap() calls which needs `Debug` as well, and this kind of hack might also lost its original (friendly-named) context. We should let the user to control this behavior, for example, we can just print the hex value of the suite name, so that the user can look it up themselves rather than adding this tax to the embedded device.

**Comment by ctz** [comment]
Thanks for raising this - I think my ideal solution involves https://github.com/rust-lang/rust/issues/129709 but I also think the ciphersuite enum is bloated and would be a quick and widely-applicable win.
