### ISSUE TITLE
0.23.13 seems to break semantic versions with the lack of default CryptoProvider

### ISSUE THREAD

**Issue by darklajid** [rustls/rustls#2148]
**Checklist**
* [X] I've searched the issue tracker for similar bugs.

**Describe the bug**
Updating my dependencies a transitive dependency is 0.23.13. If I understand the following runtime error message correctly, they didn't read the latest release notes / fail to configure this properly. However, isn't this unexpected for a bump from .12 to .13?

Error: 
> no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point

**To Reproduce**
1. Use axum-server 0.7.1 with feature tls-rustls
2. Try running a server with a TLS config
3. Boom at runtime, see above

**Applicable Version(s)**
Linux/Windows, 0.23.13

**Expected behavior**
I expect axum-server to fix this/notice this .. but I also didn't expect a point release to break things

**Comment by frederikhors** [comment]
This is happening to me too. What is the fix?

**Comment by cpu** [comment]
@frederikhors It means you have code using the default process-wide crypto provider but the rustls feature flags (intentionally or through unification) aren't unambiguous. You must either:

A) fix the feature ambiguity by useing rustls with just the ring _xor_ aws-lc-rs feature enabled (not both) so the default is unambiguous.
B) specifically set a process-wide default yourself early in your app's lifecycle before any fns relying on a default are used.

See the [CryptoProvider](https://docs.rs/rustls/latest/rustls/crypto/struct.CryptoProvider.html#using-the-per-process-default-cryptoprovider) documentation for more detail.

If you have further issues please open a new issue with more detail (versions used, error observed, reproduction code, etc)
