### ISSUE TITLE
Wildcard certificate support

### ISSUE THREAD

**Issue by janis-ab** [rustls/rustls#2179]
Is it possible to use wildcard domain names with wildcard certificate when using ResolvesServerCertUsingSni?

Let's say, i have a wildcard certificate `*.example.tld`
```rust
let wildcard_certkey = rustls::sign::CertifiedKey { /* contains *.example.tld certificate and key */ };
let mut resolver = rustls::server::ResolvesServerCertUsingSni::new();
resolver.add("*.example.tld", wildcard_certkey); // <-- this fails
```

I do not know the protocol specifics, but aren't wildcard certificates supported by ResolvesServerCertUsingSni? Although returned error is not too helpful, skimming through library code, it seems to fail due to `*.example.tld` not being a valid DNS name (which is true).

I can of course register wildcard certificate per each subdomain, and it works, but i would prefer to use single wildcard certificate and use it for responses every time any subdomain is requested.

Not sure if this is a feature request, bug report or just missing docs.

**Comment by ctz** [comment]
As you've found, `ResolvesServerCertUsingSni` does simple equality on DNS names, not wildcards. But note that `ResolvesServerCertUsingSni` is (or is intended to be) an exemplar implementation of the [`ResolvesServerCert`](https://docs.rs/rustls/latest/rustls/server/trait.ResolvesServerCert.html) trait, so there is plenty more scope for customising the behaviour past what `ResolvesServerCertUsingSni` provides.

One (perhaps slow) way of achieving what you want would be:

- keep a list of `sign::CertifiedKey`s in your object that impls `ResolvesServerCert`
- for each call to `resolve()`, go through the list, and return the first where [`verify_is_valid_for_subject_name()`](https://docs.rs/rustls-webpki/0.102.8/webpki/struct.EndEntityCert.html#method.verify_is_valid_for_subject_name) works

That would leverage the existing wildcard matching code in the rustls-webpki crate. Beware that if you have many possible certificates that is probably not sensible, and you'll probably want to look up the incoming name in a trie or similar datastructure.

**Comment by janis-ab** [comment]
Thank's for the idea. I had not thought about implementing ResolvesServerCert trait for custom struct.
