### ISSUE TITLE
Make UserCanceled Alert Warning not be tracing::warn!

### ISSUE THREAD

**Issue by TroyKomodo** [rustls/rustls#2182]
**Checklist**
* [x] I've searched the issue tracker for similar bugs.

**Describe the bug**

When running our server for hours we get warning logs from rustls

```
{"timestamp":"2024-10-26T14:36:31.330816392+00:00","level":"WARN","fields":{"message":"TLS alert warning received: AlertMessagePayload { level: Warning, description: UserCanceled }","log.target":"rustls::common_state","log.module_path":"rustls::common_state","log.file":"/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.23.14/src/common_state.rs","log.line":519},"target":"rustls::common_state","filename":/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.23.14/src/common_state.rs","line_number":519}
```

https://github.com/rustls/rustls/blob/121d813ca87fe881881cb29b04471af642131a55/rustls/src/common_state.rs#L527

**To Reproduce**

Not sure.

**Applicable Version(s)**
A list of versions and platforms you've tested with.

v0.23.14

**Expected behavior**

We are unsure if these warnings are meaningful? Is there something on our end that we should fix? How do we know if this is an issue or if we should just silence them?  

**Additional context**
-_-

**Comment by cpu** [comment]
Thanks for the report. This was resolved in #2184. You might also be interested in some of the breadcrumbs [from ctz's comment](https://github.com/rustls/rustls/pull/2184#pullrequestreview-2397627760) on the subject.
