### ISSUE TITLE
Support `certificate_authorities` extension in ClientHello  

### ISSUE THREAD

**Issue by s-arash** [rustls/rustls#2235]
**Checklist**
* [x] I've searched the issue tracker for similar requests

**Is your feature request related to a problem? Please describe.**
The TLS 1.3 [`certificate_authorities`](https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.4) extension in ClientHello can be used by the client to communicate to the server what CAs it recognizes, helping the server present a certificate acceptable to the client. Currently, this is not supported in `rustls`.

**Describe the solution you'd like**
We can add this extension to the `ClientHello` type (e.g., as the `.certificate_authorites_extension()` method), and add a default function to the `ServerCertVerifier` trait that asks for CA names that the server cert verifier recognizes. With these changes, custom `ServerCertVerifier`s on the client side can communicate their recognized CAs to the server during TLS handshake, and custom cert resolvers on the server side can take this information into account when picking a cert/key.

I've already started prototyping this, and if the maintainers are OK with the proposed solution, I can open a PR for this feature.

**Comment by ctz** [comment]
The issue, as I understand, with this extension is that it involves transmitting about 15KB of data (for the WebPKI) in the client hello. That is pretty impractical.

**Comment by s-arash** [comment]
Hi @ctz. Thanks for the quick reply. 

Just so we are on the same page, the 15KB number comes from ~100 root CAs * ~150 bytes per root CA?

I agree that this is not very practical for WebPKI, and I'm not proposing for rustls to start sending this extension by default. The proposal is to let custom cert verifiers and cert resolvers propose/check this extension.

In our use case, we want to let clients talk to our public server, and not have to rely on public root CAs for validation of the server.

**Comment by ctz** [comment]
Ah, yes that would be acceptable. FWIW this can already happen for client auth -- see https://docs.rs/rustls/latest/rustls/server/danger/trait.ClientCertVerifier.html#tymethod.root_hint_subjects so adding it for server auth seems reasonable.

**Comment by s-arash** [comment]
Great. I'll work on the PR then.
