### ISSUE TITLE
example ech-client.rs panics on some URLs

### ISSUE THREAD

**Issue by sftcd** [rustls/rustls#2276]
**Checklist**
* [x] I've searched the issue tracker for similar bugs. (Well, not really, I'm confident this sample hasn't been tried with these URLs:-)

**Describe the bug**
With some of my ECH test URLs, the sample ech-client.rs panics. I think that's for some cases with multi-valued HTTPS RRs, some of which are ok and some of which contain bad or unsupported values.

The output I see includes: 
```
thread 'main' panicked at src/main.rs:61:14:
called `Result::unwrap()` on an `Err` value: InvalidEncryptedClientHello(NoCompatibleConfig)
```
(Note, I have copied the source for this sample and done some minor edits, so line 61 above would be line 70 in the repo here.)

**To Reproduce**

Using the sample with these URLs sometimes has this behaviour, other times works. (Presumably dependent on the ordering of DNS answers, but not verified.)

https://curves1-ng.test.defo.ie/echstat.php?format=json
https://curves1-ng.test.defo.ie:15443/echstat.php?format=json
https://curves2-ng.test.defo.ie/echstat.php?format=json
https://curves2-ng.test.defo.ie:15443/echstat.php?format=json
https://curves3-ng.test.defo.ie/echstat.php?format=json
https://curves3-ng.test.defo.ie:15443/echstat.php?format=json
https://v4-ng.test.defo.ie/echstat.php?format=json
https://v4-ng.test.defo.ie:15443/echstat.php?format=json

The names for those URLs have various multi-valued HTTPS RRs. If you load https://test.defo.ie/iframe_tests.html you can see a rough description on those (search for the names in the page).

The public name in the (well-encoded) HTTPS RRs for all these should be 'public.test.defo.ie'.

**Applicable Version(s)**
0.23.19 (I think)

**Expected behavior**
Ingest the correct DNS answers and skip over the bogus ones.

I'm not sure if this is purely an issue with the sample code or if it perhaps runs deeper. (Afraid my rustiness doesn't extend that far:-)

**Comment by cpu** [comment]
Thanks for the report!

> Using the sample with these URLs sometimes has this behaviour, other times works. (Presumably dependent on the ordering of DNS answers, but not verified.)

I have a feeling that we're only trying ECH configs from the first HTTPS RR but I'll have to verify and adjust so we collect up all lists from each returned record.

**Comment by cpu** [comment]
> I have a feeling that we're only trying ECH configs from the first HTTPS RR

Indeed, that's the case: [`find_map()`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.find_map) will return the first `Some(_)`:
https://github.com/rustls/rustls/blob/d06ab266f26804aeb982a40d7a22f36a908e8b7e/examples/src/bin/ech-client.rs#L222-L233
