### ISSUE TITLE
Make it more clear what architectures that is supported

### ISSUE THREAD

**Issue by Erk-** [rustls/rustls#247]
This may be better suited as an issue in ring, but I found it hard to figure out why this did not work on POWER9 and there is no table or similar that tells it.

**Comment by TheBlueMatt** [comment]
Really, ideally the resolution here is to make ring optional and have some Rust implementation of a small subset of (reasonably required) algorithms from elsewhere. Having to hack around Ring's brokenness just to use rustls kinda sucks (let alone for my use-case, which explicitly forbids C dependencies).
