### ISSUE TITLE
Custom RootCertStore

### ISSUE THREAD

**Issue by quininer** [rustls/rustls#271]
The current `RootCertStore` must load all root certificates into memory and cannot be changed after created.

`webpki-roots` is usually good, but in many cases we want to load certificates from system to adapt various environments.

In addition, selective loading of certificates is also good for performance. It avoids [a lot of loops](https://github.com/briansmith/webpki/blob/6031d9fc9bcade8e258e64f0d1c12f5932da0622/src/verify_cert.rs#L53) when validating certificates, and avoids [scanning directories](https://github.com/sfackler/rust-native-tls/blob/master/src/imp/openssl.rs#L99) when loading certificates.

**Comment by briansmith** [comment]
If webpki is looping too much then please file an issue in the webpki repo with the steps to reproduce. We've not optimized it because nobody has ever noticed an issue with it.

**Comment by quininer** [comment]
webpki is fast! I don't think this is a bottleneck, but I believe that fewer `trust_anchors` can improve the efficiency of selecting certificates.

**Comment by ePirat** [comment]
For example on macOS it might make sense to use Keychains Root certificates store, as that is usually what users expect.

**Comment by ctz** [comment]
I'm working on integration with OS cert stores over at https://github.com/ctz/rustls-native-certs

**Comment by cpu** [comment]
There's been a lot of progress since this issue was opened. Please take a look at:

* https://github.com/rustls/rustls-native-certs
* https://github.com/rustls/rustls-platform-verifier

If there are any remaining gaps I think it would be best to file issues on one/both of those projects as appropriate.

Thanks all!
