### ISSUE TITLE
Implementing friendlier Certificate/PrivateKey APIs

### ISSUE THREAD

**Issue by djc** [rustls/rustls#348]
In Quinn, we currently have some wrapper types to make it easier to deal with `Certificate`, `PrivateKey`, as well as a `CertificateChain` type which just wraps a `Vec<Certificate>`:

https://github.com/djc/quinn/blob/9a9be3887db843a13d13db6056fea4456e23040a/quinn-proto/src/crypto/types.rs

Would you be open to upstreaming some of these more friendly APIs?

**Comment by burdges** [comment]
I never looked closely into this but did you consider using traits here?

**Comment by djc** [comment]
I'm not sure what you think traits would achieve here.

I'm mostly wondering about what about the `internal` module is deemed to stay unstable. It seems to me that the API has in fact been mostly stable over the past several releases, and the contained functionality is minimal enough that it has similarly not seen many changes. It would then be beneficial to move this functionality closer to the core types to make it easier to use.

**Comment by DemiMarie-parity** [comment]
> I'm not sure what you think traits would achieve here.

Traits allow one to add methods to a type from another crate.

**Comment by burdges** [comment]
I suppose ClientCertVerifier and ServerCertVerifier alraedy provide this really.

**Comment by briansmith** [comment]
I think like this is mostly implemented already, and also it would be obsoleted if we were to implement https://github.com/rustls/rustls/issues/850#issuecomment-999798205, so I suggest we close this.
