### ISSUE TITLE
Implement RFC 8701 - GREASE Extensions

### ISSUE THREAD

**Issue by jabedude** [rustls/rustls#357]
Hello all! RFC 8701 has been published, and I was wondering if this project would be okay with implementing it? I would be willing to work on this feature. 

I have a TLS-related crate that could benefit from rustls supporting GREASE, so this would be useful for me!

**Comment by ctz** [comment]
I don't have any objection against this, but I'd prefer this not to add to the configuration/API surface of the library -- I think care is needed to balance the costs and benefits here. I think the benefit of GREASE in a library like this with (honestly) small deployment footprint is limited; while the cost of any additional API complexity is high.

I think GREASE being implemented in BoringSSL (which is, obviously, hugely well deployed) achieves 99% of its aims. It's not even implemented by OpenSSL...

**Comment by jabedude** [comment]
I totally understand your point about the cost/benefits of adding unnecessary tuning knobs here. With that concern in mind, would this be appropriate behind a feature flag? Or could it simply be a part of the default rustls handshake? The second option seems best for not adding messy configuration.

The only downside would be the (slight, I'd imagine) overhead of the additional extension.

**Comment by austinhartzheim** [comment]
@ctz BoringSSL has seen wide deployment thanks to its inclusion in Chrome. Comparatively, the footprint of Rustls is small, but may cover additional systems not normally accessed via web browser. If you are still open to adding RFC8701 support, I've been working on an implementation (#375 ) which keeps the configuration and API changes to a minimum.

I have placed the configuration behind a feature flag (as @jabedude suggested). The current implementation modular to allow swapping alternate GREASE implementations in (for example, if one was building a TLS fuzzer or scanner requiring GREASE support), but that interface need not be exposed if it is contrary to the goals of this crate. In general, no configuration changes should be required by the user beyond enabling the feature flag.

My implementation currently supports the "client ciphers list" and "client extensions" fields. I've managed to achieve that while maintaining the majority of the GREASE logic inside a single file with minimal changes elsewhere in the code. It seems that the internal and external APIs need not change (minus the addition of some GREASE functions to the internal API).

Let me know your thoughts. I can continue working on the PR if you would like to see a more complete implementation.

**Comment by jabedude** [comment]
...I guess I'll close #358 then? ¯\_(ツ)_/¯

**Comment by briansmith** [comment]
> I have a TLS-related crate that could benefit from rustls supporting GREASE, so this would be useful for me!

What is the actual benefit to doing this? Why isn't Chrome and Firefox doing it enough? From what I know, Rustls would be better off avoiding the added complexity of doing this; i.e. we're better off not implementing this, and instead concentrating on other improvements. But, if there's some benefit I'm overlooking, I'd reconsider my position.

Otherwise, I suggest we close this and the related PR(s).

**Comment by ctz** [comment]
I think we're not going to do GREASE here. The complexity/value trade-off is not a good one for rustls. I do appreciate the effort that has gone into the PR.
