### ISSUE TITLE
Question: How can I send a TLS1.3 KeyUpdate?

### ISSUE THREAD

**Issue by faulesocke** [rustls/rustls#408]
The code seems to handle incoming KeyUpdate messages correctly. However, I was unable to find a method that would send such a KeyUpdate message with `request_update` set to `update_requested` upon calling. Is this already implemented?

**Comment by ctz** [comment]
Yeah, there's no API for this presently. What's your usecase?

**Comment by faulesocke** [comment]
I need this for a research project. For now I can fallback to OpenSSL but it would be useful to have this in rustls eventually.

I could theoretically try and implement this myself but I think this is an error-prone task because many of the `State` structs need to be changed and it is not immediately clear how the API design would be so that it prevents KeyUpdate requests during the handshake phase. Any suggestions on how to start on this?

**Comment by djc** [comment]
"A research project" is still pretty vague. Can you talk about what you are trying to accomplish with the project?

**Comment by faulesocke** [comment]
I can't go into any details yet but we are basically trying to split the communication into multiple channels. Then we are trying to do the handshake on one channel and afterwards do a KeyUpdate on other channels. This was already shown to improve theoretical security in certain scenarios.

**Comment by cpu** [comment]
I don't believe there's enough information in this ticket to be actionable from the Rustls side. I'm going to close it out and we can revisit if there's more information to motivate why this functionality should be added to the API. 

Thanks!
