### ISSUE TITLE
how to get https client certificates serialnumber  in actix-web 

### ISSUE THREAD

**Issue by baoyachi** [rustls/rustls#412]
I just find function:`get_peer_certificates()` https://github.com/ctz/rustls/blob/main/rustls/src/server/mod.rs#L623

how to get `client` certificates `serialnumber` in https with actix-web by used `rustls`

**Comment by djc** [comment]
rustls itself doesn't expose code to parse DER-encoded certificates, so you'll have to extract the DER-encoded certificate from the `get_peer_certificates()` return value and use some other crate to parse it and find the serial number. From a little Googling, it looks like https://crates.io/crates/x509-parser will do what you need.

**Comment by briansmith** [comment]
Maybe this feature is out of scope for Rustls?
