### ISSUE TITLE
Implement RFC 8446 Appendix C.4 in the default session cache.

### ISSUE THREAD

**Issue by dhobsd** [rustls/rustls#466]
I implemented an RFC8446 [appendix C.4]-capable session cache on the current `StoresClientSession` trait, but it doesn't quite feel right. I wanted to open this issue present the challenges I faced and the implementation I ended up with. I feel that the challenges presented may warrant some API changes -- even if implemented internally -- as what I ended up with isn't particularly satisfying (while also being -- I think -- relatively good given the constraints).

RFC8446 [section 4.6.1] recommends that TLS 1.3 servers send multiple session resumption tickets to clients. In [appendix C.4], it's subsequently recommended that clients use tickets at most once to avoid session tracking. The current implementation of `ClientSessionMemoryCache` does not do this, and some properties of `StoresClientSession` (and use of the cache in general) make doing so difficult.

`ClientSessionMemoryCache` iterates keys of a `std::collections::HashMap` to evict. This process executes in an arbitrary order, and it's possible to evict the just-inserted key. This results in effectively a 50% chance of reusing the same ticket, even when a new ticket was provided. The cache only stores a single ticket, while servers may send multiple ([section 4.6.1] mentions several additional reasons clients might want to have extra tickets available). Finally, failed negotiation attempts on a session reuse the last-known ticket.

The `StoresClientSession` trait is intentionally opaque about what's stored in it. Unfortunately, this doesn't allow the handler of the session cache determine whether the supplied `ClientSessionValue` is for TLS 1.3, or for RFC5077 session resumption in a previous version. This wouldn't be so bad, but the same cache is overloaded to also store TLS 1.3 key exchange hints. 

Problematically, the keyspace for TLS 1.3 tickets and RFC5077 sessions are shared, so a `StoresClientSession` implementation must first decode the supplied value as a `ClientSessionValue` and peek at the version to see whether it should be managed per C.4 or not. Although the keyspace isn't shared with key exchange hints, we still have to re-parse the value as a `NamedGroup` when it fails to parse as a `ClientSessionValue` because there's no way to gather information about what sort of `ClientSessionKey` we get to differentiate the keyspace at all.

My [cache implementation] wraps an LRU cache of opaque keys to typed values. LRU may seem like overkill for such a small cache, but I felt that it was the simplest method to reason about what to evict while not evicting random items (that can include the newly-inserted item, which has a high probability of reuse). Additionally, although I used whatever we already had available in our tree, LRU is simple to implement and verify without incurring additional dependencies.

In the case of TLS 1.3 / RFC5077 sharing keyspace, my decision was to evict the existing occupant. I believe this is safe in any system built on top of rustls given the ownership semantics of cache read results. The worst case is renegotiation every connection, but this is a worst-case scenario. It's unclear that it's any more- or less-common than other hybrid scenarios, and it felt silly to optimize for either way.

Key / value types are divined as described in the previous paragraphs.

The TLS 1.3 keyspace maps a SN to a set of keys. This set is managed in a "bounded stack", which is effectively LRU semantics mapped onto a capacity-constrained stack: push/pop happen from one end, eviction occurs on the other when push would cause capacity to be exceeded. The default ticket count chosen is 6 for this implementation, partially because that's a number that is mentioned in C.4, and partially because it's a number that works well for attempting to reach the two seconds folks are willing to wait for interactive feedback ([Miller68]) when doing a Happy Eyeballs race with the default bounds suggested by [RFC8305 Happy Eyeballs v2].

[section 4.6.1]: https://tools.ietf.org/html/rfc8446#section-4.6.1
[appendix C.4]: https://tools.ietf.org/html/rfc8446#appendix-C.4
[cache implementation]: https://fuchsia.googlesource.com/fuchsia/+/refs/changes/62/478362/24/src/lib/fuchsia-hyper/src/session_cache.rs
[Miller68]: https://dl.acm.org/doi/10.1145/1476589.1476628
[RFC8305 Happy Eyeballs v2]: https://tools.ietf.org/html/rfc8305

**Comment by briansmith** [comment]
> `ClientSessionMemoryCache` iterates keys of a `std::collections::HashMap` to evict. This process executes in an arbitrary order, and it's possible to evict the just-inserted key.

I filed issue #469 for this.

**Comment by briansmith** [comment]
Instead of changing the session cache API to allow the session cache to implement the TLS 1.3 use-at-most logic, we should change Rustls internally to enforce it.

Note the server session cache API has:
```
pub trait StoresServerSessions: Send + Sync {
    /// Find a value with the given `key`.  Return it and delete it;
    /// or None if it doesn't exist.
    fn take(&self, key: &[u8]) -> Option<Vec<u8>>;
}
```

Couldn't we change the client session cache trait so that it also has this `take` method, and then change Rustls TLS 1.3 client implementation to use `take()` to enforce automatically (assuming the session cache implementation implements `take` correctly) the "use at most once" property, for every session cache implementation?

**Comment by briansmith** [comment]
It seems to me that we need to change the session cache API to also be able to store multiple tickets per key instead of just one, in order to implement RFC 8446 C.4. Then `take()` should remove one at a time and maybe we would additionally need a `take_all()`.

> This wouldn't be so bad, but the same cache is overloaded to also store TLS 1.3 key exchange hints.

If we move all the logic for RFC 8446 C.4 into Rustls itself and out of the cache implementation, then that won't be an problem any more, at least for the reasons you describe, right?

**Comment by dhobsd** [comment]
I don't think a `take_all` is needed to implement C.4. To the extent that C.4 informs the behavior of a ticket cache, I'm not entirely sure which bits can be brought into rustls.

My thoughts after having implemented this cache are that:

 * It's unclear what to do when a SN has two servers where one supports TLS 1.3 and one supports TLS 1.2. It's not a likely scenario, but partitioning the cache requires defining a preference for key version. If TLS 1.3 is ever negotiated, and it is the preference, it becomes impossible to later resume TLS 1.2 sessions. Maybe nobody cares about this case, but it's trivially solveable by making RFC5077 and TLS 1.3 ticket resumption share keyspace and evicting whatever was there before. Whether using take() or get(), the caller owns what it got, so I don't believe this should introduce bugs.
 * If we keep RFC5077 and TLS 1.3 tickets share keyspace, the cache needs to know what kind of ticket it's storing, otherwise RFC5077 caches waste space storing however many tickets they have, when it never matters for them to have more than 1.
 * If we want to solve the problem by partitioning the keyspace for these two, we need to implement different caches, and that starts to need to creep into ClientConfig options, or making the default cache implementation more configurable.
 * kx hints should be associated with TLS 1.3 ticket storage rather than their own keyspace to prevent them from being evicted after having negotiated them, and falling back to X25519 (maybe we got HRR because the server didn't want that). Since they're associated with the handling of tickets while the session may be resumed, they don't make sense to take occupancy of the cache. This is probably part of the logic that can be moved into rustls, since we should be able to associate the kx hints when we construct the ClientSessionValue.

I'm in favor of changing the API to include what class of ticket it's storing, for RFC5077 and TLS 1.3 keyspace to be shared, and for kx hints to be associated with the stored ClientSessionValue.

**Comment by davidben** [comment]
I'm not exactly sure what partitioning means, or what it'd mean for the TLS 1.3 code to use `take()`. (The client doesn't know what version will be used yet. This is really a property of the session.) There are three cross-version cases to consider:

* Two server instances behind a cache key support different versions. It's already the case that wildly heterogenous server deployments will miss session resumptions, so whatever.
* The server previously spoke TLS 1.2 and now speaks TLS 1.3. Once you've picked up a TLS 1.3 session, you should evict the old TLS 1.2 session. Otherwise, when you run out of 1.3 tickets, you'll "fall back" to offering the 1.2 session. Not only is it most likely useless, but you undo C.4's privacy benefits for those connections.
* The server previously spoke TLS 1.3 and now speaks TLS 1.2. This may come up if a server rolled out TLS 1.3 but had to roll back due to an unexpected bug. We really want rollbacks to settle back to the previous state and not risk cascading failures, so if you pick up a TLS 1.2 session, past TLS 1.3 negotiations shouldn't prevent you from offering it.

One model is that your cache entry stories either one 1.2 session or multiple 1.3 sessions. If you pick up a session of a category different from what you have, evict.

**Comment by dhobsd** [comment]
Partitioning is referring to splitting the keyspace for 5077/1.3 or using separate caches. Based on your bullet points we can't do that. And `take` won't work for the same reason: The client doesn't know what version will be used yet.

**Comment by dhobsd** [comment]
Wanted to ping on this again.

The implementation linked does effectively what David describes ("your cache entry stories either one 1.2 session or multiple 1.3 sessions. If you pick up a session of a category different from what you have, evict."). But the implementation is still unfortunate, largely due to the API being opaque and needing to handle kx hint storage as well.

Are there opportunities for improving the API here? Two things that would improve this situation:
 * Passing the session type (RFC5077 or RFC8446) into `put` in `StoresClientSession`. This avoids the implementation needing to match on numerous TLS/SSL versions and the "Unknown" version. 
 * Storing the kx hint in the `ClientSessionValue` for TLS 1.3 rather than using a different keyspace. This would avoid TLS 1.3 session tickets from taking 2 entries per SN, which artificially constrains the capacity by up to half.

**Comment by briansmith** [comment]
I think we should fix #469 before tackling this. Roughly, I think we should do this:
1. Fix #469 so that the default memory cache is not totally broken w.r.t. eviction order.
2. Remove the API for setting a custom client cache implementation.
3. Iterate on the default client cache implementation until we're happy with its eviction policies and multi-ticket support and C.4 support.
4. Factor out as much of the common logic from the client default session cache implementation as possible into the core of Rustls.
4. Expose a new custom client cache API that mirrors the API of the default client cache implementation.
5. Do the same for the server cache API.

WDYT?

**Comment by dhobsd** [comment]
Sorry, that's kind of a jerk thing for me to have done to ping on this and then let it sit for a week. It's been a busy week.

Overall I agree with this with some caveats:

 * Removing the API should come with an ability to disable caching in the builder. This would maintain the ability for folks who want to disable session caching to do so.
 * I'm skeptical that any logic can be factored out of the cache because it's a storage system and not part of the protocol, so I don't know what sorts of things would be encapsulated in the fourth point.

WRT re-introduction of cache APIs, I'm not entirely sure how to approach that. ISTM that what API consumers really want on the client side is a way to manage the storage of the cache rather than the cache itself. It almost makes me want to suggest turning the API into CRUD operations, but I think that's going to be woefully inefficient compared to native implementations of a cache. So I think it is sensible to re-expose what we end up with.

For servers, I think a storage management API is really all that's needed and we can manage the cache. To that end, put/get/take on opaque values seem totally sufficient. The use-case is different on that end.

**Comment by jsha** [comment]
#1145 implemented the new client session behavior by default, and added a new client persistence interface. After some discussion on #1228 we decided that the Tls1[23]ClientSessionValue types should not be serializable. In other words, the only implementations possible will be in-memory session stores (which seems reasonable for clients).

I was curious what existing code implemented the old StoresClientSessions interface, to see what sort of customizations people would like. [GitHub search, plus some patience filtering through copies of rustls, yielded](https://github.com/search?q=impl+storesclientsessions&type=code):

 - Mesalink:
  - https://github.com/mesalock-linux/mesalink/blob/ef12dd6339e42a37a2c24fa4b8f0a3ce155563a5/src/libssl/ssl.rs#L149
   - https://github.com/mesalock-linux/mesalink/blob/ef12dd6339e42a37a2c24fa4b8f0a3ce155563a5/src/libssl/cache.rs#L24
   - Uses essentially `Arc<Mutex<HashMap<Vec<u8>, Vec<u8>>>`, with a max_entries to limit size . Evicts randomly when full.
   - Has logic to ignore puts where the key starts with `kx`.
   - Mesalink hasn't had a commit in 2 years, and depends on rustls 0.19.

 - Deno:
  - https://github.com/denoland/deno/blob/7e61e8f0e0abbf8cbd1a8c2ea21cee9ff11403c2/ext/tls/lib.rs#L143
  - Uses Mutex<HashMap<Vec<u8>, Vec<u8>>>
  - Evicts randomly when full.

 - Fuschia:
  - https://github.com/vsrinivas/fuchsia/commit/d5f5f63a2509d089e37e4c1d670b98c3659c4a5b
  - Implemented a nice RFC8446 Appendix C.4 session cache
  - Implementer was @dhobsd, who went on to file this issue. Thanks @dhobsd!

Rustls' [internal use of LimitedCache](https://github.com/rustls/rustls/commit/f12853839e80dc5bfa9de1c269e44f3be24de0e4) dates from April 2021, so it's entirely possible the Deno and Mesalink implementations were added before then, for the sole purpose of limiting storage growth.

Given that, and given the restriction that client session storage cannot be serialized, is there anything interesting that a user can do by implementing their own client session store?

 - Using something other than Mutex for interior mutability. The only interesting alternative I can think of would be something async like [`tokio::sync::Mutex`](https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html), but the current interface doesn't allow for that anyhow.
  - Replacing HashMap and/or LimitedCache with a more efficient implementation. This is valuable for server sessions but at the typical size of client session caches it seems unlikely to be needed.

I think #1145 and f12853839e80dc5bfa9de1c269e44f3be24de0e4 have solved, in the default memory cache, the main problems that people needed a custom cache to solve. That leaves the current ClientSessionStore trait providing a complex API surface that is unlikely to see any use. I propose that we make ClientSessionStore private and offer only [NoClientSessionStorage](https://docs.rs/rustls/0.20.8/rustls/client/struct.NoClientSessionStorage.html) and [ClientSessionMemoryCache](https://docs.rs/rustls/0.20.8/rustls/client/struct.ClientSessionMemoryCache.html), to allow users to enable or disable caching. So basically I agree with @dhobsd and @briansmith above.

We have an API-breaking release coming up very soon. If we remove the client session storage API as part of that release, we can always add it later as a non-breaking change. I think the handful of users that use the old (0.20.0) StoresClientSessions can happily delete their implementations and use the default ClientSessionMemoryCache.

**Comment by dhobsd** [comment]
Well, I thought we had removed our implementation, but I just checked myself to link the change where that happened and I see that we never ended up landing https://fxrev.dev/720219 in Fuchsia. Also unfortunate is that my comments on approval rationale apparently happened in a chat rather than on the CL. My opinion at that time was (and remains) that LimitedCache is robust enough for our use cases in the Fuchsia platform.

> but at the typical size of client session caches it seems unlikely to be needed

I might nitpick a little bit here. In Fuchsia, we have an HTTP client as a service for components, and several components choose to use the service ([`fuchsia.net.http`](https://fuchsia.dev/reference/fidl/fuchsia.net.http)) rather than implement their own client. I think this is probably an uncommon architecture, but shared clients might not be, and, especially when those clients are systems rather than people, larger caches may be present and clients may be sensitive to cache latency. This all said, Fuchsia is not currently that system.

> offer only [NoClientSessionStorage](https://docs.rs/rustls/0.20.8/rustls/client/struct.NoClientSessionStorage.html) and [ClientSessionMemoryCache](https://docs.rs/rustls/0.20.8/rustls/client/struct.ClientSessionMemoryCache.html), to allow users to enable or disable caching

I'll tack on that cache sizing is an important property when caching can be enabled. This is functionality is present in `ClientSessionMemoryCache`, but it's worth calling out as an important property of the cache that can be enabled. (Even if the cache functionality is otherwise opaque.)

**Comment by ctz** [comment]
> Given that, and given the restriction that client session storage cannot be serialized, is there anything interesting that a user can do by implementing their own client session store?

I think the two examples given are what I had in mind, specifically:

- for the first example: really sketchy, `unsafe`-heavy lockless data structures
- for the second: various LRU crates and different data structures (mostly `unsafe`)

The other example I had in mind was: directly wrapping `ClientSessionMemoryCache` for its behaviour, but via an observability/telemetry library.

I think there are cases where a program acts as a TLS client and has high performance requirements - say, a microservice whos goal is to call webhooks. That will want a huge client session cache and demand performant behaviour from it.
