### ISSUE TITLE
Allow validating the client certificate with an async function

### ISSUE THREAD

**Issue by ctron** [rustls/rustls#468]
Currently the `ClientCertVerifier` is a synchronous trait. However, having an implementation, which needs to contact an additional service, that might block, and thus block the main I/O loop of the whole application.

While async traits are still under development, it still might make sense to provide a way to validate client certificates in an async fashion.

**Comment by Ralith** [comment]
See also extensive prior discussion in https://github.com/ctz/rustls/issues/89. This probably can/should be done without async by exposing a simple, explicit state machine to the caller.

**Comment by ctron** [comment]
Thanks for the response. It looks like #89 is about a different use case (server certificates), but the problem is basically the same.

Just that I understood you correctly, please correct me if I am wrong:

You would define a function, which should return immediately, but after that, doesn't send back a response to the remote peer. When calling the function it would pass in some context, (possibly handing ownership to the caller), which the implementor of the function can use to trigger the response to the peer at a later time.

I guess that is the same as async, but without the need to using anything like async-traits in the process. It would also solve the issue that I have.

Is there any work planned on this? I am not sure if I can help, but I would try if you think this would make sense.

**Comment by djc** [comment]
I am planning to work on #89 soon, maybe worth waiting to see how that shake out before we do a similar thing for the client-side?

**Comment by ctron** [comment]
:+1: That is good to know! If waiting fixes the issue, I am happy to try :grin:! Many thanks!

**Comment by briansmith** [comment]
Although this issue predates #850, I suggest we close this in favor of #850 since #850 has more design work done, and that design work includes the async aspect.
