### ISSUE TITLE
`ClientCertVerifier` parameter `sni` is confusing

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#473]
When working on PR #462 I noticed that `ClientCertVerifier::verify_client_cert`'s `sni` parameter isn't documented clearly. Also, none of the implementations of the trait that are provided make use of it.

I think it is intended to communicate to the client certificate verifier what the identity of the server is. However, as its documentation does note, the Rustls server side doesn't actually verify that the server really does have that `sni` name. In particular, the server code never checks that its own certificate actually has that name.

This seems to be a pretty bad state. Before offering a suggestion on what to do, I'd like to better understand the intent. My guess is that the `sni` parameter should be replaced with a server-chosen/validated identity.

Note that `client_auth_mandatory` and `client_auth_root_subjects` have the same seemingly-problematic `sni` parameter.

**Comment by briansmith** [comment]
One particular concern I have is that an implementation of the interface might try to validate the client's identity for the given SNI name. If that were the case, then the server's key is compromised, then a malicious client could reflect back the server's certificate chain and then become fully authenticated to the server. This would make key compromise worse than would be typical for a TLS server. We should make sure the documentation makes it clear that the client certificate shouldn't be validated for the given SNI.

**Comment by ctz** [comment]
Background for this is #309 and #230

**Comment by briansmith** [comment]
It seems like the current design of the API is intended to let the implementer of the trait handle a subset of the problem "I want to do certificate stuff differently depending on some parameters of the ClientHello," i.e. issue 635. In theory, depending on the SNI, even totally different client cert verification mechanisms and policies could be used, so it seems like we should instead have a callback API that lets the user map (some subset of) ClientHello -> (some subset of) `Arc<ServerConfig>` and/or an API that lets the user map ClientHello -> `Arc<ClientCertVerifier>`. I think the latter API shape, combined with removing the `sni` parameters from all the functions in `ClientCertVerifier`, would be a more bulletproof, less error-prone API.

In particular, I wonder how many people are wrongly verifying the client's certificate for the DNS name in `sni`.

**Comment by djc** [comment]
I think #89 will give us an API that lets a user map a ClientHello to an Arc<ServerConfig>.

**Comment by djc** [comment]
#787 removes this.

**Comment by djc** [comment]
Going to close this since we merged #787.
