### ISSUE TITLE
ECHConfig implementation

### ISSUE THREAD

**Issue by sayrer** [rustls/rustls#508]
In #318, there's a test client that uses trust-dns to pull this data from DNS and then hand over the bytes for parsing by rustls. I think that's the right way to do things, so there's no new dependency introduced.

If there are no objections, I'd like to start work on this aspect of the ECH problem. I'll also add a command-line tool and API to generate ECHConfig records.

ECHConfig is defined here: https://tools.ietf.org/id/draft-ietf-tls-esni-09.html#name-encrypted-clienthello-confi

From the TLS WG list:

"Cloudflare is now running an ECH test server here:
https://crypto.cloudflare.com

We're running draft-ietf-tls-esni-09. The HTTPS resource record containing the current ECH config is available in DNS."

**Comment by sayrer** [comment]
Here is a small Python program that will print the DNS HTTPS-RR data for Cloudflare's expermental -09 server.

```python3
#!/usr/bin/env python3                                                                                                                                                                                         

import dns.resolver

resolver = dns.resolver.Resolver(configure=False)
resolver.nameservers = ['1.1.1.1']

answer = resolver.resolve('crypto.cloudflare.com.', 'HTTPS')

print(answer.rrset)
```

It should print something like:

```
./testdns.py 
crypto.cloudflare.com. 265 IN HTTPS 1 . alpn="h2" ipv4hint="162.159.135.79,162.159.136.79" echconfig="AEf+CQBDABNjbG91ZGZsYXJlLWVzbmkuY29tACCD91Ovu3frIsjhFKo0I1fPd/a09nzKMrjC9GZV3NvrfQAgAAQAAQABAAAAAA==" ipv6hint="2606:4700:7::a29f:874f,2606:4700:7::a29f:884f"
```

The ECHConfig is encoded as base64.

**Comment by djc** [comment]
Sounds good to me, but obviously I can't really speak for Joe.

**Comment by sayrer** [comment]
An update here: Cloudflare has updated their server to draft-10, which looks good in most respects. The WG is still thrashing on ECH and HRR interactions, so I don't expect this feature will ship until summer at the earliest. I will update my PR for draft-10, and should be able to get a lot farther now that I am more familiar with the handshake code (thanks for all the reviews, even the negative ones).

**Comment by cjpatton** [comment]
Just for everyone's awareness: Cloudflare's test endpoint now implements draft-ietf-tls-esni-14 and has been on this draft for some time.

**Comment by sayrer** [comment]
I worked on this a little bit. I have the draft -14 config working (only needed to change some data types). They changed the serialization of the encrypted ClientHello, so working through that. Once that's done, it should only change `hs.rs` on the client, as predicted.

**Comment by ckcr4lyf** [comment]
> Here is a small Python program that will print the DNS HTTPS-RR data for Cloudflare's expermental -09 server. It requires dnspython 2.1.0 or higher. https://pypi.org/project/dnspython/

FYI: Also a quick way to do it via [dig(1)](https://linux.die.net/man/1/dig)

```
$ dig +short TYPE65 crypto.cloudflare.com
1 . alpn="http/1.1,h2" ipv4hint=162.159.137.85,162.159.138.85 ech=AEX+DQBBoAAgACDyJHx3uVfPa6btcli6kSw43rYAf2otcJ7zlULAimJvCwAEAAEAAQASY2xvdWRmbGFyZS1lY2guY29tAAA= ipv6hint=2606:4700:7::a29f:8955,2606:4700:7::a29f:8a55
```

**Comment by cpu** [comment]
I think we can close this based on https://github.com/rustls/rustls/pull/1568 and associated in progress work.
