### ISSUE TITLE
Some checks that the current connection is QUIC are missing when the "quic" feature is enabled.

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#520]
This affects performance at least, and very possibly correctness.

Consider this code:
```
    #[cfg(feature = "quic")]
    {
        let write_key = if sess.early_data.is_enabled() {
            // Traffic secret wasn't computed and stored above, so do it here.
            key_schedule.client_handshake_traffic_secret(
                &hash_at_client_recvd_server_hello,
                &*sess.config.key_log,
                &handshake.randoms.client,
            )
        } else {
            _maybe_write_key.unwrap()
        };
        sess.common.quic.hs_secrets = Some(quic::Secrets {
            client: write_key,
            server: read_key,
        });
    }
```

It is guarded by `#[cfg(feature = "quic")]` but it should also be guarded by a runtime check `if sess.common.protocol == Protocol::Quic` . This means some QUIC-specific code will execute on non-QUIC connections, which seems wrong.

Probably we should write a macro `is_quic!(sess)`  that combines the compile type `#[cfg(...)]` check with the runtime check for the current protocol.

**Comment by briansmith** [comment]
```
        #[cfg(feature = "quic")]
        {
            sess.common.quic.early_secret = Some(client_early_traffic_secret);
        }
```

```
        #[cfg(feature = "quic")]
        {
            sess.common.quic.hs_secrets = Some(quic::Secrets {
                client: read_key,
                server: write_key,
            });
        }
```
(This occurs many times, both with hs_secrets and traffic_secrets)

```
        #[cfg(feature = "quic")]
        let client_hello_hash = self
            .handshake
            .transcript
            .get_hash_given(suite.get_hash(), &[]);
```

**Comment by djc** [comment]
The `is_quic!()` macro sounds like a good idea to me.

**Comment by briansmith** [comment]
It seems like this might be partially because early data is only implemented for QUIC, according to this comment:

```
    /// Amount of early data to accept; 0 to disable.
    #[cfg(feature = "quic")] // TLS support unimplemented
    #[doc(hidden)]
    pub max_early_data_size: u32,
```

**Comment by djc** [comment]
Yup, that matches what I remember.

**Comment by Ralith** [comment]
Yeah, there's some amount of code there that could be shared once the TLS side is implemented.

**Comment by briansmith** [comment]
In the case where early data stuff is guarded by `#[cfg(feature = "quic")]`, a comment saying the `#[cfg(feature = "quic")]` is there because early data is only enabled for QUIC would be useful.

**Comment by ctz** [comment]
I think I'd like it if the "quic" feature made rustls into quic-_only_. Down that same road: we could remove the `Protocol` type, and compile out version configuration, and the whole of TLS1.2.

**Comment by djc** [comment]
Making the quic feature QUIC-only wouldn't work very well for some version of hyper that wants to support both HTTP/2 and HTTP/3 with rustls.

**Comment by djc** [comment]
@Ralith do you remember why we didn't implement early data for TCP at the time? I seem to remember there were some complications related to how the API would work.

**Comment by Ralith** [comment]
To the contrary, I recall expecting it to be pretty straightforward; I just didn't want to build out an external-facing security-sensitive feature for rustls that I wasn't going to be personally exercising very well.

**Comment by briansmith** [comment]
> I think I'd like it if the "quic" feature made rustls into quic-_only_. Down that same road: we could remove the `Protocol` type, and compile out version configuration, and the whole of TLS1.2.

That's not how Rust's feature mechanism works. Some parts of the application may be using Rustls to do QUIC/UDP and another, totally separate thing might be using Rustls to do TLS 1.2 over TCP. Rust's feature mechanism is additive; adding a feature flag to a dependency must not disable any functionality that was enabled when the feature flag wasn't used.

**Comment by Ralith** [comment]
Alternative options:
- Make TCP support also a feature, so QUIC-only apps are lighter
- Publish different crates that share source (but this could bloat apps that need both)

**Comment by djc** [comment]
I don't think there's a lot of TCP-specific code. Making 1.2 optional is #633, which could be nice.

**Comment by briansmith** [comment]
> * Make TCP support also a feature, so QUIC-only apps are lighter

If there is substantial code other than TLS 1.2 that is not used by QUIC, please file a separate issue detailing those.

> * Publish different crates that share source (but this could bloat apps that need both)

Because of the bloat issue you mention, this seems like a non-starter.

**Comment by ctz** [comment]
We no longer have the quic feature.
