### ISSUE TITLE
RFC: Unify client and server APIs

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#522]
* Whenever possible, the API for configuring a client and configuring a server should have one API, instead of two APIs that are the same. This way, we can write a single function that constructs the common parts of our TLS configuration.

```
#[derive(Clone)]
pub struct Config {
    /// List of ciphersuites, in preference order.
    pub ciphersuites: Vec<&'static SupportedCipherSuite>,

    /// Our MTU.  If None, we don't limit TLS message sizes.
    pub mtu: Option<usize>,

    /// Protocol names we support, most preferred first.
    /// If empty we don't do ALPN at all.
    pub alpn_protocols: Vec<Vec<u8>>,

    /// Supported protocol versions, in no particular order.
    /// The default is all supported versions.
    pub versions: Vec<ProtocolVersion>,

    /// How to output key material for debugging.  The default
    /// does nothing.
    pub key_log: Arc<dyn KeyLog>,
}

struct ClientConfig {
    common: Config,
    ...
}

struct ServerConfig {
    common: Config,
}
```

* Instead of having `ServerSession` and `ClientSession`, we should have one `Session` type with an API that abstracts away whether we're the client or the server after the handshake has started. Currently things that want to do this have to do something like this:
```
enum Session {
    Client(ClientSession),
    Server(ServerSession),
}
```
Then they create their own `Session` API that does this abstraction. I believe if we do this within Rustls instead, not only can we eliminate the need for such wrappers, but we can also eliminate significant duplicate logic within Rustls. For example, instead of having `server_cert_chain` in `ClientSession` and `client_cert_chain` in `ServerSession`, we should have `peer_cert_chain` in `SessionCommon`.

* We should merge some of the Server- and Client- specific plugin APIs. I think we should merge `ClientStoresSession` and `ServerStoresSession` into a single thing. Perhaps we should factor out the commonality of `ClientCertVerifier` and `ServerCertVerifier` APIs into a common super-trait; this might allow implementers of those APIs to reduce duplication, and may also allow Rustls internally to reduce some duplication. I am planning to experiment with changing the webpki API to facilitate this.

**Comment by djc** [comment]
> an API that abstracts away whether we're the client or the server after the handshake

I'm not sure how this would look. Can you write some example code? I think it would cause ergonomic issues if the type of a session changes throughout the handshake.

**Comment by Ralith** [comment]
We do exactly what's described above in quinn at https://github.com/quinn-rs/quinn/blob/main/quinn-proto/src/crypto/rustls.rs#L33, so I'd be quite happy to see this change and save the effort. More broadly, in quinn we made a deliberate decision to unify the client/server interface post-establishment and it's worked out great.

**Comment by Ralith** [comment]
This would also let rustls ditch the awkward `QuicExt` trait that has to be stubbed out when quic support is disabled, since there would no longer be any need for a universal `Session` trait.

**Comment by ctz** [comment]
I would like to do this, yes. On a branch I have a builder-style interface for ClientConfig/ServerConfig[1] -- the change proposed above would make this much smaller.

[1]: The intention for this is to make it impossible to create a ServerConfig which doesn't have any certificates.

**Comment by djc** [comment]
What do we do with the public peer-specific APIs?

* `ClientSession::early_data(&mut self) -> Option<WriteEarlyData<'_>>`
* `ClientSession::is_early_data_accepted(&self) -> bool`
* `ServerSession::get_sni_hostname(&self) -> Option<&str>`
* `ServerSession::received_resumption_data(&self) -> Option<&[u8]>`
* `ServerSession::set_resumption_data(&mut self, data: &[u8])`
* `ServerSession::reject_early_data(&mut self)`

Presumbly the `Option`-returning methods could just return `None` if called from the wrong peer, but that still leaves `is_early_data_accepted()` (I suppose it could return the correct value on both peers), `get_sni_hostname()` (don't think we want to necessarily keep SNI around on the client?), `set_resumption_data()` and `reject_early_data()` (I suppose the latter two could just do nothing).

The more typestatey version is perhaps that we have a single `Session` type with `client() -> Option<ClientSession<'_>>` and `server() -> Option<ServerSession<'_>>` accessors and keep these APIs separate. @briansmith what did you have in mind?

**Comment by ctz** [comment]
Where we are on this; matching up with the three disjoint suggestions here:

1. The ConfigBuilder interface gets most of the way towards this.
2. In my experience, most APIs like this end up writing boilerplate to manually implement dynamic dispatch. I'd prefer to just use traits for that.
3. This seems like a minor usability improvement, and then only for consumers who both originate and terminate TLS in the same codebase (most libraries, but not many applications).

**Comment by djc** [comment]
I wrote up a suggested approach in [a PR comment](https://github.com/ctz/rustls/pull/721#discussion_r654508045). With that approach it would be pretty straightforward to offer both a side-specific API and a way to reduce to a fully functional both-sides API. I've seen quite a few users who get confused by the way the trait is the main gateway to the connection functionality, and I think we can do better than that.

**Comment by eloff** [comment]
See also #775 for an example of a user (me) running into this problem and solving it basically the same way with an enum.

> In my experience, most APIs like this end up writing boilerplate to manually implement dynamic dispatch. I'd prefer to just use traits for that.

@ctz A trait requires boxing to use it as a struct field (or generics, but that has it's own issues.) So you have allocation, indirection overhead (potential cache miss), and a slower vtable based dynamic dispatch over an enum with two values. I'd rather the enum than the Trait-based approach for these reasons.

**Comment by djc** [comment]
@eloff I'd be interested in your thoughts on design proposed in the comment I linked to previously.

**Comment by eloff** [comment]
@djc I had a look at your proposal, it's very similar to the generics Transport<T: Connection> I implemented as my first attempt at solving the problem. What ended up happening is everywhere I used it, I needed to make generic on <T: Connection> as well, so it spread through my code like a disease. When I switched to using an enum, everything got a lot simpler and I didn't need to import Connection everywhere for the trait bounds.

Which is a long winded way of saying, that approach is probably ok as an implementation strategy, but I'll still have to make an enum wrapper over it.

**Comment by briansmith** [comment]
If we were to go with the enum-based approach, we'd have to ensure it doesn't force all the server code to be linked into every client and vice versa.

If we have parameterization in the public interface then the problem is that many applications, even small ones, would end up monomorphizing Rustls multiple times. We'd have to be careful that we minimize how much bloat this causes by being careful to minimize how much is parameterized internally.

Note that the enum from the enum-based approach could implement the trait. The people who want to minimize how much the parameterization spreads through their code would use the enum. Or they could just implement such an enum themselves, which I think is already done by tokio-rustls or similar crates.

**Comment by djc** [comment]
I'd like to experiment with this, but it really needs #721 to be merged. I don't want to further extend that PR, making it harder to review (it has already had one round of review) and harder to rebase. I think we could the following:

* `ClientConnection`
* `ServerConnection`
* `Connection` as an enum of both `ClientConnection` and `ServerConnection`

If all of these `impl Deref<Target = ConnectionState>`, we can define very few methods on `ClientConnection`/`ServerConnection`/`Connection` itself, and rely on the deref for most of the other methods (thus minimizing monomorphization bloat).

**Comment by eloff** [comment]
@djc That sounds like an excellent solution to me.

**Comment by djc** [comment]
I made an implementation in #789.
