### ISSUE TITLE
Panic when TLS 1.2 is enabled for a QUIC connection

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#555]
In https://github.com/ctz/rustls/issues/549#issuecomment-796705388 @djc wrote:
> Starting new QUIC sessions currently panics if any version other than 1.3 is in config.versions.

There shouldn't be a panic here.

When starting a QUIC session, Rustls should just disable TLS 1.2 for the session and carry on.

**Comment by Ralith** [comment]
Requesting TLS 1.2 support is an error on the part of a QUIC implementation. I don't think that should be silently ignored.

**Comment by sayrer** [comment]
Maybe it should be a trait bound or something, and impossible to create in the first place.

**Comment by djc** [comment]
If we use a builder to build the config, we can presumably statically prevent this from happening.

**Comment by briansmith** [comment]
> Requesting TLS 1.2 support is an error on the part of a QUIC implementation. I don't think that should be silently ignored.

The most likely case where this would happen is where an application is trying to use the same configuration for both QUIC and non-QUIC TLS.

There are three options I see:
1. Redo the API such that it is statically impossible to enable TLS 1.2 and QUIC at the same time.
2. Return an error if the application attempts to do QUIC when TLS 1.2 is enabled.
3. Since Rustls knows QUIC is TLS 1.3+-only, have Rustls only negotiate TLS 1.3 and ignore whether or not TLS 1.2 is enabled.

All of those are reasonable behaviors. The only one that's seems totally wrong is the current behavior of panicking.

The problem I see with having separate builder APIs for QUIC and non-QUIC configurations is that an application that wants to do both QUIC and TLS with the otherwise same configuration would likely have to do duplicate work in separate codepaths to configure the security properties of QUIC vs. the security properties of non-QUIC TLS. That should be avoided, because it's error-prone to keep two different code paths that are supposed to do the same thing in sync.

**Comment by Ralith** [comment]
A builder API could be constructed in a way that would avoid the duplication. For example, all common configuration could be exposed through a single interface, which could then be used to construct either a QUIC builder or a TLS builder, each exposing the specialized options.

**Comment by sayrer** [comment]
> * Redo the API such that it is statically impossible to enable TLS 1.2 and QUIC at the same time.

I think this approach makes the most sense. There are other problems that are similar, too. For example, ECH requires SNI and TLS 1.3, but requiring a bunch of conditionals to check this invariant seems like the wrong approach.

**Comment by briansmith** [comment]
> > * Redo the API such that it is statically impossible to enable TLS 1.2 and QUIC at the same time.
> 
> I think this approach makes the most sense. There are other problems that are similar, too. For example, ECH requires SNI and TLS 1.3, but adding a bunch of conditionals to check this invariant seems like the wrong approach.

That sounds fine to me. 

Once we have something, we'll need to look at how a real application would actually use the API to choose between these the various cases depending on what the server has available:

1. QUIC + ECH
2. TLS + ECH
3. QUIC w/o ECH
4. TLS w/o ECH

We should ensure that the solution doesn't push a bunch of conditional logic into each such application when it could be done once within Rustls.

**Comment by djc** [comment]
It does seem like it might be useful to have a `ServerConfig` that can support all of these scenarios at once.

**Comment by briansmith** [comment]
@djc Does the new builder-based design for the configuration API prevent this panic?

**Comment by djc** [comment]
It does not so far, and I'm no longer sure that that was the best way to go about it anyway. Fixed the panics discussed here in #666 by returning an error.

**Comment by ctz** [comment]
Was fixed in #666.
