### ISSUE TITLE
LibreSSL interop options

### ISSUE THREAD

**Issue by sayrer** [rustls/rustls#579]
I asked the LibreSSL folks about the -no_ecdhe option, and they provided some choices. Do we want to re-add that ECDHE test if it can be made to work?

https://github.com/libressl-portable/portable/issues/652

**Comment by briansmith** [comment]
I do think their suggested idea of configuring the openssl server with an explicit list of cipher suites, instead of using `-no_ecdhe`, is a good one. In fact, we should probably be using an explicit list of cipher suites to enable on the server for every test.

**Comment by briansmith** [comment]
@sayrer I'm not sure what the latest status of this is, after reading https://github.com/libressl-portable/portable/issues/652. Maybe it's a non-issue now as it seems to have been addressed on the libressl side? Maybe if you have a new enough macOS version it will have a new-enough LibreSSL?

**Comment by briansmith** [comment]
All the use of OpenSSL has been removed from the test suite so this issue is no longer relevant. Thanks for reporting it!
