### ISSUE TITLE
impl Hash & Ord for Certificate

### ISSUE THREAD

**Issue by mleonhard** [rustls/rustls#588]
My project puts [`rustls::Certificate`](https://docs.rs/rustls/0.19.0/rustls/struct.Certificate.html) structs in a [`HashSet`](https://doc.rust-lang.org/std/collections/hash_set/struct.HashSet.html).  It also uses them as keys in a [`HashMap`](https://doc.rust-lang.org/std/collections/hash_map/struct.HashMap.html).  If `Certificate` implemented `Hash`, I could delete some brittle code that depends on `rustls` internals.

If `Certificate` implemented `Ord`, we could easily use it with other [collection types](https://doc.rust-lang.org/std/collections).

**Comment by brockelmore** [comment]
It has a public Vec<u8> as an internal that you can access. Here is an example:

```
vuse std::collections::{BTreeSet, HashSet};

#[derive(Clone, Eq, PartialEq)]
pub struct Certificate(pub Vec<u8>);


pub fn to_bytes(cert: Certificate) -> Vec<u8> {
    let Certificate(as_bytes) = cert;
    as_bytes
}

fn main() {
    // setup bytes that simulate a certificate
    let t = vec![0u8, 10, 5, 12];
    let cert = Certificate(t);
    
    // create the hash set
    let mut my_hash_set = HashSet::new();
    let as_bytes = to_bytes(cert);
    my_hash_set.insert(as_bytes);
    
    println!("{:?}", my_hash_set);
}
```

**Comment by djc** [comment]
I'm okay with adding Hash, but I don't think adding Ord or PartialOrd makes sense since there is as far as I understand no common natural ordering for certificates.

**Comment by mleonhard** [comment]
Depending on internals of a struct is brittle. Depending on the internals of a struct from a third-party library is exceedingly brittle and invites random build breakage or worse.

One could argue that `rustls::Certificate` defines its tuple field as `pub` so it is not internal.  I think this will be changed eventually, or the library will be unable to implement important features.  Tuple members make poor interfaces.

There are ways to workaround the lack of `Hash` & `Ord`.  Every user of the library can write and maintain their own copy of the code.  This is a waste of effort.  The `Hash` and `Ord` implementations belong in the library where everyone can use them.

A struct's ordering doesn't have to be common or natural to be useful.  Using the order of the internal `Vec<u8>` would be fine.  It will let us put `Certificate` structs into:
- [`std::collections::BTreeMap`](https://doc.rust-lang.org/stable/std/collections/struct.BTreeMap.html)
- [`std::collections::BTreeSet`](https://doc.rust-lang.org/stable/std/collections/struct.BTreeSet.html)

Are there any downsides to implementing `Hash` & `Ord`?

**Comment by briansmith** [comment]
> A struct's ordering doesn't have to be common or natural to be useful. 

Interesting thought. I'm not sure I agree with that, though I don't have a strong argument against it either.

> Are there any downsides to implementing `Hash` & `Ord`?

As long as a `Certificate` is defined to be just the bytes of the encoded certificate, and that's how it's implemented, then I don't see any problem with it.

**Comment by edward-shen** [comment]
If I may chime in, official API documentation [suggests](https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits) to eagerly implement common traits. Not saying that we should blindly follow it, but unless there's a reasonable issue with implementing `Hash` and `Ord` (e.g. some security concern), I'm inclined to believe that it's best practice to implement them, regardless of the internals of `Certificate` itself.

Even if `Certificate` no longer is simply the bytes of the encoded cert, it still reasons to have a `Ord` implementation for it, e.g. with the serial number field in the X.509 format if `Certificate` fully parses an input, for a contrived example.

**Comment by djc** [comment]
#809 adds `Hash` and `Ord` derivations for `Certificate`.
