### ISSUE TITLE
Public/Private Key Validation

### ISSUE THREAD

**Issue by daxpedda** [rustls/rustls#618]
I am currently trying to validate keys that are passed into `ServerConfig`/`ClientConfig`. Currently `ServerConfig::set_single_cert` forces to pass both keys in, but I need an API to validate them separately, and do only validation.

I would be willing to make a PR. But wanted to get some feedback first.

The idea would be to introduce a `Certificate::from_validated` and basically link it to `webpki::EndEntityCert::verify_is_valid_tls_server_cert` with the exact same settings `ServerConfig`/`WebPKIVerifier` uses.
`PrivateKey::from_validated` seems to use `RSASigningKey`, `ring::signature::EcdsaKeyPair` and `ring::signature::Ed25519KeyPair`, so I guess encapsulating the implementation of `ServerConfig::set_single_cert` would help here.

**Comment by djc** [comment]
It's not quite obvious to me what you're proposing. I don't see `from_validated()` anywhere in the current API. Can you be a little bit more concrete about the API you are envisioning?

**Comment by daxpedda** [comment]
I am proposing to **add** `from_validated`.
So the idea is to be able to validate `Certificate`s and `PrivateKey`s before using them in the server.
With validation I mean making sure, that when they are loaded into `ServerConfig`/`ClientConfig` they don't produce an error.

This validation is already done in `ServerConfig`/`ClientConfig`, my proposal would add this validation as a "standalone" API.
My idea was that the new API could be `Certificate::from_validated`, considering that I'm new around here, this may be not the right place or name.

Currently it's possible to do this validation with external crates like x509-parser, but considering that rustls has all the tools available to make the validation, I hoped that doing this in rustls would prevent consumers from having to introduce additional dependencies.

Additionally any validation done by rustls can also ensure 100% that it is valid for rustls, other external crates might not fulfill the exact requirements.

**Comment by djc** [comment]
It seems to me there would be a bit of a chicken and egg situation: either you already have a `Config` that contains all the required state which need to be passed in to webpki's functions for this, or you need to gather up a bunch of state and awkwardly pass all of it into `Certificate::from_validated()`. Neither of which seem like great ergonomics.

Can you explain more on why you need API to only validate them, and to do so separately?

As some additional guidance, we're currently discussing changing how `ServerConfig`/`ClientConfig` are built, potentially using a builder instead of the current wide-open fields struct. On current main, we already made some of the `Config` fields private, only allowing them to be set using the `new()` method. What you're asking for sounds like it might changes that would require going in the opposite direction.

**Comment by daxpedda** [comment]
Can you elaborate what kind of state we are talking about here?
As far as I've seen in the code, the only required "state" would be supported algos by the client or server. I am assuming, that what you have in mind for validation, might be a wider scope then what I envisioned.

The use case would be to validate certificates before they get stored, without having to use any of the configuration structures.
Looking in the code, what I'm talking about is quiet minimal, as far as I could see.

Let me be a bit more precise, for example, I've followed the private key validation in rustls and found the following:
https://github.com/ctz/rustls/blob/c627076b7aeae1c8b5de59dbd4be46a7fbbe55d5/rustls/src/sign.rs#L130-L170
So I realize there is more validation going on when the server actually starts and runs, but this might be a start.

My hope is to do minimal validation, that basically just checks if the certificate can be parsed and has supported algos, requiring no "state" otherwise. Therefore I would hope it doesn't conflict with any changes in `ServerConfig`/`ClientConfig`.

**Comment by djc** [comment]
By state I basically meant all the arguments that `webpki::EndEntityCert::verify_is_valid_tls_server_cert()` would need. `rustls::sign::any_supported_type()` is actually already public; would it be sufficient for your use case at least for private keys?

By your use case, I was hoping to dig a bit deeper. Why do you need minimal validation compared to what is already available from checking the return value of `set_single_cert()`? If the minimal validation fails, what will your code do next?

**Comment by daxpedda** [comment]
Somehow I missed that `any_supported_type` is public ... my bad! `webpki::EndEntityCert::verify_is_valid_tls_server_cert()` also fits the bill, and is what I've been using, it is just currently very unergonomic to query the default supported algos from rustls and translate them to someting `webpki` understands, but maybe I missed something?

I might not have been clear, what I'm proposing is not to add a feature to rustls, this is purely an API improvement.
> By your use case, I was hoping to dig a bit deeper. Why do you need minimal validation compared to what is already available from checking the return value of `set_single_cert()`? If the minimal validation fails, what will your code do next?

`set_single_cert()` only validates the private key, it doesn't do any certificate validation, as far as I could see.
The only other I could imagine to add, is a validation that both keys pair up properly.

Just to summarize:
- check that both the `Certificate` and `PrivateKey` can be correctly parsed
- check that both support a given list of algos
- (optional) check that they are a pair

Again, the first two points are already doabble with the help of `webpki::EndEntityCert::verify_is_valid_tls_server_cert()` (I think it's missing a check for an existing `SubjectAlternativeName`?) and `rustls::sign::any_supported_type()`, I'm only proposing a more ergonomic alternative.

**Comment by ctz** [comment]
You may also find https://docs.rs/rustls/0.13.0/rustls/sign/struct.CertifiedKey.html#method.cross_check_end_entity_cert to be useful.

**Comment by daxpedda** [comment]
> You may also find https://docs.rs/rustls/0.13.0/rustls/sign/struct.CertifiedKey.html#method.cross_check_end_entity_cert to be useful.

Thank you, I stumbled on this before, maybe combining some of these "validations" would be useful?

**Comment by briansmith** [comment]
@daxpedda I suggest you add an API to webpki's `EndEntityCert` that takes a private key and returns `Ok(())` if and only if the private key corresponds to the public key in the cert.

I also think Rustls should do this check by default.

**Comment by daxpedda** [comment]
> @daxpedda I suggest you add an API to webpki's `EndEntityCert` that takes a private key and returns `Ok(())` if and only if the private key corresponds to the public key in the cert.

Great, I will look into it hopefully soon!

@ctz I would like to have an okay that this is a desired feature to attempt making a PR, I'm not looking for assurance that you will accept it. If I wasn't clear I'm willing to explain myself further of course.

**Comment by cpu** [comment]
> I suggest you add an API to webpki's EndEntityCert that takes a private key and returns Ok(()) if and only if the private key corresponds to the public key in the cert.

Here's a PR implementing this approach: https://github.com/rustls/webpki/pull/67

**Comment by ctz** [comment]
Given #1918, I'm going to close this as complete.
