### ISSUE TITLE
Unable to work around old RSA 1024-signed cert by adding server cert

### ISSUE THREAD

**Issue by John-Nagle** [rustls/rustls#639]
I'm trying to connect to a large antiquated set of servers which use this certificate hierarchy:

0: Corporate root CA certificate, RSA 1024, obsolete, created in 2005, expires 2025.
1: Server certificate, non-CA, RSA 2048, valid, found on each of several thousand servers.

I have copies of both certificates. I realize that putting the root CA cert into rustls does nothing, and understand why. If I add cert 1) using "config.root_store.add(...)", that does nothing either, presumably because it's neither a CA nor self-signed. 

(Error messages in cert loading would be appreciated. It's hard to tell what's going wrong.)

Is there some way I can add cert 1) and then connect to servers that use it? That's not a security risk; I'm explicitly telling TLS that a server cert is valid for that server. This will let me use Rust while I beat on someone to fix the server side problem. ETA 1-2 years for that.

OpenSSL will connect with these settings:

openssl s_client -verifyCAfile OBSOLETEROOTCERT.crt -connect HOSTNAME :12043 -verify_return_error -auth_level 1

but only at auth_level 1. Auth_level 2, which locks out RSA 1024, will not work. So everything is valid, just obsolete.

Suggestions?

**Comment by djc** [comment]
Have you investigated the path of writing a custom `ServerCertVerifier` (and installing it, after enabling the `dangerous_configuration` flag? I think this will allow you to do what you need, although you may have to reimplement some parts yourself to get around the things that webpki (on which the default verifier is based) won't allow you to do.

**Comment by John-Nagle** [comment]
I'm hoping to avoid that. I'm looking at trying the OpenSSL crate instead.

**Comment by djc** [comment]
You can use the older webpki release with the last rustls release, I think?

**Comment by John-Nagle** [comment]
Yes, everything works with rustls 0.19.0 and webpki 0.21.0.

Warning messages for un-usable root certificates loaded would be helpful. It took me quite a while to figure out what rustls was unhappy about.

**Comment by briansmith** [comment]
> Is there some way I can add cert 1) and then connect to servers that use it? That's not a security risk; I'm explicitly telling TLS that a server cert is valid for that server. This will let me use Rust while I beat on someone to fix the server side problem. ETA 1-2 years for that.

Is there an intermediate certificate? If so, you could try using the intermediate(s) as trust anchor(s). Let me know if that doesn't work.

**Comment by John-Nagle** [comment]
> Is there an intermediate certificate? If so, you could try using the intermediate(s) as trust anchor(s). Let me know if that doesn't work.

Nope. The cert chain is very simple:

0: Corporate root CA certificate, RSA 1024, obsolete, created in 2005, expires 2025.
1: Server certificate, non-CA, RSA 2048, valid, found on each of several thousand servers.

The issuer of the server cert matches the CA cert; there really is no intermediary.

This is for Second Life, the big virtual world. The API is public and I'm writing a client for it in Rust. (The open source C++ client is 20 year old single thread code and there's a need for a more modern client.) Each of about 50,000 server processes on about 10,000 computers offers that server certificate. The corporate root certificate file is in every client. No intermediate certificates are used.

I tried using the server certificate itself as a trust anchor, but that had no effect. Can you use a certificate not marked as a CA and not self-signed as a trust anchor?  All the servers use the same server cert, which is for "*.secondlife.io". That cert does get replaced occasionally, so nailing it into the client is not good.

**Comment by briansmith** [comment]
OK, I think the custom certificate verifier approach makes sense for your use case since it's so niche and the security is so questionable. I'm not convinced it would be worth exposing the bad RSA 1024 support to webpki to make it work even as an opt-in, as the entire infrastructure you describe really needs to be rethought. (I know it's not your fault.)

**Comment by John-Nagle** [comment]
I agree. I have a workaround for now, and the appropriate bug report has been filed with the service for a long term fix. They're in the final stages of migrating their entire infrastructure to "the cloud", and they've had to fix other cert problems along the way, along with other legacy issues, so this might get fixed soon.

I'd suggest better error messages for rejected root cert situations, though. This took two days to figure out, because everything looked legit, browsers could make the connection,  but rustls rejected the connection with a generic error code.

**Comment by briansmith** [comment]
Should we close this now? I think whatever action there is here in improving the error reporting would need to be done in the certificate verification library. Webpki already has an open issue for that.

**Comment by John-Nagle** [comment]
Yes, go ahead and close if webpki has an issue, but add a reference to the issue, please.

**Comment by djc** [comment]
I think that's https://github.com/briansmith/webpki/issues/221.
