### ISSUE TITLE
"Format" job in CI is too slow

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#645]
According to https://github.com/ctz/rustls/actions/runs/753327095 this job takes 7 minutes. I'm guessing that's because building it from source is slow. We should consider using the GitHub Actions cache feature to cache the resultant binary.

It is very annoying to wait 7+ minutes and only then find out that I forgot to run admin/fmt, and then have to wait another 7+ minutes.

**Comment by djc** [comment]
Once https://github.com/rust-lang/rustfmt/pull/4782 lands, I think we can just use a pre-built nightly rustfmt (and stable in 3 months or so). Before that happens, I'm not very motivated to fix this. Another potential workaround could be to set up a pre-commit git hook that runs `admin/fmt`.
