### ISSUE TITLE
Ticketer has inefficient Mutex usage patterns

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#656]
When working on PR #654 I noticed that the Ticketer holds the mutex over potentially long-running operations. In particular, when rolling the key, a new random key is generated, and that process uses the system PRNG while holding the mutex. This is either a syscall or even File I/O (if falling back to /dev/urandom or equivalent). This is bad for two reasons:

1. The lock is held for potentially a long time.
2. It's hard for us to be confident that File I/O operations will never panic within libstd. Panicking would poison the lock.

In PR #654 I eliminated one lock/unlock pair per operation. Thus we could easily be able to refactor the code to avoid holding the lock during key generation. Even the most naïve way of doing this would likely have better performance than the pre-PR-654 code.

**Comment by briansmith** [comment]
Also, the generator is a callback and in general it is bad to assume that a callback will never panic. If the generator does panic then we'd poison the mutex.

**Comment by briansmith** [comment]
@davidv1992 It seems like your PR #861 fixes this. Is there anything else that needs to be done?

**Comment by cpu** [comment]
I think we can consider this closed by #861 unless there's further input to consider. Thanks!
