### ISSUE TITLE
Big Sur test coverage

### ISSUE THREAD

**Issue by sayrer** [rustls/rustls#684]
Rustls doesn't currently test macOS Big Sur (11).

GitHub Actions `macos-latest` is still Catalina (10.15.7).

**Comment by djc** [comment]
Seems to be available as an option: https://github.blog/changelog/2020-10-29-github-actions-macos-big-sur-preview/.

Do we have reason to think Big Sur is very different from Catalina for the things we care about?

**Comment by sayrer** [comment]
It is no longer available as described there (they had to limit access in January 2021). I just filed it to make a note, as I was surprised to discover that macOS GitHub tests run on 2013 Mac Pros without AVX2, etc. Newer Intel and ARM macOS builds would be more realistic.

**Comment by ctz** [comment]
I think this is obsolete now -- but I think macos-latest, windows-latest and ubuntu-latest are pretty reasonable targets for us to build and test on.
