### ISSUE TITLE
"webpki" now out of sync with "rustls"

### ISSUE THREAD

**Issue by John-Nagle** [rustls/rustls#687]
Over at "webpki", "DNS" in names has been changed to "Dns", and "TLS" has been changed to "Tls". This prevents rustls 0.22 and webpki 0.22 from playing well together. Had to back off webpki to 0.21.

**Comment by djc** [comment]
Yes, released rustls is only compatible with webpki 0.21. The main branch already switched to webpki 0.22 though, so the next release will have it. Is there any particular reason you want to use newer webpki?

**Comment by John-Nagle** [comment]
I was just using the versions crates.io suggested. That didn't work.

**Comment by briansmith** [comment]
@John-Nagle Are you by chance trying to use webpki-roots 0.22? If so, it won't work. You have to use a version of webpki-roots that matches the version of webpki (0.21) used by the Rustls release you are using.

**Comment by John-Nagle** [comment]
Rustls/webpki, both at 0.22 did not work together, as noted above.

**Comment by briansmith** [comment]
There is no rustls 0.22. Could you post a link to the build log?

**Comment by John-Nagle** [comment]
rustls = {version = "0.19", features = ["dangerous_configuration"]}
rustls-pemfile = "0.2"
#   Always get the latest TLS certificates
- webpki = "0.21.0"
- webpki-roots = "*"
+ webpki = "0.21"
+ webpki-roots = "0.21"

That's what fixed the problem. I wanted to always get the latest trust roots, so I had "*" for that, expecting it to be pure data.

**Comment by VictorKoenders** [comment]
Is there an estimate on when the next rustls release is, or what you really want to have fixed for the next rustls release?

**Comment by djc** [comment]
We have no concrete timeline, since a lot of the work happening in this repository depends on volunteer efforts. However, I personally hope we will able to release rustls 0.20 in the next few weeks or so.
