### ISSUE TITLE
admin/fmt doesn't format all the Rust source code

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#693]
For example, fuzz/fuzzers/server.rs isn't getting formatted using the script.

**Comment by djc** [comment]
This seems to happen because the fuzz crate is not part of the top-level workspace. I can fix the CI to separately format the fuzz workspace? Then you'd still be on the hook to run `./admin/fmt` in `fuzz` yourself, though (the same would happen for `cargo fmt`, I think.)

**Comment by briansmith** [comment]
> Then you'd still be on the hook to run `./admin/fmt` in `fuzz` yourself, though (the same would happen for `cargo fmt`, I think.)

admin/fmt should just `cargo fmt` everything it needs to format.

**Comment by ctz** [comment]
Deleted in 6628e5465 once we could use stable rustfmt
