### ISSUE TITLE
Cargo warns "file found to be present in multiple build targets: rustls/rustls/tests/benchmarks.rs"

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#694]
Every time I build Rustls using Cargo I get this warning:

```
warning: /home/runner/work/rustls/rustls/rustls/Cargo.toml: file found to be present in multiple build targets: /home/runner/work/rustls/rustls/rustls/tests/benchmarks.rs
```

It would be nice to get a warning-free build.

**Comment by djc** [comment]
The benchmark we have depends on the utility code used by the integration tests. I guess we could move the utility code into a separate crate, depended upon by path?

**Comment by briansmith** [comment]
> The benchmark we have depends on the utility code used by the integration tests. I guess we could move the utility code into a separate crate, depended upon by path?

I think that is a good idea.

**Comment by kiwipool** [comment]
Hi, I'm trying to build rustls and getting the same warning that Brian has mentioned above and the build fails

Building as follows:

cd /home/$USER/git/rustls/rustls

cargo build

warning: /home/cnuser/git/rustls/rustls/Cargo.toml: file found to be present in multiple build targets: /home/cnuser/git/rustls/rustls/tests/benchmarks.rs

Any other ways to get this successfully built?

M

**Comment by djc** [comment]
This particular warning doesn't prevent Cargo from building rustls (at least I haven't seen it actually fail). So feel free to just ignore it for now (as everyone else has so far).
