### ISSUE TITLE
Support TLS-SRP

### ISSUE THREAD

**Issue by SoniEx2** [rustls/rustls#727]
TLS-SRP is the ***only*** TLS-on-LAN system that actually works today. Ideally it'd be TLS-[OPAQUE](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-opaque) but that isn't yet a thing. Anyway, would it be possible to have an aPAKE (asymmetric PAKE, means the server doesn't store the password) API and use TLS-SRP under the hood for now (which isn't considered insecure altho it is crappy) but then switch to TLS-OPAQUE if that ever becomes available?

The benefit of TLS-SRP is just on LAN. On LAN, your options are:

1. [Some hacks](https://letsencrypt.org/docs/certificates-for-localhost/) that are trivially vulnerable to DNS hijacking, even when done "properly" for some definition of "properly" (especially if the attacker is in the LAN - which is our use-case for TLS-SRP).
2. Ignoring the cert entirely, thus achieving ARP attack vulnerability. But hey, at least this doesn't require relying on public DNS.
3. TLS-SRP, which mitigates the above vulnerabilities. It's vulnerable to weak passwords but, eh, so is life.
4. DIY CA. Forget it, not gonna happen, nobody should need to setup a DIY CA just to run software locally. Especially when things like mDNS exist, which greatly simplify running software on a LAN. Besides, if you have the CA private key behind a password on the LAN, it's no more secure than the TLS-SRP, and in fact may be *less* secure if the NAS protocol is using plaintext passwords.

All in all, TLS-SRP is the best option for a LAN. It's more secure than even running a DIY CA, simply because it's harder to get wrong. Sure, it doesn't allow anonymous access, but do you really need anonymous access for something on a *LAN*?

Anyway, maybe rustls wants ppl to avoid enforcing TLS, so that their apps can be used on a LAN. However, it'd be better to just enforce TLS and patch over the LAN issue instead. So this feature would be greatly appreciated, for the sake of just straight-up enforcing TLS, yet still maintaining compatibility with the LAN.

**Comment by djc** [comment]
I don't see that many downsides to the DIY CA scenario. Using something like the rcgen crate, having a single CA certificate and signing the other entities with that cert seems perfectly serviceable for LANs to me.

I doubt that we'll prioritize TLS-SRP any time soon.

**Comment by sayrer** [comment]
I don't think TLS-SRP is long for this world. The CFRG has chosen OPAQUE instead. See: 

https://mailarchive.ietf.org/arch/msg/cfrg/LKbwodpa5yXo6VuNDU66vt_Aca8/

and the first effort at integration with TLS 1.3:

https://datatracker.ietf.org/doc/html/draft-sullivan-tls-opaque-00

**Comment by tglman** [comment]
Hi, 

I understand that this protocol is not too widely used for implementing it, does it exist a good alternative that can be used to get "TLS SRP" or maybe to own bake it from multiple crates ?

Bye

**Comment by djc** [comment]
What problem are you solving? What capabilities do you need for it and why do you think TLS-SRP is the solution?

**Comment by djc** [comment]
As I understand it, the new hotness here (adopted by the WG) is draft-ietf-tls-pake-01.

https://datatracker.ietf.org/doc/draft-ietf-tls-pake/

**Comment by sayrer** [comment]
> As I understand it, the new hotness here (adopted by the WG) is draft-ietf-tls-pake-01.
> 
> https://datatracker.ietf.org/doc/draft-ietf-tls-pake/

That's correct. You can probably close this one and aim at that new draft.

**Comment by tglman** [comment]
Hi,


The software I develop is already using cert based ssl already as optional configuration, anyway is open source software that I do not control where/how is run, actually the server side is java, and I'm building client side with rust, In that context I do want to provide a encrypted connection also when the user do not setup a certificate, and because the basic setup already require a password, building encryption on top of that it looked as the most obvious solution. (all of this is just using SSL sockets and custom protocol  not ~HTTPS ) 

Also I do not have preference on the algorithm itself as far as is supported by [BoyncyCastle](https://www.bouncycastle.org/) I'm happy with it.

Thank you for all the work, and let me know if I can help somehow on it.

Regards

**Comment by sayrer** [comment]
FWIW, the use case for 

https://datatracker.ietf.org/doc/draft-ietf-tls-pake/

has been said to be bootstrapping home devices (Homepod, Apple TV, etc)
