### ISSUE TITLE
Generalize support for per-key AEAD limits from QUIC to TLS

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#755]
In PR #750 we're planning to expose information about the AEAD algorithm's limits as far as the amount of data that is safe to encrypt and/or authenticate using a given AEAD key. The idea is that the application should do a key update or close the connection before hitting either limit.

It seems like the same thinking applies to TLS, both TLS 1.2 and TLS 1.3. We should consider having the TLS API, not just the QUIC API, exposes a good interface for dealing with this. In the case of TLS 1.2 then the only option would be to close the connection since we don't support renegotiation. For TLS 1.3 key update could be used.

BTW, I seem to remember that the limits mentioned in RFC 9001 were derived in a quite approximate way. We might want to redo the math before we decide what limits to expose.

Also, for a TLS connection, we should consider keeping track of the number of bytes encrypted and/or authenticated and refuse to exceed those limits. This is beyond what the QUIC stuff in PR #750 does.

**Comment by briansmith** [comment]
See https://cfrg.github.io/draft-irtf-cfrg-aead-limits/draft-irtf-cfrg-aead-limits.html. Note that we should double-check the logic and math there.

**Comment by djc** [comment]
https://datatracker.ietf.org/meeting/110/materials/slides-110-saag-analysis-of-usage-limits-of-aead-algorithms-00.pdf

**Comment by briansmith** [comment]
* Right now we use hard-coded, not-algorithm-specific, key limits: `static SEQ_SOFT_LIMIT: u64 = 0xffff_ffff_ffff_0000u64; static SEQ_HARD_LIMIT: u64 = 0xffff_ffff_ffff_fffeu64;` If we're going to use limits different than the ones we expose for each algorithm, then we should have tests to verify that `SEQ_SOFT_LIMIT` is less than the limit of every algorithm we support, and that `SEQ_HARD_LIMIT` is less than or equal to the limit of every algorithm we support. Or else we should use algorithm-specific limits. I having soft one soft limit for all algorithms makes sense, but maybe the hard limit should be per-algorithm? Quinn already uses the algorithm-specific limits, though they don't seem to implement the "soft" limit idea, which seems wrong?

* When we git `SEQ_SOFT_LIMIT`, we send a `close_notify` alert for all versions of TLS 1.3. We should only do that for TLS < 1.3 (if even then). For TLS 1.3, we should initiate a key update. Quinn already does this, although again they use different limits.

* This is another case where we need to send data in response to receiving a message post-handshake, after the handshake has completed, independent of any request by the user to send data. This is similar to alerts and responses to key updates.

The code as of today is https://github.com/rustls/rustls/blob/3e466251eb73bf05fe452aadff9764ac0222c6b0/rustls/src/conn.rs#L977-L984

**Comment by Ralith** [comment]
> though they don't seem to implement the "soft" limit idea, which seems wrong?

Can you elaborate on this? Quinn triggers a key update immediately when the number of packets sent with a certain set of keys is within 10k packets of the limit. Given that there's no roundtrip needed for a key update to execute, this should be quite robust.

**Comment by briansmith** [comment]
> Can you elaborate on this? Quinn triggers a key update immediately when the number of packets sent with a certain set of keys is within 10k packets of the limit.

Sorry, I overlooked the "10k" part as I was reading the code from the GitHub search results and I didn't notice the `KEY_UPDATE_MARGIN` stuff. I'll strike out that part of my comment above.
