### ISSUE TITLE
How practical would it be to make structures related to traffic encryption/decryption and secrets handling public?

### ISSUE THREAD

**Issue by p1-mmr** [rustls/rustls#786]
Hello,

In RusTLS 0.19.1, the `rutls::session::SessionSecrets` struct was module-public, and the corresponding module crate-public: https://github.com/ctz/rustls/blob/v/0.19.1/rustls/src/session.rs#L281

In the RustTLS 0.20.0 beta, the `rustls::conn::ConnectionSecrets` struct is crate-public: https://github.com/ctz/rustls/blob/v/0.20.0-beta1/rustls/src/conn.rs#L437

Similarly, in RustTLS 0.19.1, the `rustls::cipher::MessageDecrypter` trait was module-public, and the corresponding module crate-public: https://github.com/ctz/rustls/blob/v/0.19.1/rustls/src/cipher.rs#L14

In the RustTLS 0.20.0, it is now as well as associated stuff crate-public: https://github.com/ctz/rustls/blob/v/0.20.0-beta1/rustls/src/cipher.rs#L15

My use case of RustTLS is to attempt to statically decrypt TLS traffic from a given NSS-format `SSLKEYLOGFILE` file, containing connections secrets.

It is not practical to me to rely on the functions of the crate instancing this code because:

1. Obviously, I can't send back a Server Hello to a Client Hello as there is no interactivity in my context
2. And I can't neither perform any kind of Diffie-Hellman or curve-based exchange: I need to use the secrets that I was directly provided from an external source

However, RusTLS internally provides relevant packet decryption and TLS frame parsing routines that I am willing to use.

Hence, I would like to know how possible and conceivable it would be to make the parts of the corresponding module exposed to external users by changing attributes, without having to copy/fork the corresponding parts of the code?

Regards,

**Comment by p1-mmr** [comment]
I think that [exposing under `::internal`](https://github.com/ctz/rustls/blob/v/0.20.0-beta2/rustls/src/lib.rs#L287) like you do for the `::msgs` module could be great.

(If useful to precise, the subject of this use case would be to provide PCAP-formatted and reprocessed excerpts of decrypted TLS traffics generated by our own application for debugging purposes.)

**Comment by djc** [comment]
I suppose exposing it under `internal` would be okay. @ctz what is the purpose for `internal` that you had in mind? Is it mainly in order to enable testing from our side, or do you explicitly want to support the use cases from this issue and #784 as long as it doesn't cause extra maintenance burden in terms of semantic versioning?

**Comment by djc** [comment]
@p1-mmr do you want to propose a PR exposing everything you need through `internal`? Then we can assess what you need exactly and whether we're okay exposing it in that namespace.

**Comment by p1-mmr** [comment]
Hello,

@djc Done: https://github.com/rustls/rustls/pull/815

**Comment by djc** [comment]
Merged the PR. I think this just covers TLS 1.3, if someone would like 1.2 support that needs to be added still.
