### ISSUE TITLE
Session resumption in TLS 1.2 violates RFC 

### ISSUE THREAD

**Issue by tanyav2** [rustls/rustls#797]
In the section of code for session resumption in TLS 1.2, the case where `session_id` has length zero for both `resuming` and `self` is not considered: https://github.com/rustls/rustls/blob/5e9ccd4b5b1154ac4b55316dfad178ba09957069/rustls/src/client/tls12.rs#L114-L115

According to the [TLS 1.2 RFC](https://datatracker.ietf.org/doc/html/rfc5246)

> The server may return an empty session_id to indicate that the session will not be cached and therefore cannot be resumed.

This can cause an error where a peer switches from using TLS 1.3 to TLS 1.2 (which causes a change in the negotiated ciphersuite) which results in a `PeerMisbehavedError` being thrown: https://github.com/rustls/rustls/blob/5e9ccd4b5b1154ac4b55316dfad178ba09957069/rustls/src/client/tls12.rs#L117-L122

I have reproduced the error here: https://github.com/tanyav2/replicate-rustls-bug

This doesn't occur when a TLS 1.2 server is restarted again using TLS 1.2 because when the `rustls-client` sends a certain `session_id` to the server, and the server responds with an empty `session_id`, which are different, and so the session is not resumed.

However, if the client first connects to a server running TLS 1.3, and then the server is restarted with TLS 1.2, the client sends an empty `session_id` because it is expecting to connect to a TLS 1.3 server. But because the server is now TLS 1.2, the empty `session_id` that the server sends in response matches the client's `session_id`, and the client ends up believing that the server is agreeing to resume the session. 

The fix can be something like https://github.com/tanyav2/rustls/blob/d70ee9240209d4acafdaf7cac1f911f9c681e5b5/rustls/src/client/tls12.rs#L113-L114:
```rust
    if (SessionID::empty() != resuming.session_id)
        && (resuming.session_id == self.session_id) 
    {
        debug!("Server agreed to resume");
```

The other thing worth noting is when TLS 1.2 server is restarted, it has an empty `session_id` but it sets the `SessionTicketAck` extension in response to the `SessionTicketOffer` sent by the client during `ClientHello`. However, when the server is downgraded from 1.3 -> 1.2, the client doesn't send a `SessionTicketOffer` or `SessionTicketRequest`, so the server doesn't respond with a `SessionTicketAck`.

**Comment by briansmith** [comment]
@tanyav2 Which version of Rustls were you testing? Could you please repeat your test with the current `main` branch and report back the results? Thanks!

**Comment by tanyav2** [comment]
> @tanyav2 Which version of Rustls were you testing? Could you please repeat your test with the current `main` branch and report back the results? Thanks!

I have updated https://github.com/tanyav2/replicate-rustls-bug to use the latest version of `rustls` from the main branch and I get the same error. I'm using the version of `tokio-rustls` that was updated to use the current `main` branch of `rustls` here: https://github.com/tokio-rs/tls/pull/68

I added `branch = "main"` here: https://github.com/djc/tls/blob/eliza/rustls-0.20/tokio-rustls/Cargo.toml#L16 to ensure that the latest version of `rustls` gets used.
