### ISSUE TITLE
Try renego implementation for a specific need

### ISSUE THREAD

**Issue by CedricCouton** [rustls/rustls#801]
Hi all,

We have to implement a tls client which should be compatible with the renegotiation protocol. I know and I understood why it's not currently implemented in rustls. But, I want to test an implementation of it. I create this PR with my quick and dirty modification for it. #800 . My context : a server which establish a basic tls link and after the fist applicationData message it want to renegotiate the link with a client certificate.
Here the messages scenario : 

> Basic tls link : ClientHello , ServerHello, Certificate, ServerKeyExchange, ServerHelloDone, ClientKeyExchange, Finished, Finished
> First Application Data
> Renego : HelloRequest, ClientHello , ServerHello, Certificate, ServerKeyExchange, CertificateRequest, ServerHelloDone, Certificate, ClientKeyExchange, CertificateVerify, Finished, Alert (BadRecordMac)

So I have a BadRecordMac after the client Finished message at the end of the renego. 
Note : 

> If I test rustls with another server which ask the client certificate at the first handshake there is no problem.
> If I test the same server (which ask the renego) with a java client, all it's good

After around 10 days of research, without the server log, I'm dry .
 With your high experience on TLS protocol would you have an idea of what I made wrong in my quick and dirty implementation of the renego. My researches indicate that it's probably the encrypter use for the Finished message which is incorrectly initialized but I don't see anything. So please can you help me ?

 thanks very very much in advance!

**Comment by djc** [comment]
Since we don't want to support renegotiation in rustls due to questionable security, I don't feel it makes sense for us to spend time/energy on your project. Therefore I'll close this issue and the associated PR.

**Comment by briansmith** [comment]
> a server which establish a basic tls link and after the fist applicationData message it want to renegotiate the link with a client certificate.

@CedricCouton Are you aware that TLS 1.3 implements protection for the client certificate similar to this mechanism that uses TLS 1.2 + renegotiation? Is there any way you could enable TLS 1.3 for this application? That would be a cleaner way to achieve the same effects.
