### ISSUE TITLE
FreeBSD root certificates

### ISSUE THREAD

**Issue by LukeMauldin** [rustls/rustls#817]
I have a FreeBSD 13 system and curl looks for certificates in /bin/local/share/certs/ca-root-nss.crt 
What path(s) does rustls search for on FreeBSD for certificates?

**Comment by Ralith** [comment]
rustls does not contain certificate search logic. Were you looking for https://github.com/rustls/rustls-native-certs?

**Comment by LukeMauldin** [comment]
Yes, that pointed me to the correct location.  Thank you.
