### ISSUE TITLE
Why Does tls1.3 Not Support RSA_PKCS1_SHA256?

### ISSUE THREAD

**Issue by silence-coding** [rustls/rustls#818]
https://github.com/rustls/rustls/blob/14c024db16354c189ad6f5b3430cfca477ebcd8a/rustls/src/sign.rs#L384

https://tlswg.org/tls13-spec/draft-ietf-tls-rfc8446bis.html
![image](https://user-images.githubusercontent.com/32766901/133068155-63c15116-e2dd-4c8a-996f-ed7a2efc6f04.png)

**Comment by djc** [comment]
There is some discussion of RSA PKCS1 here: https://docs.rs/rustls/0.19.1/rustls/manual/_02_tls_vulnerabilities/index.html#rsa-pkcs1-encryption. It seems to be talking about key exchange more than signing, though, in which case I'm not sure why rustls doesn't have support for these particular signature schemes.

 To turn the question around: why do you need/want support for RSA_PKCS1_SHA256?

**Comment by silence-coding** [comment]
Well, I find that the pkcs1 padding algorithm seems to be more widely used, and I've had cases where only pkcs1 is supported.

https://crypto.stackexchange.com/questions/48407/should-i-be-using-pkcs1-v1-5-or-pss-for-rsa-signatures

**Comment by ctz** [comment]
`rsa_pss_rsae_sha256` is mandatory-to-implement in TLS1.3 ([ref](https://datatracker.ietf.org/doc/html/rfc8446#section-9.1)), so in my opinion it is reasonable to rely on the peer to support it if we negotiate this version.

While it is true that PKCS#1 signatures do not have known major cryptographic weaknesses, it does have a reasonable amount of implementation defect baggage. And while PSS is indeed more complex, with a silly amount of configurability, fundamentally it's a better design than PKCS#1 signatures.

**Comment by silence-coding** [comment]
@ctz Thank you very much. If TLS 1.3 mandates a pss algorithm, I don't think the implementation of pkcs1 should be an urgent need.
