### ISSUE TITLE
Add support for requesting a client certificate without giving the list of DNs

### ISSUE THREAD

**Issue by horazont** [rustls/rustls#828]
As far as I can tell, that is supported by TLS in general. 

It is obviously suboptimal in some situations (such as when used with interactive clients which have to choose from a set of certificates). However, in server-to-server situations where the standard server side certificates are used, having to send the DNs of the entire root store is really excessive (in addition, it causes interops with some Java SSL implementation which restricts handshake packets to 32 kiB – which is easily exceeded when sending the list of DNs from the entire root store).

So I would wish for [ClientCertVerifier::client_auth_root_subjects](https://docs.rs/rustls/0.20.0-beta2/rustls/trait.ClientCertVerifier.html#tymethod.client_auth_root_subjects) to have a way to say "No, don't send any root DNs, but also keep the connection going."

**Comment by horazont** [comment]
Ohhh… I only now realized that I can just pass `Some(Vec::new())` … Would you mind a trivial patch to the docs to make that explicit? ("An empty vector can be returned if no hint about the allowed CAs should be sent to the client" or so)

**Comment by djc** [comment]
Sounds good, thanks!
