### ISSUE TITLE
`UnknownIssuer` with cert from private CA

### ISSUE THREAD

**Issue by cmusser** [rustls/rustls#841]
RustTLS is returning `UnknownIssuer` errors when attempting to verify a certificate signed with my private CA. I use `openssl` to perform all the CA operations (request generation, cert signing). The CA has a root cert and an intermediate cert I use to sign the leaf certs. Initially, I encountered this problem using the Quinn crate, but I also get the error with `tlsserver` and `tlsclient`. However if I  use OpenSSL's `s_client` instead of `tlsclient` (using the same CA parameters), it can connect to the `tlsserver` just fine.

This is how I run the test programs:

    cargo run --example tlsserver -- --port 5001 --certs ~/tls-test/fullchain.pem --key ~/tls-test/key.pem --verbose echo

    echo "hello there" | cargo run --example tlsclient -- --port 5001 --cafile ~/tls-test/private-ca-root.pem myhost.internal

    openssl s_client -CAfile ~/tls-test/private-ca-root.pem -connect myhost.internal:5001

The `tlsclient` invocation fails with `UnknownIssuer` and if I run it with `--verbose`, it additional says `BadCertificate`.

Other information:

- The intermediate signing cert has DNS name constraints: `internal` (which is the domain I used for tests) `a54` a made up top-level I used at some point, and `a54.io` which is a valid domain. `a54` is clearly not valid, and I am not sure `internal` is either. I don't know if any of this is significant to RusTLS.

- I tried a cert provided by Let's Encrypt and `tlsclient` was able to successfully verify it (as was `s_client`).

Any ideas what causing the `UnknownIssuer` error?

**Comment by YT-SUN97** [comment]
Hi, I guess I met the same problem when using webpki. Did you solve it?
