### ISSUE TITLE
Release 0.20.1

### ISSUE THREAD

**Issue by paolobarbolini** [rustls/rustls#843]
https://github.com/launchbadge/sqlx/pull/1505 depends on 6d673fbf90da4d75944d4ad3abddb2e836c0efce. When is the next release planned to be done?

**Comment by djc** [comment]
(Added #847 to the list.)

**Comment by djc** [comment]
Also want #836 for https://github.com/rustls/hyper-rustls/pull/156.

**Comment by ctz** [comment]
https://crates.io/crates/rustls/0.20.1
