### ISSUE TITLE
Passing multiple --protover flags to tlsclient

### ISSUE THREAD

**Issue by xvzcf** [rustls/rustls#855]
The [tlsclient usage string](https://github.com/rustls/rustls/blob/main/rustls-mio/examples/tlsclient.rs#L313) says that the `--protover` flag `May be used multiple times.` 

How does one do so? I've tried passing in  `--protover 1.2 --protover 1.3`, `--protover 1.2 1.3` among other variations, but I just get an `Invalid arguments.` response.

**Comment by tanyav2** [comment]
Created a PR that should fix the issue, it needs to be used as `--protover 1.2 --protover 1.3` because `docopt` doesn't allow multiple arguments for an option as it goes against standard POSIX cli: https://github.com/docopt/docopt/issues/484#issuecomment-680743971
