### ISSUE TITLE
Writable/Readable on stream

### ISSUE THREAD

**Issue by huguesBouvier** [rustls/rustls#857]
OwnedReadHalf, OwnedWriteHalf obtained when splitting regular TcpStream contains useful function like Writable, Readable.

However, when creating a tlsStream and splitting it, we get the type:
WriteHalf, ReadHalf

Those type don't implement those important feature. 
They are necessary for implementing a correct Tcp proxy for example.

**Comment by djc** [comment]
I'm not sure exactly what you mean. rustls does not expose, as far as I can tell, a `TlsStream` type. Are you referring to tokio-rustls' [TlsStream](https://docs.rs/tokio-rustls/0.23.1/tokio_rustls/enum.TlsStream.html)?

**Comment by jsha** [comment]
@huguesBouvier you might also be interested in reading #288.

**Comment by briansmith** [comment]
@huguesBouvier As @djc said, I think we need a little more hand-holding to understand what you're asking for.

**Comment by bdaehlie** [comment]
No update from reporter in a while, closing.
