### ISSUE TITLE
Howto SNI-dependent Client CA?

### ISSUE THREAD

**Issue by moschroe** [rustls/rustls#859]
I am working on a TLS proxy where one socket will accept connections for any number of server names and if client authentication is configured for a particular server name, then it will need have its separate CA(s) to check client certs against.

Prior to 0.20, there was a sni parameter for all the `ClientVerifier` callbacks. This has been removed in favour of an `Acceptor` where a whole different `ServerConfig` with any custom `ClientVerifier` can be provided to `into_connection()`.

Am I correct in my understanding that there is currently no other way to have separate trust roots for client cert verification? There seems to be no convenient equivalent to `ResolvesServerCert` (like a fictitious `ResolvesClientCa`).

**Comment by djc** [comment]
Yes, I think that is correct. See #473 for more discussion; having a `ResolvesClientCa` trait might make sense, I guess?

**Comment by moschroe** [comment]
If there was a way to provide a resolver into the rustls machinery as part of a ServerConfig, one could reuse existing code and tack on this functionality without much effort (on the library user side, of course).

Changing from a `ServerConnection` to an `Acceptor` requires changes to topology and state machines using rustls in order to implement an entirely new workflow for handling connections.

**Comment by djc** [comment]
The `Acceptor` gives you much more freedom (notably including the use of async/await). I suspect we might go with a similar approach for this, see #850.

**Comment by moschroe** [comment]
So much for trying to talk myself out of some work :) I'll go on to refactoring then.

Just for clarity:
1. Assume there is a TCP socket listening
2. on TCP accept, create new `Acceptor`
3. while `Acceptor::accept()` is `Ok(None)`, keep running `Acceptor::read_tls(&mut tcp_stream)`
4. Inspect `Accepted` for Client Hello, adapt config as appropriate
5. then turn into `ServerConnection` with `Accepted::into_connection(fancy_cfg)`, continue as before from here

Right?

**Comment by djc** [comment]
That's pretty much right. You might want to keep a collection of `Arc<ServerConfig>`s ready to go on the side of the `Acceptor` so you can minimize the work in building one.

**Comment by moschroe** [comment]
Thank you very much!
