### ISSUE TITLE
Recognise two more cipher suites (how to add to `enums.rs`?)

### ISSUE THREAD

**Issue by ShadowJonathan** [rustls/rustls#864]
Heya, when looking at [this](https://github.com/pion/dtls/blob/415eb6f8a18b35b8fbae137c83046692e159f1e6/internal/ciphersuite/ciphersuite.go#L48-L67) description of cipher suites, I noticed that the top two weren't in `enums.rs`.

These two are defined in [rfc7251](https://datatracker.ietf.org/doc/html/rfc7251#section-2), while not necessary, i'm interested in what the process is in adding these cipher suite numbers to `enums.rs`, if any.

**Comment by djc** [comment]
I'm guessing this primarily depends on https://github.com/briansmith/ring/issues/25.

**Comment by ShadowJonathan** [comment]
Huh, does `enums.rs` only contain combinations that can possibly be supported, or are those just the ones that're recognised?

**Comment by djc** [comment]
Ah, sorry -- in that case we can probably just add them to `enums.rs`. Want to submit a PR?

**Comment by ShadowJonathan** [comment]
I was thinking about it, but i saw that it was auto-generated, and it made me think of `go generate`, in which case adding something to a generated file wouldn't be useful, as it is drawing the data from somewhere else. This issue was more to ask if this is the case, or if me adding these cipher suites as-is to the files is okay.
