### ISSUE TITLE
Fill `enums.rs` CipherSuite information from ciphersuite.info

### ISSUE THREAD

**Issue by ShadowJonathan** [rustls/rustls#866]
https://ciphersuite.info/ contains a list of cipher suites and their hex codes, i think it would be interesting if `enums.rs` could be more exhaustively defined (possibly with an automated tool to occasionally update it) by the hex codes defined on that site.

**Comment by ctz** [comment]
IANA is the canonical source for these: https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml

**Comment by djc** [comment]
@ctz should we keep the comment about these being auto-generated from ctz/tls-hacking or do we now maintain these here?

**Comment by ShadowJonathan** [comment]
I think either we could maybe change the comment to something like "this file was *initially* generated...", or a tool that updates this file from that site could be maintained under a contrib part of the library, and the comment updated to reflect the relative path to there.
