### ISSUE TITLE
Support client TLS connection to a server without having the full chain

### ISSUE THREAD

**Issue by didjcodt** [rustls/rustls#883]
Hello, 
I am currently using rustls as part of a dependency to Tonic in order to connect to a gRPC server. During the connection, I insert the root CA certificate. The server presents a full chain containing the root CA certificate and its intermediate certificate.
When connecting, I get the following error:
```
[2021-12-15T11:21:46Z WARN  rustls::session] Sending fatal alert BadCertificate
Error: transport error

Caused by:
    0: error trying to connect: invalid certificate: UnknownIssuer
    1: invalid certificate: UnknownIssuer
```

If I connect using the intermediate certificate, it works. Is there any way to use to root CA only?

Thanks,

**Comment by djc** [comment]
It's a little unclear to me what you mean by

> During the connection, I insert the root CA certificate.

and

> If I connect using the intermediate certificate, it works.

As far as I know clients should only configure the trust roots, and servers are supposed to return any necessary intermediates as well as the root to prove their certificate can be trusted.

**Comment by didjcodt** [comment]
What I mean is that in the client code I fill `root_store` in `ClientConfig` with the CA certificate, and the server is already returning the intermediates but it seems to be ignored by rustls. This is a behaviour I did not expect because in the other clients I wrote in go/python, I always gave only the CA certificate to the client and everything was working out of the box.

**Comment by djc** [comment]
This is certainly supposed to work, so there is likely something about your particular CA or intermediate certificates that rustls (or really, webpki) doesn't know how to deal with.

**Comment by didjcodt** [comment]
Do you know any way I could debug this?

**Comment by djc** [comment]
Well, I would use a standalone reproducer with a patched copy of webpki and put some `println!()` statements in to see where it's throwing an `UnknownIssuer`. You might also want to use the `openssl` binary to print a textual representation and compare it to other CA certs that work (you might also put it here so I can have a look).

**Comment by didjcodt** [comment]
Ok, I'll try debugging with `println!` and see up to where I can go, and I'll post the results here :)
Thanks :)

**Comment by didjcodt** [comment]
After some digging into `webpki` and `ring` I finally found out that the issue I have is linked to this issue: https://github.com/briansmith/webpki/pull/226
I'll close this issue as it's not linked to rustls directly.

Thanks for the help :)

**Comment by djc** [comment]
I'm happy that you figured it out, and sorry for the trouble!
