### ISSUE TITLE
Inaccurate docs for ServerCertVerifier impl of WebPKIVerifier

### ISSUE THREAD

**Issue by teisenbe** [rustls/rustls#885]
The docs for the `ServerCertVerifier` impl of `WebPKIVerifier` claim that `verify_server_cert` verifies that OCSP data was present, but the function's result as implemented does not depend on the `ocsp_response` argument.

I don't think this is a particularly meaningful security vuln, given that the guarantee didn't even say anything about whether the OCSP data was valid, but the docs should probably be corrected. I'll send a PR in a few

**Comment by djc** [comment]
I see a PR in your fork, did you mean to submit that here?

**Comment by teisenbe** [comment]
Whoops, yes, thank you. I've moved it over
