### ISSUE TITLE
Handle the case where no supported versions are enabled

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#904]
Check out #903 and focus on this code when emitting ClientHello:

> ```rust
>     let mut exts = Vec::new();
>     if !supported_versions.is_empty() {
>         exts.push(ClientExtension::SupportedVersions(supported_versions));
>     }
> ```

My understanding of the TLS 1.3 spec is that a conformant client MUST always send the supported_versions extension, whether TLS 1.3 is enabled or not. Thus, we must not have any branch that skips adding the extension. It seems like we don't have tests for this?

**Comment by ctz** [comment]
Removed in 7aaffe69
