### ISSUE TITLE
Skip constructing `*Payload` types when serializing handshake messages

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#906]
Currently, we send the peer a handshake message by doing this following:
1. Construct a `Payload` structure, e.g. `ServerHelloPayload `.
2. Call `Codec::encode` on that structure.

Step #1 allocates a bunch of small objects on the heap, usually `Vec<_>` fields of the `Payload` structure.

In most (all?) cases (except potentially `ClientHelloPayload` in the future, if my proposal in #905 is accepted), for each `*Payload` type there appears to be a single caller that does both steps above, or the code could be easily refactored such. It seems like we could simply inline the `Codec::encode` implementation of the `Payload` structures into the callers. Then we could change the callers to have the encoding operate on the local variables that were used to construct the `Payload` type, eliminating the need to create the `Payload` object at all. This should eliminate many of the intermediate `Vec` allocations; further refactoring should make it possible to eliminate basically all of them.

Making this change to the serializing side would enable us to further refactor the `Payload` types so that they borrow data from the input handshake messages, avoiding the need for copying that data into `Vec` (though, it is more complicated than this). In turn, we'd have many fewer allocations in Rustls which would make #886 much more practical and should also improve performance and suitability for smaller embedded targets.

We should be able to do this incrementally, one handshake message type at a time.

**Comment by djc** [comment]
IMO having the outgoing messages represented by a concrete type rather than as a collection of encoding calls makes the code easier to read. If we just make the messages have Cow instead of Vec (and potentially slow further down the line) we'd achieve the same efficiency while retaining a design that is easier to follow.

**Comment by briansmith** [comment]
> IMO having the outgoing messages represented by a concrete type rather than as a collection of encoding calls makes the code easier to read.

I'm not sure that's true, because each `encode` function ends up being "a collection of encoding calls," and if there's only one caller then the result would be simpler.

> If we just make the messages have Cow instead of Vec (and potentially slow further down the line) we'd achieve the same efficiency while retaining a design that is easier to follow.

That's another thing that may work but it wouldn't enable the idea in #907, AFAICT.

**Comment by briansmith** [comment]
> If we just make the messages have Cow instead of Vec

When I experimented with this, I think `Cow<[T]>` wouldn't work. With `Cow<[T]>`, even in the borrowed case you need a slice. In order to build the slice in our code, we often need a `Vec<T>` with `Cow<[T]>` since there are a variable number of items in many of the things we encode. However, if we instead used `IntoIterator<Item = T>` and/or `IntoIterator<Item = Result<T, Error>>` instead, then things could be made to work without allocations in more cases.

> (and potentially slow further down the line)

What do you mean by "potentially slow further down the line"? Maybe a typo?

**Comment by djc** [comment]
> I'm not sure that's true, because each `encode` function ends up being "a collection of encoding calls," and if there's only one caller then the result would be simpler.

It might be simpler, but unlike the version where there's a type specifying what a message consists of, you lose the support of the type system in ensuring that all the required fields are encoded. Instead, you have to rely (more) on code review to see that all the elements are encoded into the message in the correct order. In the current approach, you sort of still have that problem but it's better contained. We might even consider writing procedural macros to generate `Codec` impls for us (although that would come at the cost of additional dependencies).

> What do you mean by "potentially slow further down the line"? Maybe a typo?

Yeah, "slow" -> "slice".

> When I experimented with this, I think `Cow<[T]>` wouldn't work. With `Cow<[T]>`, even in the borrowed case you need a slice. In order to build the slice in our code, we often need a `Vec<T>` with `Cow<[T]>` since there are a variable number of items in many of the things we encode. However, if we instead used `IntoIterator<Item = T>` and/or `IntoIterator<Item = Result<T, Error>>` instead, then things could be made to work without allocations in more cases.

Fair enough. Maybe `impl Iterator<Item = T>` (or `&T` or `Result<T, Error>`) could work for both incoming and outgoing messages (I think you could write a generic `DecodingIterator` for the incoming side that covers TLS vectors).

**Comment by briansmith** [comment]
Good points.

> We might even consider writing procedural macros to generate `Codec` impls for us (although that would come at the cost of additional dependencies).

I would suggest we first try to just try regular macros and seeing if that will work. Regardless, I do think we should probably be able to generate the `encode` and `decode` methods for all the structures. Whether it ends up being a win or not is something that would take some experimentation, I think.

**Comment by briansmith** [comment]
Closing this based on the above discussion. I updated #907 with the relevant results from this discussion. Thanks for the feedback and good ideas.
