### ISSUE TITLE
Establish conventions for tracking whether the `main` branch is SemVer-compatible with latest release

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#928]
I can't tell if the `main` branch is intended to be SemVer-compatible with the latest release or not.

I suggest:
* We communicate clearly what our hopes are for maintaining SemVer compatibility in the main branch. I assume that by default we're OK with making SemVer-breaking changes whenever we feel like, and we've made SemVer-breaking-changes, but I've also seen comments saying we're deferring some SemVer-breaking-changes until later, for some reason. It's not clear what the goals are here, and it would be good to get clarity.
* When we knowingly make a SemVer-breaking change, we bump the crate version in rustls/Cargo.toml accordingly.

**Comment by djc** [comment]
Bumping the crate version (maybe to an alpha or beta pre-release version) when we make a semver-breaking change seems reasonable. I think we have not made (API) breaking changes since 0.20.2 so far (especially with the key log file change reverted).

I agree that keeping semver compatibility on the main branch isn't very important, since we can always branch off a release version if we need it. However, I also think batching up semver-breaking changes is valuable -- that is, we should not have semver-breaking releases more often than every few months or so.

**Comment by ZargorNET** [comment]
> Bumping the crate version (maybe to an alpha or beta pre-release version) when we make a semver-breaking change seems reasonable. I think we have not made (API) breaking changes since 0.20.2 so far (especially with the key log file change reverted).
> 
> I agree that keeping semver compatibility on the main branch isn't very important, since we can always branch off a release version if we need it. However, I also think batching up semver-breaking changes is valuable -- that is, we should not have semver-breaking releases more often than every few months or so.

Now you've broken async-nats https://github.com/nats-io/nats.rs/issues/1017 with the change in https://github.com/rustls/rustls/pull/1339

**Comment by ctz** [comment]
> Bumping the crate version (maybe to an alpha or beta pre-release version) when we make a semver-breaking change seems reasonable.

This ^ is the summary of what we're doing.

https://github.com/obi1kenobi/cargo-semver-checks now runs on both main (which at the time of writing has breaking changes, so the version in Cargo.toml is one ahead of the latest released line) and current release branch (which must not have breaking changes). Compare it's output for main and the release branch:

- https://github.com/rustls/rustls/actions/runs/5522413915/jobs/10071964137#step:3:43 (main)
- https://github.com/rustls/rustls/actions/runs/5522482950/jobs/10072139213#step:3:47 (release branch)
