### ISSUE TITLE
Certificate error variants are too tied to BOGO's expectations

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#932]
Currently we have these error variants intended to be used for certificate errors:
```
    /// We received an invalidly encoded certificate from the peer.
    InvalidCertificateEncoding,

    /// We received a certificate with invalid signature type.
    InvalidCertificateSignatureType,

    /// We received a certificate with invalid signature.
    InvalidCertificateSignature,

    /// We received a certificate which includes invalid data.
    InvalidCertificateData(String),
```
When implementing custom certificate verifiers we've found that we're often just returning `InvalidCertificateData` or else we're doing wasted work to return one of the other variants.

It seems like the distinction between these five variants is primarily driven by the desire of BOGO to differentiate between different types of errors. But, if that is the case then it would be good to find a way to limit this classification to just BogoShim and not require every implementation to do this classification. In some implementations it isn't clear that we even can accurately classify the errors returned by the underlying certificate verification library into the above.

If we implement my suggestion in #930, then we can have BogoShim do the mapping from webpki::Error to the five categories above, and save other implementations the trouble.

**Comment by briansmith** [comment]
Just to clarify, my recommendation here is that we replace all of the aforementioned variants with a single variant, perhaps `PeerCertificateInvalid(Box<dyn std::error::Error>`.

**Comment by jsha** [comment]
That would be a nice cleanup for rustls-ffi. Right now we offer a helper method to determine whether a returned error is related to certificate verification. It would be nice if there was a single error variant to check and we could do away with the helper method.
