### ISSUE TITLE
Is the interface for sending "0.5-RTT" data from the server to the client safe?

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#944]
I see this in the code:
```
    // when client auth is enabled, we don't sent 0.5-rtt data, as we'd be sending
    // it to an unauthenticated peer. so it happens here, in the server's second
    // flight (42 and 32 are lengths of appdata sent above).
    server.process_new_packets().unwrap();
```

This reasoning seems questionable to me. Client authentication being disabled (or optional?) isn't a sufficient condition for sending data to the client before the handshake has been fully authenticated (i.e. before receiving the client Finished message).

AFAICT "0.5-RTT data" is only mentioned in one place, in the QUIC spec, here:
> For instance, the server's first flight contains Initial packets, Handshake packets, and "0.5-RTT data" in 1-RTT packets.

The TLS 1.3 spec doesn't refer to it using that term, and it doesn't have much to say about that data except:
> Note that while the server may send Application Data prior to receiving the client's Authentication messages, any data sent at that point is, of course, being sent to an unauthenticated peer.

In particular, up until we receive the client's Finished message, a MitM can control which crypto algorithms (and other parameters) are negotiated, right?

Except in exceptional circumstances, the server shouldn't send any application data to the client until it has received the client's Finished message. AFAICT, this "0.5-RTT data" should be handled like 0-RTT data, both from the sender's and receiver's perspective.

In particular, why doesn't `ServerConnection` expose a `WriteEarlyData` for sending such data to the client, and then reserve the normal sending APIs for sending data only after the handshake completes? That seems like a much safer API design to me.

**Comment by Ralith** [comment]
> Except in exceptional circumstances, the server shouldn't send any application data to the client until it has received the client's Finished message.

To be clear, after the client's Finished message is received, the server can send 1-RTT data, right? i.e. you're observing that 0.5-RTT is, like 0-RTT, less secure and therefore merits an isolated API that is difficult to use by accident?

**Comment by briansmith** [comment]
> In particular, up until we receive the client's Finished message, a MitM can control which crypto algorithms (and other parameters) are negotiated, right?

Debating with myself here about this specific example: if the server doesn't authenticate the client, then a MitM that wants us to encrypt and send some data with a particular mutually-supported algorithm can do so regardless of whether we wait for Finished. Further, in TLS 1.3 any application data is encryption using keys are bound to all the prior handshake messages. So I don't think there's particular risk regarding data sent over the wire.

https://datatracker.ietf.org/doc/html/rfc8446#section-4.4.4 says:
> Once a side has sent its Finished message and has received and validated the Finished message from its peer, it may begin to send and receive Application Data over the connection. There are two settings in which it is permitted to send data prior to receiving the peer's Finished:
>  1.  Clients sending 0-RTT data as described in Section 4.2.10.
>   2.  Servers MAY send data after sending their first flight, but because the handshake is not yet complete, they have no assurance of either the peer's identity or its liveness (i.e., the ClientHello might have been replayed).

The thing I want to emphasize is the way this is stated, the default expectation of applications is "Once a side has sent its Finished message and has received and validated the Finished message from its peer, it may begin to send and receive Application Data over the connection;" the principle of least surprise tells us to require an opt-in before deviating from that expectation.

I would also extend this to any accessors we provide the user to data provided by the peer within the handshake: By default, we should have all accessors avoid returning that data unless/until it has been authenticated, which would mean having them return `None` until the peer's Finished message has been validated.

For some callback APIs, e.g. the one we use for choosing our certificate, we have to expose some data from the handshake to the callback; in these cases we should document clearly that that data is unauthenticated and provide guidelines on limiting how it is used or trusted.

In the case of things like QUIC transport parameters, it does seem like when we want to support sending "0.5-RTT data," it seems like we'd do so using an interface just like we use for early data, something like what I suggested at https://github.com/rustls/rustls/issues/655#issuecomment-1015805566. That makes it clear that that version/subset of the data is only to be used for that limited duration.
