### ISSUE TITLE
Is there Equivalent of ServerConfig::new(NoClientAuth::new()) in Builder mode?

### ISSUE THREAD

**Issue by Tsai002** [rustls/rustls#949]
I found there is no way to update to 0.23 because of this issue. And I checked new builder apis, none of them could get that.

**Comment by djc** [comment]
Have you tried this?

```rust
ServerConfig::builder()
    .with_safe_defaults()
    .with_no_client_auth()
    .with_single_cert(certs, private_key)
    .expect("bad certificate/key");
```

**Comment by Tsai002** [comment]
@djc Sorry. I update tokio-rustls from 0.22 to 0.23, I made a mistake.

I know `with_no_client_auth()`, but it returns ` ConfigBuilder` rather than `ServerConfig`. I have to call `with_single_cert_with_ocsp_and_sct` or `with_cert_resolver`, which you have to provide certs and keys. That's not the same as
`ServerConfig::new(NoClientAuth::new())`.

Thank you for your time.

**Comment by djc** [comment]
You can't run a server without setting a certificate (resolver), right? In the previous version you also had to do that, but you did it after instantiating the `ServerConfig`. Now, the builder API requires you to do it as part of building the config.

**Comment by Tsai002** [comment]
It's a local SMTP server.

```rust
if let Some(tls_config) = self.handler.tls_request().await {
        return Ok(Some(LoopExit::STARTTLS(tls_config)));
    } else {
        socket.send(Reply::not_implemented()).await?;
    }
```

```rust
Ok(LoopExit::STARTTLS(tls_config)) => {
            let acceptor = TlsAcceptor::from(tls_config);
            let mut tls_socket = acceptor.accept(socket).await?;
            config.enable_starttls = false;
            handler.tls_started(tls_socket.get_ref().1).await;
            match smtp_server(&mut tls_socket, &mut handler, &config, shutdown, false).await {
                Ok(_) => debug!("TLS Server done"),
                Err(e) => error!("TLS Top level error: {:?}", e),
            }
            tls_socket.shutdown().await?;
        }
```

**Comment by djc** [comment]
I meant the code that builds the `tls_config`.

**Comment by Tsai002** [comment]
```rust
let mut config = ServerConfig::new(rustls::NoClientAuth::new());
        config.set_single_cert(certs, key).unwrap();
let tls_config = Arc::new(config);
```

**Comment by Tsai002** [comment]
I mean if I did not set ` config.set_single_cert(certs, key).unwrap();`, It will return `ServerConfig`.

**Comment by djc** [comment]
So if you replace

```rust
let mut config = ServerConfig::new(rustls::NoClientAuth::new());
        config.set_single_cert(certs, key).unwrap();
```

with 

```rust
ServerConfig::builder()
    .with_safe_defaults()
    .with_no_client_auth()
    .with_single_cert(certs, key)
    .unwrap();
```

what is the problem?

**Comment by Tsai002** [comment]
The problem is if I have no certs and keys, it returns `ServerConfig`.

**Comment by djc** [comment]
So that's no longer supported. You'll need to defer the initialization of `ServerConfig` until you have the certs and keys.
