### ISSUE TITLE
`cargo check --all-features` is broken on non-nightly builds

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#951]
We now have the `read_buf` feature that only works on Nightly Rust. `cargo check --all-features` now only works on Nightly Rust. This is unfortunate as it has broken some workflows for people using Stable Rust, including in particular the way my IDE is set up to check/build Rustls. Also this has lead to a lot of ugliness in the CI/CD pipelines.

I suggest we change the semantics of the `read_buf` feature as follows:
* When `read_buf` is enabled, build.rs will check if Rust is currently a Nightly build. If so, then set a configuration flag "nightly" that will be tested in the source code. This might require adding a `rustc_version` or similar dependency if the `read_buf` feature is enabled.
* Change `cfg(feature = "read_buf")` to `cfg(all("nightly", feature = "read_buf"))` in the source code and tests.
* Once the `ReadBuf` API becomes stable, remove all of this.

**Comment by djc** [comment]
Yup, I also dislike the current setup. On the other hand, not a big fan of build scripts either. Seems like [#[rustversion::nightly]](https://docs.rs/rustversion/latest/rustversion/) could do the trick nicely, though?

**Comment by ctz** [comment]
Have we done something terribly wrong, or is it really this hard to have a crate feature that depends on an unstable std feature? As it is I agree it is pretty terrible.

The rustversion thing looks pretty reasonable; I guess this route we can just get rid of the feature altogether as AIUI the purpose of it was to avoid making rustls nightly-only.

**Comment by djc** [comment]
I don't think we've done anything wrong, so I guess it's really this hard.

**Comment by briansmith** [comment]
> On the other hand, not a big fan of build scripts either. Seems like [#[rustversion::nightly]](https://docs.rs/rustversion/latest/rustversion/) could do the trick nicely, though?

`rustversion` has its own build script. I agree it's better for it to have one and not us, though.

**Comment by briansmith** [comment]
This was fixed in PR #960.
