### ISSUE TITLE
Review approvals should be canceled automatically on any modification to the PR

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#963]
I noticed this sequence:
1. I posted a PR for review
2. The PR was approved.
3. I updated the PR

I expect that if the the PR is changed at all after the approval, then the approval should be canceled. But, this doesn't seem to happen; my PR stayed "approved."

**Comment by djc** [comment]
<img width="686" alt="Screenshot 2022-01-23 at 21 40 36" src="https://user-images.githubusercontent.com/158471/150697203-75f6f823-48e1-444a-8177-55a18299aa06.png">

**Comment by briansmith** [comment]
@djc Maybe the GitHub UI just wasn't updated with the approval being canceled? Regardless, I manually canceled the review myself when I noticed. Regardless, if I notice this again then I'll file the issue again.

**Comment by djc** [comment]
Sorry -- I meant, I just fixed this.
