### ISSUE TITLE
TLS 1.3 client: Sometimes client silently skips sending its `CertificateVerify` after sending `Certificate`

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#969]
Currently we have this https://github.com/rustls/rustls/blob/8d76aa67a9d1fef86d1acf413d1f78610ad49ba0/rustls/src/client/tls13.rs#L789-L800

AFAICT, this doesn't make sense; if we send a `Certificate` message (which we already have, by this point) then we must also send the `CertificateVerify` message, instead of just silently skipping it and carrying on.

I think instead we need to check this condition before sending `Certificate` and then refuse to send the `Certificate` if we wouldn't be able to sign the `CertificateVerify`.

**Comment by ctz** [comment]
In both TLS1.2 and TLS1.3 the client can be asked to do client authentication, but refuse (by sending an empty Certificate message). In this flow the CertificateVerify message is omitted and the server has to decide whether to allow an unauthenticated client.

RFC5246:

> (on Certificate) If no suitable certificate is available,  the client MUST send a certificate message containing no certificates.
> (on CertificateVerify) This message is only sent following a client certificate that has signing capability (i.e., all certificates except those containing fixed Diffie-Hellman parameters).

RFC8446:

> (on CertificateVerify) Clients MUST send this message whenever authenticating via a certificate (i.e., when the Certificate message is non-empty).

This is actually the same issue that I reported on s2n's formal verification of their handshake state machine (the verification did not account for the optionality of CertificateVerify).

**Comment by briansmith** [comment]
OK, I actually understood that. I got tripped up by the test that the signer is `None`. 

When I look at the code I see this:
```
            let maybe_signer = certkey
                .key
                .choose_scheme(&compat_sigschemes);
            client_auth.certkey = Some(certkey);
            client_auth.signer = maybe_signer;
            client_auth.auth_context = Some(certreq.context.0.clone());
```
If `maybe_signer` is `None` here, then why don't we set client_auth.certkey to `None` too? Otherwise, aren't we at risk of sending a non-empty Certificate message but no CertificateVerify?

**Comment by djc** [comment]
I have an old PR that tries to make this clearer. I can try to dig it up if you think that's useful.
