### ISSUE TITLE
Do we wrongly accept malformed/oversized ChangeCipherSpec messages in TLS 1.3

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#970]
I was looking into refactoring this code and I noticed there might be a bug, if my understanding is correct:
https://github.com/rustls/rustls/blob/8d76aa67a9d1fef86d1acf413d1f78610ad49ba0/rustls/src/conn.rs#L540-L565

Before we do `return Ok(state);`, don't we need to make sure that the `ChangeCipherSpec` message is exactly one byte that has value 0? I think with this logic we'd accept a ChangeCipherSpec message of any non-zero length (zero-length records are rejected when a `OpaqueMessage` is constructed) and with any values in its payload.

We should make sure we have tests for these scenerios.

**Comment by ctz** [comment]
Yeah that is a bug. We should ideally be looking for a `ChangeCipherSpecPayload` there, and not look at the `typ` field, ever.
