### ISSUE TITLE
`Acceptor` API should not force the use of `ALL_CIPHER_SUITES`

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#973]
There's no way to use `Acceptor` without depending on `ALL_CIPHER_SUITES`. This means there's no way to ensure we avoid linking in the code for unused cipher suites.

**Comment by jsha** [comment]
How would it not serve all the use cases? What is currently `Acceptor::new()` would become `ServerConfig::builder().with_safe_defaults().acceptor()`, which would have the exact same semantics as today (but would be slightly longer).

**Comment by djc** [comment]
It's not obvious to me that we'll need similar fixes for KX groups and TLS versions. In fact, I think #1053 is a simpler way to fix this without changing the public API -- I haven't thought of any downsides of that approach.
